### ISSUE TITLE
Expo + Nativewind: Unhandled JS Exception: Unexpected token '{'. Import call expects one or two arguments

### ISSUE THREAD

**Issue by dancamdev** [marklawlor/nativewind#110]
The error happens after adding the nativewind plugin to `babel.config.js`

```JavaScript
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ["nativewind/babel"],
  };
};
```

My very limited RN experience doesn't allow me to debug it further, but I'm happy to share any other useful info.

**Comment by dancamdev** [comment]
cc. @marklawlor

**Comment by marklawlor** [comment]
This is typically an error when you use [too broad of a content configuration](https://tailwindcss.com/docs/content-configuration#pattern-recommendations).

@dancamdev You should be able to fix this by using a more refined content glob. I'm also still trying to work out the source of this error, if you have a minimal reproduction can you please publish it to a public repo. That way I can catch the error and produce a better warning.

**Comment by duc-gp** [comment]
this has been closed?

iam facing the same issue, just installed a fresh expo react native project and followed steps on https://tailwindcss-react-native.vercel.app/quick-start
