### ISSUE TITLE
Nativewind stylings are not working all on a sudden

### ISSUE THREAD

**Issue by Saad-Bashar** [marklawlor/nativewind#111]
I have added nativewind and it was even working fine few days back. But now no stylings are working all of a sudden. Not sure what happened.

My version is "nativewind": "^2.0.0-next.43", I have done the following, 

1. yarn add nativewind
2. yarn add --dev tailwindcss
3. tailwind.config.js file, 
```
/** @type {import('tailwindcss').Config} */
const colors = require('./app/theme/colors');
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './stories/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: colors,
    fontFamily: {
      base: ['Karla-Regular'],
      baseBold: ['Karla-Bold'],
      heading: ['Poppins-SemiBold'],
    },
  },
  plugins: [],
};
```
4. added the babel plugin, 
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['nativewind/babel'],
};
```
5. added type reference in d.ts file

Please let me know if there is something that I can do to fix this. Thanks a lot!

**Comment by marklawlor** [comment]
Can you please publish your code to a public repo so I can investigate.

**Comment by Saad-Bashar** [comment]
The repo that I am working is a private one, let me try to create a new project. But even yesterday it was working super fine. Today I start the bundler, I  might have reset the cache, nativewind is installed properly. Not sure what's going on :(

**Comment by Saad-Bashar** [comment]
With a fresh new project it is working fine, So I guess it must be my current project. But strangely it has been working fine the whole time. Any idea where it can go wrong? @marklawlor

**Comment by marklawlor** [comment]
I would follow the Tailwind troubleshooting guide https://tailwindcss.com/docs/content-configuration#troubleshooting

As a new project works  I'm going to close this issue, but feel free to continue commenting if you find more information. Eg Your app works but not styles in stories.

**Comment by marklawlor** [comment]
In terms for caching, there is no build cache except for the Babel cache. Clearing that should clear everything 👍

**Comment by Saad-Bashar** [comment]
I think I am kind of getting there, for example, I have a button component and it has variants like this,
```
 'solid-primary': 'bg-primary-500',
 'solid-default': 'bg-neutral-200',
```

previously I was adding this into `TouchableOpacity` inside className and which was working fine. Something like the following, So I can pass size, variants as props to these component.   
```
className={`self-start rounded-lg items-center justify-center ${
        SIZES[size]
      } ${VARIANTS[variant]} ${rounded && 'rounded-full'} ${
        fullWidth && 'w-full'
      }`}
```

It seems not to work now but If I add them in style then it starts to work,
```
style={[style, VARIANTS[variant], rounded && 'rounded-full']}
```

So I am confused now.

**Comment by Saad-Bashar** [comment]
Oh I also found out we have to add flex to use any flex styles like flex-1 or flex-row in RN.

**Comment by Saad-Bashar** [comment]
@marklawlor not sure what changed, so overall tailwind is actually working. But I see a bit difference between stylings. For example,
```
className="flex-row items-center"
```
is not working and I have to add flex property to it so the content is arranged in row. However if I remove items-center then it works. 

I am getting some of these changes at the moment

**Comment by marklawlor** [comment]
Please see https://nativewind-git-next-mwlawlor.vercel.app/core-concepts/quirks

The flexbox model on Native is different to Web.
