### ISSUE TITLE
`leading-` utilities don't work

### ISSUE THREAD

**Issue by sam3d** [marklawlor/nativewind#117]
Hello!

I've tried to use the `leading` utilities in iOS to increase/decrease the line spacing, and it doesn't seem to affect it in any `<Text />` element.

Is this a known issue? Tested with [2.0.0-next.45](https://github.com/marklawlor/nativewind/releases/tag/nativewind%402.0.0-next.45)

**Comment by marklawlor** [comment]
The `leading-[n]` utilities such as `leading-3` should work as they are absolute values. The relative (unitless) utilities such as `leading-normal` won't work React Native due to being relative to the font-size.

https://www.nativewind.dev/tailwind/typography/line-height

**Comment by sam3d** [comment]
@marklawlor sorry I should have included a reproduction:

https://snack.expo.dev/@sam3d/nativewind-repro

**Comment by marklawlor** [comment]
- `text-lg` This looks correct with a line height of 1.75rem
- `text-lg leading-0` Leading-0 isn't a valid tailwind class so it's ignored. The lowest leading class is `leading-3`. So its rendering at 1.75rem
- `text-lg leading-4` Text-lg has a line height of 1.75rem while leading 4 has 1rem. This looks like its correctly rendering as 1rm
