### ISSUE TITLE
BUG - TypeError: null is not an object (evaluating 'child.props')

### ISSUE THREAD

**Issue by lewisd1996** [marklawlor/nativewind#118]
![simulator_screenshot_61E0003F-7C7E-4C62-A063-EEBC596B9CA9](https://user-images.githubusercontent.com/25225528/178978571-aa42e0d6-d8a0-4b26-ba53-fe94531bcb30.png)

At location: `/node_modules/tailwindcss-react-native/dist/with-styled-children.js`

Component in question:
```
function ListingButtons({ listing }) {
  return (
    <View className="mt-4 flex flex-col space-y-4">
      {listing?.buyNow && (
        <View>
          <Button>Buy now</Button>
        </View>
      )}
      {listing?.bestOffer && (
        <View>
          <Button>Send offer</Button>
        </View>
      )}
    </View>
  );
}
```

**Comment by marklawlor** [comment]
@lewisd1996 Thanks for the report, should be fixed in `latest`
