### ISSUE TITLE
[Question] Passing styles to components.

### ISSUE THREAD

**Issue by Saad-Bashar** [marklawlor/nativewind#123]
I am following the documentation to pass styles to components, I believe in the documentation example, it should have been `style` instead of `styles`. 

From the doc,
```
function A({ styles }) {
  return <B className={`font-bold`} />;
}

function B({ styles }) {
  // You need to use styles, className is not passed down!
  return <Text styles={styles} />;
}
```

My 2nd question is, since we are not using `className` as a prop to our child component we should not need to add `className` in our child component types or interface. But right now the TS complains if we add `className` as a prop to our parent component. How can we resolve this one? Thanks!
![Screenshot 2022-07-20 at 11 26 20 AM](https://user-images.githubusercontent.com/13269141/179889984-6d8f2b77-4d45-4da0-ab3e-a9ac8bcfbee1.png)

**Comment by marklawlor** [comment]
Yes `styles` is a typo and should now be fixed 👍 

As for your second question, you will need to add the Typescript types https://www.nativewind.dev/getting-started/typescript
