### ISSUE TITLE
Are `rounded` working?

### ISSUE THREAD

**Issue by binajmen** [marklawlor/nativewind#126]
**Describe the bug**
`rounded-full` doesn't seem to work in my RN app.

**To Reproduce**

In the Expo present on nativewind.dev, it seems replacing the styled text with the following works as expected:
```
      <StyledText className="bg-red-300 p-2 rounded-full">
        Try editing me! 🎉
      </StyledText>
```

But in my RN app (not Expo), it doesn't work:

```
<Text className="bg-red-300 p-2 rounded-full">Rounded badge</Text>
```
Color and padding are working though:

<img width="132" alt="Screenshot 2022-07-21 at 15 10 41" src="https://user-images.githubusercontent.com/15611419/180221593-e51bbf69-0f15-4df2-83dc-6b8a9de83bab.png">

Additionally, `nativewind` works flawlessly everywhere but there, so wondering what could cause an issue with rounding..
🤔 

**Additional context**
Version used:
```
  "dependencies": {
    "nativewind": "^2.0.0-next.52",
    "react": "18.0.0",
    "react-native": "0.69.2",
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "babel-plugin-module-resolver": "^4.1.0",
    "metro-react-native-babel-preset": "^0.70.3",
    "tailwindcss": "^3.1.6",
  },
```

**Comment by jmeistrich** [comment]
It could be a difference between iOS vs. Android? It's generally not well supported to have a `border-radius` on `Text` elements in React Native. Try putting `rounded-full` on the View element above it and see if that works?

**Comment by binajmen** [comment]
I can confirm it works with `View`:
```html
        <View className="bg-red-300 p-2 rounded-xl">
          <Text>Rounded badge</Text>
        </View>
```
I was misled by the Expo Snack where `rounded` is working on `Text` element.

Thank you for the suggestion @jmeistrich
