### ISSUE TITLE
`space-..` is not working

### ISSUE THREAD

**Issue by binajmen** [marklawlor/nativewind#127]
Hi (again)!

`space`ing is not working in my RN project

What I'd like to achieve (taken from a Expo Snack):
<img width="615" alt="Screenshot 2022-07-22 at 02 06 16" src="https://user-images.githubusercontent.com/15611419/180334843-182ab900-0983-4a3a-8459-ee0211fcb479.png">

What I have instead:
<img width="98" alt="Screenshot 2022-07-22 at 02 10 36" src="https://user-images.githubusercontent.com/15611419/180335231-6fa18181-5b92-4df5-8b59-7521aa68045f.png">

The code is the following:
```ts
      <View className="flex-row space-x-4">
        <Text className="text-base">Alice</Text>
        <Text className="text-base">Bob</Text>
      </View>
```

I've read the caveats mentioned in https://github.com/marklawlor/nativewind/pull/44:
> Only components with a className or tw prop are transformed.

First I was missing the `className` on the `Text` but I've added them after reading the caveats, but it still does not work. Most probably I'm doing something wrong 🙈

**Comment by marklawlor** [comment]
Can you try updating to NativeWind? It resolves a lot of issues around `space-` and doesn't have the restrictions on children.

NativeWind is very close to release so I probably won't fix any existing issues on tailwindcss-react-native.

**Comment by binajmen** [comment]
Hi @marklawlor,

Thank you for this quick reply. I'm already using nativewind `^2.0.0-next.52` and loving it ❤️ 

Also I noticed that I'm using `space-x-{n}` somewhere else and it works. Very strange stuff. Adding `mb-2` next to it and it breaks. I'll end my day (3am) and test further later today ;)

**Comment by marklawlor** [comment]
Are you able to share an Expo snack demonstrating the issue?

**Comment by binajmen** [comment]
I'm using RN without expo, I don't know if it's doable. Would that be handy enough if I add you to my private repo? I don't mind to share it with you if it can help you improve the lib :)

**Comment by binajmen** [comment]
I'll take the time to create a repro in expo and keep you updated ;)

**Comment by marklawlor** [comment]
I think I can see your issue, you are using components that do not accept a `style` prop as children.

```
<View className="flex-row items-center space-x-4">
          <Text className="font-black text-3xl">{order.id.slice(-5)}</Text>
          <BadgeStatus status={order.status} />
          <BadgePayment paid={order.isPaid} />
</View>
```

This will not work as BadgeStatus does not accept `style` as a prop.

**Comment by binajmen** [comment]
Good lord! That makes sense! I'll see how I can fix that :)

**Comment by binajmen** [comment]
Thanks a lot for taking the time to help, really appreciate it!

<img width="234" alt="Screenshot 2022-07-22 at 16 20 51" src="https://user-images.githubusercontent.com/15611419/180459255-dd3157fa-4f12-4b68-b854-e36c4c3eb001.png">
