### ISSUE TITLE
TextInput component placeholder text not updating

### ISSUE THREAD

**Issue by ytsruh** [marklawlor/nativewind#128]
**Description:**
<TextInput /> component placeholder text unable to be updated using Nativewind classes

**Steps to reproduce the behavior:**
1) Add a TextInput component to page
2) Add class text-black (or alternative)
3) Additionally try placeholder: modifier (placeholder:text-black)

**Expected behavior**
Placeholder text should be updated via text classes and/or placeholder modifier

**Additional notes**
I assume this is happening becuase this component has "placeholderTextColor" prop to modify the color and behaviour but I'm unsure if its possible to get Tailwind/Nativewind to interact with it?

**Comment by marklawlor** [comment]
`2.0.0-next.53` has a [workaround](https://www.nativewind.dev/api/styled#styling-non-style-properties), but I would recommend simply importing the color from your theme. 

Looking at `react-native-web` internals, we should be able to implement proper `placeholder:` support, so I'm going to close this issue and add it to the features backlog. When I start implementing the feature I'll reopen this issue.
