### ISSUE TITLE
space-x- not preserved in active: mode

### ISSUE THREAD

**Issue by binajmen** [marklawlor/nativewind#129]
Hi there,

Still loving the lib ❤️  I thought I would inform you that spacing is not kept in active mode (only case I tested):
https://snack.expo.dev/dlXET-ZuQ

While clicking and holding on the button, you'll notice that spacing is disabled.

Adding `active:space-x-2` to `Pressable` solve the issue, but I believe it should stay by default. I let you decide if it worth further investigation.

**Comment by marklawlor** [comment]
Fixed in `2.0.0-next.53`
