### ISSUE TITLE
Allow overriding styles using the `style` property

### ISSUE THREAD

**Issue by mohammed-elhaouari** [marklawlor/nativewind#136]
**Describe the bug**
We can't override element styles using `style` property when using `className`

**To Reproduce**
```jsx
<Pressable
  className="bg-white h-20 w-full"
  style={({ pressed }) => [
    {
      backgroundColor: pressed ? "blue" : "red",
    },
  ]}
>
  <Text>Button</Text>
</Pressable>
 ```

**Expected behavior**
the background of the element should be blue when element is pressed and red when element is not pressed.

**Expo Snack**
NA

**Screenshots**
NA

**Additional context**
In the following scenario, we need the `pressed` variable to style background differently. it would be super usefull to allow for `className` to accept a function that returns a string.

**Comment by marklawlor** [comment]
Overriding styles via the `style` prop is support - except for styled functions like in your example

I'm going to close this issue and add it to the features backlog. I'll reopen it when I start on this feature.

In the mean time, you can replicate the functionality of the Pressable style function by using Tailwind modifiers

```tsx
<Pressable className="bg-white h-20 w-full bg-blue-500 active:bg-red-500">
  <Text>Button</Text>
</Pressable>
```
