### ISSUE TITLE
Button component don't get styled

### ISSUE THREAD

**Issue by wizevlad** [marklawlor/nativewind#144]
**Describe the bug**
Styling a RN Button does nothing

**To Reproduce**
This is only happening to Button element, I configured babel and works fine
```
import {  Button } from "react-native";
```
<img width="1093" alt="Screen Shot 2022-08-01 at 19 03 26" src="https://user-images.githubusercontent.com/54042260/182264712-baf185a9-6589-440a-8ea4-160e18baf7f8.png">

**Expected behavior**
Button gets styled with the TW css color

**Expo Snack**
https://snack.expo.dev/@vladejs/nw-btn-bug

**Additional context**
I correctly configured babel in my project and View, Text are getting the correct styles

**Comment by eugeneZolotarenko** [comment]
+1, seems like buttons couldn't be styled with tailwind class names.

**Comment by thowitz** [comment]
It seems react native buttons can't be styled, they don't even have a style prop. The best you can do is change the colour through the color prop, [this](https://docs.expo.dev/ui-programming/react-native-styling-buttons/) expo page explains it.

You can however use a `<Pressable />` component wrapped around a `<Text />` component, so you can do something like [this](https://snack.expo.dev/@thowitz/nw-btn-bug) using `<StyledPressable />` and `<StyledText />`.

**Comment by marklawlor** [comment]
@thowitz Is correct - React Native's `button` does not have a `style` prop and hence cannot be styled by this library. From the RN docs

> A basic button component that should render nicely on any platform. **Supports a minimal level of customization.**
> 
> If this button doesn't look right for your app, you can build your own button using [TouchableOpacity](https://reactnative.dev/docs/touchableopacity) or [TouchableWithoutFeedback](https://reactnative.dev/docs/touchablewithoutfeedback).

Altho the docs say to use the touchable components, I find you get more control (especially on web) with `Pressable`

**Comment by mkuchak** [comment]
An example of how to componentize this using Typescript.

Using component:
```js
<Button
  className="bg-sky-400 px-4 py-2 rounded-2xl text-white text-2xl"
  onPress={() => setCount(count + 1)}
>
  Increment me! 🚀
</Button>
```

Component source:
```js
import { styled } from "nativewind";
import { PropsWithChildren } from "react";
import { Pressable, PressableProps, Text, TextProps } from "react-native";

type PropsWithoutConflicts = Omit<PressableProps, "children" | "style"> &
  Omit<TextProps, "onLongPress" | "onPress" | "onPressIn" | "onPressOut">;

interface ButtonProps extends PropsWithoutConflicts {
  className?: string;
}

const TwText = styled(Text);

export function Button({
  className,
  children,
  android_disableSound,
  android_ripple,
  unstable_pressDelay,
  delayLongPress,
  disabled,
  hitSlop,
  onLongPress,
  onPress,
  onPressIn,
  onPressOut,
  pressRetentionOffset,
  testOnly_pressed,
  ...props
}: PropsWithChildren<ButtonProps>) {
  return (
    <Pressable
      android_disableSound={android_disableSound}
      android_ripple={android_ripple}
      unstable_pressDelay={unstable_pressDelay}
      delayLongPress={delayLongPress}
      disabled={disabled}
      hitSlop={hitSlop}
      onLongPress={onLongPress}
      onPress={onPress}
      onPressIn={onPressIn}
      onPressOut={onPressOut}
      pressRetentionOffset={pressRetentionOffset}
      testOnly_pressed={testOnly_pressed}
    >
      <TwText className={className} {...props}>
        {children}
      </TwText>
    </Pressable>
  );
}
```
