### ISSUE TITLE
Weird Behaviour [Question]

### ISSUE THREAD

**Issue by Saad-Bashar** [marklawlor/nativewind#149]
I do not know how to describe this properly but here it is. The nativewind works perfectly for me. However when I sometimes change the branch, then `yarn install`, `pod install` and try to run the project again, all the stylings stop working.

I found out that if I put tw strings like `py-4` etc in  the styling prop then it starts to work but not fully, I can see that it is coming back for some places. It's pretty strange. And with restarting the machine it seems to fix the problem totally. Is it only my machine or something else is happening here? I found this case twice and it freaks me out as the whole project is dependent on the library.

Thanks @marklawlor for this amazing work!

**Comment by marklawlor** [comment]
React Native projects often aggressively cache the Babel transformed files. You most likely want to clear the cache after switching branches.

**Comment by marklawlor** [comment]
A (small) troubleshooting guide has been created to help resolve issues like this https://www.nativewind.dev/guides/troubleshooting

**Comment by Saad-Bashar** [comment]
This is super useful, thanks a lot. I will update you if anything comes up. Again thanks for your amazing work.
