### ISSUE TITLE
Can't run expo-electron when NativeWind is enabled

### ISSUE THREAD

**Issue by matallui** [marklawlor/nativewind#150]
**Describe the bug**
I have an expo project for which I'm trying to add desktop support via [expo-electron](https://docs.expo.dev/guides/using-electron/).
If I set up a brand new blank expo app, then setup electron, it works fine.
However, after setting up NativeWind, I can't run the electron app anymore.

Error:
```
Uncaught /Users/ltanica/tmp/expo/demo-46/node_modules/react-native/index.js:14
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
       ^^^^^^

SyntaxError: Unexpected token typeof
    at new Script (vm.js:83:7)
    at createScript (vm.js:265:10)
    at Object.runInThisContext (vm.js:313:10)
    at Module._compile (internal/modules/cjs/loader.js:712:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ltanica/tmp/expo/demo-46/node_modules/nativewind/dist/styled/use-interaction.js:5:24)
```

**To Reproduce**
1. Create new Expo app: `yarn create expo-app --template blank-typescript@sdk-46`
2. Bootstrap Electron: `yarn add -D @expo/electron-adapter && yarn expo-electron`
3. Start Electron app: `yarn expo-electron start` (this works)
4. Setup NativeWind
5. Verify you can change the text color via `className` for mobile (this works)
6. Start Electron app again (this fails)

**Expected behavior**
Would expect the Electron app to work just as well as the web build.

**Comment by marklawlor** [comment]
I can it test this right now, but you most likely need to transpile `nativewind`. You get the same error with `react-native-web`.

**Comment by matallui** [comment]
@marklawlor thanks for the quick response! If you point me in the right direction, I'd be happy to give it a try and do some more testing. Not really sure how to transpile `nativewind`.

**Comment by matallui** [comment]
Ok, I think I see what you meant. I've added this config to my `app.json` and now it seems to work.

```
{
  "expo": {
    "web": {
      "build": {
        "babel": {
          "include": ["react-native-web", "nativewind"]
        }
      }
    }
  }
}
```
