### ISSUE TITLE
[Docs] Missing documentation for fontFamily

### ISSUE THREAD

**Issue by Ahmedreda20** [marklawlor/nativewind#151]
When i want to use custom font name inside Text element and use `tailwindcss-react-native` classes 

The font does not work with the classes used, unlike the use of the rest of the available features, is there any solution?

**Comment by marklawlor** [comment]
Can you explain your issue more clearly, preferably with an example? NativeWind / tailwindcss-react-native should be working with custom fonts. I would recommend testing with an inline style to ensure you have loaded the font correctly.

**Comment by dionimercado** [comment]
Hi @marklawlor , I was wondering if we can extend the tailwindcss.config.js theme and add some google fonts using @expo-google-fonts. I thought this package does not support custom font family because it wasn't mentioned in the documentation.

It would be great if you add that to the docs with a quick a example 👌

**Comment by Ahmedreda20** [comment]
Well, it is good to attach a copy of the code and illustrations of what is required

Let me explain to you exactly what I mean

I downloaded the required packages of fonts as shown in the following code, and indeed the download is working properly, a downloading part appears, and then after completion, the application screens appear, this is good for here 

```JS
const [fontsLoaded] = useFonts({
    Inter_400Regular,
    Inter_500Medium,
    Inter_600SemiBold,
    Inter_700Bold,
    Cairo_500Medium,
    Cairo_600SemiBold,
    Cairo_400Regular,
    Cairo_700Bold,
  });
```

When I wanted to use fonts, I used the following code, but it didn't work yet with the custom classes in that library to customize the appearance of the elements. 

```JS
<AppText
               className="text-center font-bold"
              style={{
                color: isFocused ? activeColor().color : notActive().color,
                fontFamily: 'Cairo_400Regular',
              }}
            >
              {label.toUpperCase()}
            </AppText>
```
![IMG_20220805_094413.jpg](https://user-images.githubusercontent.com/62707388/183029678-9f1efd61-dd6e-4f9c-9731-1d107152452a.jpg)

But when I hid them as shown in the following code worked well . 

```JS
<AppText
              // className="text-center font-bold"
              style={{
                color: isFocused ? activeColor().color : notActive().color,
                fontFamily: 'Cairo_400Regular',
              }}
            >
              {label.toUpperCase()}
            </AppText>
```
![IMG_20220805_094404.jpg](https://user-images.githubusercontent.com/62707388/183029834-c6318433-dec7-45e8-ada4-e7e4a686b43b.jpg)

**Comment by crstnmac** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/20360870/183029699-4b668732-8753-4cd1-9c73-ee84f46b05a7.png)

For me it works partially with custom fonts. I have to add ```font-body``` to the classNames. I cant choose custom weights

``` theme: {
    extend: {
      fontFamily: {
        thin: ['Saturn-Light', 'sans-serif'],
        normal: ['Satoshi-Regular', 'sans-serif'],
        medium: ['Satoshi-Medium', 'sans-serif'],
        bold: ['Satoshi-Bold', 'sans-serif'],
        extrabold: ['Satoshi-Black', 'sans-serif'],
      },
    },
  }
```


I used ```npx react-native-asset``` to link assets

**Comment by Ahmedreda20** [comment]
> Im using react-native-cli
> 
> ![Screenshot (10)](https://user-images.githubusercontent.com/20360870/183029699-4b668732-8753-4cd1-9c73-ee84f46b05a7.png)
> 
> For me it works partially with custom fonts. I have to add ```font-body``` to the classNames. I cant choose custom weights
> 
> ``` theme: {
>     extend: {
>       fontFamily: {
>         thin: ['Saturn-Light', 'sans-serif'],
>         normal: ['Satoshi-Regular', 'sans-serif'],
>         medium: ['Satoshi-Medium', 'sans-serif'],
>         bold: ['Satoshi-Bold', 'sans-serif'],
>         extrabold: ['Satoshi-Black', 'sans-serif'],
>       },
>     },
>   }
> ```
> 
> 
> I used ```npx react-native-asset``` to link assets

Already added fonts to tailwind config file but nothing happend

**Comment by Ahmedreda20** [comment]
> Here is a workaround, that should allow you to use custom fonts with nativewind: 
> 
> 1. Load Fonts
> ```jsx
> export default function useLoadedFonts() {
>   const [fontsLoaded] = useFonts({
>     Inter_300Light,
>     Inter_400Regular,
>     Inter_500Medium,
>     Inter_700Bold,
>   });
>   return fontsLoaded;
> }
> ```
> 
> 2. Extend `tailwind.config.js`
> ```js
> module.exports = {
>   theme: {
>     extend: {
>       fontFamily: {
>         interLight: ["Inter_300Light"],
>         interRegular: ["Inter_400Regular"],
>         interMedium: ["Inter_500Medium"],
>         interBold: ["Inter_700Bold"],
>       },
>     },
>   },
> };
> ```
> 
> 3. Use fonts with classname
> ```tsx
> <Text classname="text-base font-interLight">Text light</Text>
> <Text classname="text-base font-interRegular">Text regular</Text>
> <Text classname="text-base font-interMedium">Text medium</Text>
> <Text classname="text-base font-interBold">Text bold</Text>
> ```


Yes it worked well. 

Another wearied question, if you please.

 Is there a way to use two types of fonts together, like what we do in the web, an English font and an Arabic font like that 

```CSS
...
font-family: "Inter", "Cairo", sans-serif;
...
```

**Comment by Ahmedreda20** [comment]
> yes you can declare it as following: 
> 
> ```js
> module.exports = {
>   theme: {
>     extend: {
>       fontFamily: {
>         heading: ["Inter_700Bold", "Cairo_700Bold", sans-serif],
>         body: ["Inter_400Regular", "Cairo_400Regular", sans-serif],
>       },
>     },
>   },
> };
> ```
> 
> Then use it as follows:
> ```jsx
> export default function() {
>     return (
>         <>
>             <Text classname="text-lg font-heading">This is a header text</Text>
>             <Text classname="text-base font-body">This is a body text</Text>
>        </>
> };
> ```


Cool, thank you mohammed I will try that

**Comment by marklawlor** [comment]
@Ahmedreda20 @mohammed-elhaouari React Native does not allow specifying multiple font families for text or font fallbacks. https://reactnative.dev/docs/text-style-props#fontfamily, On native if an array is provided, NativeWind will simply pick the first font.

NativeWind simply turns the style strings into `StyleSheet.create` objects. If you have certain font requirements you should follow the methods you would use in a standard React Native project.

> Here is a workaround, that should allow you to use custom fonts with nativewind

This isn't a workaround, this is the standard way to use custom fonts.

I'm going to rename this issue as it seems the only problem is lack of documentation

**Comment by marklawlor** [comment]
Added documentation https://www.nativewind.dev/tailwind/typography/font-family
