### ISSUE TITLE
Can't find variable: globalThis when running on iPhone 6s iOS 12

### ISSUE THREAD

**Issue by tunnaduong** [marklawlor/nativewind#152]
**Describe the bug**
As the title said, I was trying to run my app on an old iPhone 6s running iOS 12.1.4 and this bug happened. The app said: "Can't find variable: globalThis" with the above source file:

`tailwindcss-react-native > dist > context > style-sheet.js (6:17)`
```javascript
"use strict";
var _a, _b;
Object.defineProperty(exports, "__esModule", { value: true });
exports.useStyleSheet = exports.StyleSheetContext = void 0;
const react_1 = require("react");
(_a = globalThis.tailwindcss_react_native_style) !== null && _a !== void 0 ? _a : (globalThis.tailwindcss_react_native_style = {});
(_b = globalThis.tailwindcss_react_native_media) !== null && _b !== void 0 ? _b : (globalThis.tailwindcss_react_native_media = {});
exports.StyleSheetContext = (0, react_1.createContext)({
    styles: {},
    media: {},
});
function useStyleSheet() {
    return (0, react_1.useContext)(exports.StyleSheetContext);
}
exports.useStyleSheet = useStyleSheet;
```

**To Reproduce**
1. Install the app via Xcode to iPhone 6s
2. Click on app icon
3. Wait for the app to bundle and launch

**Expected behavior**
It should show my login screen

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**
![IMG_3541](https://user-images.githubusercontent.com/17230355/183235189-0fcd46db-b416-4e13-94db-188981c82798.PNG)

**Additional context**
I'm using Expo Dev Client

**Comment by marklawlor** [comment]
This has been fixed in `nativewind`
