### ISSUE TITLE
`group` is not working

### ISSUE THREAD

**Issue by koka0012** [marklawlor/nativewind#156]
**Describe the bug**
Using the pseudo-class group focus does not work correctly. The component doesn't change

**To Reproduce**
Steps to reproduce the behaviour:
Look at this code:

**Custom Input Code**
```TSX
return (
    <Pressable onPress={onInputPress}>
      <View className="px-3 border border-gray-500 rounded flex-row items-center">
        {leftAccessory?.()}
        <NativeTextInput
          className="flex-1 my-2 align-middle text-[16px] group"
          {...props}
          ref={mergeRefs([ref, forwardedRef])}
        />
      </View>
    </Pressable>
  );
```

**LeftAccessoryCode**

```TSX
function IconAccessory({
  name,
  focused,
  outlined = false,
}: IconAccessoryProps) {
  const IconComponent = styled(
    outlined? IconsOutlined[name] : IconsSolid[name],
    { props: { color: "color" } }
  );

  return (
    <View className="bg">
      <IconComponent className="text-red-500 group-focus:text-blue-500" />
    </View>
  );
}

export default IconAccessory;
```

**Expected behaviour**
The Icon should get blue when focusing the input

**Additional context**
Even if I add another component like text in the place of the Icon it still doesn't work.

**Comment by marklawlor** [comment]
[`group` is for styling based on parent state.](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state) For your example to work the icon needs to be a child of the input.

What I think you want is [`peer`](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state), which is similar to group but for the next siblings. For this to work, you would have the icon **after** the input and use `flex-row-reverse` to reverse the visual appearance. Same how you would do this on the web.

However `peer` is currently not supported as I'm still working out a nice way to implement it.
