### ISSUE TITLE
The two contents of the doc are the same.

### ISSUE THREAD

**Issue by chenzesam** [marklawlor/nativewind#157]
**Describe the bug**
The two contents of the doc are the same.

**To Reproduce**
1. Go to [here](https://www.nativewind.dev/guides/babel-compile-only#thats-it-)
2. And go to [here](https://www.nativewind.dev/guides/babel-transform-only#thats-it-)
3. You will see the same content.

**Expected behavior**
The content [here](https://www.nativewind.dev/guides/babel-transform-only#thats-it-) needs to fit the context.

**Expo Snack**

**Screenshots**

**Additional context**

**Comment by marklawlor** [comment]
Updated the transform docs, thanks for reporting 👍
