### ISSUE TITLE
tailwind.config.js theme configuration is not updated on reload using expo

### ISSUE THREAD

**Issue by testssoftware** [marklawlor/nativewind#172]
**Describe the bug**
While theming my app using `tailwind.config.js`,  i notice styles were not being updated on expo `"expo": "~46.0.6"`

**To Reproduce**
https://www.nativewind.dev/quick-starts/expo
```
<View className="flex-1 items-center justify-center bg-blue">
  <Text  className="text-primary">Open up App.js!</Text>
  <StatusBar style="auto" />
</View>
```

if  u update the primary color to "#ff00ff" the text above does not change even after restarting and building the app.

```
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend:{
      colors: {
        primary: "#ff0000"
      },
    },
  },
  plugins: [],
}
```

**Expected behavior**
when tailwind configuration ->theme changes, it should reflect on the screen, reloading the app should be able fix that.

**Comment by marklawlor** [comment]
Please reset your cache https://www.nativewind.dev/guides/troubleshooting

**Comment by testssoftware** [comment]
Thank you for your quick response, `expo start -c` does clear the cache
