### ISSUE TITLE
Bug - Render Error - Cannot read property 'props' of null

### ISSUE THREAD

**Issue by syahirdev** [marklawlor/nativewind#174]
**Describe the bug**
I'm doing a conditional rendering but the component has render error

**To Reproduce**
This is the component:
```
<View>
  {/*Description*/}
  {customer?.description && (
    <View className="flex-row items-center gap-x-2">
      <View className="bg-primary/10 p-2 rounded-full">
       <Text className="text-gray-400">Title</Text>
      </View>
      <View className="flex-1">
        <Text className="text-gray-400">Description</Text>
        <Text
          className="text-lg text-gray-800">{customer.description}</Text>
      </View>
    </View>
  )}
</View>
```

**Expected behavior**
If customer?.description is null, the component does not render. Else if customer?.description has value, render the component

**Screenshots**
![image](https://user-images.githubusercontent.com/67471898/184854318-8f6de585-e3e0-44c4-9853-b7993563a36e.png)

**Additional context**
Error at `/node_modules/tailwindcss-react-native/dist/with-styled-children.js (43:25)` based on screenshots

**Comment by Darkace01** [comment]
I am having an error similar to this. Mine is on the installation of the package. You can re-create it by just creating a react-native app with expo and follow the minimum installation process on the documentation.

**Comment by marklawlor** [comment]
This issue should be fixed on the latest version (the screenshot is showing an older version), can you please upgrade and test again.
