### ISSUE TITLE
How can I extend Nativewinds types in my custom component?

### ISSUE THREAD

**Issue by JessedeJonge** [marklawlor/nativewind#177]
Following [the tutorial to allow innerstyles](https://www.nativewind.dev/api/styled#styling-multiple-properties).
How can this example be aplied to Typescript? Let's say I have a custom prop called textStyle, how can I type this prop to allow my editor to fill in the right props? Since the Text style prop expects something else then a string its not working. Also my editor is not autocompleting with a tailwind string (with TextProps["className"]) as type, so looks like I should use another type. Any help?

```
`import {
  Pressable,
  PressableProps,
  ActivityIndicator,
  ActivityIndicatorProps,
  Text,
  View,
  TextProps,
} from "react-native";
import { styled } from "nativewind";

const variantStyles = {
  default: {
    view: "rounded-xl bg-black text-white flex justify-center items-center h-10",
    text: "",
  },
  primary: { view: "bg-blue-700 text-white", text: "" },
  secondary: { view: "bg-blue-700 text-white", text: "" },
};

type ButtonProps = {
  variant: keyof typeof variantStyles;
  isLoading?: boolean;
  onPress: () => void;
  children: React.ReactNode;
  textStyle: TextProps["className"];
};

export const Butt = (props: ButtonProps) => {
  const { variant, isLoading = false, onPress, children, textStyle } = props;
  return (
    <Pressable onPress={onPress}>
      <View
        className={`
    ${variantStyles.default}
    ${variantStyles[variant].view}
  `}
      >
        {isLoading ? (
          <ActivityIndicator />
        ) : (
          <Text
           style={textStyle}
            className={`
          ${variantStyles.default}
          ${variantStyles[variant].text}
        `}
          >
            {children}
          </Text>
        )}
      </View>
    </Pressable>
  );
};

export const Button = styled(Butt, {
  props: {
    textStyle: true,
  },
});`
```

**Comment by OrJDev** [comment]
Hey there,

This is happening because classname is string and there is no autocomplete for string, 
however the tailwind vscode extension offers autocomplete for the property "className" so if you want to have autocomplete you could change the property name from textStyle to className.

**Comment by OrJDev** [comment]
Here is an example

![ex](https://user-images.githubusercontent.com/91349014/185380529-d76638d1-707c-4438-a00e-cc3f29ef234e.png)

As you can see tailwind autocomplete is there

**Comment by marklawlor** [comment]
I've updated the docs with a simple typescript example https://www.nativewind.dev/guides/custom-components#typescript.

The `latest` release also has better Typescript support for custom components.

As for auto-complete in your editor - that's out of scope for this project and I would recommend consulting the docs of your editor extension. I don't use VS Code but the comment above looks helpful.

Remember that NativeWind isn't doing anything new here. The advantage of NativeWind is that it does stuff exactly like Tailwind CSS on web. So you can simply search their issues/discussions on how to get autocomplete working for components with multiple className attributes. 

Personally I use a custom classRegex https://github.com/tailwindlabs/tailwindcss/discussions/7554
