### ISSUE TITLE
Getting "Uncaught TypeError: dispatcher is null"

### ISSUE THREAD

**Issue by mauriceoegerli** [marklawlor/nativewind#181]
**Describe the bug**
When using react-native with expo, the following error appears on the web version.
expo version 46.0.8
react version 18.0.0
react-native version 0.69.4
react-native-web version 0.18.7
nativewind version 2.0.0-next.62

Using the babel plugin and the webpack config from the documentation

**The full error**
```
Uncaught TypeError: dispatcher is null
    useRef React
    useSyncExternalStoreWithSelector with-selector.development.js:51
    useTailwind use-tailwind.js:40
    Styled index.js:47
    React 12
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    run setImmediate.js:40
    runIfPresent setImmediate.js:69
    onGlobalMessage setImmediate.js:109
[react.development.js:1630](http://localhost:19006/home/****/src/****/node_modules/react/cjs/react.development.js)

---

The above error occurred in the <ForwardRef(NativeWind.View)> component:

Styled@http://localhost:19006/static/js/bundle.js:26379:27
ThemeProvider@http://localhost:19006/static/js/bundle.js:4915:31
div
./node_modules/react-native-web/dist/exports/View/index.js/View<@http://localhost:19006/static/js/bundle.js:82931:19
PortalHost@http://localhost:19006/static/js/bundle.js:67763:81
Provider@http://localhost:19006/static/js/bundle.js:73391:30
App
ExpoRootComponent@http://localhost:19006/static/js/bundle.js:25221:83

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by marklawlor** [comment]
Hi thanks for creating this issue, unfortunately this issue does not have enough information for me to troubleshoot and/or reproduce. Please consider explaining your issue in more detail or sharing a repository that reproduces the issue.

**Comment by marklawlor** [comment]
I have updated the Expo example in the docs (https://github.com/marklawlor/nativewind/tree/next/examples/expo) and was unable to find your issue. 

I'm going to close this issue, but if you are still have issues please reply with more information
