### ISSUE TITLE
_NativeWindStyleSheet is undefined in nativewind-output.js

### ISSUE THREAD

**Issue by jsellam** [marklawlor/nativewind#186]
Hi, I'm using the version 2.0.0-next.64 and this is the content of my nativewind-output.js generated : 

```
/*This file was generated by NativeWind. Do not edit!*/
const {NativeWindStyleSheet: NativeWindStyleSheet} = require('nativewind');

_NativeWindStyleSheet.create({
  styles: {},
});
```

As you can see, _NativeWindStyleSheet should be replaced by NativeWindStyleSheet.

there is an issue here ? https://github.com/marklawlor/nativewind/blob/next/packages/nativewind/src/postcss/serialize.ts#L102
and here ? https://github.com/marklawlor/nativewind/blob/next/packages/nativewind/src/postcss/fs-writer.ts#L28

or I did an error somewhere ?

**Comment by jsellam** [comment]
I did a PR for that https://github.com/marklawlor/nativewind/pull/187

**Comment by marklawlor** [comment]
Release on `latest`

If you don't mind, can you detail why you are using the Tailwind CLI? That option was added as a fallback when all the other options do not fit, so I'm interested to know why people would use it. Did you have trouble with the other configurations or do you like how explicit the Tailwind CLI workflow is?

**Comment by jsellam** [comment]
> Release on `latest`
> 
> If you don't mind, can you detail why you are using the Tailwind CLI? That option was added as a fallback when all the other options do not fit, so I'm interested to know why people would use it. Did you have trouble with the other configurations or do you like how explicit the Tailwind CLI workflow is?

Hi, It's just because I prefer to import View, Text and others directly from react-native than wrapped components. 

I thought it was a second method, but not a fallback.

**Comment by marklawlor** [comment]
NativeWind needs two things need to happen for it to work. Your components need to be transformed (so they understand className) and the React Native styles need to be injected.

The babel plugin does both those steps for you (but you can optionally do one or the other)

From your comment it sounds like you are:

* Using babel to transform your components (you are importing from `react-native` and using the `className` attribute)
* You are also running the Tailwind CLI to generate `nativewind-output.js` to inject your styles.

If that's the case, you don't need to do that second step - babel can do that for you. Just use the plugin with no options https://www.nativewind.dev/guides/babel#3-configure-your-babelconfigjs

**Comment by jsellam** [comment]
> NativeWind needs two things need to happen for it to work. Your components need to be transformed (so they understand className) and the React Native styles need to be injected.
> 
> The babel plugin does both those steps for you (but you can optionally do one or the other)
> 
> From your comment it sounds like you are:
> 
> * Using babel to transform your components (you are importing from `react-native` and using the `className` attribute)
> * You are also running the Tailwind CLI to generate `nativewind-output.js` to inject your styles.
> 
> If that's the case, you don't need to do that second step - babel can do that for you. Just use the plugin with no options https://www.nativewind.dev/guides/babel#3-configure-your-babelconfigjs

And for custom colors and fonts I need to use NativeWindStyleSheet.create instead tailwind.config.js if I don't use the CLI ?

**Comment by marklawlor** [comment]
If you use the default setup you never have to touch `NativeWindStyleSheet` or the Tailwind CLI. Your config file will be respected and custom themes/colours/plugins will work.

The experience should be the same as using a web framework like creare-react-app, Next.js, etc
