### ISSUE TITLE
`.cjs` support

### ISSUE THREAD

**Issue by juliusmarminge** [marklawlor/nativewind#191]
**Describe the bug**

**To Reproduce**
1. Use setup-guide, but use `tailwind.config.cjs`.
2. Start app 
3. See `Unhandled JS Exception` (screenshot below)

*Expected behavior**
Would be nice to also support `tailwind.config.cjs`. At `t3-oss`, we like to be explicit about why we have certain `js` files. Maybe it's just us? `cjs` is supported for regular Tailwind using Next.js (haven't tried elsewhere)

**Screenshots**
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-25 at 21 12 41](https://user-images.githubusercontent.com/51714798/186749102-b2e0b4ba-4786-4de3-8021-fb8f6a8d8ed1.png)

**Additional context**
Original issue: https://github.com/t3-oss/create-t3-turbo/issues/6

**Comment by marklawlor** [comment]
I'll try and get this out over the weekend. Probably should be using the [resolveConfigPath](https://github.com/tailwindlabs/tailwindcss/blob/master/src/util/resolveConfigPath.js) helper from Tailwind.

**Comment by marklawlor** [comment]
Fixed in `2.0.3`
