### ISSUE TITLE
Unable to resolve "./main.css" from "App.tsx"

### ISSUE THREAD

**Issue by ibnshayed** [marklawlor/nativewind#196]
I try to follow nativewind.dev docs to start a project but I stack on Unable to resolve "./main.css" from "App.tsx"
I search on google but that doesn't fix my problem then I cloned this repo from the expo folder and tried to run this project but the same problem showed. 
Please tell me how to start a project without any bugs. Maybe it's my problem but I need a clean step to create a new project with nativewind. thank you.

**Comment by marklawlor** [comment]
Sorry about that, updated the example. The `main.css` is just for web
