### ISSUE TITLE
Border width 1 is too thin

### ISSUE THREAD

**Issue by zainwebhr** [marklawlor/nativewind#199]
**Describe the bug**
Border width 1 is too thin as compared to React Native StyleSheet's border width 1. It looks more like 0.2 width.

**Screenshots**

<img width="404" alt="Screen Shot 2022-08-26 at 11 33 15 AM" src="https://user-images.githubusercontent.com/54834436/186837634-f9b9456e-41c0-4d9b-af58-977bf347598b.png">

In the screenshot the React Native Styles for "UserType" field is:
```
{      borderBottomWidth: 1,
      borderBottomColor: 'red',
}
```

and NativeWind styles for User Name and Password field are:

`border-red-700 border-b`

There is significant difference between width of both borders.

Also the border is not visible when I use it like this:

`border-red-700 border-b-[1]`

<img width="433" alt="Screen Shot 2022-08-26 at 11 37 49 AM" src="https://user-images.githubusercontent.com/54834436/186838361-b38bc687-a7ca-47db-913d-9fb5e8ec9f70.png">

**Dependencies**

 "nativewind": "^2.0.2",
"tailwindcss": "^3.1.8"

**Comment by marklawlor** [comment]
Opps :sweat_smile: I forgot to change this before the 2.0.0 release

I just released `2.0.4` where:

- `border` is `{ borderBottomWidth: 1 }`
- `border-0.5` is `{ borderBottomWidth: StyleSheet.hairlineWidth() }`
