### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_NativeWindStyleSheet.create')

### ISSUE THREAD

**Issue by anniebabannie** [marklawlor/nativewind#203]
**Describe the bug**
After adding the `nativewind` package, my app failed to compile after running into the following error (after I ran `expo start`):

```
TypeError: undefined is not an object (evaluating '_NativeWindStyleSheet.create')
```

**To Reproduce**
1. Create a blank expo app with `yarn create expo-app`
2. Install `nativewind` and `tailwindcss` as per these instructions: https://www.nativewind.dev/quick-starts/expo
3. Start app with `expo start` and you should see this error.

This happens on a fresh install of an expo app, without adding any other packages.

**Expected behavior**
Expected the app to compile without error.

**Additional context**
Using the latest versions of `expo-cli` and `nativewind` and `tailwindcss`, and `node v18.7.0`

**Comment by marklawlor** [comment]
Please try resetting your cache as per the troubleshooting guide https://www.nativewind.dev/guides/troubleshooting

If you issue persists, can you please share a github repo with your project as cannot replicate your issue following the instructions provide.

**Comment by anniebabannie** [comment]
@marklawlor Yay, looks like it was just a cache issue! Thanks for the help.

**Comment by amorriscode** [comment]
@marklawlor I'm actually able to recreate this by following the [Expo quick start](https://www.nativewind.dev/quick-starts/expo) line by line. I'm starting expo with `npx expo --clear` and it still happens.

Here's the repo where I have the issue: https://github.com/amorriscode/nativewind-expo-quick-start

This was happening on an actual project of mine so I started fresh here: https://github.com/amorriscode/nativewind-expo-quick-start

**Comment by amorriscode** [comment]
> @amorriscode did you find a solution to this error?

I did not! I ended up using [`twrn`](https://github.com/jaredh159/tailwind-react-native-classnames) instead.

**Comment by marklawlor** [comment]
@perhp  @amorriscode This is caused when you incorrectly set a `content` that covers your entire node_modules. This will be fixed in v3, but is always causing your builds to be much slower as Tailwind CLI needs to process every file in node_modules

**Comment by perhp** [comment]
@marklawlor thank you for the quick response, that could very well be it, since i do have something like **/*.tsx as my content rule i believe. I'll try fixing that later and get back!

**Comment by perhp** [comment]
@marklawlor  That was the problem, it all works a charm now 🙏

Thanks alot for the help ✌️
