### ISSUE TITLE
Don't work with react-native-dotenv

### ISSUE THREAD

**Issue by jsellam** [marklawlor/nativewind#213]
Hi, My project is working well with the last release of nativewind.
I have just added  react-native-dotenv in my project and I have now this error : 
`error: node_modules/nativewind/dist/tailwind/native/index.js: /Users/jeremie/Documents/PROJETS/southpigalle/vibes-app/mobile/node_modules/nativewind/dist/tailwind/native/index.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"`

I have also added NATIVEWIND_NATIVE_PLUGIN_ENABLED=1 in my .env but I have the same error...

**Comment by marklawlor** [comment]
I added `react-native-dotenv` to the Expo example in the `examples/expo` folder of this repo and was unable to replicate your issue.

I'm going to close this issue for now, but if you reply with more information I'll happily reopen it. The best option would be sharing a link to a repo with a minimal example that reproduces the issue.
