### ISSUE TITLE
Expo Web api.addExternalDependency is not a function

### ISSUE THREAD

**Issue by thefinnomenon** [marklawlor/nativewind#218]
I tried to replicate the [example project](https://github.com/marklawlor/nativewind/tree/next/examples/expo) but keep getting the following error when I run Expo web,

```
index.js:1 ./node_modules/expo/AppEntry.js
TypeError: [BABEL] /.../node_modules/expo/AppEntry.js: api.addExternalDependency is not a function (While processing: "/.../node_modules/nativewind/babel.js")
```

Is there anyway you could document the steps you took please.

**Comment by marklawlor** [comment]
Ah sorry, `addExternalDependency` is part of `Babel@7.17` but that example is running an older version.

I think I'm just going to remove that line as I'm not 100% I'm actually using correctly and need to do more research.

Fix released in `2.0.7`

**Comment by thefinnomenon** [comment]
Thanks & it's also worth mentioning that you can't use the newest version of postcss-loader -- you have to use,
`"postcss-loader": "^4.2.0",`

**Comment by marklawlor** [comment]
There's a general warning in the docs https://www.nativewind.dev/quick-starts/expo#example-webpack-setup. Do you think that needs to be more specific? I'm open to wording suggestions

**Comment by thefinnomenon** [comment]
Oh yeah that's fair. Since it's not immediately obvious what version of postcss-loader supports Webpack 4 and most people will be using it, I think it's worth pointing out the recommended version.
