### ISSUE TITLE
Animations from @legendapp/motion throwing error after migrating to nativewind from tailwindcss-react-native

### ISSUE THREAD

**Issue by ammarfaris** [marklawlor/nativewind#221]
**Describe the bug**
After migrating to nativewind from taildwindcss-react-native, animations from @legendapp/motion (https://github.com/LegendApp/legend-motion) seems to still work but now throwing error: 

> styleq: transform typeof [object Object] is not "string".

**To Reproduce**
1. add @legendapp/motion library and configure nativewind library (https://www.nativewind.dev/quick-starts/expo)
2. add  a basic Motion.View component
3. See error in browser console. 

**Expected behavior**
No error in browser console.

**Screenshots**
Attached
![Screenshot 2022-09-01 at 10 09 18 AM](https://user-images.githubusercontent.com/1182205/187817279-b993d02f-ffe8-469b-aa3b-27d1eac78a41.png)

**Additional context**
Maybe due to @legendapp/motion library still relying on   "tailwindcss-react-native": "^1.3.1" as peerDependencies

**Comment by marklawlor** [comment]
This looks to be an upstream issue.

I suspect it's mix between the RNW workarounds @jmeistrich added and/or NativeWind uses a slightly different format than tailwindcss-react-native.

However, I was recently pinged that RNW are experimenting with a fix for @jmeistrich issues, so I assume that he is waiting for that to pan out before upgrading to NativeWind, to prevent releasing two breaking changes so close together.

I'm going to close this issue, but I'm happy to continue the discussion if you have any other questions.

**Comment by jmeistrich** [comment]
Yes, this is a @legendapp/motion bug and I will try to fix it soon. See https://github.com/LegendApp/legend-motion/issues/9

**Comment by jmeistrich** [comment]
This should be fixed in the latest @legendapp/motion version 2.2.0.

**Comment by 0xBigBoss** [comment]
For what it's worth, I'm seeing this issue with a moti as well when building for next/react native web. A lot of these libraries are new for me so not sure where to start how best to integrate animations with nativewind. The errors popup only when adding a `className` to the MotiImage or MotiView. Any insight you can provide would be greatly appreciated!

Here's what the props look like, where Img is a custom component that renders a `MotiImage`.
```js
<Img
        accessible
        accessibilityRole="image"
        accessibilityLabel="poktwallet"
        from={{ opacity: 0, scale: 0.5 }}
        animate={{ opacity: 1, scale: 1 }}
        source={myImgSource}
        className="w-full flex-1 max-h-20 px-4 mb-4"
        resizeMode="contain"
      />
```

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/95193764/189027257-0c01dccc-1da0-45a8-a330-b4f089cae1c4.png">

**Comment by marklawlor** [comment]
Using NativeWind with Moti is not recommend if you plan on using NativeWind on the web. This is because Moti uses JavaScript and NativeWind uses CSS, so the data never exists for Moti to read it.

This is exactly the same as trying to use Tailwind CSS with any web animation library like Framer Motion.

**Comment by 0xBigBoss** [comment]
> Using NativeWind with Moti is not recommend if you plan on using NativeWind on the web. This is because Moti uses JavaScript and NativeWind uses CSS, so the data never exists for Moti to read it.
> 
> This is exactly the same as trying to use Tailwind CSS with any web animation library like Framer Motion.

Thanks @marklawlor appreciate the prompt reply! That makes a lot of sense. Love the direction of the project.
