### ISSUE TITLE
Dark mode doesn't work on Android

### ISSUE THREAD

**Issue by igoro00** [marklawlor/nativewind#224]
**Describe the bug**
Classes with `dark:` variant are ignored when changing dark mode system-wide on Android

**To Reproduce**
1. Open the provided snack. It's a modified snack from the dark mode page in the docs without the clicking-to-change-theme part.
2. Open the app in iOS emulator. The app has white background
4. Go to iOS settings->developer and set Dark Appearance to true
5. Go back to the app. Background color has changed(good)
6. Now do the same thing in Android emulator(Dark mode is in System settings -> Display -> Dark theme). Background hasn't changed.

**Expected behavior**
To change background color both on Android and iOS. 

**Expo Snack**
https://snack.expo.dev/@igoro00/dark-mode

**Notes**
On both iOS and Android `colorScheme` variable didn't update. Even on the iPhone where background color did update it still says its light. I've had it update on system theme change on my real project and real device though(still, background doesn't change).

**Comment by igoro00** [comment]
Ok, nvm I fixed it. Note to my future self: RTFM.

I didn't follow [the expo docs for dark mode](https://docs.expo.dev/guides/color-schemes/#managed-projects) and I didn't have `expo-system-ui` package installed. Installing it solved the issue. 
What's weird was that I could get dark mode styles by writing:
```
import {useColorScheme} from 'react-native'

function App(){
  const isDarkMode = useColorScheme()==="dark"
  return (...)
}
```
and switching styles with ternaries and it actually worked so I didn't think it was an issue with expo. 

I guess it could be helpful to mention [this link](https://docs.expo.dev/guides/color-schemes/#managed-projects) in the docs.

**Comment by marklawlor** [comment]
Cheers, I'll add a note on the website.
