### ISSUE TITLE
Flow `className` is missing in `ViewProps`

### ISSUE THREAD

**Issue by bradleyflood** [marklawlor/nativewind#227]
Hi :) Excellent module. Thank you 🙏

I'm using Flow types in my RN app. And it reports..
```
Flow: Cannot create `View` element because property `className` is missing in `ViewProps` [1] but exists in props [2]. 
```

I see that this was solved for Typescript in https://github.com/marklawlor/nativewind/issues/124#issuecomment-1190630695

Any suggestions on how to solve this for Flow? I'm hoping we can extend Flow config somehow... 🤔

![Screen Shot 2022-09-05 at 22 30 01](https://user-images.githubusercontent.com/1085976/188449635-a7154b46-0e88-4cf0-91fd-b6c2c10f2f72.png)

**Comment by bradleyflood** [comment]
Temporary workaround:
```
{/*$FlowIgnore*/}
<View className='mt-8'>
```

**Comment by marklawlor** [comment]
I'm not a Flow user so I'll have to do some research into how module augmentation works within it's type system

If you know of other libraries that were written in Typescript but have good Flow types can you let me know and I'll look at their workflow.

**Comment by bradleyflood** [comment]
So Flow is looking at the types declared in `node_modules/react-native/Libraries/Components/View/View.js`, hence not finding `className`, which makes sense because that's the file I'm importing with `import {View} from 'react-native'`.

How is this problem solved in TypeScript? What new type definition of `View` is used? and how does TS (or my IDE) know to reference that instead of what I'm importing?

I'm assuming we need to plug in to Flow to tell it about extending `View` from `react-native` mobile?

**Comment by marklawlor** [comment]
Typescript solves this via module augmentation, which allows custom types to be merged on top of the RN types.

I'm trying to find a similar concept in Flow

**Comment by bradleyflood** [comment]
Cool. Perhaps we need a `lib` entry in the `.flowconfig` > https://flow.org/en/docs/config/libs/

And/or we need our own `flow-typed` definition > https://github.com/flow-typed/flow-typed/blob/master/README.md

**Comment by marklawlor** [comment]
So this is going to be more difficult than I thought as Flow does not support module augmentation. If you develop a plug-in library the current method is to simply add your types onto the parent library

Eg here are the Flow types for Jest, which also includes types for popular plugins. If you use a plugin not listed, you can't get types. https://github.com/flow-typed/flow-typed/blob/master/cli/flow-typed/npm/jest_v27.x.x.js#L193

Unfortunately React Native include their types in the main repo, not part of Flow Typed. As I doubt Meta will allow me to modify their types, I would need to fork the RN types into NativeWind and ask people to use my fork.

The part I don't like about forking is now NativeWind is tied to RN. Each patch of RN is potentially a breaking change for NativeWind. To reduce version turmoil I would only support some RN versions or force Flow user's to lock their version. 

The last option I'm considering is a script that users can run to export the RN types themselves. This eliminates the versioning issue.

If you have any other suggestions I'd love to hear them.

**Comment by bradleyflood** [comment]
Thanks so much for the investigation.

For my situation I’ve decided to migrate my RN app from Flow over to TypeScript. 

Perhaps if there is more demand in the future this might be worthwhile. But for now I guess we can close. 

Thanks for your time @marklawlor
