### ISSUE TITLE
Using nativewind with react-native-template-typescript and className prop

### ISSUE THREAD

**Issue by kabeza** [marklawlor/nativewind#231]
Hi
I've started a new React Native app using

`npx react-native init tailwindTest --template react-native-template-typescript`

Followed all the steps, tailwind.config.js, babel.config.js etc.

I guess everything works because I can create a custom View with tailwindcss parameters, but I keep vsCode alerting about **className** attribute in every component

Is there a way to add this keyword/attribute to known types so vsCode doesn't alert about it ?

Thanks

**Comment by marklawlor** [comment]
https://www.nativewind.dev/getting-started/typescript
