### ISSUE TITLE
`group` not working

### ISSUE THREAD

**Issue by matallui** [marklawlor/nativewind#233]
**Describe the bug**
Below is a snippet of the code, where I have a parent `Pressable` with the `group` class and then the children (in here just one for demo purposes) use `group-active-*`. However, when I tap the button on a native device, I don't see anything change, even though I get the `"pressed"` message.

```tsx
      <Pressable
        className='p-2 select-none items-center flex-row group'
        onPress={() => {
          console.log('pressed');
        }}>
        <Text className='text-[#21232F] group-active:text-[#FF3367] font-[Lato-Medium] ml-[10px]'>
          Primary to All
        </Text>
    </Pressable>
```

**To Reproduce**
1. Create basic project with NativeWind support
2. Create a page with the snippet above embedded in it
3. Tap button on native devices

**Expected behavior**
I'd expect the text to turn pink when I tap the button (which is what happens on Web).

**Comment by johkade** [comment]
Can confirm. Also, `group-isolate` does not seem to work at all currently. (tried with latest solito-starter)

**Comment by KULTI1995** [comment]
When will it be fixed?

**Comment by marklawlor** [comment]
If you are experiencing this issue, please test the `next` version via `nativewind@next`. Please see #308 for more information

**Comment by marklawlor** [comment]
This has been fixed in `v4`
