### ISSUE TITLE
Pseudo-class is supported yet? (odd, event, first, last)

### ISSUE THREAD

**Issue by syahirdev** [marklawlor/nativewind#238]
Hi, I just want to ask if pseudo-class is fully supported on NativeWind 2.0?
Specifically on "odd","even","first" and "last".

I tried using them on my project but it's not working.

**Comment by marklawlor** [comment]
Not yet, most likely in the next month or so.

I'm going to close this issue and add it to the features backlog. I'll update the status it when I start on this feature.
