### ISSUE TITLE
The styles are not exporting after the build of a UI component Library in React Native.

### ISSUE THREAD

**Issue by imrishabh18** [marklawlor/nativewind#242]
**Describe the bug**
I am creating a UI component Library for React native but when importing the components to another App, the nativewind styles are not showing up. 

**Question**
I am guessing the nativewind bable plugin uses the classNames and exports it as a style object, It works when using directly on the App, but not building a Library and importing it to another App. Can you give some insights into this issue please?

**Comment by marklawlor** [comment]
Current active conversation on this topic https://github.com/marklawlor/nativewind/discussions/240
