### ISSUE TITLE
nativewind.d.ts is not a module.

### ISSUE THREAD

**Issue by juanchaur** [marklawlor/nativewind#244]
**Describe the bug**
Typescript configuration doesn't work.

**To Reproduce**
1. Added in my project root `nativewind.d.ts` with: `/// <reference types="nativewind/types" />`
3. Every time I try to create a styled component by importing: `import { styled } from 'nativewind'`
4. I see the error: `TS2306: File '/Users/app/nativewind.d.ts' is not a module.`

**Screenshots**
![Screen Shot 2022-09-15 at 22 33 58](https://user-images.githubusercontent.com/1659402/190544626-968d2a42-ec69-4163-b56e-8ae81071b9db.png)

**Comment by marklawlor** [comment]
You have set your Typescript paths  to override module imports.

Normally when you use `from 'nativewind' it will be looking at `node_modules/nativewind` but your error says it's looking in `~app`

Similar issue https://github.com/marklawlor/nativewind/issues/58#issuecomment-1139230845

**Comment by juanchaur** [comment]
@marklawlor Thank you so much!
