### ISSUE TITLE
Slow app startup after bundle has been created

### ISSUE THREAD

**Issue by PsykoSoldi3r** [marklawlor/nativewind#246]
**Describe the bug**
Very slow startup performance after implementing this library. After metro has finished building the bundle it will take like 10 seconds to launch the app.

**Expected behavior**
Fast startup performance after bundle has been created.

**Comment by marklawlor** [comment]
Hey @PsykoSoldi3r, I don't have details to share right now but I'm actively working on some things that will drastically improve startup and runtime performance. Do you mind sharing more details about your project (happy to talk via twitter DMs https://twitter.com/mark__lawlor), or is the code publicly available for me to run some tests on?

**Comment by PsykoSoldi3r** [comment]
@marklawlor Thank you! After my work shift I will contact with a DM on Twitter and share some details. The app right now in the app store is build with tailwind-react-native-classnames. Would be cool if we could solve the startup issue. I do prefer your library above tailwind-react-native-classnames. https://apps.apple.com/gb/app/scoreify/id1547173288

I have also tried to do it on a 'clean' react native project. But there I don't see any slow startup issues.

**Comment by marklawlor** [comment]
If you are experiencing this issue, please test the `next` version via `nativewind@next`. Please see #308 for more information

**Comment by PsykoSoldi3r** [comment]
Update is looking good! 

Sorry for this delay, could not yet found the right time to look into the issue. It also seems that it is a issue with my project, cause when building a bundle without this dependency it is also very very slow (production builds).

I hope that I have time next weekend to look into this issue

**Comment by PsykoSoldi3r** [comment]
Sorry for the long wait on this issue. I got just this weekend time to look into it. It seems a problem with my react native setup. Even without NativeWind compiling to a bundle would take between 10 to 15 minutes. I have upgraded my project from a scratch react-native 0.71 project and the compiling of the bundle will now take around 18-20 second even with NativeWind.

NativeWind: `v2.0.11`
