### ISSUE TITLE
Is there has a way to add custom utilities

### ISSUE THREAD

**Issue by liaoliao666** [marklawlor/nativewind#252]
I face with the pain-point that I can not add a custom utilities. so that I can not benefit by IntelliSense of tailwind.
Is there has a way like below to define my own class?
```js
plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        '.text-base': "text-dark dark:text-white"
      })
    })
  ]
```

**Comment by marklawlor** [comment]
You should be able to add that directly to your `tailwind.config.js`. You may need to reset your babel cache after doing so https://www.nativewind.dev/guides/troubleshooting

**Comment by liaoliao666** [comment]
Such syntax `text-dark dark:text-white` is not working fo in addUtilities. this syntax can only valid in the css file but nativewind can not suport css file😢

**Comment by marklawlor** [comment]
I believe the correct syntax is

```
addComponents({
    '.text-base': {
      "@apply text-dark dark:text-white": {},
    }
  });
```

Please note that Tailwind CSS discourages this way and recommends simply creating new components https://tailwindcss.com/docs/reusing-styles

**Comment by liaoliao666** [comment]
@marklawlor wow. my bad. thanks u very much

**Comment by liaoliao666** [comment]
@marklawlor It's weird that the dark style(dark:text-white) is working but the light style(text-dark)  is not working.

**Comment by marklawlor** [comment]
`text-dark` is not a valid Tailwind class. If this is a custom class you are using please provide a link to your repo

**Comment by liaoliao666** [comment]
@marklawlor here is my repo link https://github.com/liaoliao666/v2ex
I totally understand what u mean. but I still wanna using @apply to add new utilities for composing className more easier insead of abstract into components.
and the `text-dark` is a typo. I did use `text-black` in my project, but it's still not working

**Comment by liaoliao666** [comment]
even I using the standard css to add utilities but still caused same issue. like below
```
addUtilities({
        '.border-color': {
          'border-color': '#eff3f4',
          '@media(prefers-color-scheme: dark)': {
            'border-color': '#2f3336',
          },
        },
```

**Comment by marklawlor** [comment]
@liaoliao666 Does your plugin actually work with Tailwind CSS? It looks like it generates invalid CSS. Because of that, NativeWind cannot parse it.

This version should be parsable

```
addUtilities({
  '.border-color': {
    'border-color': '#eff3f4',
  }
  '@media(prefers-color-scheme: dark)': {
    '.border-color': {
      'border-color': '#2f3336',
    },
  }
},
```

**Comment by liaoliao666** [comment]
@marklawlor It's regret that this is also not working for dark mode.
