### ISSUE TITLE
Padding is not working properly

### ISSUE THREAD

**Issue by Saikat180891** [marklawlor/nativewind#257]
**Describe the bug**

When I am passing padding with p-1, p-2, p-4, p-12 etc are not working for me. Only p-8 is working

**To Reproduce**
Just add className="p-4"

**Expected behavior**
Should apply the padding value available in the tailwind default config

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by milon27** [comment]
facing same issue on ios, working fine on Android
