### ISSUE TITLE
Error on toggeling dark theme on expo

### ISSUE THREAD

**Issue by AhmedRyad22** [marklawlor/nativewind#261]
When i try to toggle dark mode i get this error
![Screenshot_20220927-124159_Expo Go.jpg](https://user-images.githubusercontent.com/54637658/192516316-06cbb50d-94ec-4926-9625-45642f06e6a7.jpg)

Also  I followed all steps on installation.

**Comment by nrowley** [comment]
+1 what am i todo here?

**Comment by marklawlor** [comment]
If you are experiencing this issue, please test the `next` version via `nativewind@next`. Please see #308 for more information

**Comment by srdjanbogicevic** [comment]
> If you are experiencing this issue, please test the `next` version via `nativewind@next`. Please see #308 for more information

This solved my issue with toggling the color scheme.

**Comment by marklawlor** [comment]
This is fixed in the v4 release
