### ISSUE TITLE
Babel: Unexpected token 'export'

### ISSUE THREAD

**Issue by rubycop** [marklawlor/nativewind#267]
![Screenshot 2022-09-27 at 20 54 54](https://user-images.githubusercontent.com/9679385/192601120-13baa20b-38ab-43d2-9d09-1dca27698ac4.png)

**To Reproduce**
```
"dependencies": {
   "nativewind": "^2.0.11",
   "react": "18.0.0",
   "react-native": "0.69.3",
},
"devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "babel-jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.70.3",
    "tailwindcss": "^3.1.8"
  },
 ```
babel.config.js
```
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: ["react-native-reanimated/plugin", "nativewind/babel"],
};
```

**Comment by marklawlor** [comment]
I cannot reproduce with the code provided. Can you please share a full code reproduction

**Comment by SeanRoberts** [comment]
@rubycop Did you ever solve this? I'm running into the same thing, presumably it's configuration related.

**Comment by rubycop** [comment]
> @rubycop Did you ever solve this? I'm running into the same thing, presumably it's configuration related.
No
I've switched to `tailwindcss` instead
