### ISSUE TITLE
nativewind not working for web with @react-navigation/native-stack and "@react-navigation/native": "^6.0.13"

### ISSUE THREAD

**Issue by jsbaguette** [marklawlor/nativewind#269]
**Describe the bug**

**To Reproduce**
- add react navigation native to your project
- create a basic routing

**Expected behavior**
- should work with tailwind classes
- its working without react navigation native

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

<img width="1611" alt="Screenshot 2022-09-28 at 7 17 34 AM" src="https://user-images.githubusercontent.com/11556276/192765829-dc5e276a-a044-4d41-ad80-af877ded2380.png">

**Additional context**

**Comment by marklawlor** [comment]
Please ensure you have followed the troubleshooting guide and your content is correctly set https://www.nativewind.dev/guides/troubleshooting

NativeWind required multiple files to be setup, giving me screenshots of two mostly unrelated files will not help identify the problem. Please link a code reproduction.

**Comment by marklawlor** [comment]
Closing issue due to lack of response
