### ISSUE TITLE
Babel plugin appears to be incompatible with expo-router

### ISSUE THREAD

**Issue by brentvatne** [marklawlor/nativewind#271]
Hi there! I've been enjoying using this library but ran into some difficulty getting it to work alongside the new / beta expo-router.

**Describe the bug**
When using alongside [expo-router](https://expo.github.io/router/docs/intro/), styles are not applied on fragment routes in the `app` directory.

**To Reproduce**
1. Initialize a new project with expo-router: `npx create-react-native-app -t with-router`
2. Add nativewind according to these instructions: https://www.nativewind.dev/quick-starts/expo
3. Update `content` in **tailwind.config.js** as follows: `["./app/**/*.{js,jsx,ts,tsx}"],`
4. `mkdir app && touch app/index.js`
5. Copy the following into `app/index.js`:

```js
import { Text, View } from "react-native";

export default function Page() {
  return (
    <View className="flex-1 justify-center items-center p-6 bg-red-100">
      <Text>Hello, world</Text>
    </View>
  );
}
```

6. Run the app, it will work! Great. Now close dev server
7. `mkdir "app/(tabs)" && touch "app/(tabs).js && mv app/index.js "app/(tabs)/index.js"`
8. Copy the following to "app/(tabs).js":

```
import { Tabs } from 'expo-router'
export default Tabs;
```

9. Start up the app again, notice that styles from nativewind are not applied to "app/(tabs)/index.js"

**Expected behavior**
Should work well with expo-router fragment routes

**Expo Snack**
N/A

**Screenshots**

### Outside of fragment route

![image](https://user-images.githubusercontent.com/90494/193344055-eba72da7-e707-4088-a1cf-3d9fab1d8dbb.png)

### Inside of fragment route

![image](https://user-images.githubusercontent.com/90494/193344099-656578fe-0ea4-4919-bed7-d1509391ba43.png)

**Additional context**

It is possible there is some interaction between the two babel plugins.

**Comment by marklawlor** [comment]
Yep the two conflict, but #260 should address this.

**Comment by koka0012** [comment]
Just a update here, after using the next branch it still doesn't work.

**Comment by marklawlor** [comment]
The `next` branch is highly unstable and isn't expected to be working state

**Comment by marklawlor** [comment]
Update: `nativewind@next` works only for android & ios. Web support is blocked by Metro as it does not support for CSS files.

**Comment by gorbypark** [comment]
> Update: `nativewind@next` works only for android & ios. Web support is blocked by Metro as it does not support for CSS files.

Looks like [there's a PR](https://github.com/expo/router/pull/223) for expo-router that add CSS support for Metro (expo-router uses Metro to bundle for the web), so hopefully this will allow for nativewind@next and expo-router to play nicely when it is merged!

**Comment by a-eid** [comment]
the package is working with expo router, however when changing the `require.context` it stops working. even `styled` doesn't work. 


```tsx
import { registerRootComponent } from "expo"
import { ExpoRoot } from "expo-router"

// Must be exported or Fast Refresh won't update the context
export function App() {
  const ctx = require.context("./src/screens")
  return <ExpoRoot context={ctx} />
}

registerRootComponent(App)
```

**Comment by marklawlor** [comment]
This has been fixed in `v4`. Expo Router v3 allows you to provide a custom directory without modifying `require.context`
