### ISSUE TITLE
Dosnt work on web but works perfectly on iOS & android

### ISSUE THREAD

**Issue by SkroooB** [marklawlor/nativewind#273]
**Describe the bug**
So i'm facing this problem where nativewind dosnt work correctly on web but works perfectly on iOS and android, i have created a new project with minimal  settings from expo added nativewind still dosnt work,

**To Reproduce**
1. Create expo project
2. add nativewind
3. add expo web
4. write a className

The only time it works is by setting only one tailwind variable once more added it stops working

This dosnt work:
> import React from "react";
import { Text, View } from "react-native";

```
export default function App() {
  return (
      <View>
        <Text className="text-red-500 text-3xl">Hello world</Text>
      </View>
  );
}

```

This works:
```
import React from "react";
import { Text, View } from "react-native";


>export default function App() {
  return (
      <View>
        <Text className="text-red-500 text-3xl">Hello world</Text>
      </View>
  );
}
```

**Screenshots**
With multiple variables
![image](https://user-images.githubusercontent.com/38193519/193790698-11ce9833-911d-4bbb-9c04-f71f66af3822.png)

With one variable
![image](https://user-images.githubusercontent.com/38193519/193790818-32866af5-a270-4a91-9f3d-5edff6e428a5.png)

babel.config.js:
```
module.exports = function(api) {
    api.cache(true);
    return {
        presets: ['babel-preset-expo'],
        plugins: ["nativewind/babel"],
    };
};
```

tailwind.config.js:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./App.{js,jsx,ts,tsx}", "./screens/*.{js,jsx,ts,tsx}"],
    theme: {
        extend: {},
    },
    plugins: [],
}
```

package.json:
```
 {
    "name": "test",
    "version": "1.0.0",
    "main": "index.js",
    "scripts": {
        "start": "expo start --dev-client",
        "android": "expo run:android",
        "ios": "expo run:ios",
        "web": "expo start --web"
    },
    "dependencies": {
        "@expo/webpack-config": "^0.17.0",
        "expo": "~46.0.13",
        "expo-splash-screen": "~0.16.2",
        "expo-status-bar": "~1.4.0",
        "nativewind": "^2.0.11",
        "react": "18.0.0",
        "react-dom": "18.0.0",
        "react-native": "0.69.6",
        "react-native-safe-area-context": "4.3.1",
        "react-native-screens": "~3.15.0",
        "react-native-web": "~0.18.7"
    },
    "devDependencies": {
        "@babel/core": "^7.12.9",
        "tailwindcss": "^3.1.8"
    },
    "private": true
}
```

**Comment by marklawlor** [comment]
Please read the setup instructions for Expo Web https://www.nativewind.dev/quick-starts/expo#expo-web

You need to setup your web project just like a normal Tailwind CSS app. 

There is an example in the repo https://github.com/marklawlor/nativewind/tree/main/examples/expo
