### ISSUE TITLE
Docs for Next.js with React Native for Web

### ISSUE THREAD

**Issue by steida** [marklawlor/nativewind#276]
First, thank you for this awesome project! I just dropped my own Tailwind-like abstraction 😁

One thing that's not obvious from docs is how to set up Nativewith for Next.js with React Native for Web. This should be highlighted more:

`const withTM = require("next-transpile-modules")(["nativewind"]);`

But I still think I am doing something wrong because hover should depend on RNfW logic, and it works with disabled JavaScript, so it depends on CSS.

Is that something version 3 is going to fix? Thank you.

**Comment by marklawlor** [comment]
NativeWind on web uses CSS as the default. You can revert back to native styling but you will lose a number of features, such as SSR support. Native styles also reduce performance and increase your bundle size.

Can you explain why you want to use native styles on web?

**Comment by steida** [comment]
I'm concerned more about correctness than performance. But, RNfW 18 should be as on par with using css-modules. https://github.com/necolas/react-native-web/releases/tag/0.18.0

Anyway, the reason I'm asking for native styling is https://necolas.github.io/react-native-web/docs/interactions and especially this https://github.com/necolas/react-native-web/issues/1708#issuecomment-678403800

> Yeah, and as a result, on those devices touch interactions trigger hover effects.

**Comment by steida** [comment]
OK, need to test it and open a new issue.
