### ISSUE TITLE
Merging of inline styles not always picked up

### ISSUE THREAD

**Issue by alexmngn** [marklawlor/nativewind#277]
**Describe the bug**
I am trying to create a custom Text component with restricted styles.
It seems like nativewind doesn't like the merging of inline styles. When I make changes to the props, it doesn't always apply the new style. A refresh of the app sometimes works. A full restart with `react-native start --reset-cache` sometimes works but not always either. Replacing the variables with hard-coded values with a restart of the app always works and the styles gets picked up. 
It seems the caching is very strong, or the transpiler is confused with the merged inline styles and they aren't always picked up. 

With the following component 

**To Reproduce**
This is my custom component:

```ts
import React from 'react';
import { Text as RNText, TextProps } from 'react-native';

type Props = Omit<TextProps, 'style'> & {
  size?: 'base' | 'sm' | 'lg';
  weight?: 'regular' | 'medium' | 'bold';
  color?: 'grey-600' | 'orange-500';
  className?: never;
};

const Text = ({
  size = 'base',
  color = 'orange-500',
  weight = 'regular',
  ...props
}: Props) => (
  <RNText
    className={`text-${size} text-${color} font-family-${weight}`}
    {...props}
  />
);

export default Text;
```

And this is how I use it:

```
import Text from './Text'

export default () => (
  <Text size="lg">Hello world</Text>
)
```

**Expected behavior**
Merged inline styles should always be picked up without needing to restart react native bundler.

**Comment by supreme** [comment]
+1 experiencing this issue as well

**Comment by langtube** [comment]
This is because tailwind does not allow "Dynamic class names", as documented [here](https://github.com/marklawlor/nativewind/blob/main/apps/website/docs/troubleshooting.md#dont-construct-class-names-dynamically).

**Comment by marklawlor** [comment]
@langtube is correct - Tailwind CLI, the tool that compiles the styles does not allow dynamic styles this manner. 

You can achieve this if you create a prop map, eg:

```tsx
const textSizes = {
  base: "text-base",
  sm: "text-sm"
  ...
}
```

However, writing components like that goes against the advantages of Tailwind. Eg what happens when you need a text with arbitrary size?

A better way to write this component would be

```tsx
const MyText = styled(Text, "text-base text-orange-500 font-regular")
```

Then just apply the overrides when you need to

```tsc
<MyText className="text-medium" />
<MyText className="text-grey-500" />
```

**Comment by alexmngn** [comment]
When writing a component library with strict rules, you don't want arbitrary values but only want to allow specific values.  Which is what I've tried to do above with typescript. This is to prevent developers from diverging from the design system. 
I'll give a try at using the prop map 👍  thanks
