### ISSUE TITLE
Can't use nativewind with node v14

### ISSUE THREAD

**Issue by Ahmedreda20** [marklawlor/nativewind#278]
Node current version is  `14.17.0`

```CMD
error nativewind@2.0.11: The engine "node" is incompatible with this module. Expected version ">=14.18". Got "14.17.0"
error Found incompatible module.
```

When installed another version of Node got the same error again, the latest version installed on my PC is `15.0.0` but got it again.

> I have some projects running an old version so I have to use the same version they are working on.

![image](https://user-images.githubusercontent.com/62707388/194611142-b79de859-9430-4625-a4ca-a8a53d34f069.png)
![image](https://user-images.githubusercontent.com/62707388/194612100-d980cda3-b0cc-495f-988b-23bc7c01a9bd.png)

**Comment by marklawlor** [comment]
Node `15.0.0` is a 2 year old unmaintained version of node which reached End Of Life in 2020-10-20.

I'm sorry for your situation, but those are the minimum requirements. I'd suggest you upgrade to `v14.18`

I'll update the update the engine string remove v15

**Comment by Ahmedreda20** [comment]
> Node 15 is a 2 year old unmaintained version of node which reached End Of Life in 2020-10-20.
> 
> I'm sorry for your situation, but those are the minimum requirements. I'd suggest you upgrade to `v14.18`
> 
> I'll update the update the engine string remove v15

Cool, but I tried that version too and got the same error message

**Comment by marklawlor** [comment]
That error comes directly from Node.js, not NativeWind. It is saying that Node cannot find an inbuilt Node.js module. I would verify your installation.

**Comment by Ahmedreda20** [comment]
Does it look like I won't be able to work in that library yet?

What do you want me to send to you?

**Comment by marklawlor** [comment]
The `node:path` module was introduced as a core module of Node.js in `14.18`. If you application cannot find it, then you are not using node `>=14.18`. You said you upgraded, but still recieved that error message - which sounds like you incorrectly upgraded Node and it is still running the `14.17`. I would at a minimum run `node -v` to verify what version you are running.

If you have having trouble upgrading your Node version, I would consult stackoverflow.com.

Sending me your code will not resolve your issue. This is not a problem with NativeWind or your codebase, rather the version of Node installed on your machine.

**Comment by Ahmedreda20** [comment]
> The `node:path` module was introduced as a core module of Node.js in `14.18`. If you application cannot find it, then you are not using node `>=14.18`. You said you upgraded, but still recieved that error message - which sounds like you incorrectly upgraded Node and it is still running the `14.17`. I would at a minimum run `node -v` to verify what version you are running.
> 
> If you have having trouble upgrading your Node version, I would consult stackoverflow.com.
> 
> Sending me your code will not resolve your issue. This is not a problem with NativeWind or your codebase, rather the version of Node installed on your machine.

Thanks it is working fine now
