### ISSUE TITLE
The instructions to get it working in Expo web does not work

### ISSUE THREAD

**Issue by trajano** [marklawlor/nativewind#281]
**Describe the bug**
I started a new app using the blank typescript template and the instructions in https://www.nativewind.dev/quick-starts/expo

**To Reproduce**
1. npx create-expo-app
2. choose blank typescript
3. yarn add nativewind
4. yarn add --dev tailwindcss  @expo/webpack-config@^0.17.0 postcss-loader@4.2.0 
5. npx tailwindcss init
6. Change `content: ["./App.tsx"],`
7.  babel.config.js add `nativewind/babel` plugin
8. create webpack.config.js as per https://www.nativewind.dev/quick-starts/expo#expo-web
9. Modify App.tsx as per https://www.nativewind.dev/quick-starts/expo#expo-web but change to `bg-red`

**Expected behavior**
Red screen with text in the middle

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**
![image](https://user-images.githubusercontent.com/110627/194969824-ee386d59-f0a3-45c1-b232-91b3fc5081bc.png)

**Additional context**

**Comment by marklawlor** [comment]
Please follow the instructions, especially this step "You will need follow a [Tailwind CSS installation guide](https://tailwindcss.com/docs/installation)"

NativeWind is just a compatibility layer on the web, it doesn't compile the styles.

Additionally there an example Expo project in the repo

**Comment by younes0** [comment]
@marklawlor I also had the same misunderstanding, may I suggest to put a link to the expo example in the section: https://github.com/marklawlor/nativewind/tree/main/examples/expo

**Comment by younes0** [comment]
@marklawlor I also had the same misunderstanding, may I suggest to put a link to the [expo example](https://github.com/marklawlor/nativewind/tree/main/examples/expo) in this section: https://www.nativewind.dev/quick-starts/expo#expo-web

**Comment by marklawlor** [comment]
A link has always existed? If you have a suggestion on how to improve it can you please open a PR

![Screenshot from 2022-10-21 06-41-17](https://user-images.githubusercontent.com/3946701/197053785-328954ad-94eb-444c-8407-7d3cca7f34f4.png)
