### ISSUE TITLE
Importing nativewind in tailwind.config.js throws Babel error "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by pjadavies** [marklawlor/nativewind#282]
**Describe the bug**
I want to customize font sizes to scale with the pixel ratio and followed the instructions at https://www.nativewind.dev/customization/theme. But adding the line `const { fontScale } = require('nativewind');` results in a Babel build error `Cannot use import statement outside a module`

I've looked around but don't see an obvious way to fix this but seems like something nativewind expects to work?

**Comment by lstellway** [comment]
Confirming I am experiencing the same thing. 

> *src/component.tsx: [BABEL] /path/to/component.jsx: Cannot use import statement outside a module (While processing: "/path/to/node_modules/nativewind/babel.js")*

Here is my `tailwind.config.js`, referenced from the [Theme Customization](https://www.nativewind.dev/customization/theme) documentation page:

```js
const {hairlineWidth} = require('nativewind');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      borderWidth: {
        hairline: hairlineWidth(),
      },
    },
  },
};
```

Following the `babel.js` file, it is exporting from files that include `import` statements. Not super familiar with the project setup, but could it be that the releases aren't compiling for the correct target?

**Comment by lstellway** [comment]
I was trying to step through the commits and build locally to see if I could spot where the issue was cropping up. 

Steps I am trying:
- Checkout commit hash
- Install dependencies `npm install`
- `npm run build` to build the package files
- Copy `./packages/nativewind/dist/` to my project's `node_modules/nativewind/` directory

I am using the following helper script:
```sh
#!/bin/bash

SCRIPT_NAME=$(basename $0)
OUTPUT_DIR="${1}"

[ -z "${OUTPUT_DIR}" ] && echo "Release path required\r\nEg. \`${SCRIPT_NAME} ~/Desktop/nativewind\`" && exit 1;
[ -d "${OUTPUT_DIR}" ] || (echo "Directory '${OUTPUT_DIR}' does not exist." && exit 1);

npm run build
rm -rf "${OUTPUT_DIR}"
mv ./packages/nativewind/dist/ "${OUTPUT_DIR}"
```

Version `2.0.10` does not seem to have the same issue. 
I'm out of time for today, but hopefully will be able to continue soon.

**Comment by marklawlor** [comment]
If you are experiencing this issue, please test the `next` version via `nativewind@next`. Please see #308 for more information

**Comment by pipinet** [comment]
same issues


<img width="1791" alt="image" src="https://user-images.githubusercontent.com/6096680/199217345-10396a6f-8906-49d9-99f1-8401d1de880e.png">

**Comment by amritk** [comment]
Same issue here, I tried the @next version as well. 

https://github.com/amritk/nativewind-expo-next/tree/next

**Comment by badalsaibo** [comment]
Happening here on version `2.0.11`

**Comment by marklawlor** [comment]
This has been fixed in `v4`. It uses `tailwindcss/loadConfig` to load the config file. If your having issues, please debug by create a NodeJS file

```
import loadConfig from "tailwindcss/loadConfig";

console.log(loadConfig("./tailwind.config.js"))
```

Please only report issues where this works, but NativeWind is failing.
