### ISSUE TITLE
 Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by ElkinSantiana** [marklawlor/nativewind#286]
Error: Requiring module "node_modules\nativewind\dist\style-sheet\index.js", which threw an exception:

 TypeError: Cannot read properties of undefined (reading 'create')

**Comment by marklawlor** [comment]
You have set your `content` to include everything in node_modules, which has created a recursive loop, resulting in undefined.

This will be fixed in v3, but its killing your build time Tailwind need to scan every file in node_modules
