### ISSUE TITLE
[Feature] Styling components with props other than style

### ISSUE THREAD

**Issue by AndyZZH** [marklawlor/nativewind#287]
Thank you for this amazing lib!! 

Could we style components with props other than style? If not, I am making a feature request.

I am trying to style a [Swipeable component](https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/swipeable/#containerstyle). Naturally I wanna keep using NativeWind with all the theme setup. Basically, I would like to use something similar to [sx hook](https://www.dripsy.xyz/apis/useSx#recommendations) in Dripsy but with tailwind class name. eg.
```
<FlatList
    contentContainerStyle={sx("flex-1 h-full")}
    data={data}
    renderItem={renderItem}
  />
```

**Comment by marklawlor** [comment]
https://www.nativewind.dev/api/styled

**Comment by ChrisYohann** [comment]
Hi @marklawlor , I did not want to reopen an issue because my problem looks pretty similar, but do you have an example when you have to pass a style object (and you cannot derive a styled component to embed tailwind class names ?)

For example, coming from [tailwind-react-native-classnames](https://github.com/jaredh159/tailwind-react-native-classnames), I have a `BottomTabNavigator` from `@react-navigation/bottom-tabs` and I'm styling the `TabBarLabel` like this : 
```javascript
    <TabNavigator.Navigator
      screenOptions={{
        headerTitleAlign: 'center',
        headerShadowVisible: false,
        tabBarLabelStyle: tw.style('text-center text-xs font-display'),
      }}
    >
    //...
   </TabNavigator.Navigator>
```

Do you have an idea of how I can achieve it with nativewind ?

Thanks, and awesome work by the way :)

**Comment by marklawlor** [comment]
Styled will not style nested props. You can fix your issues by simply evaluating the prop you wish to style

```tsx
const StyledNavigator = styled(
  ({ tabBarLabelStyle, ...props }) => <TabNavigator.Navigator {...props} screenOptions={{ ...props.screenOptions, tabBarLabelStyle }} />, 
  {
    props: {
      tabBarLabelStyle: true
    }
  }
)
```

**Comment by chrisarts** [comment]
I was struggling with the FlatList props infer using generics, I end up doing this:

```typescript
interface TFlatListProps<T extends unknown> extends FlatListProps<T> {}

export const StyledFlatList = styled(NativeFlatList);

export const FlatList = <ItemsT extends unknown>(props: TFlatListProps<ItemsT> & StyledProps<TFlatListProps<ItemsT>>) => {
  return <NativeFlatList {...props} />;
};
```

**Comment by marklawlor** [comment]
If you are using the `next` branch you can simply cast the styled component into having the generic props

```
import { ComponentProps, FlatList as RNFlatList, FlatListProps as RNFlatListProps } from "react-native"

// Create the Styled component
const StyledFlatList = styled(RNFlatList);

// Cast it into a generic version
export const FlatList = StyledFlatList as <T>(
  props: RNFlatListProps<T> & ComponentProps<typeof StyledFlatList>
) => ReturnType<typeof StyledFlatList>;
```

If anyone knows of a simpler method I'd love to document it / create a helper type.

**Comment by joelrojo** [comment]
> 



> Hi @marklawlor , I did not want to reopen an issue because my problem looks pretty similar, but do you have an example when you have to pass a style object (and you cannot derive a styled component to embed tailwind class names ?)
> 
> For example, coming from [tailwind-react-native-classnames](https://github.com/jaredh159/tailwind-react-native-classnames), I have a `BottomTabNavigator` from `@react-navigation/bottom-tabs` and I'm styling the `TabBarLabel` like this :
> 
> ```js
>     <TabNavigator.Navigator
>       screenOptions={{
>         headerTitleAlign: 'center',
>         headerShadowVisible: false,
>         tabBarLabelStyle: tw.style('text-center text-xs font-display'),
>       }}
>     >
>     //...
>    </TabNavigator.Navigator>
> ```
> 
> Do you have an idea of how I can achieve it with nativewind ?
> 
> Thanks, and awesome work by the way :)

@ChrisYohann were you able to figure this out using styled wrapped component?

Also having the same issue. Trying specifically to do this with React Navigation and struggling to figure out the best way to use nativewind to add style to the props.

@marklawlor do you happen to have any examples of how to style something like this? I'm currently using `twrnc` and would like to fully migrate to nativewind:

```javascript
<Stack.Navigator
  screenOptions={{
    headerStyle: tw.style('bg-gray-800'),
    headerTintColor: tw.color('gray-100'),
    headerTitleStyle: tw.style('font-sans'),
    headerBackTitleVisible: false,
    headerShadowVisible: false,
    title: ''
  }}
>
...
<Stack.Navigator>
```

My current attempt is this, but can't seem  to get it to work:
```javascript
const StyledStackNavigator = styled(
  (children, { headerStyle, ...props }) => (
    <Stack.Navigator
      {...props}
      screenOptions={{ ...props.screenOptions, headerStyle, headerTitleStyle }}
    >
      {children}
    </Stack.Navigator>
  ),
  {
    props: {
      headerStyle: true,
      headerTitleStyle: true
    }
  }
)
```

Really awesome work by the way!

**Comment by ChrisYohann** [comment]
Hi @joelrojo , I did not touched that part for a while, but if you still struggling with it, that's what I've finally written (with typing)

```javascript
const HomeTabNavigator = createBottomTabNavigator<MainTabParamList>();

type StyledNavigatorProps = {
  tabBarLabelStyle: StyleProp<TextStyle>;
} & ComponentProps<typeof HomeTabNavigator.Navigator>;

const StyledNavigator = styled(
  ({ tabBarLabelStyle, ...props }: StyledNavigatorProps) => (
    <HomeTabNavigator.Navigator
      {...props}
      screenOptions={{
        ...props.screenOptions,
        tabBarLabelStyle,
      }}
    />
  ),
  {
    props: {
      tabBarLabelStyle: true,
    },
  },
);
```

And later, I use my component like this : 
```javascript
<StyledNavigator
      tabBarLabelStyle="text-center text-xs font-display"
      {...otherProps}
/>
```

Hope it helps !
