### ISSUE TITLE
Extracting Classes

### ISSUE THREAD

**Issue by rasitcolakel** [marklawlor/nativewind#296]
I want to extract and add custom classes, is it possible to use them with NativeWind?

You can check it on -> [Tailwind Play](https://play.tailwindcss.com/kDy7s52pUV)

My styles.css file 

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .btn-primary {
    @apply bg-red-500;
  }
}
```

**Comment by marklawlor** [comment]
You can do this now via Tailwind's plugin system, and it will have experimental support in v3 https://github.com/marklawlor/nativewind/pull/260

**Comment by rasitcolakel** [comment]
I. will check it thanks @marklawlor
