### ISSUE TITLE
Why solito recommends styled wrapper and not babel plugin?

### ISSUE THREAD

**Issue by Jonatthu** [marklawlor/nativewind#301]
https://solito.dev/tailwind

_If you're reading the NativeWind docs, you might find that you can use className directly without using styled. Since this requires the Babel plugin for all platforms, it won't work with Solito. Be sure to always wrap your components with styled._

Is there anyway to make this actually work? I have tried babel config js but whatever I set on the packages folder does not work with className only styled HOC.

**Comment by marklawlor** [comment]
Solito advocates for the use of SWC with Next.js, as it provides a better development experience. NativeWind doesn't have a SWC plugin so you should use the `styled()` API. Additionally, `styled()` as upcoming features that make it easier to build a component library  https://github.com/marklawlor/nativewind/pull/260
