### ISSUE TITLE
Style not working properly on custom component while changing

### ISSUE THREAD

**Issue by fortezhuo** [marklawlor/nativewind#303]
**Describe the bug**
Since nativewind styles are generated at build time, I have found issue while changing tailwind className after built on custom component

**To Reproduce**

1. Copy this simple script

```
import * as React from "react"

import { Text, View } from "react-native"
import { styled } from "nativewind"

const StyledText = styled(Text)

const Box = ({ className, ...props }: any) => {
  return <StyledText className={className} {...props} />
}

export default function App() {
  return (
    <View>
      <Text className="text-yellow-500">01</Text>
      <Box className="bg-blue-500 basis-1/4">02</Box>
      <Box className="bg-red-500 basis-1/4">03</Box>
    </View>
  )
}
```
2. replace text-yellow-500 to text-blue-500 and save (it will be working) 
3. replace bg-blue-500 to bg-yellow-500 and save(it's not working)
4. replace bg-red-500 to bg-green-500 and save(it's not working)
5. replace bg-yellow-500 (from no.3) to bg-red-500 and save (bg-red-500 had been generated before, and it's working)

**Screenshots**
I run this script using ```expo start``` on web and changing the tailwind class

- On StyledText, I change the color.. it will be changed as expected
- On Custom Component, I change the color, it won't be change if the class was not generated before (I change to bg-green not working, but if I change to bg-red will work again because of previous className

![Screen Recording 2022-10-29 at 10 56 16](https://user-images.githubusercontent.com/9128724/198812992-e0d04490-b98b-49b6-ac09-6dbd833d51b4.gif)

**Expected behavior**
Change className / styles should works on custom component

**Comment by marklawlor** [comment]
This is expected behaviour, the babel plugin turns `className` to `style`, so Box never receives a className prop at runtime.

Please see https://www.nativewind.dev/guides/custom-components for more information

**Comment by fortezhuo** [comment]
Ah I see. But how to improve DX while changing tailwind class on creating component using nativewind ? 
I use styled API without "nativewind/babel" plugin, and seems the followed custom component url that suggested before won't work while changing tailwind class on dev env

**Comment by marklawlor** [comment]
Tailwind is a style preprocessor - there is no runtime style generation. There are multiple guides on the website, but if you only want to use the `styled()` API, using `nativewind/babel` in `compileOnly` mode is the simplest.

https://www.nativewind.dev/guides/babel-compile-only
