### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_nativewind.NativeWindStyleSheet.create')

### ISSUE THREAD

**Issue by itsramiel** [marklawlor/nativewind#316]
**Describe the bug**
I am trying to use with expo but after following the docs for expo, I get `TypeError: undefined is not an object (evaluating '_nativewind.NativeWindStyleSheet.create')` when starting the app

**To Reproduce**
1. initialize a new expo project
2. follow the docs for integrating with expo
3. run the app

**Expected behavior**
Nativewind to be working fine, without any errors

**Github Repo**
Here is a very minimal reproducable. https://github.com/itsramiel/tailwind-repro

**Comment by marklawlor** [comment]
Please reset your Babel cache as per https://www.nativewind.dev/guides/troubleshooting

You can also update to #308 which does not have this issue.

Duplicate #240 #286  #294

**Comment by itsramiel** [comment]
I tried running `expo start --clear` several times with no success. Can you try running by sample repo? I'll try to update to `next` but v2 is not working
