### ISSUE TITLE
No border on android images

### ISSUE THREAD

**Issue by stesvis** [marklawlor/nativewind#322]
**Describe the bug**
On Android the border does not apply to images. On iOS it works but not the 1px border (has to be 2px)

**To Reproduce**
This does not show any border on Android or iOS:
```jsx
<StyledImage 
        className="h-12 w-12 rounded-full border border-red-600" 
        source={require('./no-profile-icon.jpg')}/>
```

This only shows a 2px border on iOS:
```jsx
<StyledImage 
        className="h-12 w-12 rounded-full border-2 border-red-600" 
        source={require('./no-profile-icon.jpg')}/>
```

I also added a non-rounded image in the snack example to make sure that the issue was not caused by the rounded shape.

**Expected behavior**
The image should have a red border.

**Expo Snack**
https://snack.expo.dev/@stesvis/image-border?platform=android

**Screenshots**
See snack example.

**Comment by marklawlor** [comment]
This is a quirk of React Native, you need to add `overflow: hidden` when using `borderRadius`, especially on Android devices.

https://reactnative.dev/docs/view-style-props#borderradius

**Comment by marklawlor** [comment]
The Expo snacks are giving me 500 errors right now, but I know from experience that this issue is fairly device specific on android eg I just tested on a Pixel 4 and a Galaxy S10+ and both render fine without the `overflow:hidden`.

**Comment by stesvis** [comment]
> The Expo snacks are giving me 500 errors right now, but I know from experience that this issue is fairly device specific on android eg I just tested on a Pixel 4 and a Galaxy S10+ and both render fine without the `overflow:hidden`.

I am afraid the `overflow: "hidden"` is not making any difference...

**Comment by marklawlor** [comment]
Are you testing on device or in the emulator? Can you please provide more detail

Expo Snacks are now loading, but any changes I make are not reflected on the device or though my device when I use Expo Go

**Comment by stesvis** [comment]
I tried on expo snacks, on a local emulator (API 32) and on my device (Android 12). And on an iOS phone.
The image code is this:
```jsx
      <Image
        className="h-8 w-8 rounded-full border-2 border-red-600 overflow-hidden"
        source={require("../../../assets/no-profile-icon.jpg")}
        style={style}
      />
```

And see the screenshots. Only iOS shows the red border (i included it to verify that the border is indeed there).
I've tried with and without `overflow-hidden`. I also tried to add it as a style instead of the tailwindcss class, same result.

Emulator:
![android-emulator](https://user-images.githubusercontent.com/6062684/200438756-02b358c4-bace-476c-8e8a-d2b3403de9ee.png)

iPhone
![ios-simulator](https://user-images.githubusercontent.com/6062684/200438758-ef4397bb-62ed-40eb-9a8c-670a39903caf.PNG)

Android device
![android-device](https://user-images.githubusercontent.com/6062684/200438759-f7104edf-0194-49b3-b8cb-5c8ee32f1901.jpg)

**Comment by stesvis** [comment]
> Are you testing on device or in the emulator? Can you please provide more detail
> 
> Expo Snacks are now loading, but any changes I make are not reflected on the device or though my device when I use Expo Go

Expo Snacks says I need the tailwindcss depedency but it fails to install it...so i am not sure

**Comment by stesvis** [comment]
If I just use style it works on android:
```jsx
      <Image
        source={require("../../../assets/no-profile-icon.jpg")}
        style={{
          height: 32,
          width: 32,
          borderRadius: 16,
          borderWidth: 2,
          borderColor: "red",
        }}
      />
```

![Screenshot_1667879385](https://user-images.githubusercontent.com/6062684/200470878-b8968fe9-a97a-4e31-b860-a27253f873f2.png)

**Comment by marklawlor** [comment]
I cannot replicate your issue in the emulator or on devices. My best advise is to try and upgrade to the `next` branch #308 and resetting your babel/metro cache

**Comment by stesvis** [comment]
> I cannot replicate your issue in the emulator or on devices. My best advise is to try and upgrade to the `next` branch #308 and resetting your babel/metro cache

Do you mean that the border shows correctly on your side using tailwind classes?

**Comment by stesvis** [comment]
I wanted to ask what is the difference between
```jsx
<Image className="h24 w-24 rounded" source={require("my-image.png"} />
```
and
```jsx
const StyledImage = styled(Image);

<StyledImage className="h24 w-24 rounded" source={require("my-image.png"} />
```

Does `style()` only provide intellisense for the `className` property? I can't see any difference in the end result.

**Comment by marklawlor** [comment]
> Do you mean that the border shows correctly on your side using tailwind classes?

Yes I see the border.

`styled()` does other things like add event handlers if you are using classNames that need them (`hover:*`/`active:*`) and/or modify the children if needed. But for your example it should simply be setting the `style` prop. 

If you write 

```
const StyledImage = styled((props) => {
  console.log(props)
  return <Image {...props } />
})
```

You can see the prop's its passing though.

**Comment by stesvis** [comment]
Could I have some misconfiguration? Any config file that you'd like me to post here to double check if everything is configured correctly?

**Comment by marklawlor** [comment]
If your seeing the correct props being passed though, then everything has been configured correctly. What I don't understand is why manual inline styles work but the inline styles passed from `styled()` do not.

I also just realized I may of accidently done my testing on the `next` branch.

**Comment by stesvis** [comment]
I tried to migrate to the `next` branch and follow the instructions but when i started the app i got the error:

> Error: Cannot find module 'nativewind/metro'

So maybe i did something wrong. I believe I cleared the cache with `expo start -c` and tried also `npx expo start -c`

**Comment by stesvis** [comment]
I don't have it at the moment (i reverted back to the stable release). Is it supposed to be created after the `next` installation?

**Comment by marklawlor** [comment]
You cannot use the `next` project setup with the `stable` version, the project setups changed between the two. See the breaking changes of #308

**Comment by stesvis** [comment]
Yes I was just asking whether the metro.js file is supposed to exist only in `next` or also in the stable version.
If it's supposed to exist in both, then I definitely do not have it in the stable version.
I'll try `next` once I can upgrade it again.

**Comment by stesvis** [comment]
I was able to configure everything and now I see the red border finally! Thank you so much.
