### ISSUE TITLE
Can't customize theme to change default font sizes

### ISSUE THREAD

**Issue by stesvis** [marklawlor/nativewind#323]
**Describe the bug**
Can't change the default `fontSize` (aka `text-base`).
I followed [this sample](https://tailwindcss.com/docs/font-size#customizing-your-theme) and tested with double font size `base: "2rem"`

**To Reproduce**
My **tailwind.config.js**:
```js
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
    fontSize: {
      sm: "0.8rem",
      base: "2rem",
      xl: "1.25rem",
      "2xl": "1.563rem",
      "3xl": "1.953rem",
      "4xl": "2.441rem",
      "5xl": "3.052rem",
    },
  },
  plugins: ["nativewind"],
};
```

**Expected behavior**
Base font size should double but instead it looks the same.

Is it a known bug? Or how to change the default fontSize?

**Comment by marklawlor** [comment]
`rem` units are not currently supported. They will be available in the next release see #308

**Comment by stesvis** [comment]
I installed the `next` release `"nativewind": "^3.0.0-next.15"` but I still can't see any changes in the font sizes.
I also tried to set it using pixels like `base: "20px",`  or just a number `base: 20`

What are my options to define custom font sizes?

**Comment by marklawlor** [comment]
Your theme looks incorrect, `next` changed from being a plugin to a preset. See #308 

Here is a working version https://github.com/marklawlor/nativewind-react-native-cli/tree/font-sizes

**Comment by stesvis** [comment]
Thank you, I am finding some issues with v`next`, some random crashes when using certain classes that worked before.
At the moment there would be too much to refactor.

Do you know if there is a way to customize the font size in the stable release?
I know that you said `rem` values are not supported, is there another option?

**Comment by stesvis** [comment]
> `stable` only supports `px`, however there are various issues with babel/cache `tailwind.config.js` (#235), so may need to update your babel cache.
> 
> Can you please list your issues with `next` in #308

Would you be able to tell me the steps to make it work with `px` in `stable`?
