### ISSUE TITLE
className Type declaration 

### ISSUE THREAD

**Issue by Lihemen** [marklawlor/nativewind#326]
**Describe the bug**
While using nativewind with RN+Typescript, red squiggly lines appear below the className property with the error No overload matches this call. Although the className property works and allows for styling, it just looks ugly

**To Reproduce**
1. Setup an expo Typescript project 
2. Add support for nativewind
3. Add a className property to any native element

**Expected behavior**
It is expected that the type declaration for className be supported and the tsc not show an error underline

**Screenshots**
![16681534739302736057521930393255](https://user-images.githubusercontent.com/56772226/201293329-e99412a6-d262-4694-938f-041c25f1ed28.jpg)

**Additional context**

**Comment by marklawlor** [comment]
Please follow the typescript setup instructions https://www.nativewind.dev/getting-started/typescript
