### ISSUE TITLE
Typed helper for Nativewind variants

### ISSUE THREAD

**Issue by steida** [marklawlor/nativewind#328]
I miss autocomplete for variants defined outside of className, so I made a small helper for that. Maybe it can be useful for Nativewind. Having variants defined within className allows us to style components made from more elements, for example, a Button with Pressable and Text inside it.

```ts
/** Typed helper for Nativewind. */
export const variant = <V extends string | number>(
  value: V,
  styles: { [key in V]: string }
): string => styles[value];
```

```tsx
className={clsx(
  "mb-4 mt-2 text-gray-900 dark:text-gray-200 dark:antialiased",
  variant(level, {
    1: "text-3xl",
    2: "text-2xl",
    3: "text-xl",
  })
)}
```

**Comment by Jonatthu** [comment]
Add the vscode regex pattern, that the documentation tells you! Add an extra one change styled word for variants on that regex! That worked for me.

**Comment by steida** [comment]
@Jonatthu Where exactly, please?

**Comment by Jonatthu** [comment]
```
	"tailwindCSS.classAttributes": [
		"class",
		"className",
		"classNames",
		"ngClass",
		"style",
	],
	"tailwindCSS.experimental.classRegex": [
		[
			"styled\\(.+,([^)]*)\\)",
			"[\"'`]([^\"'`]*).*?[\"'`]"
		],
		[
			"styled\\(.+, .+,([^)]*)\\)",
			"[\"'`]([^\"'`]*).*?[\"'`]"
		],
		[
			"variants\\(([^)]*)\\)",
			"[\"'`]([^\"'`]*).*?[\"'`]"
		],
		[
			"clsx\\(([^)]*)\\)",
			"[\"'`]([^\"'`]*).*?[\"'`]"
		]
	],
```

**Comment by steida** [comment]
@Jonatthu Your regex does not work for me for some reason, but https://github.com/paolotiu/tailwind-regex-list works, but without Prettier autoformat...
