### ISSUE TITLE
Expo web needs restart when adding a new class

### ISSUE THREAD

**Issue by rborn** [marklawlor/nativewind#329]
**Describe the bug**
It looks like hot reload is not fully working on expo web.  It does work on ios as it fully rebuilds

**To Reproduce**

Set the App.tsx to return 
```
  return (
    <View className={"flex-1 items-center justify-center"}>
      <View className={"bg-pink-500"}>
        <Text className="p-4">Web</Text>
        <StatusBar style="auto" />
      </View>
    </View>
  );
```
Start `expo web`

Change the inner View to 
```
      <View className={"bg-blue-500"}>
```
It will lose the bg color, restart `expo web` -> we're blue now

**Expected behavior**
Recompile styles on hot reload

I'm using nativewind@next with this instructions  https://github.com/marklawlor/nativewind/issues/308 and had to keep webpack.config.js

Thank you 🙏

**Comment by marklawlor** [comment]
This is not a NativeWind issue so I'm going to close it, but I would like to continue the discussion.

Hot reloading Tailwind CSS is a Tailwind CSS/webpack issue. This previously worked fine, but Expo has not yet been updated to Webpack 5, and all the plugins have been upgraded / moved on. So you have to use older webpack loaders, which don't work as well with the newer versions of PostCSS/Tailwind. The solution could be to downgrade, but then you lose the JIT features of Tailwind 😢 

If you can find a combination of webpack loaders/postcss versions that work I'll happily document it. I'm adding a section about this in the new docs (currently in process)

The other option is simply refreshing the browser page so it loads the new styles.

**Comment by rborn** [comment]
Thank you for replying 🙂

Refresh won't work. If I find any way I'll let you know.
