### ISSUE TITLE
[Next] style prop of pressable is not receiving pressed argument when className is used

### ISSUE THREAD

**Issue by itsramiel** [marklawlor/nativewind#331]
**Describe the bug**
The `style` prop of __Pressable__ can be a function which takes an object with `pressed` value to return different style depending on state is pressed or not. It works fine if `style` props is used without `className`, but if both `style` and `className` are used then the `pressed` argument is not working anymore.

**To Reproduce**
1. use Pressable component
2. use `style` prop to style it differently depending if pressed
3. add `className` to Pressable
4. Pressable no longer show different style depening if pressed

**Expected behavior**
`className` does not affect `style`

**Repo**
https://github.com/itsramiel/nativewind-pressable/tree/repro/style-pressable

**Comment by marklawlor** [comment]
`className` affecting `style` is entirely how this library works. I'm on the fence for support style functions, can you provide your use-case in more detail?

**Comment by itsramiel** [comment]
My bad, you are right that it should affect it, but what I expect is styles defined in `className` to override styles in `style` prop which is what happens with other components, except for Pressable which just stops passing the pressed state at all. 

My use-case is really to have a different opacity for the `Pressable` component depending on if it is pressed or not, which is achieved using style functions.

**Comment by marklawlor** [comment]
You can achieve this with the `active:` modifier eg `bg-red-500 active:bg-red-500/50` will show the background colour red at 50% opacity when pressed.

The reason I'm on the fence about the style functions is that people seem to only use them to implement functionality that NativeWind already provides!

**Comment by itsramiel** [comment]
Alright interesting. I was not aware of the modifiers and i will most likely solve my use case, but in my opinion I think the `style` props should still maintain its original behavior of receiving the pressed boolean.

**Comment by marklawlor** [comment]
Closing this issue, as it has been added to the feature request project
