### ISSUE TITLE
v3: SyntaxError

### ISSUE THREAD

**Issue by chenhb23** [marklawlor/nativewind#344]
**Describe the bug**
return config withNativewind while start a metro server

```shell
error: SyntaxError: /Users/home/Documents/work/xxx/node_modules/.cache/nativewind/output.js: Missing initializer in destructuring declaration. (1:30)

> 1 | const { NativeWindStyleSheet } from "nativewind/dist/style-sheet";
    |                               ^
  2 | NativeWindStyleSheet.create({"absolute":{"styles":[{"position":"absolute"}]},"inset-0":{"styles":[{"top":0,"right":0,"bottom":0,"left":0}]},"mb-1":{"styles":[{"marginBottom":4}]},"mt-10":{"styles":[{"marginTop":40}]},"flex":{"styles":[{"display":"flex"}]},"h-10":{"styles":[{"height":40}]},"h-[130px]":{"styles":[{"height":130}]},"h-full":{"styles":[{"height":"100%"}]},"w-full":{"styles":[{"width":"100%"}]},"w-[200px]":{"styles":[{"width":200}]},"flex-1":{"styles":[{"flexGrow":1,"flexShrink":1,"flexBasis":"0%"}]},"flex-row":{"styles":[{"flexDirection":"row"}]},"items-center":{"styles":[{"alignItems":"center"}]},"justify-center":{"styles":[{"justifyContent":"center"}]},"justify-between":{"styles":[{"justifyContent":"space-between"}]},"border":{"styles":[{"borderWidth":1}]},"bg-black/70":{"styles":[{"backgroundColor":"rgb(0, 0, 0, 0.7)"}]},"p-2":{"styles":[{"padding":8}]},"px-6":{"styles":[{"paddingLeft":24,"paddingRight":24}]},"py-4":{"styles":[{"paddingTop":16,"paddingBottom":16}]},"pt-6":{"styles":[{"paddingTop":24}]},"pb-8":{"styles":[{"paddingBottom":32}]},"text-yellow-800":{"styles":[{"color":"#854d0e"}]},"text-orange-500":{"styles":[{"color":"#f97316"}]},"text-xl":{"styles":[{"fontSize":20,"lineHeight":28}]},"text-sm":{"styles":[{"fontSize":14,"lineHeight":20}]}});
```

**To Reproduce**

outputJSPath: `node_modules/.cache/nativewind/output.js`

```ts
const { NativeWindStyleSheet } from "nativewind/dist/style-sheet";
NativeWindStyleSheet.create({"absolute":{"styles":[{"position":"absolute"}]}...
```

**Expected behavior**

change `const` to `import`

```ts [1]
import { NativeWindStyleSheet } from "nativewind/dist/style-sheet";
NativeWindStyleSheet.create({"absolute":{"styles":[{"position":"absolute"}]}...
```

**Screenshots**

<img width="884" alt="image" src="https://user-images.githubusercontent.com/74194963/203534414-40ec420e-807b-479d-802f-143b19193915.png">

**Comment by marklawlor** [comment]
What version are you running? The current `next` output looks like this https://github.com/marklawlor/nativewind/blob/c9f60d47518a871cd83fd406b8ff4d17450a4f77/packages/nativewind/src/metro/tailwind.ts#L116

**Comment by chenhb23** [comment]
> What version are you running? The current `next` output looks like this
> 
> https://github.com/marklawlor/nativewind/blob/c9f60d47518a871cd83fd406b8ff4d17450a4f77/packages/nativewind/src/metro/tailwind.ts#L116

```json
"nativewind": "^3.0.0-next.28",
```

**Comment by marklawlor** [comment]
Can you please share your repo? I'm quite confused how you got that error with the current version.

**Comment by chenhb23** [comment]
I'm sorry to share the private repo...

use `yarn add nativewind@next` will install `"nativewind": "^3.0.0-next.28",`

---

the follow is my patches:

```patch
diff --git a/node_modules/nativewind/dist/metro/index.js b/node_modules/nativewind/dist/metro/index.js
index f638ba1..b053539 100644
--- a/node_modules/nativewind/dist/metro/index.js
+++ b/node_modules/nativewind/dist/metro/index.js
@@ -31,7 +31,7 @@ function withNativeWind(config, { inputPath, postcssPath } = {}) {
         cli.stdout.on("data", (data) => {
             const output = data.toString().trim();
             const createOptions = JSON.stringify((0, extract_1.getCreateOptions)(output));
-            (0, node_fs_1.writeFileSync)(outputFile, `const { NativeWindStyleSheet } from "nativewind/dist/style-sheet";\nNativeWindStyleSheet.create(${createOptions});`);
+            (0, node_fs_1.writeFileSync)(outputFile, `import { NativeWindStyleSheet } from "nativewind/dist/style-sheet";\nNativeWindStyleSheet.create(${createOptions});`);
         });
         cli.stderr.on("data", (data) => {
             const output = data.toString().trim();

```

**Comment by marklawlor** [comment]
@chenhb23 What is the version number inside your `node_modules/nativewind/package.json`? 

If I create a new folder and run `npm init && npm i nativewind@3.0.0-next.28` and inspect `node_modules/nativewind/dist/metro/index.js` it does not contain the code for your patch.

**Comment by chenhb23** [comment]
@marklawlor 

<img width="840" alt="image" src="https://user-images.githubusercontent.com/74194963/203553037-0cba8881-dfbd-4dae-b10d-2f962cfa0b15.png">

**Comment by marklawlor** [comment]
Can you please follow these steps

* Create a new folder
* cd into that folder and run `npm init`
* Run `npm install nativewind@3.0.0-next.28`
* Verify that `node_modules/nativewind/dist/metro.js` has the problematic code

I have run this on two computers and am unable to replicate your issue

**Comment by chenhb23** [comment]
it's ok now, maybe the cache of yarn is update

**Comment by RaederDev** [comment]
I have the same issue, with `^3.0.0-next.34`. 

Package.json from node_modules/nativewind:
```json
{
  "version": "3.0.0-next.1-9-g4f4fcc8",
  "name": "nativewind",
  "description": "Use Tailwindcss in your cross-platform React Native applications",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "sideEffects": false,
  "keywords": [
    "react-native",
    "react",
    "native",
    "tailwind",
    "tailwindcss",
    "theme",
    "style"
  ],
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/marklawlor/nativewind.git"
  },
  "author": {
    "name": "Mark Lawlor",
    "url": "https://github.com/marklawlor"
  },
  "homepage": "https://nativewind.dev",
  "bugs": {
    "url": "https://github.com/marklawlor/nativewind/issues"
  },
  "engines": {
    "node": ">=14.18"
  },
  "scripts": {
    "test": "jest",
    "test:debug": "node --inspect-brk node_modules/.bin/jest --runInBand",
    "lint": "eslint .",
    "prepublishOnly": "npm run build",
    "build": "rm -rf dist && tsc -p tsconfig.build.json",
    "experiment": "npm run build;npm version $(git describe --tags) --no-git-tag-version;npm publish --tag experiment"
  },
  "files": [
    "babel.js",
    "dist/",
    "metro.js",
    "plugin.js",
    "postcss.js",
    "tailwind.js",
    "tailwind/",
    "types.d.ts"
  ],
  "dependencies": {
    "@babel/helper-module-imports": "7.18.6",
    "@babel/types": "7.19.0",
    "css-tree": "^2.2.1",
    "find-cache-dir": "^3.3.2",
    "micromatch": "^4.0.5",
    "postcss": "^8.4.12",
    "proper-lockfile": "^4.1.2",
    "react-is": "^18.1.0",
    "use-sync-external-store": "^1.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.19.1",
    "@babel/plugin-syntax-jsx": "7.18.6",
    "@testing-library/react-hooks": "8.0.1",
    "@testing-library/react-native": "11.1.0",
    "@types/css-tree": "^1.0.7",
    "@types/find-cache-dir": "^3.2.1",
    "@types/jest": "29.0.3",
    "@types/micromatch": "4.0.2",
    "@types/proper-lockfile": "^4.1.2",
    "@types/react": "18.0.21",
    "@types/react-is": "17.0.3",
    "@types/react-native": "0.70.3",
    "@types/use-sync-external-store": "0.0.3",
    "babel-plugin-tester": "10.1.0",
    "jest": "29.0.3",
    "jest-environment-jsdom": "29.0.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.70.1",
    "react-native-svg": "13.2.0",
    "react-native-web": "0.18.9",
    "react-test-renderer": "^18.2.0",
    "tailwindcss": "3.1.8",
    "ts-jest": "29.0.2",
    "typescript": "4.8.3"
  },
  "peerDependencies": {
    "tailwindcss": "~3"
  }
}
```

node_modules/nativewind/dist/metro/index.js contains:
```js
cli.stdout.on("data", (data) => {
            const output = data.toString().trim();
            const createOptions = JSON.stringify((0, extract_1.getCreateOptions)(output));
            (0, node_fs_1.writeFileSync)(outputFile, `const { NativeWindStyleSheet } from "nativewind/dist/style-sheet";\nNativeWindStyleSheet.create(${createOptions});`);
        });
```

**Comment by marklawlor** [comment]
This issue was because the user had a cached version installed instead of the latest. If you have cleared your caches (both your package manager & React Native) and still have an issue please create a new issue.

**Comment by kyle-belle** [comment]
on the latest version of nativewind@next (cleared my entire yarn cache using `yarn cache clean` and start react-native with --resetCache option

it still has the erroneous  (but im not sure its causing any issues, im kinda having another issue but not sure if its just something caused by my metro config or yarn workspace settings)
![Screenshot from 2023-11-16 02-31-58](https://github.com/marklawlor/nativewind/assets/43228761/caeafffc-f62a-4422-a8cc-6d01cf56d027)

HERE is my current issue btw (just in case its something you are able to offer insights on)
```cmd
rror: Error: Unable to resolve module /home/kyle/Documents/Thrive/packages/mobile/node_modules/.cache/nativewind/output.js from /home/kyle/Documents/Thrive/packages/mobile/node_modules/nativewind/dist/index.js: 

None of these files exist:
  * node_modules/.cache/nativewind/output.js(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * node_modules/.cache/nativewind/output.js/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
> 1 | "use strict";
  2 | var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
  3 |     if (k2 === undefined) k2 = k;
  4 |     var desc = Object.getOwnPropertyDescriptor(m, k);
    at ModuleResolver.resolveDependency (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 4)
    at async Graph._processModule (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/home/kyle/Documents/Thrive/packages/mobile/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
```

**Comment by kyle-belle** [comment]
actually i can confirm this is the reason the above error is happening. when i manually went and changed `const` to `import` that fixed that particular issue for me

**Comment by kyle-belle** [comment]
> I have the same issue, with `^3.0.0-next.34`.
> 
> Package.json from node_modules/nativewind:
> 
> ```json
> {
>   "version": "3.0.0-next.1-9-g4f4fcc8",
>   "name": "nativewind",
>   "description": "Use Tailwindcss in your cross-platform React Native applications",
>   "main": "dist/index.js",
>   "types": "dist/index.d.ts",
>   "sideEffects": false,
>   "keywords": [
>     "react-native",
>     "react",
>     "native",
>     "tailwind",
>     "tailwindcss",
>     "theme",
>     "style"
>   ],
>   "license": "MIT",
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/marklawlor/nativewind.git"
>   },
>   "author": {
>     "name": "Mark Lawlor",
>     "url": "https://github.com/marklawlor"
>   },
>   "homepage": "https://nativewind.dev",
>   "bugs": {
>     "url": "https://github.com/marklawlor/nativewind/issues"
>   },
>   "engines": {
>     "node": ">=14.18"
>   },
>   "scripts": {
>     "test": "jest",
>     "test:debug": "node --inspect-brk node_modules/.bin/jest --runInBand",
>     "lint": "eslint .",
>     "prepublishOnly": "npm run build",
>     "build": "rm -rf dist && tsc -p tsconfig.build.json",
>     "experiment": "npm run build;npm version $(git describe --tags) --no-git-tag-version;npm publish --tag experiment"
>   },
>   "files": [
>     "babel.js",
>     "dist/",
>     "metro.js",
>     "plugin.js",
>     "postcss.js",
>     "tailwind.js",
>     "tailwind/",
>     "types.d.ts"
>   ],
>   "dependencies": {
>     "@babel/helper-module-imports": "7.18.6",
>     "@babel/types": "7.19.0",
>     "css-tree": "^2.2.1",
>     "find-cache-dir": "^3.3.2",
>     "micromatch": "^4.0.5",
>     "postcss": "^8.4.12",
>     "proper-lockfile": "^4.1.2",
>     "react-is": "^18.1.0",
>     "use-sync-external-store": "^1.1.0"
>   },
>   "devDependencies": {
>     "@babel/core": "7.19.1",
>     "@babel/plugin-syntax-jsx": "7.18.6",
>     "@testing-library/react-hooks": "8.0.1",
>     "@testing-library/react-native": "11.1.0",
>     "@types/css-tree": "^1.0.7",
>     "@types/find-cache-dir": "^3.2.1",
>     "@types/jest": "29.0.3",
>     "@types/micromatch": "4.0.2",
>     "@types/proper-lockfile": "^4.1.2",
>     "@types/react": "18.0.21",
>     "@types/react-is": "17.0.3",
>     "@types/react-native": "0.70.3",
>     "@types/use-sync-external-store": "0.0.3",
>     "babel-plugin-tester": "10.1.0",
>     "jest": "29.0.3",
>     "jest-environment-jsdom": "29.0.3",
>     "metro-react-native-babel-preset": "0.72.3",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-native": "0.70.1",
>     "react-native-svg": "13.2.0",
>     "react-native-web": "0.18.9",
>     "react-test-renderer": "^18.2.0",
>     "tailwindcss": "3.1.8",
>     "ts-jest": "29.0.2",
>     "typescript": "4.8.3"
>   },
>   "peerDependencies": {
>     "tailwindcss": "~3"
>   }
> }
> ```
> 
> node_modules/nativewind/dist/metro/index.js contains:
> 
> ```js
> cli.stdout.on("data", (data) => {
>             const output = data.toString().trim();
>             const createOptions = JSON.stringify((0, extract_1.getCreateOptions)(output));
>             (0, node_fs_1.writeFileSync)(outputFile, `const { NativeWindStyleSheet } from "nativewind/dist/style-sheet";\nNativeWindStyleSheet.create(${createOptions});`);
>         });
> ```

was having the exact same issue down to the same package.json and all.
i am using yarn. i did 
`yarn remove nativewind`
then
`yarn cache clean nativewind` and `yarn cache clean nativewind@next`

and that seems to have solved the issue

**Comment by kyle-belle** [comment]
> I have the same issue, with `^3.0.0-next.34`.
> 
> Package.json from node_modules/nativewind:
> 
> ```json
> {
>   "version": "3.0.0-next.1-9-g4f4fcc8",
>   "name": "nativewind",
>   "description": "Use Tailwindcss in your cross-platform React Native applications",
>   "main": "dist/index.js",
>   "types": "dist/index.d.ts",
>   "sideEffects": false,
>   "keywords": [
>     "react-native",
>     "react",
>     "native",
>     "tailwind",
>     "tailwindcss",
>     "theme",
>     "style"
>   ],
>   "license": "MIT",
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/marklawlor/nativewind.git"
>   },
>   "author": {
>     "name": "Mark Lawlor",
>     "url": "https://github.com/marklawlor"
>   },
>   "homepage": "https://nativewind.dev",
>   "bugs": {
>     "url": "https://github.com/marklawlor/nativewind/issues"
>   },
>   "engines": {
>     "node": ">=14.18"
>   },
>   "scripts": {
>     "test": "jest",
>     "test:debug": "node --inspect-brk node_modules/.bin/jest --runInBand",
>     "lint": "eslint .",
>     "prepublishOnly": "npm run build",
>     "build": "rm -rf dist && tsc -p tsconfig.build.json",
>     "experiment": "npm run build;npm version $(git describe --tags) --no-git-tag-version;npm publish --tag experiment"
>   },
>   "files": [
>     "babel.js",
>     "dist/",
>     "metro.js",
>     "plugin.js",
>     "postcss.js",
>     "tailwind.js",
>     "tailwind/",
>     "types.d.ts"
>   ],
>   "dependencies": {
>     "@babel/helper-module-imports": "7.18.6",
>     "@babel/types": "7.19.0",
>     "css-tree": "^2.2.1",
>     "find-cache-dir": "^3.3.2",
>     "micromatch": "^4.0.5",
>     "postcss": "^8.4.12",
>     "proper-lockfile": "^4.1.2",
>     "react-is": "^18.1.0",
>     "use-sync-external-store": "^1.1.0"
>   },
>   "devDependencies": {
>     "@babel/core": "7.19.1",
>     "@babel/plugin-syntax-jsx": "7.18.6",
>     "@testing-library/react-hooks": "8.0.1",
>     "@testing-library/react-native": "11.1.0",
>     "@types/css-tree": "^1.0.7",
>     "@types/find-cache-dir": "^3.2.1",
>     "@types/jest": "29.0.3",
>     "@types/micromatch": "4.0.2",
>     "@types/proper-lockfile": "^4.1.2",
>     "@types/react": "18.0.21",
>     "@types/react-is": "17.0.3",
>     "@types/react-native": "0.70.3",
>     "@types/use-sync-external-store": "0.0.3",
>     "babel-plugin-tester": "10.1.0",
>     "jest": "29.0.3",
>     "jest-environment-jsdom": "29.0.3",
>     "metro-react-native-babel-preset": "0.72.3",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-native": "0.70.1",
>     "react-native-svg": "13.2.0",
>     "react-native-web": "0.18.9",
>     "react-test-renderer": "^18.2.0",
>     "tailwindcss": "3.1.8",
>     "ts-jest": "29.0.2",
>     "typescript": "4.8.3"
>   },
>   "peerDependencies": {
>     "tailwindcss": "~3"
>   }
> }
> ```
> 
> node_modules/nativewind/dist/metro/index.js contains:
> 
> ```js
> cli.stdout.on("data", (data) => {
>             const output = data.toString().trim();
>             const createOptions = JSON.stringify((0, extract_1.getCreateOptions)(output));
>             (0, node_fs_1.writeFileSync)(outputFile, `const { NativeWindStyleSheet } from "nativewind/dist/style-sheet";\nNativeWindStyleSheet.create(${createOptions});`);
>         });
> ```

was having the exact same issue down to the same package.json and all.
i am using yarn. i did 
`yarn remove nativewind`
then
`yarn cache clean nativewind` and `yarn cache clean nativewind@next`

and that seems to have solved the issue

**Comment by kyle-belle** [comment]
Actually somehow the exact same issue came back. idk how since im not changing the versions of anything. to be fair i am kind of deleting my node_modules folder fairly frequently as im trying to debug something else but this somehow came back up. I am only using nativewind in one place/package.json
