### ISSUE TITLE
overflow-visible not working

### ISSUE THREAD

**Issue by rosanche** [marklawlor/nativewind#345]
`overflow-visible` className isn't working.

When I put it directly in the styleSheet with `style={{ overflow: 'visible' }}`, it's working totally fine....

**Comment by marklawlor** [comment]
Can you please try the `next` branch. The setup instructions are detailed here #308

**Comment by marklawlor** [comment]
Closing due to lack of response. I was unable to reproduce with the current version, so leads me to believe this may be a configuration issue.
