### ISSUE TITLE
How to use plugins ?

### ISSUE THREAD

**Issue by chrisarts** [marklawlor/nativewind#346]
**Describe the bug**
How to use external plugins like daisyUI ? I try to use it but the output shows some rem values that crashes on expo, is there any way to create a patch or transform function to change those values on native ?

**To Reproduce**

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by marklawlor** [comment]
Plugins work exactly has described here https://tailwindcss.com/docs/plugins

NativeWind is not a full featured CSS engine - we only try to support the same feature set of TailwindCSS. DaisyUI extends Tailwind and takes advantage of all the features of CSS such as inheritance and composite styles. As such it doesn't work with NativeWind
