### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by chirag-codealchemy** [marklawlor/nativewind#348]
tailwind.config.js

/** @type {import('tailwindcss').Config} */

// const nativewind = require("nativewind/tailwind")

module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}", 
    "./pages/**/*.{js,jsx,ts,tsx}", 
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [require('nativewind/tailwind/css')],
  // presets: [nativewind],
  important: 'html',
  theme: {
    extend: {},
  },
}

babel.config.js

module.exports = {
    presets: ["babel-preset-expo"],
    plugins: ['nativewind/babel'],
};

![Screenshot 2022-11-28 at 11 49 52 AM](https://user-images.githubusercontent.com/111970008/204207546-02b819a2-2c6c-4523-8152-0eb391e3bb3e.png)

**Comment by marklawlor** [comment]
This appears to be a Expo or Next.js project using React Native Web. You are getting that error because you have not setup transpilation for your app. Please consult the setup instructions on React Native Web for your choosen platform, as you may need to add NativeWind to your transpilation allow list

**Comment by chirag-codealchemy** [comment]
some how i slove this error but the style is not working in web 
what i change 

next.config.js

const { withExpo } = require('@expo/next-adapter')
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')([
    "react-native-web",
    "solito",
    "expo-linking",
    "next-images",
    "next-fonts",
    "nativewind"  < --- add this line 
  ])

module.exports = withPlugins(
    [withTM, [withExpo, { projectRoot: __dirname, webpack5: true }]],
    {}
)

babel.config.js

module.exports =   {
    presets: ["@expo/next-adapter/babel"],
    plugins: [
    [
        '@babel/plugin-proposal-class-properties', 
        { loose: true }
    ], 
    [
        '@babel/plugin-proposal-private-methods', 
        { loose: true }
    ],
    [
      '@babel/plugin-proposal-private-property-in-object',
      { loose: true }
    ],
    [
        'nativewind/babel', 
        { mode: 'transformOnly' }
    ],
    ],
};
  
but style is not working

**Comment by marklawlor** [comment]
Do TailwindCSS styles on a `div` work?

**Comment by chirag-codealchemy** [comment]
can i share my code

**Comment by marklawlor** [comment]
Please share the entire repo if you do

**Comment by chirag-codealchemy** [comment]
https://github.com/chirag-codealchemy/expo-next-main

**Comment by marklawlor** [comment]
You need to follow the Tailwind CSS setup guide for Next.js https://tailwindcss.com/docs/guides/nextjs and include the required CSS file.

**Comment by chirag-codealchemy** [comment]
now i complated setup but still not working

**Comment by marklawlor** [comment]
The current version of NativeWind works better as a monorepo - where configs are not changed between apps. The `next` version #308 makes this setup easier

**Comment by chirag-codealchemy** [comment]
so i should change version

**Comment by marklawlor** [comment]
That is entirely up-to-you. I think the `next` version is simpler to use and fixes a lot of things with the current version, but its not finished so it comes with the usual early access disclaimers

**Comment by chirag-codealchemy** [comment]
i change to next version and getting new problem 
TypeError: tokens.join(...).trimStart(...).replace(...).replace(...).replaceAll is not a function
![Screenshot 2022-11-28 at 5 43 01 PM](https://user-images.githubusercontent.com/111970008/204275046-63e86d8f-9dd3-4caf-90a1-57c13b431240.png)

**Comment by marklawlor** [comment]
`next` requires Node 16+

**Comment by chirag-codealchemy** [comment]
sir can you help me to setup one expo with next js project with nativewinde integration 
like me can you create one demo project and setup netivewind in expo and next js i am newbee and i don't know many thing so please can you help me

**Comment by marklawlor** [comment]
I unfortunately do not have the capacity. If you are new, you should start a starter project instead of trying to setup from scratch

For example:

`npx create-solito-app@latest my-solito-app -t with-tailwind` which comes from https://solito.dev/tailwind`

There a couple of other projects from the community on Github
