### ISSUE TITLE
Text size fails to convert to double

### ISSUE THREAD

**Issue by ospfranco** [marklawlor/nativewind#351]
**Describe the bug**
When using one of the font size classes (text-base for example) in a custom component, I'm getting a runtime error saying "1rem" cannot be casted to a double, followed by an application crash:

![screen](https://user-images.githubusercontent.com/1634213/204779397-01659ff7-d276-472d-bc38-ff84e6e46e97.png)

I'm not able to figure out why it is behaving like this, maybe due a custom font? or because of the custom component?

```ts
import React, {FC} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  TextProps,
  Switch as RNSwitch,
  SwitchProps,
} from 'react-native';

type ITProps = TextProps;

export const T: FC<ITProps> = ({children, style}) => {
  return <Text style={[styles.baseText, style]}>{children}</Text>;
};


// And then on my component
<T className="text-base">Quack</T>
```

**Expected behavior**
1rem class should not be passed to the text component but rather the actual number size.

**Comment by marklawlor** [comment]
Classes using REM units are not available in the current `stable`. If you upgrade to `next` (see pinned issue #308) you can use them.

**Comment by ospfranco** [comment]
You closed this too fast, I don't care about rem units, just want to set a smaller font size, which in theory does not require `next`

I'm also having problems updating to next, the only example you provided is for expo, but the current configuration I have doesn't seem to be working:

```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const {getDefaultConfig} = require('metro-config');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withNativewind = require('nativewind/metro');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
    ...rest
  } = await getDefaultConfig(__dirname);
  const config = {
    ...rest,
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: [...assetExts.filter(ext => ext !== 'svg'), 'bin', 'jar'],
      sourceExts: [...sourceExts, 'svg'],
    },
  };
  console.warn('config before native wind');
  console.warn(config);
  console.warn('config AFTER native wind');
  console.warn(withNativewind(config));

  return config;
})();
```

Any idea what might be wrong?

**Comment by ospfranco** [comment]
I managed to get metro to work with the following config:

```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const {getDefaultConfig} = require('metro-config');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withNativewind = require('nativewind/metro');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
    ...rest
  } = await getDefaultConfig(__dirname);
  const config = {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      getTransformOptions: rest.transformer.getTransformOptions,
    },
    resolver: {
      assetExts: [...assetExts.filter(ext => ext !== 'svg'), 'bin', 'jar'],
      sourceExts: [...sourceExts, 'svg'],
    },
  };

  return withNativewind(config);
})();
```

But now when the app loads the bundle I get a runtime error:

```
Error: tailwindcss plugin function argument object prop "web" not implemented, js engine: hermes
```

**Comment by marklawlor** [comment]
> You closed this too fast, I don't care about rem units, just want to set a smaller font size, which in theory does not require next

NativeWind overrides your theme `fontSizes` to `px` values, so if `text-base` is giving an rem value then I assumed you had overridden it's value, or were using a plugin that sets it.

If I test `text-base` in a new project, it render correctly without error and the Expo Snacks appear to be working fine.

> Error: tailwindcss plugin function argument object prop "web" not implemented, js engine: hermes

I would need to see your `tailwind.config.js` to debug

**Comment by marklawlor** [comment]
@ospfranco What platform are you using iOS/Android/Web/etc?

**Comment by ospfranco** [comment]
ah, now I understand, yeah, I was using TWRNC which did allow to replace the fontSizes with rem values. After removing the sizes now it works.

I hope the problems I faced with `next` are still useful to you though. Thanks a lot for the help!
