### ISSUE TITLE
[NEXT] Babel preset throws when nativewind tailwind preset loaded indirectly

### ISSUE THREAD

**Issue by nderscore** [marklawlor/nativewind#352]
**Describe the bug**

When the nativewind tailwind preset is loaded indirectly, such as may be the case when using a shared configuration in a monorepo workspace ([like in this example from the create-t3-turbo template](https://github.com/t3-oss/create-t3-turbo/tree/main/packages/config/tailwind)) the babel plugin throws an error: 

> NativeWind preset was not included

This is caused by this check to see if the `nativewind` preset is in the current tailwind config:

https://github.com/marklawlor/nativewind/blob/0e285148072ea0ab381fedb64185b80ad64493df/packages/nativewind/src/babel/index.ts#L76-L86

**To Reproduce**

Minimal reproduction:

`shared-tailwind.config.js`:
```js
const nativewind = require('nativewind/tailwind');

module.exports = {
  presets: [nativewind],
  content: ['./**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

`tailwind.config.js`:
```js
module.exports = {
  presets: [require('./shared-tailwind.config.js')],
};
```

**Workaround**

This check can be bypassed by tricking the `hasPreset` check into thinking the shared preset _is_ the nativewind preset 😅 

`shared-tailwind.config.js`:
```diff
const nativewind = require('nativewind/tailwind');

module.exports = {
  presets: [nativewind],
  content: ['./**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
+  nativewind: true,
};
```

**Comment by marklawlor** [comment]
Fixed in `3.0.0-next.33`
