### ISSUE TITLE
`className` is not passed down - but it is...

### ISSUE THREAD

**Issue by Myzel394** [marklawlor/nativewind#356]
**Describe the bug**
The docs state that the `className` attribute is not passed down to custom components - but it is.

**To Reproduce**
1. Create an Expo project
2. Create a custom project
3. You now have a `className` prop with the class string

**Expected behavior**
`className` should be compiled to `style` and that should be passed down.

**Expo Snack**
Sorry but Expo Snack seems like it can't resolve `tailwindcss` :/

But here's what to do

1. Create a new expo project `npx create-expo-app`
2. Install nativewind
3. Type the following code for `App.js`:
```javascript
import {Text, View } from 'react-native';
import CustomComponent from "./CustomComponent";

export default function App() {
  return (
  <View className="flex-1 items-center justify-center bg-white">
      <Text>Open up App.js to start working on your app!</Text>
      <Text className="text-red-500">Color</Text>
      <CustomComponent className="bg-white" />
    </View>
  );
}
```

Create a new file called `CustomComponent.js` and add the following code:
```javascript
import {Text} from "react-native";

export default function CustomComponent(props) {
    return <Text>{JSON.stringify(props)}</Text>
}
```

**Screenshots**
These are the props that get passed

<img width="389" alt="Screenshot 2022-12-03 at 23 11 33" src="https://user-images.githubusercontent.com/50424412/205464140-06064c63-d9c7-4cbd-a513-ad3e878d1edd.png">

**Additional context**

**Comment by Myzel394** [comment]
Okay so seems like it was a very specific problem. Here's  my situation and how I solved it, maybe someone in the future might need this:

I was creating a custom component with specific code for Android and iOS, so I was having two files: `CustomComponent.android.js` and `CustomComponent.ios.js`. In the same folder was an `index.js` that would export this `CustomComponent`.

The solution was to simply name the components (aka the functions) to `CustomComponentAndroid` and `CustomComponentIos`, as previously they had the same name. Now everything is working.

**Comment by Myzel394** [comment]
Oh and also make sure to configure your `tailwind.config.js` to include your `src` folder or your other files, otherwise it won't work either (that's why the example above isn't working, you need to add `CustomComponent.js` to the `tailwind.config.js` file)

**Comment by Myzel394** [comment]
Nevermind, seems like that doesn't solve the problem. I now had to manually import the component, that worked.

**Comment by Myzel394** [comment]
Strangely in my case it was actually covered by `content`, the problem seems to be when you create files specifically for Android and iOS using `CustomComponent.android.js` and `CustomComponent.ios.js` and export them in an `index.js`. @marklawlor Do you have an idea on why this is happening?

**Comment by lgibso34** [comment]
> This needs better documentation, but your `content` inside the `tailwind.config.js` dictates what files and **components** get transformed. You can see that the component is not being transformed because its still passing `className` and no `style` prop.
> 
> The reason for why it works at a component level is to both speed up Babel compilation and better compatibility with web only components, which might have an actual `className` prop!
> 
> So you simply need to ensure that the file your importing `CustomComponent` from is covered by your `content`

Thank you for this additional info. I was expecting the className to be passed down but you explained why it shouldn't.


I expected this to work
```tsx
const WhiteText = ({
  children,
  className = '',
}: PropsWithChildren & {className?: string}) => {
  return <Text className={`text-white ${className}`}>{children}</Text>;
};
```

but usage of `<WhiteText className="text-red-500" />` actually sends the `style` prop like `style: [{"color": "#ef4444"}]`


This seems to be the best way to create a custom component and have it extend styles:
```tsx
const WhiteText = ({
  children,
  ...rest
}: PropsWithChildren & {className?: string}) => {
  return (
    // props.style gets added to the <Text> component that was change by babel from className to style
    // this will override the white text and make it red if we use the same component as above
    <Text className={`text-white`} {...rest}>
      {children}
    </Text>
  );
};
```
