### ISSUE TITLE
unable to resolve `.cache/nativewind/output.js` when creating expo template

### ISSUE THREAD

**Issue by itsramiel** [marklawlor/nativewind#361]
**Describe the bug**
I am trying to create a template to be used with expo like this: 
`yarn create expo-app AppName -t expo-template-blank-typescript-nativewind`, but when trying to run the project I get: 

```
Unable to resolve "/Users/ramiel/Desktop/Typescript/expo/AppName/node_modules/.cache/nativewind/output.js" from "node_modules/nativewind/dist/index.js"
```

however removing and adding it again with `yarn remove nativewind && yarn add nativewind@next` makes it work

**To Reproduce**
1. Go to terminal
2. Enter ''yarn create expo-app AppName -t expo-template-blank-typescript-nativewind"
3. Enter "cd AppName && yarn expo start"

**Expected behavior**
Not really sure why the error happens. I am expecting it to work right away.

**Comment by marklawlor** [comment]
I'm not sure who maintains the project, but when I run that commands you listed it doesn't properly lock the pre-release version in the package.json (it shouldn't use `^` for a pre-release). This can lead to confusing behaviour and I suspect the cause of your issue.
