### ISSUE TITLE
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by threemak** [marklawlor/nativewind#362]
My package.json file screenshot 
![packagejson](https://user-images.githubusercontent.com/50118354/207384765-041f2958-2b70-49f2-81a6-df38e5580dce.png)

Webpack config file screenshot
![webpack](https://user-images.githubusercontent.com/50118354/207384870-26bcbbd6-da7d-4dba-9f13-0158d30bee88.png)

Error screenshot
![Error](https://user-images.githubusercontent.com/50118354/207385235-2df9af6c-62ed-44ea-acc6-6cb6abf65205.png)

when i change config.node = false
Throw Error: byDependency and undefined for a single property is not supported

**Comment by marklawlor** [comment]
This is an issue with Expo Web, and you should create an issue there.

My assumption is you have multiple versions of webpack installed. You should explicitly define inside your package.json the same version that is required by @expo/webpack-config
