### ISSUE TITLE
Inconsistencies between on how the styles are applied in native and web

### ISSUE THREAD

**Issue by guplem** [marklawlor/nativewind#364]
**Bug description**
There are inconsistencies with the way the styles are applied for web and for mobile.

**To Reproduce**
1. Create a new project that includes nativewind (v2.0.9 in my case)
2. Create a component that wraps (inside a styled View) different text components.
Example code:
```
import { Text, TextInput, View } from 'react-native'
import { styled } from 'nativewind'

const StyledView = styled(View)
const StyledText = styled(Text)

export function LoginScreen() {
  return (
    <StyledView className="gap-3 bg-red-100 text-center">
      <StyledText>First text</StyledText>
      <StyledText>Another text</StyledText>
      <StyledText>Last text</StyledText>
    </StyledView>
  )
}
```
3. Set up the className to “text-center” for the styled view
4. See the differences between native and web versions.
5. If the className “text-center” is set to one of the StyledText (instead of the StyledView), it will be centered on android and on web. 
Example code:
```
      <StyledText className="text-center">
        This text has className=&quot;text-center&quot;
      </StyledText>
```

**Expected behavior**
The style should be the same in all platforms. It should be “propagated” the same way in web and in android.
Having differences in how the style is applied makes the cross-platform development much more tedious.

**Expo Snack**
The issue doesn't seem reproducible with Expo Snack, but at the same time some styles (background color and gap) are not being applied on any version there, but they do in my local machine. Check the snack [here](https://snack.expo.dev/@guplem/4d200f).

**Screenshots**
Web:
![2022-12-14 08_42_14-Solito Example App](https://user-images.githubusercontent.com/11029629/207518793-20550fdf-20c8-42b7-9bc5-f289504a88d6.png)

Android:
![Screenshot_2022-12-14-08-45-07-38_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/11029629/207519007-2d77863c-89af-46f2-b2ac-da4b71b5cd33.jpg)

**Additional context**
I am using [Tailwind (Nativewind) with Solito](https://solito.dev/tailwind) (expo React Native)

**Comment by marklawlor** [comment]
I'm going to close this issue as its expected behaviour, however there does appear to be a misunderstanding of the purpose of this library.

NativeWind is simply trying to be a replacement for `StyleSheet.create`. It is not trying to replicate how a browser works, or change how React Native works. If you used `StyleSheet.create` to add  `textAlign: 'center'` to the View, you would have the exact same issue (works on web but not native).

> The style should be the same in all platforms. It should be “propagated” the same way in web and in android.
> Having differences in how the style is applied makes the cross-platform development much more tedious.

I think this is the core of the misunderstanding. NativeWind isn't "make native the same as web". It's a React Native styling library, so you still have to follow the same rules as React Native. Only the syntax has changed to something that is more familiar.

**Comment by timedtext** [comment]
RN only supports limited css inheritance.
A detailed explanation is available [here](https://reactnative.dev/docs/text#limited-style-inheritance).

```jsx
//This should work
<StyledText className="gap-3 bg-red-100 text-center">
  <StyledText>First text</StyledText>
  <StyledText>Another text</StyledText>
  <StyledText>Last text</StyledText>
</StyledText>
````

**Comment by guplem** [comment]
> I think this is the core of the misunderstanding. NativeWind isn't "make native the same as web". It's a React Native styling library, so you still have to follow the same rules as React Native. Only the syntax has changed to something that is more familiar.

Do you know of any styling & layout library/package for React Native (expo) that would achieve that? I found [Dripsy](https://www.dripsy.xyz/), but I believe it is only for layout.

**Comment by marklawlor** [comment]
There is no RN library that I know of that simulates web complete style inheritance in React Native. I don't believe Dripsy has any custom inheritance logic?

**Comment by marklawlor** [comment]
Just wanted to add, I'm am actively thinking about ways to improve the developer experience around this issue. I believe its possible to make an editor/eslint plugin that warns a user when they use a className incorrectly or in a non-cross platform manner - I just need to learn a bit more about Typescript's compiler API.
