### ISSUE TITLE
Constant Rebuilds during expo development using nativewind@next

### ISSUE THREAD

**Issue by Wolfleader101** [marklawlor/nativewind#371]
**Describe the bug**
Constantly rebuilding the app and refreshing it on expo go makes testing state changes impossible.

**To Reproduce**
Setup nativewind@next and run expo start.

**Expected behavior**
It shouldn't have to constantly rebuild.

**Screenshots**
![image](https://user-images.githubusercontent.com/25214835/209036407-40a3a291-ad76-452f-b78c-4f56c89d736f.png)

**Comment by marklawlor** [comment]
What is the `content` string in your `tailwind.config.js`? Those rebuild times are quite long - make sure your not including `node_modules` within your content glob! That could also be why its constantly rebuilding, as NativeWind writes to `node_modules/.cache` by default.

**Comment by Wolfleader101** [comment]
> What is the `content` string in your `tailwind.config.js`? Those rebuild times are quite long - make sure your not including `node_modules` within your content glob! That could also be why its constantly rebuilding, as NativeWind writes to `node_modules/.cache` by default.

It is
` content: ["./App.{js,jsx,ts,tsx}", "./**/*.{js,jsx,ts,tsx}"],` as I don't have a src folder

**Comment by marklawlor** [comment]
`"./**/*.{js,jsx,ts,tsx}"` is including your `./node_modules`. https://tailwindcss.com/docs/content-configuration#pattern-recommendations
