### ISSUE TITLE
export an util function to create style object

### ISSUE THREAD

**Issue by sapjax** [marklawlor/nativewind#372]
For example, we have a `TabBar` component of [react-native-tab-view](https://github.com/react-navigation/react-navigation/tree/main/packages/react-native-tab-view#tabbar): 
```tsx
<TabBar
    {...props}
    style={{
      backgroundColor: 'transparent'
    }}
    tabStyle={{
      height: 38,
      padding: 0,
      width: 'auto'
    }}
    labelStyle={{ fontSize: 12 }}
    indicatorStyle={{ backgroundColor: '#3B82F6' }}
  />
```
The `styled` function is not very convenient to use here, we need to wrap the `Tabbar` and pass many style props into it.

If there is a function like `tw()` of  [twrnc](https://github.com/jaredh159/tailwind-react-native-classnames#api):
```ts
import tw from 'twrnc';

tw`pt-6 bg-blue-100`;
// -> { paddingTop: 24, backgroundColor: 'rgba(219, 234, 254, 1)' }
```

then we can use it directly on `TabBar`:
```tsx
<TabBar
    {...props}
    style={tw`bg-transparent`}
    tabStyle={tw`h-9 p-0 w-auto`}
    labelStyle={tw`text-xs`}
    indicatorStyle={tw`bg-blue-500`}
  />
```
That will be more convenient 😀.

**Comment by marklawlor** [comment]
https://www.nativewind.dev/api/styled#styling-multiple-properties

**Comment by sapjax** [comment]
> https://www.nativewind.dev/api/styled#styling-multiple-properties

That's exactly what I mean
> The `styled` function is not very convenient to use here, we need to wrap the Tabbar and pass many style props into it.

We don't have to wrap them if we can directly get style objects, especially when they are 3rd components.

**Comment by marklawlor** [comment]
The `tw` style doesn't work with NativeWind. It does much more than `twrnc` such as adding additional props, modifying the children and wrapping your components in a context.

**Comment by joelrojo** [comment]
Also having the same issue. Trying specifically to do this with React Navigation and struggling to figure out the best way to use nativewind to add style to the props.

@marklawlor do you happen to have any examples of how to style something like this? I'm currently using `twrnc` and would like to fully migrate to nativewind:

```javascript
<Stack.Navigator
  screenOptions={{
    headerStyle: tw.style('bg-gray-800'),
    headerTintColor: tw.color('gray-100'),
    headerTitleStyle: tw.style('font-sans'),
    headerBackTitleVisible: false,
    headerShadowVisible: false,
    title: ''
  }}
>
...
<Stack.Navigator>
```

My current attempt is this, but can't seem  to get it to work:
```javascript
const StyledStackNavigator = styled(
  (children, { headerStyle, ...props }) => (
    <Stack.Navigator
      {...props}
      screenOptions={{ ...props.screenOptions, headerStyle, headerTitleStyle }}
    >
      {children}
    </Stack.Navigator>
  ),
  {
    props: {
      headerStyle: true,
      headerTitleStyle: true
    }
  }
)
```

This would also solve #287

Really awesome work by the way!

**Comment by switz** [comment]
would also like to echo the sentiments here. some 3rd party components expect style objects and it would be nice to generate nativewind styles from a template string or function call
