### ISSUE TITLE
npm instead of Yarn

### ISSUE THREAD

**Issue by AkbarBakhshi** [marklawlor/nativewind#375]
I followed the instruction [here](https://www.nativewind.dev/quick-starts/expo) to install and configure the package on my expo project. I did everything as instructed **except for using npm instead of yarn** to install the package and tailwindcss. It seems like the class names don't work. 

I have tried installing using **Yarn** and it worked fine. Is this the intended behavior? Any insights?

**Comment by marklawlor** [comment]
There should be no difference between using `npm` or `yarn`. I would need to see your code to assist you futher
