### ISSUE TITLE
ERROR  TypeError: cannot add a new property, js engine: hermes

### ISSUE THREAD

**Issue by mustafaskyer** [marklawlor/nativewind#384]
**Describe the bug**
using `react-native-modalize` modal  and toggling color scheme generated this issue  
` ERROR  TypeError: cannot add a new property, js engine: hermes`
once i open the modal then close without doing any interactions inside the modal, If I am trying to switch mode after that I am getting the above error
**To Reproduce**
1. opening the modal
```tsx
const modalRef = React.useRef<Modalize>(null);

const handleChangeLanguage = React.useCallback(() => {
    modalRef?.current?.open();
  }, []);

<Portal>
        <SelectLanguageModalContent ref={modalRef} />
</Portal>

```
3. toggling mode
```tsx

 const {toggleColorScheme} = useColorScheme();

  const transition = (
    <Transition.Together>
      <Transition.In type="fade" durationMs={350} />
      <Transition.Out type="fade" durationMs={350} />
    </Transition.Together>
  );

  const handleChangeMode = () => {
    transitionRef?.current?.animateNextTransition();
    toggleColorScheme();
  };
```

Extras
`react-native-modalize` link: https://github.com/jeremybarbet/react-native-modalize

**Expected behavior**
toggling and switching mode as expected without any affect from any modal

**Screenshots**

![simulator_screenshot_4B659247-B0B6-4CDB-A0C4-92CF81284694](https://user-images.githubusercontent.com/15132084/212487233-59883d92-9b69-4566-b243-9d08d052bb86.png)

**Additional context**
```tsx
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 260.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by atanaskanchev** [comment]
Same in `@gorhom/bottom-sheet`

**Comment by atanaskanchev** [comment]
@mustafaskyer this has been fixed in the `@next` version

**Comment by 360macky** [comment]
> @mustafaskyer this has been fixed in the `@next` version

Hi, how can I install now this version on my app? I'm having this problem when I'm toggling dark/light mode.

**Comment by mustafaskyer** [comment]
@360macky 
upgrade to latest version, and not that this only happen at dev mode.
