### ISSUE TITLE
native flex-gap support of react-native 0.71

### ISSUE THREAD

**Issue by joeykamsteeg** [marklawlor/nativewind#386]
With the release over react-native 0.71 there is native support for flex-gap. It would be nice if the future nativewind release will also make use of the native flex-gap behaviour. 

**Expected behavior**
Project with minimal version of 0.71 will use the native flex-gap support

**Comment by skoob13** [comment]
As a temporary solution it's possible to add a custom plugin:
```javascript
module.exports = {
  theme: {
    g: ({ theme }) => theme('spacing'),
    extend: {},
  },
  plugins: [
    plugin(function ({ matchUtilities, theme }) {
      matchUtilities(
        {
          g: (value) => ({
            gap: value,
          }),
        },
        { values: theme('g') }
      );
    }),
  ],
};
```
It creates `g-*` utility classes.

**Comment by marklawlor** [comment]
Native gap will be the default, with a flag to restore the current behaviour for people who cannot upgrade. @skoob13 comment is a great work around

**Comment by Nova41** [comment]
> As a temporary solution it's possible to add a custom plugin:
> 
> ```js
> module.exports = {
>   theme: {
>     g: ({ theme }) => theme('spacing'),
>     extend: {},
>   },
>   plugins: [
>     plugin(function ({ matchUtilities, theme }) {
>       matchUtilities(
>         {
>           g: (value) => ({
>             gap: value,
>           }),
>         },
>         { values: theme('g') }
>       );
>     }),
>   ],
> };
> ```
> 
> It creates `g-*` utility classes.

Thanks for the solution, but it doesn't seem to work for me. Do you have any idea what is going on?

Here's my `tailwind.config.js`:
```
const plugin = require('tailwindcss/plugin');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    g: ({theme}) => theme('spacing'),
    extend: {},
  },
  plugins: [
    plugin(function ({matchUtilities, theme}) {
      matchUtilities(
        {
          g: value => ({
            gap: value,
          }),
        },
        {values: theme('g')},
      );
    }),
  ],
};
```

My usage:

```
<View className="g-16">
  ...
</View>
```

This does not seem to have any effect. However specifying `styles={{gap: 16}}` works. I am running RN 0.71.2 and have babel transformation cache reset.

**Comment by btraut** [comment]
> Thanks for the solution, but it doesn't seem to work for me. Do you have any idea what is going on?

I couldn't get this solution working with Nativewind 2.x either, but it appears to have started working once I switched to Nativewind 3.x.

Steps:
1. Install `"nativewind": "3.0.0-next.34"`.
2. Follow [breaking changes guide](https://github.com/marklawlor/nativewind/issues/308).
3. Apply the hack above.

**Comment by btraut** [comment]
I dug a little deeper into this and figured out why it's not working on nativewind 2.x. The issue is that nativewind maintains a [list of valid react native properties](https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/src/postcss/to-react-native/is-invalid-property.ts) and 2.x doesn't include gap. AFAIK, there's no API to change this, so you'll need to fork or patch the package to allow it.

**Comment by ospfranco** [comment]
For anyone that is still looking for a workaround, here is a more detailed guide:

https://ospfranco.com/post/2023/08/21/add-gap-support-to-native-wind-2.x.x/

**Comment by ayhamnajem** [comment]
Hi,

I wanted to check if this is still on the radar.

Since react native already supports flex gap 
https://reactnative.dev/blog/2023/01/12/version-071
It would be really handy to have it supported with nativewind.

Thanks!

**Comment by marklawlor** [comment]
Native gap is available in the v4 release
