### ISSUE TITLE
Overwriting sans fontFamily does not apply new font as default

### ISSUE THREAD

**Issue by mohetti** [marklawlor/nativewind#387]
**Describe the bug**
Hi,

fist of all, thanks for this great project. It makes developing css for react native much more fun and efficient!

I'm not sure if this is a bug or intended behaviour. Couldn't find anything in the docs about it so I just wanted to make sure, what's the approach here:

Platform: Expo SDK 47

If I overwrite the `sans` property on `fontFamily` inside `tailwind.config.js` with a font loaded by Expo's `useFonts` hook inside `App.js`, I would expect the loaded font to be used as the default font. However, it is not applied by default. But I can confirm that tailwind recognizes the font through calling it explicitly. Eg by calling `className="font-sans"` or `className="font-[OpenSans]`.

I could imagine that it does not get applied by default the same way you can't use dynamic classNames like `h-${height}`? Anyway, if this is not a bug. What would my best approach be. Maybe a wrapper text component like:

`const DefaultFontText = ({classString, children}) => <Text> className={`classString` font-sans}>{children}</Text>`

Thanks for any input

**To Reproduce**
1. Setup project based on [nativewind expo guide](https://www.nativewind.dev/quick-starts/expo)
2. Overwrite or extend `fontFamily.sans` in the `tailwind.config.js` with the custom loaded font (here OpenSans)
3. Add OpenSans as font in the assets folder
4. Load OpenSans into the App with `expo-fonts` hook
5. Create 2 Text components. One without a className, the other with `className="font-sans"` or `className="font-[OpenSans]`

**Expected behavior**
I would expect that OpenSans gets applied to all `Text` components by default, without calling `font-sans` or `font-[OpenSans]` explicitly.

**Expo Snack**
Couldn't set up a snack, but here's a minimal repo of the problem: [Github repo](https://github.com/mohetti/tailwind_default_font)

**Screenshots**
![example](https://user-images.githubusercontent.com/73931283/213097973-2cde5674-3a00-4188-adcc-ff5961b97242.png)

It's a bit hard to see. But the first and third `Text` component are slightly smaller in width, indicating that they don't use OpenSans like the second and fourth `Text` components.

**Comment by BooDeer** [comment]
There's still no way to setup a custom default font...?

**Comment by FilipeMarch** [comment]
Curious too

**Comment by moritzlang** [comment]
Any update on this for v4?

**Comment by premdasvm** [comment]
Any update on this ?

**Comment by parkwherever** [comment]
Also running into this. I can apply the font at the base level, or on a particular text item. However, the given the limited font inheritance https://reactnative.dev/docs/text#limited-style-inheritance any `Text` that doesn't have a specific font family specified takes the default system fonts. This would be awesome to have instead of having to use @apply and reference the desired font on each text object

**Comment by feledori** [comment]
As styles in react native are not cascading you can't set a default per se like on the web. You probably can trough some native config but not with a global css var. The recommended setup is to extend the Text component and creating an own Text component with default styling applied.

**Comment by mohetti** [comment]
I did implement it in a way as what @feledori describes. Works like a charm. Also this seems not be something nativewind should be responsible for so I close my issue.

**Comment by mohetti** [comment]
Closed
