### ISSUE TITLE
spawnCommands using incorrect npx package

### ISSUE THREAD

**Issue by adampash** [marklawlor/nativewind#389]
https://github.com/marklawlor/nativewind/blob/854ccd0b1ffcec1857f543aa04e4b52dc2f8243c/packages/nativewind/src/metro/tailwind.ts#L50-L58

I believe this should be `tailwindcss` instead of `tailwind`, correct?

**Comment by marklawlor** [comment]
Tailwind creates an alias for both https://github.com/tailwindlabs/tailwindcss/blob/master/package.json#L11-L14

**Comment by adampash** [comment]
Thanks for the quick response. For some reason if I don't change `tailwind` to `tailwindcss`, I get:

```
NativeWind: Rebuilding...
NativeWind: npm ERR! could not determine executable to run
```

If i change it to `tailwindcss`, I don't have this problem — it builds successfully. I'm on `nativewind@3.0.0-next.34` and `tailwindcss@3.2.4`.

**Comment by tyrauber** [comment]
Thank you @adampash, I was seeing this same issue with pnpm. Perhaps pnpm isn't respecting the alias? A patch of `tailwind` to `tailwindcss` does resolve the issue.

**Comment by psteinroe** [comment]
same issue here! how did you resolve it @tyrauber? Did you apply a patch to `nativewind`?

**Comment by tyrauber** [comment]
Hi @psteinroe, I did. To do the same, `pnpm patch nativewind@next --edit-dir tmp`, make the change and then apply the patch with `pnpm patch-commit tmp`. Then update your patched dependencies.
```
    "patchedDependencies": {
      "nativewind@3.0.0-next.34": "patches/nativewind@3.0.0-next.34.patch"
    }
 ```
