### ISSUE TITLE
output.css file missing in node_modules cache

### ISSUE THREAD

**Issue by adampash** [marklawlor/nativewind#390]
**Describe the bug**
In `3.0.0-next.34`, the first time I try running nativewind/tailwind on my project, I get an error because `node_modules/.cache/nativewind/output.css` does not exist.

**To Reproduce**
1. Install nativewind in a metro project, following the directions [here](https://github.com/marklawlor/nativewind/issues/308).
2. Run on ios.

**Expected behavior**
I expect it to build the output. If I just:

```bash
touch node_modules/.cache/nativewind/output.css
```

...it starts working as expected.

**Additional context**
I'm using yarn, in a yarn workspace/monorepo.

**Comment by michaelkremenetsky** [comment]
+1 was having the same issue. Seems like it's because It's trying to use postcss instead of babel, even though postcss is deprecated in this version.

**Comment by MarcK98** [comment]
+1 also happening to me

**Comment by desonyuan** [comment]
+1

**Comment by badalsaibo** [comment]
+1

**Comment by Maddemacher** [comment]
+1 in 4.0.22

**Comment by marklawlor** [comment]
If your experiencing this issue in 4.0 please create a new issue with more information.
