### ISSUE TITLE
Updating tailwind.config.js doesn't change values in the app.

### ISSUE THREAD

**Issue by drfree1** [marklawlor/nativewind#393]
I use tailwind.congif.js to add custom colors for my app so everybutton every textinput's color can be changed easily if the customer wants it but the problem is when i change the values it doesn't change in the app. i tried npx tailwindcss -w and minify but it didn't solved the issue. What is the problem the way i making this app wrong? Should i have had used brackets for this job?   

i tried deleting the app and used npx react-native run-android but still colors didn't changed. I

It is kinda time sensitive problem for me what i can do to fix this problem?

: (

**Comment by drfree1** [comment]
Nobody knows a solution for this?

**Comment by nawalpro** [comment]
Same problem for me ..

**Comment by marklawlor** [comment]
This is being address in an upcoming version (see the pinned issue). The problem is that Metro is not aware of your `tailwind.config.js`, so you need to clear your meto/expo cache when you change a value.

**Comment by EL-MEHDI-ESSAADI** [comment]
Same here, hopefully they will address it soon

**Comment by EL-MEHDI-ESSAADI** [comment]
to clear metro cache run `npm start -- --reset-cache` and then restart the app
