### ISSUE TITLE
[BABEL]: Cannot find module 'tailwindcss/lib/util/resolveConfigPath'

### ISSUE THREAD

**Issue by AndresdoSantos** [marklawlor/nativewind#399]
Could not find module `resolveConfigPath`

1. expo init myapp
2. Install nativewind following the documentation step by step
3. Reload the app

I was hoping to get to use the library.

**Comment by marklawlor** [comment]
I need more detail. What version of tailwindcss do you have install? If you look in `node_modules/tailwindcss/lib/util` does the `resolveConfigPath.js` file exist?

**Comment by AndresdoSantos** [comment]
Hello @marklawlor, sorry for the lack of information.

In an attempt to find what you asked for, I realized that I had not installed `tailwindcss` itself (it would be interesting to put it in the installation doc).

After installing it worked.

Thanks!
