### ISSUE TITLE
cannot find module node:path - but i'm using node 18

### ISSUE THREAD

**Issue by carlosedof** [marklawlor/nativewind#400]
**Describe the bug**
Error "cannot find module node:path" at launch, yarn run ios..
![Captura de Tela 2023-01-30 às 13 15 08](https://user-images.githubusercontent.com/25438470/215532349-354939b3-7f2f-48ea-aded-f4f1c7d5f8d2.png)

**To Reproduce**
running my app with Yarn run ios, already tried with node 16 version... cannot get rid of this error, already deleted node modules and yarn lock, reinstalled, rerun app.. and nothing...

**Expected behavior**
Run app without any errors

**Additional context**
This is my versions:
```
package.json
  "dependencies": {
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.71.1",
    ...
  },
```

 ```
"devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "babel-jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.8.3",
    ...
  },
```

babel.config.js 
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['nativewind/babel', 'react-native-reanimated/plugin'],
};
```

already checked #122 and #106 and #278 all of them tell me to update my node version, but I am already using 18:
```
main ⨯ node --version                         13:06:07
v18.13.0
```
already tried with node 16...

**Comment by marklawlor** [comment]
In your `babel.config.js` file, can you please print the node version to confirm that it is running as Node 18 `console.log('Version: ' + process.version);`

**Comment by carlosedof** [comment]
@marklawlor first of all, thanks for taking time to help!
`transform[stdout]: Version: v14.15.4`
yeah, it seems that it is not on node 18... but i'm not sure why, I think the build is getting node from somewhere else, not from my terminal set up, because I use fish terminal and nvm and i set to 18 before running build... must be something wrong related to my terminal/nvm config. I'll look into it, I will close the issue because for sure its not nativewind related. 
Thanks again!
