### ISSUE TITLE
Custom fontWeight and lineHeight properties don't work

### ISSUE THREAD

**Issue by francosbenitez** [marklawlor/nativewind#404]
**Describe the bug**
NativeWind is not working with Tailwind customization of the 'theme'. For example, when trying to override the 'fontSize'.

**To Reproduce**
1) Go to 'tailwind.config.js'
2) Click on 'theme' -> 'fontSize' -> AND, for example:
  - Add a custom 'xs' property, with default fontWeight and lineHeight
  - No matter what, it doesn't work. That doesn't work as expected. Only the pixel attribute is taken into account.
3) See error
  - Properties like "fontWeight" and "lineHeight" are not taken into account by NativeWind.

**Expected behavior**
Those properties should work.

**Screenshots**
![Screenshot from 2023-02-02 18-31-42](https://user-images.githubusercontent.com/62864550/216454182-5790f8ce-84e1-47cc-837c-449a20330244.png)

**Comment by XantreGodlike** [comment]
I found source of issue
https://github.com/marklawlor/nativewind/blob/75d7744843b60dbdb4c1ef984a4421ff43f1e76f/packages/nativewind/src/tailwind/native/font-size.ts#L17C17-L17C27

**Comment by XantreGodlike** [comment]
This patch solves this issue
```diff
diff --git a/node_modules/nativewind/dist/tailwind/native/font-size.js b/node_modules/nativewind/dist/tailwind/native/font-size.js
index 9bc6bd7..c4d39d2 100644
--- a/node_modules/nativewind/dist/tailwind/native/font-size.js
+++ b/node_modules/nativewind/dist/tailwind/native/font-size.js
@@ -2,6 +2,9 @@
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.fontSize = void 0;
 const utils_1 = require("./utils");
+
+const toHyphen = (string) => string.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
+
 /**
  * This "fixes" the fontSize plugin to calculate relative lineHeight's
  * based upon the fontsize. lineHeight's with units are kept as is
@@ -13,12 +16,20 @@ const utils_1 = require("./utils");
 const fontSize = ({ matchUtilities, theme }) => {
     matchUtilities({
         text: (value) => {
-            const [fontSize, options] = Array.isArray(value) ? value : [value];
-            const { lineHeight, letterSpacing } = (0, utils_1.isPlainObject)(options)
-                ? options
-                : { lineHeight: options, letterSpacing: undefined };
+            const [_fontSize, _options] = Array.isArray(value) ? value : [value];
+            const options = (0, utils_1.isPlainObject)(_options)
+                ? {..._options, fontSize: _fontSize}
+                : { lineHeight: _options, letterSpacing: undefined, fontSize: _fontSize };
+            const lineHeight = options.lineHeight;
             return {
-                "font-size": fontSize,
+                ...Object.fromEntries(
+                    Object.entries(options)
+                    .map(([key, value]) => [
+                      toHyphen(key),
+                      value])
+                    .filter(([, value]) => value !== undefined)
+                  ),
+
                 ...(lineHeight === undefined
                     ? {}
                     : {
@@ -26,9 +37,6 @@ const fontSize = ({ matchUtilities, theme }) => {
                             ? lineHeight
                             : `${Number.parseFloat(fontSize) * lineHeight}px`,
                     }),
-                ...(letterSpacing === undefined
-                    ? {}
-                    : { "letter-spacing": letterSpacing }),
             };
         },
     }, {
```

**Comment by XantreGodlike** [comment]
@marklawlor

**Comment by z1haze** [comment]
I know this issue has only been open for a year, but could you maybe please fix this?

**Comment by XantreGodlike** [comment]
> I know this issue has only been open for a year, but could you maybe please fix this?
> 
> also, @XantreGodlike this issue exists for font size too. Did you run into this? This is specifically when using the `text-lg` type classes, where you'd expect the fontSize and lineHeights to be respective of what they are set in tailwind. In my example, neither are respected.

In my case only lineHeight is affected. There are chances that this behaviour is fixed in nativewind4

**Comment by z1haze** [comment]
I attempted to play with v4 a few days ago and its just a complete mess. I had so many issues I don't even know where to begin? If you've had success setting up v4 in your project? Could we connect on discord? We should use some help.

**Comment by marklawlor** [comment]
This appears to be fixed in the v4 release
