### ISSUE TITLE
Border not working when Dark mode is enabled in Tailwind Config

### ISSUE THREAD

**Issue by alexqs96** [marklawlor/nativewind#406]
i just found out that border doesnt work with the default value (1px) just after i enabled dark mode by class in the tailwind config

tw config : darkMode: 'class'

```
<View className="border border-red-700">
{content}
</View>
```

but it works if i define it with : border-[1px]

my packages

"expo": "~47.0.13",
"react-native": "0.71.2",
"nativewind": "^2.0.11"

the problem can be seen even in the expo example from the docs

[https://www.nativewind.dev/core-concepts/dark-mode](Dark Mode NativeWind)

**Comment by yybawang** [comment]
add one more class `border-solid`

**Comment by marklawlor** [comment]
I think you were experiencing a cache issue. This issue has been resolved in v4
