### ISSUE TITLE
error: can show custom image as bg in a View React-native 

### ISSUE THREAD

**Issue by rodrigodiasf1984** [marklawlor/nativewind#420]
"nativewind": "^2.0.11",
 "react": "18.1.0",
  "react-native": "0.70.6",

tailwind.config.js
![image](https://user-images.githubusercontent.com/30758309/218518140-f329f42b-c853-4d37-be33-84e4316a629a.png)

![image](https://user-images.githubusercontent.com/30758309/218518463-ae36af99-b528-45ef-8898-b7fd677c8454.png)

how can I show this custom image ? Thx

**Comment by marklawlor** [comment]
React Native does not support background image styles - so they are unsupported in NativeWind.
