### ISSUE TITLE
Errors in console: StyleSheetRuntime.dangerouslyCompileStyles

### ISSUE THREAD

**Issue by RafalGrabowski95** [marklawlor/nativewind#423]
Hi, 

in my project that uses expo and nativewind there are problems visible in the screenshot. This is the code in App:
```
import { withExpoSnack, styled } from "nativewind";
import { View as NativeView } from 'react-native';

export const View = styled(NativeView);

const App = () => {
 
  return (
      <View className="bg-red-200"></View>
  );
};

export default withExpoSnack(App);

```

Inserting the classname attribute into the View results in an error.
Does anyone know the cause of the error and suggest a solution?

<img width="492" alt="image" src="https://user-images.githubusercontent.com/97595531/219151645-733c44ee-a445-417a-894c-22311082aa75.png">

**Comment by marklawlor** [comment]
Are you using `withExpoSnack` outside an Expo Snack? If so it is expected to error and I recommend you follow the setup instructions on nativewind.dev
