### ISSUE TITLE
The base colour does not work

### ISSUE THREAD

**Issue by JaLe29** [marklawlor/nativewind#424]
I have code simple code:
```
const RegularText: React.FC<Props> = ({ customClassName, children }) => {
	const clsx = `${customClassName}`;
	// eslint-disable-next-line no-console
	console.log({ clsx, children }); // {"children": "Next", "clsx": "text-white"}
	return <Text className={clsx}>{children}</Text>;
};
```
Whre I am trying to set `text-white` - color white.

Out of 100 attempts to render the component, the text is white once.

I'm 100% sure that my class name is correct.  `text-white` .

The behaviour is strange, can anyone advise me how to resolve this? 

My configuration is:

tailwind.config.cjs:
```
/** @type {import('tailwindcss').Config} */

module.exports = {
	content: ['./src/**/*.{js,ts,jsx,tsx}', './src/components/*.{js,ts,jsx,tsx}'],
	theme: {
		colors: {
			white: '#ffffff',
			tahiti: '#3ab7bf',
		},
		extend: {
			fontFamily: {
				'montserrat-bold': ['montserrat-bold'],
				'montserrat-regular': ['montserrat-regular'],
			},
		},
	},
	plugins: [],
};
```
theme.cjs
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const colors = require('tailwindcss/colors');

module.exports = {
	colors: {
		...colors,
		primaryGradient: {
			start: '#F2EA21',
			middle: '#E4B845',
			end: '#DC831B',
		},
	},
};
```

```
"expo": "~47.0.12",
"nativewind": "^2.0.11",
"tailwindcss": "^3.2.7"
```
I'm just trying to set white text, which doesn't seem like a complicated operation.

**Comment by kmanadkat** [comment]
Facing similar issue with `border-gray-200` Sometimes it shows black border, sometimes it is gray

**Comment by Rossella-Mascia-Neosyn** [comment]
@JaLe29 I have the same problem were you able to solve it?

**Comment by bentburton** [comment]
Any update on this? Having similar issue

**Comment by marklawlor** [comment]
This issue is resolved in v4. You no longer have to use a `customClassName`, `className` is passed down to components
