### ISSUE TITLE
undefinded ins not an object (evaluating '_NativeWindStyleSheet.create')

### ISSUE THREAD

**Issue by ManabBala** [marklawlor/nativewind#426]
**Describe the bug**
## "Cannot read property 'create' of undefined.

Its a fresh expo app with just nativewind and tailwind.
these output were generated in a Expo go android app also with web version.

**To Reproduce**
1. npx create-exp-app my-app
(at this point app just work fine with Expo android app)
2. yarn add nativewind
yarn add --dev tailwindcss
3. edit babel.config.js and add tailwind.config.js
4. now the app showing error
(to clear cache- npx expo start --clear)

** my package.json **
```json
	"dependencies": {
		"expo": "~48.0.4",
		"expo-status-bar": "~1.4.4",
		"nativewind": "^2.0.11",
		"react": "18.2.0",
		"react-native": "0.71.3"
	},
	"devDependencies": {
		"@babel/core": "^7.20.0",
		"tailwindcss": "^3.2.7"
	},
```
**Expected behavior**
This setup worked just two days ago before the react, reat-native, and expo update.

**Screenshots**
![Screenshot_2023-02-26-18-32-56-04](https://user-images.githubusercontent.com/94683653/221426654-30dfb349-d253-4e79-a9be-121c3094f592.jpg)
![Screenshot_2023-02-26-22-56-16-10_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/94683653/221426656-520bec24-8e75-43ec-bffb-548e03a93088.jpg)

**Comment by marklawlor** [comment]
Make sure your `content` glob in `tailwind.config.js` does not include your `node_modules`.

**Comment by ManabBala** [comment]
> Make sure your `content` glob in `tailwind.config.js` does not include your `node_modules`.

Thank you so very much.
I used wild card to include everything in my project folder.
```js
content: ["./App.{js,jsx,ts,tsx}", "./**/*.{js,jsx,ts,tsx}"],
```
For anyone dumb as me:(use this instead)
```js
content: [
"./App.{js,jsx,ts,tsx}",
"./screens/**/*.{js,jsx,ts,tsx}",
"./components/**/*.{js,jsx,ts,tsx}",
],
```

**Comment by Aberdeener** [comment]
Facing the same issue here, even when fixing the Tailwind config file.
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./comp/App.tsx",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

<img width="564" alt="image" src="https://user-images.githubusercontent.com/26070412/228425688-bf0ead18-077e-4da9-b09a-45800dcaa531.png">

Is there anything else that could cause this problem? Thanks.

**Comment by BJDubb** [comment]
Am also having this issue

tailwind.config.js
```
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./App.tsx"],
    theme: {
        extend: {},
    },
    plugins: [],
}
```



-cleared npm cache
-deleted node modules
-am using typescript
