### ISSUE TITLE
styled doesn't work correctly on Web with Tamagui components

### ISSUE THREAD

**Issue by giacomosardo** [marklawlor/nativewind#432]
**Describe the bug**
I tried to install Nativewind on NextJS and I tried to install [Tamagui](https://tamagui.dev/) library, but using the `styled` of Nativewind with a Tamagui component doesn't work correctly on NextJS. I also tried creating an app on Expo and it works correctly there.

I'm getting this from NextJS console:
`Warning: Unsupported style property text-blue-500. Did you mean textBlue500?`

**To Reproduce**
1. Install [Nativewind to NextJS](https://www.nativewind.dev/quick-starts/nextjs)
2. Add [Tamagui](https://tamagui.dev/docs/intro/installation) to project
3. Create a simple component

```
import { styled } from 'nativewind';
import { Text, TextProps } from 'tamagui';

export const Label: React.FC<TextProps> = styled(
  Text,
  'text-blue-500',
);
```

**Expected behavior**
Get blue text

**Comment by marklawlor** [comment]
On web, NativeWind turns classNames into React Native Web className objects.

```
className="text-blue-500" -> { $$css: true, "text-blue-500": "text-blue-50" }
```

It looks like Tamagui didn't respect the `$$css: true` flag. I think this is fixed in the latest tamagui
