### ISSUE TITLE
Dark mode order class matters

### ISSUE THREAD

**Issue by 360macky** [marklawlor/nativewind#437]
**Describe the bug**

Hi everyone!

I notice that the order of the `dark:` class matters, and it needs to be written at the end.

If it is the behavior expected by the design of the library, I think it is valuable to describe this behavior in the [Dark Mode section](https://www.nativewind.dev/core-concepts/dark-mode) of the documentation.

```
border-slate-800 dark:border-slate-100 ✅
```

```
dark:border-slate-100 border-slate-800 ❌
```

**To Reproduce**
1. Create two texts, both with different colors for dark mode and light mode2. 
2. Try to switch the order of the classes between the first and the second text.

**Expected behavior**
That the order does not matter when writing the dark mode classes.

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

https://user-images.githubusercontent.com/47821093/225178642-56572465-e69f-447f-ada1-5164f6b3634f.mov

**Comment by tbezman** [comment]
me too

**Comment by justmammt** [comment]
you solved my problems, thanks!

**Comment by marklawlor** [comment]
This is fixed in v4, we follow the CSS specificity of the classNames
