### ISSUE TITLE
A custom component's displayName is removed when adding className/tw properties

### ISSUE THREAD

**Issue by yiglas** [marklawlor/nativewind#440]
**Describe the bug**
Adding the className property to a custom component that has a displayName set, removes it.

**To Reproduce**
1. Create new React Native app, I followed [Create React Native App](https://www.nativewind.dev/quick-starts/create-react-native-app) instructions
2. Create a Label custom component

    ```js
   const Label = React.forwardRef((props, ref) => <Text {...{ ref, ...props }} />);
   Label.displayName = "Label";
    ```

3. Create a Layout custom component

    ```js
    const Layout = ({ children, ...props }) => {
      const remainingChildren = [];

      React.Children.map(children, (child) => {
        console.log({ displayName: child.type.displayName });
        remainingChildren.push(child);
      });

      return <View {...props}>{children}</View>;
    };
    ```

4. Update the main App

    ```js
    export default function App() {
      return (
        <Layout className="flex-1 items-center justify-center bg-white">
          <Label>has a displayName</Label>
          <Label className="text-lg text-blue-500">does not have displayName</Label>
          <Label>has a displayName</Label>
        </Layout>
      );
    }
    ```

5. Run `npm run ios`
6. Once app is opened the output show:

    ```
     LOG  {"displayName": "Label"}
     LOG  {"displayName": undefined}
     LOG  {"displayName": "Label"}
    ```

**Expected behavior**
Adding the className or tw properties should not wipe the displayName of the custom component

**Comment by marklawlor** [comment]
This is fixed in v4, but we now renamed the component to `CssInterop.<ComponentName>`. This way you can tell if the interop was applied or not
