### ISSUE TITLE
How to use merge strategy for web in v3?

### ISSUE THREAD

**Issue by victorwpbastos** [marklawlor/nativewind#449]
![Screenshot_20230328-130926_Chrome](https://user-images.githubusercontent.com/1017515/228302390-9734cbdb-92d3-41bb-90ca-5daaf8101305.jpg)

In the v3 docs says that we can use this approach to configure the merge strategy for web version. I tried to use tailwind-merge but it didn't work as expected. Do someone have an example of how to make it work?

**Comment by shubham-cpp** [comment]
I'm guessing that this would be like 

```jsx
if (Platform.OS === 'web') {
  NativeWindStyleSheet.setWebClassNameWebStrategy = twMerge
}
```

In our index.js/main.js

**Comment by marklawlor** [comment]
> I'm guessing that this would be like
> 
> ```js
> if (Platform.OS === 'web') {
>   NativeWindStyleSheet.setWebClassNameWebStrategy = twMerge
> }
> ```
> 
> In our index.js/main.js

This is the correct answer.

If you update to v4, you can use `tailwind-merge` as documented in its repo
