### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by renatonmag** [marklawlor/nativewind#451]
After installing nativewind I got this error:

`TypeError: Cannot read property 'create' of undefined, js engine: hermes`

This is my package.json

```
{
  "name": "condoconnect-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.9",
    "expo-status-bar": "~1.4.4",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.71.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.14",
    "tailwindcss": "^3.3.0",
    "typescript": "^4.9.4"
  },
  "private": true
}

```

This is tailwind.config.js

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

This is babel.config.js

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['nativewind/babel'],
  };
};
```

Can someone help me understand this?

EDIT:
It was a problem with the cache. I cleared it and the issue is gone.
`yarn start --clear`

**Comment by etc-tiago** [comment]
Same issue.

**Comment by etc-tiago** [comment]
When I use style(View) this error happens. I need to use it because the code is shared between solito/nextjs and expo.

**Comment by etc-tiago** [comment]
Changing js engine to jsc the error changes to ```'TypeError: undefined is not an object (evaluating '_NativeWindStyleSheet.create')'```

**Comment by AndresdoSantos** [comment]
I have the same problem, when I try to use landscape I get the error `TypeError: cannot add a new property, js engine: hermes`.

**Comment by renatonmag** [comment]
Didn't the restart with the clean cache solve it?

**Comment by CONST-4-NTINE** [comment]
As mentioned by @marklawlor in this comment : https://github.com/marklawlor/nativewind/issues/286#issuecomment-1280301118

edit your content to : content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'] to

**Comment by MedChahboun** [comment]
As mentioned by @marklawlor in this comment : https://github.com/marklawlor/nativewind/issues/286#issuecomment-1280301118

edit your content to : content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'] so that node modules is no longer included !

**Comment by subhranshuchoudhury** [comment]
> As mentioned by @marklawlor in this comment : [#286 (comment)](https://github.com/marklawlor/nativewind/issues/286#issuecomment-1280301118)
> 
> edit your content to : content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'] so that node modules is no longer included !

This worked for me. "expo": "~49.0.5". Thanks a lot.

**Comment by Serpentarius13** [comment]
This is still happening to me with
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

**Comment by marklawlor** [comment]
This is fixed in v4. If your `context` array needs adjusting it will provide a warning message
