### ISSUE TITLE
Not woriking inside react navigation

### ISSUE THREAD

**Issue by dhawalpatil200** [marklawlor/nativewind#457]
Home.js
import { View, Text } from 'react-native';
import React from 'react';

const Home = () => {
  return (
    <View className='flex justify-center items-center'>
      <Text className='text-red-600'>Home screen </Text>
    </View>
  );
};

export default Home;

App.js
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import HomeScreen from './screens/HomeScreen';

import { NativeWindStyleSheet } from 'nativewind';

NativeWindStyleSheet.setOutput({
  default: 'native',
});

export default function App() {
  const Stack = createNativeStackNavigator();

  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name='Home' component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

styles are not applying

**Comment by script8888** [comment]
Mine was fixed when  I added the directory to the Tailwind.config.js

**Comment by Nishant-Khatri** [comment]
> Mine was fixed when I added the directory to the Tailwind.config.js

Which directory you added to tailwind.config i have been facing the same issue

**Comment by MikeCheek** [comment]
I had the same issue and fixed by adding src files to tailwind config.

`
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
`

In my example it is in the "content" array, be sure that your files are included there

**Comment by Jordi-Buitrago** [comment]
I had the same problem and this is how I solved it:

 1. Install the Expo CLI with `npm install expo-cli --global`.
 2. Run `expo start -c` or `react-native start --reset-cache` as described
    in the [documentation](https://www.nativewind.dev/guides/troubleshooting).
 3. If that doesn't work, make sure that the routes in the **content**
    section of your Tailwind configuration file are set correctly.

For example, the following configuration file will only apply Tailwind styles to files in the **App.js**, **src/screens** directory, and ***src/components*** directory:

```
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/screens/**/*.{js,jsx,ts,tsx}", "./src/components/**/*.{js,jsx,ts,tsx}"],
    theme: {
      extend: {},
    },
    plugins: [],
}
```

**Comment by marklawlor** [comment]
Requiring a content glob required and is both documented by NativeWind and Tailwind CSS.

**Comment by IGIRANEZAJosue** [comment]
I tried all of the above methods and none of them worked

**Comment by mikemedina22800** [comment]
> I tried all of the above methods and none of them seem to work.

Same, maybe they're not even compatible anymore.
