### ISSUE TITLE
styling only work when flex-1 is on view componentn

### ISSUE THREAD

**Issue by shanoysinc** [marklawlor/nativewind#461]
**Describe the bug**
```
import React from "react";
import { Text, View } from "react-native";
import { format } from "date-fns";
export const HomeScreenHeader = () => {
  return (
    <View className="flex-1">
      <View>
        <Text className={`font-bold text-lg`}>
          {format(new Date(), "MMMM dd")}
        </Text>
        <Text>Greetings from the team at testing</Text>
      </View>
    </View>
  );
};
```

**To Reproduce**
Once i remove flex-1 on the view component the styling on text doesnt work. I am on  react native expo 48.0.11

**Comment by marklawlor** [comment]
Its hard to tell exactly why from that code snippet alone (e.g what was the parent component?)

Its was either because of the flex-1 quirk of React Native, or a cache bug in v2 (this is fixed in v4)
