### ISSUE TITLE
Project status: development is moving to Expo

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/nativewind#464]
Hello everyone,

I hope you're doing well! If you're following me on GitHub, you may have noticed that I recently joined Expo and am working on projects such as Expo Router. My goal at Expo is to focus on the web platform and improve the multi-platform experience. This includes enhancing how React Native projects can integrate with the web, such as styling via CSS.

There is significant overlap between NativeWind and Expo's vision, as both aim to provide a layer of CSS interoperability for React Native. Expo's plan is to release the CSS interoperability as a Metro transform and will not be exclusive to Expo (but expect a first-class experience if you use Expo CLI/EAS!). From my experience, the transform works better than NativeWind is all aspects. It has better performance and the development experience is so much more enjoyable. You won't have to worry about cache resets and gain new features like hot reloads on `tailwind.config.js` updates! For Next.js apps, they will finally be able to remove the `babel` plugin and upgrade to `swc` 

For this reason, I'm going to put a pause on the development of NativeWind and instead focus on working on the Metro CSS transform. After the transform stabilises, I'm going to re-evaluate how NativeWind fits into this new ecosystem. NativeWind will most likely turn into a wrapper around the transform, improving the overall Tailwind experience.

I understand that some people might be frustrated that they have been waiting for bug fixes and new features. I ask for your patience during this transitional period. Hopefully, the positive news you can take from this is that I'm employed and will be actively working on native styling as part of my job description.

But I do hope that most people are excited by this news. There are many, many open issues about bugs about how NativeWind integrates with Metro, people being stuck on weird cache bugs and no documentation on Expo Web. I'm super excited to see these issues go away.

Last but not least, I'm sorry for the slow updates - it's been a busy year for me and wanted to make sure that everything was in order before sharing this with you all.

More updates coming soon! If you want a peek of how things are progressing check out this PR https://github.com/expo/router/pull/498 (**NOTE:** It's not called `@expo/styling` and is not part of the Expo Router project. This is placeholder/development)

Cheers,

Mark

**Comment by timedtext** [comment]
Great news！

**Comment by Unforgiven-wanda** [comment]
Congratulations. I look forward to seeing what you'll come up with.
Best of luck going forward.

**Comment by akashsharma99** [comment]
I am starting out a new project, should I use native wind now or wait. Meanwhile is there a good actively maintained library that helps use tailwind in RN?

**Comment by NandoMB** [comment]
> I am starting out a new project, should I use native wind now or wait. Meanwhile is there a good actively maintained library that helps use tailwind in RN?

Up!

**Comment by javascripter** [comment]
> I am starting out a new project, should I use native wind now or wait. Meanwhile is there a good actively maintained library that helps use tailwind in RN?

I think it's still okay to continue using NativeWind while we wait. NativeWind works fine for now and the syntax of NativeWind mostly matches the original Tailwind.

Even if a migration to another library is needed in the future I suppose the migration won't be too painful either.

There are some alternative libraries you can choose as well:
- https://github.com/jaredh159/tailwind-react-native-classnames
  - Comparison: https://github.com/jaredh159/tailwind-react-native-classnames/discussions/171#discussioncomment-3097079

**Comment by NandoMB** [comment]
@marklawlor, any progress?? 😃

**Comment by tconroy** [comment]
Thanks for the update!
I just stated using NativeWind and really like it. However, my project is not Expo based. Will I still be able to use this Expo-focused alternative? My project does use metro, for what it's worth.

**Comment by mozzius** [comment]
Hey @marklawlor! Looks like expo/router#498 got merged with Expo 49/Expo router v2 beta, congrats! Any update on what that means for this project?

**Comment by xinha-sh** [comment]
I guess @marklawlor has started working on [V4](https://github.com/marklawlor/nativewind/tree/v4) I have been using V3 alpha. Greatly looking forward to this

**Comment by tconroy** [comment]
Keeping us all in suspense! 😄 Happy to see there's some movement for v4 but a little confused given the previous messaging for dev moving to expo. @marklawlor, not to pester you too much, but are you able to share any updates with the community? We're all super excited about what you're working on!

**Comment by teddybee** [comment]
As far as I have seen, the expo router v2 uses css and tailwind only for web platform.

**Comment by marklawlor** [comment]
Hi everyone, 

This move has been put on hold but a new release will still be happening soon-ish.

**Comment by Eprince-hub** [comment]
When you say `development is moving to Expo` does it mean it can't be used anymore with `react-native-cli` projects?

**Comment by rohankm** [comment]
> Hi everyone,
> 
> This move has been put on hold but a new release will still be happening soon-ish.

Hi we are waiting for the new release :)

**Comment by karthickcypher** [comment]
@marklawlor Any updates on v4 ?

**Comment by teddybee** [comment]
> @marklawlor Any updates on v4 ?

[4.0.0-alpha.12](https://www.npmjs.com/package/nativewind/v/4.0.0-alpha.12)
0
8 hours ago

**Comment by karthickcypher** [comment]
Yeah, I was wondering if there's an ETA or something?

**Comment by Stancobridge** [comment]
@marklawlor thanks for this project, I see u have started working on the V4 and the docs is also accessible now. I appreciate that

**Comment by barbinbrad** [comment]
What's the status of this project?

**Comment by marklawlor** [comment]
Moving the Expo was cancelled as it didn't really fit within the organisation structure. NativeWind v4 is in active development, and is somewhat stable. Its actively being published to `npm`

**Comment by teddybee** [comment]
@marklawlor Could you estimate the time, when will the v4 beta(enough stable to start a production app with it)?

**Comment by barbinbrad** [comment]
Oh shit, this project is amazing! Great work @marklawlor

**Comment by umardev500** [comment]
wtf this a good project why paused bro

**Comment by teddybee** [comment]
> wtf this a good project why paused bro

He recently put up the 4.1.1 version to npm. Please gather information before write next time.
