### ISSUE TITLE
Nativewind styles are not working on web platform

### ISSUE THREAD

**Issue by Abror4544** [marklawlor/nativewind#470]
**Describe the bug**
Nativewind does not work on the web platform. Works only when we add 1 style (i.e. 1 class). For example, if you add className="bg-gray-400" to the View, then it works if className="bg-gray-400 hidden" then the styles of this block are cleared.

**Expected behavior**
To ensure that the styles on the web platform are the same with mobile devices

**Screenshots**
![browser](https://user-images.githubusercontent.com/70596977/236253066-9f582107-793d-4945-8173-211790fc71c1.jpg)
![mobile](https://user-images.githubusercontent.com/70596977/236253072-f44418f8-dbe7-4cdb-9ed2-3c9bfbd0001b.jpg)

ps: I tried to follow the example, I tried to change the webpack and metro configurations. Changed versions. Tried different configurations postcss, tailwind, app, babel

**Comment by jeltehomminga** [comment]
yes, same here

**Comment by msalehy** [comment]
following ,. same issue

**Comment by lukaszradziak** [comment]
I have the same issue. Tailwind classes do not appear in the browser.
<img width="644" alt="image" src="https://github.com/marklawlor/nativewind/assets/1611323/4702398a-f392-4e71-8c7e-52b5f3c93cc6">
Maybe rollback to older version will help?

**Comment by Ayoubjouda** [comment]
same issue , styles don't apply on web.

**Comment by titicarabina** [comment]
same issue here , any fixes yet?

**Comment by vendramini** [comment]
Yep, same problem. My config is:
```
"expo": "48.0.16",
"nativewind": "^2.0.11",
"next": "13.4.5",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.71.8",
"react-native-web": "~0.18.12",
```
tailwind.config.js
```javascript
const nativewind = require('nativewind/tailwind/css');
const {PrimaryColors, SecondaryColors} = require("../../libs/business/src");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    '../../libs/ui/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: PrimaryColors.primary,
        secondary: PrimaryColors.secondary,
        white: SecondaryColors.fourth,
      }
    },
  },
  plugins: [nativewind],
  important: 'html',
};

```

**Comment by lukaszradziak** [comment]
I use twrnc and no problems on web - https://github.com/jaredh159/tailwind-react-native-classnames

**Comment by vendramini** [comment]
@lukaszradziak I tried and it works. However, on web it creates every style inside the style tag, which means we will ship a tons of unnecessary repeated styles, right?

nativewind still the best solution if we can fix this problem.

Anyone was able to manage it?

**Comment by MartiiDev** [comment]
I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
```
import { NativeWindStyleSheet } from "nativewind";

NativeWindStyleSheet.setOutput({
  default: "native",
});
```

(I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)

**Comment by carbondesigned** [comment]
> I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> 
> ```
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });
> ```
> 
> (I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)

good catch, works for me, thanks! 👍 

btw, using Expo Router so instead of putting it in my `App.js` I put it in my root `_layout.tsx`

**Comment by vendramini** [comment]
When importing a `<View className='tw classes'></View>' into nextjs, how is this solution related to? It still not putting the tailwind classes on web.

My setup are nx workspaces:

1. Expo.
2. NextJS.
3. Shared UI Libraries.

I'm importing my components from the shared UI libraries. Works fine on Expo, but not dropping tw classes on nextjs (and there's no error). If I use style or twrnc as mentioned before, it works (however, as I said, twrnc adds a ton of inline styles, which I don't want).

**Comment by vendramini** [comment]
Hey guys, I managed to solve my problem. I don't know why and how, probably I unintentionally deleted my babel config and I didn't notice. I'm wrapping my components now with `styled` as docs says to, and everything is working as expected.

There are some differences between web and mobile styles, but that's another problem.

Thanks.

**Comment by rafaelalexandrino** [comment]
> I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> 
> ```
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });
> ```
> 
> (I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)

This worked perfectly!

**Comment by GustavoSmith** [comment]
> I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> 
> ```
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });
> ```
> 
> (I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)

This does solve the problem.

It is mentioned in the docs: https://www.nativewind.dev/quick-starts/expo

"Expo SDK <=45 supports React Native Web <=0.17 which cannot output classNames. You need to change the NativeWindStyleSheet output to use native for all platforms."

afaik i'm using Expo SDK 48, so I don't know why I needed this.

**Comment by cupid20103** [comment]
We can solve above problem using below code.

```
import { NativeWindStyleSheet } from "nativewind";

NativeWindStyleSheet.setOutput({
  default: "native",
});
```

You can define above code in the index.tsx or _layout.tsx in the project.

**Comment by 0tii** [comment]
> I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> 
> ```
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });
> ```
> 
> (I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)

Can confirm this fixing the issue even in Expo SDK 50 with nativewind 2.0.11. Putting it in my _layout.tsx allowed it to work in web.

**Comment by jackadair** [comment]
Yo if anyone has this issue on NativeWind v4 with Metro, run useFonts hook on your index route:

```
import { useFonts } from 'expo-font';
const [fontsLoaded, fontError] = useFonts({
    Athletics: require('../assets/fonts/Athletics-Regular.otf'),
});
  ```

**Comment by patlux** [comment]
I think that's intentional. So it will not work. See https://www.nativewind.dev/quick-starts/expo#expo-web

> When running on web, NativeWind is a compatability layer between [Tailwind CSS](http://www.tailwindcss.com/) and React Native.

> You will need follow a [Tailwind CSS installation guide](https://tailwindcss.com/docs/installation) and ensure NativeWind is transpiled.

This means you need to setup it like with every other web app:

Create `src/tailwind.css`:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Run 

```sh
npx tailwindcss -i ./src/tailwind.css -o ./public/tailwind.css --watch
```

With expo-router add to your `app/_layout.tsx`

```tsx
import Head from 'expo-router/head'

      <Head>
        <link href="/tailwind.css" rel="stylesheet" />
      </Head>
```

Now it's working.

**Comment by Peyu5h** [comment]
Any way to fix h-screen/w-screen for web i am getting `Prop `style` did not match. Server: "width:0px" Client: "width:1536px"`

**Comment by minhquan1313** [comment]
> I think that's intentional. So it will not work. See https://www.nativewind.dev/quick-starts/expo#expo-web
> 
> > When running on web, NativeWind is a compatability layer between [Tailwind CSS](http://www.tailwindcss.com/) and React Native.
> 
> > You will need follow a [Tailwind CSS installation guide](https://tailwindcss.com/docs/installation) and ensure NativeWind is transpiled.
> 
> This means you need to setup it like with every other web app:
> 
> Create `src/tailwind.css`:
> 
> ```css
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> Run
> 
> ```shell
> npx tailwindcss -i ./src/tailwind.css -o ./public/tailwind.css --watch
> ```
> 
> With expo-router add to your `app/_layout.tsx`
> 
> ```tsx
> import Head from 'expo-router/head'
> 
>       <Head>
>         <link href="/tailwind.css" rel="stylesheet" />
>       </Head>
> ```
> 
> Now it's working.

- Following this and the nativewind doc(v2), after step 3 `Add the Babel plugin` is done, you will need to install postcss and autoprefixer using `npm install -D postcss autoprefixer` (from tailwind's doc).
- Then create a css file, for example `assets/styles/tailwind.css` and add the default values from tailwind's doc.
- Then import the file to `app/_layout.tsx` or whatever your main file, something like `import "@/assets/styles/tailwind.css";`
- Then `npx tailwindcss init -p` to get the postcss config file.
- After this, you can restart expo server and your app is good to go. No need `npx tailwindcss -i ...` or `<link href="/tailwind.css"...` because you already imported it _layout.tsx or index.tsx.

**Comment by yunusparvezkhan** [comment]
> I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> 
> ```
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });
> ```
> 
> (I have no idea where this comes from, I have just seen this snippet in some other projects on GitHub and it seems to work)

Great. Thanks for this catch. This somehow made it work. I would love to know why it was not working on the web and why this piece of code made it work. It would be beneficial if anybody elaborate on the theory. Eagerly waiting to see responces.

**Comment by Emmanuel-xt** [comment]
> issue

This worked for me in 
Add this way 

import { StyleSheet, Text, View } from 'react-native'
import React, { useEffect } from 'react'
import { Slot, SplashScreen, Stack } from 'expo-router'
import { useFonts } from 'expo-font'
import { NativeWindStyleSheet } from "nativewind";

SplashScreen.preventAutoHideAsync();

const RootLayout = () => {
  const [fontsLoaded, error] = useFonts({
    "Poppins-Black": require("../assets/fonts/Poppins-Black.ttf"),
    "Poppins-Bold": require("../assets/fonts/Poppins-Bold.ttf"),
    "Poppins-ExtraBold": require("../assets/fonts/Poppins-ExtraBold.ttf"),
    "Poppins-ExtraLight": require("../assets/fonts/Poppins-ExtraLight.ttf"),
    "Poppins-Light": require("../assets/fonts/Poppins-Light.ttf"),
    "Poppins-Medium": require("../assets/fonts/Poppins-Medium.ttf"),
    "Poppins-Regular": require("../assets/fonts/Poppins-Regular.ttf"),
    "Poppins-SemiBold": require("../assets/fonts/Poppins-SemiBold.ttf"),
    "Poppins-Thin": require("../assets/fonts/Poppins-Thin.ttf"),
  });
  
  useEffect(() => {
    if (error) throw error;
  
    if (fontsLoaded) {
      SplashScreen.hideAsync();
    }
  }, [fontsLoaded, error]);
  
  if (!fontsLoaded && !error) {
    return null;
  }
  return (
    <Stack>
      <Stack.Screen name='index' options={{headerShown : false}} />
    </Stack>
  )
  }
  
  export default RootLayout
  
  NativeWindStyleSheet.setOutput({
    default: "native",
  });

// const styles = StyleSheet.create({})

**Comment by RobSteward** [comment]
I've played around with both solutions now and for me both of them work (individually and adding both at the same time).

I've decided to stick with @patlux 's solution based @minhquan1313's implementation, simply based on the premise that it looks like the more intended implementation of TailwindCss on the web. So my final `_layout.tsx` looks like this:
```
import { Stack } from 'expo-router'
import * as SplashScreen from 'expo-splash-screen'
import { GluestackUIProvider, Text } from '@gluestack-ui/themed'
import { config } from '@gluestack-ui/config'
import '@/assets/styles/tailwind.css'

export {
  // Catch any errors thrown by the Layout component.
  ErrorBoundary,
} from 'expo-router'

export const unstable_settings = {
  // Ensure that reloading on `/modal` keeps a back button present.
  initialRouteName: '(tabs)',
}

// Prevent the splash screen from auto-hiding before asset loading is complete.
SplashScreen.preventAutoHideAsync()

export default function RootLayout() {
  [... some fonts stuff]

  return <RootLayoutNav />
}

function RootLayoutNav() {
  return (
    <GluestackUIProvider config={config}>
      <Stack>
        <Stack.Screen
          name='index'
          options={{ headerShown: false }}
        />
        <Stack.Screen
          name='modal'
          options={{ presentation: 'modal' }}
        />
      </Stack>
    </GluestackUIProvider>
  )
}

```

 `assets/styles/tailwind.css`
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

 `package.json`
```
{
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@gluestack-style/react": "^1.0.56",
    "@gluestack-ui/config": "^1.1.18",
    "@gluestack-ui/themed": "^1.1.30",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.14",
    "expo-av": "^14.0.5",
    "expo-constants": "^16.0.2",
    "expo-device": "^6.0.2",
    "expo-document-picker": "^12.0.2",
    "expo-font": "~12.0.7",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.16",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.6",
    "expo-web-browser": "~13.0.3",
    "lucide-react-native": "^0.395.0",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.2",
    "react-native-appwrite": "^0.4.0",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-svg": "~15.2.0",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "~0.19.10"
  },
  "devDependencies": {
    "@babel/core": "^7.24.3",
    "@types/react": "~18.2.45",
    "autoprefixer": "^10.4.19",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.1",
    "postcss": "^8.4.38",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "~5.3.3"
  },
  "private": true
}

```

**Comment by Pollick0** [comment]
> I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> 
> ```
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });
> ```
> 
> (I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)

I love you ❤️

**Comment by muhammadalaa20** [comment]
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });

You are a legend <3

**Comment by kibecodes** [comment]
Anyone got this working with nativewind v4 ?

**Comment by ManasaGDL** [comment]
> > I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> > ```
> > import { NativeWindStyleSheet } from "nativewind";
> > 
> > NativeWindStyleSheet.setOutput({
> >   default: "native",
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)
> 
> good catch, works for me, thanks! 👍
> 
> btw, using Expo Router so instead of putting it in my `App.js` I put it in my root `_layout.tsx`

Worked for me too...thank you

**Comment by JuliusWallblom** [comment]
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });

I would also love to know

**Comment by waellolo123** [comment]
hi every one , i'm using expo and i have same issue but i added it in my index.js and it works thanks everyone

import { NativeWindStyleSheet } from "nativewind";

NativeWindStyleSheet.setOutput({
default: "native",
});

**Comment by vineckjs** [comment]
> I've played around with both solutions now and for me both of them work (individually and adding both at the same time).
> 
> I've decided to stick with @patlux 's solution based @minhquan1313's implementation, simply based on the premise that it looks like the more intended implementation of TailwindCss on the web. So my final `_layout.tsx` looks like this:
> 
> ```
> import { Stack } from 'expo-router'
> import * as SplashScreen from 'expo-splash-screen'
> import { GluestackUIProvider, Text } from '@gluestack-ui/themed'
> import { config } from '@gluestack-ui/config'
> import '@/assets/styles/tailwind.css'
> 
> export {
>   // Catch any errors thrown by the Layout component.
>   ErrorBoundary,
> } from 'expo-router'
> 
> export const unstable_settings = {
>   // Ensure that reloading on `/modal` keeps a back button present.
>   initialRouteName: '(tabs)',
> }
> 
> // Prevent the splash screen from auto-hiding before asset loading is complete.
> SplashScreen.preventAutoHideAsync()
> 
> export default function RootLayout() {
>   [... some fonts stuff]
> 
>   return <RootLayoutNav />
> }
> 
> function RootLayoutNav() {
>   return (
>     <GluestackUIProvider config={config}>
>       <Stack>
>         <Stack.Screen
>           name='index'
>           options={{ headerShown: false }}
>         />
>         <Stack.Screen
>           name='modal'
>           options={{ presentation: 'modal' }}
>         />
>       </Stack>
>     </GluestackUIProvider>
>   )
> }
> ```
> 
> `assets/styles/tailwind.css`
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> `package.json`
> 
> ```
> {
>   "version": "1.0.0",
>   "main": "expo-router/entry",
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "web": "expo start --web",
>     "test": "jest --watchAll"
>   },
>   "jest": {
>     "preset": "jest-expo"
>   },
>   "dependencies": {
>     "@expo/vector-icons": "^14.0.0",
>     "@gluestack-style/react": "^1.0.56",
>     "@gluestack-ui/config": "^1.1.18",
>     "@gluestack-ui/themed": "^1.1.30",
>     "@react-navigation/native": "^6.0.2",
>     "expo": "~51.0.14",
>     "expo-av": "^14.0.5",
>     "expo-constants": "^16.0.2",
>     "expo-device": "^6.0.2",
>     "expo-document-picker": "^12.0.2",
>     "expo-font": "~12.0.7",
>     "expo-linking": "~6.3.1",
>     "expo-router": "~3.5.16",
>     "expo-splash-screen": "~0.27.5",
>     "expo-status-bar": "~1.12.1",
>     "expo-system-ui": "~3.0.6",
>     "expo-web-browser": "~13.0.3",
>     "lucide-react-native": "^0.395.0",
>     "nativewind": "^2.0.11",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-native": "0.74.2",
>     "react-native-appwrite": "^0.4.0",
>     "react-native-gesture-handler": "^2.16.2",
>     "react-native-reanimated": "~3.10.1",
>     "react-native-safe-area-context": "4.10.1",
>     "react-native-screens": "3.31.1",
>     "react-native-svg": "~15.2.0",
>     "react-native-url-polyfill": "^2.0.0",
>     "react-native-web": "~0.19.10"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.24.3",
>     "@types/react": "~18.2.45",
>     "autoprefixer": "^10.4.19",
>     "jest": "^29.2.1",
>     "jest-expo": "~51.0.1",
>     "postcss": "^8.4.38",
>     "react-test-renderer": "18.2.0",
>     "tailwindcss": "3.3.2",
>     "typescript": "~5.3.3"
>   },
>   "private": true
> }
> ```

Thanks for share your devDependencies. Following those versions, works for me

**Comment by LBeckX** [comment]
But why this is a problem with expo ~51.x and react-native-web > 17

**Comment by usmankhalid444** [comment]
i am getting this error when applying the recommended solution

Module '"nativewind"' has no exported member 'NativeWindStyleSheet'.

**Comment by exoer** [comment]
> Hi ! I can't use NativeWindStyleSheet with 4.0.36 version. How can I fix this in other ways ? Thanks a lot !

https://www.nativewind.dev/blog#nativewindstylesheet-renamed-to-stylesheet

**Comment by waellolo123** [comment]
hi sir, to me i stoped all kinds of css frameworks for react native, now i use only Stylesheet On Nov 1, 2024 2:37 PM, Arne ***@***.***> wrote:

Hi ! I can't use NativeWindStyleSheet with 4.0.36 version. How can I fix this in other ways ? Thanks a lot !

https://www.nativewind.dev/blog#nativewindstylesheet-renamed-to-stylesheet

**Comment by sgClaudia98** [comment]
> > Hi ! I can't use NativeWindStyleSheet with 4.0.36 version. How can I fix this in other ways ? Thanks a lot !
> 
> https://www.nativewind.dev/blog#nativewindstylesheet-renamed-to-stylesheet

The setOutput function is deprecated too, if someone has another fix, please share
https://www.nativewind.dev/blog#miscellaneous-updates

**Comment by wadpas** [comment]
In `tailwind.config.js` change `content` to:
content: [
'./app/**/*.{js,jsx,ts,tsx}',
'./components/**/*.{js,jsx,ts,tsx}'
]

package:
"expo": "~52.0.23",
"nativewind": "^4.1.23",
 "tailwindcss": "^3.4.17"

**Comment by rayanfer** [comment]
Add nativewind/babel in presets. This worked for me.

```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { unstable_transformImportMeta: true }],
      "nativewind/babel",
    ],
  };
};

```

Restart the server with `npm run web --reset-cache`

**Comment by itseriqq** [comment]
> I don't know if it fixes everyone's problem but in my case adding this in my _App.js_ worked:
> 
> ```
> import { NativeWindStyleSheet } from "nativewind";
> 
> NativeWindStyleSheet.setOutput({
>   default: "native",
> });
> ```
> 
> (I have no idea where this comes from, I have just seen this snippet in some other projects on Github and it seems to work)

i love you brother
