### ISSUE TITLE
Pseudo classes?

### ISSUE THREAD

**Issue by allpwrfulroot** [marklawlor/nativewind#475]
**Describe the bug**

I can't seem to get any pseudo classes working: First, last, even, odd, group, etc. Using the "parent" signifier in the parent. Currently using an Android dev device.

**To Reproduce**
1. Try the following:
```
const Text = styled(RNText, "font-normal text-primary-800 dark:text-primary-100 first:text-red-600");
export default Text;

const Stack = styled(View, "parent", {...})
export default Stack
```
2. Play around with those components and the specific pseudo classes. Nothing seems to work; I'm not sure hover etc are working either.

**Expected behavior**
The first Text in a Stack displays in red.

**Additional context**
Following the install descriptions for nativewind@3.0.0-next.34, with tailwindcss@3.3.2 and RN 0.71.8 (Expo 48.0.15). One patch added to remove gap plugin, since it's no longer necessary.

**Comment by pixelkoduje** [comment]
Same, doesn't work.

**Comment by FujiwaraChoki** [comment]
I don't think nativewind is the optimal solution... Try react-native-tailwindcss

**Comment by oliviercperrier** [comment]
Not even working in their doc: https://www.nativewind.dev/core-concepts/states#hover-focus-and-active

**Comment by juddey** [comment]
Found the same.

**Comment by marklawlor** [comment]
These classes are not supported. I attempted them in the v3 beta, but they are too fragile. If anyone can provide code examples of how to detect first/last children with concepts such as suspense boundaries then I'll implement it.
