### ISSUE TITLE
TextInput Misalignment Issue with Text Size Classes

### ISSUE THREAD

**Issue by zxcvbinz** [marklawlor/nativewind#477]
## Describe the bug
When applying text size classes (e.g. text-sm, text-xl, text2xl, etc.) to TextInput in NativeWind, the line-height becomes incorrect. The cursor is not perfectly centered within the TextInput, indicating a misalignment issue.

## To Reproduce

- Create a TextInput element.
- Apply a text size class to the TextInput element (for example, text-sm, text-xl, or text2xl).
- Click on the TextInput to start typing.

Notice that the cursor is not perfectly centered, suggesting an issue with the line-height.
Expected behavior
When applying text size classes to a TextInput element, the line-height should adjust accordingly to ensure that the cursor remains centered within the TextInput. The current behavior disrupts the visual alignment and provides an inconsistent user experience.

## Screenshots
| With Nativewind | With Styles |
|:-----:|:-------:|
| <img width="400" alt="CleanShot" src="https://github.com/marklawlor/nativewind/assets/42217807/6b58f808-5537-4096-91a8-bf4c0ea96752"> | <img width="400" alt="CleanShot" src="https://github.com/marklawlor/nativewind/assets/42217807/f5fab1ab-55ff-4d35-81dc-23a713c98311"> |

**Code 1:**
```typescript
// TextInput with className
<TextInput
  className={"border-b-2 border-gray-400 mb-8 py-2 text-lg"}
  placeholder="Email"
  value={email}
  onChangeText={setEmail}
/>
```
**Code 2:**
```typescript
// TextInput with className and style
<TextInput
  className={"border-b-2 border-gray-400 mb-8 py-2"}
  style={{ fontSize: 20 }}
  placeholder="Email"
  value={email}
  onChangeText={setEmail}
/>
```

**Comment by chunghn** [comment]
It won't fix even with `textAlignVertical="center"` or any similar style.

Encountered the same issue with 
```
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "expo": "~49.0.5"
```

**Comment by chunghn** [comment]
I found that the issue persists without applying nativewind. Looks like it is a react native issue.

**Comment by Sietze111** [comment]
> I found that the issue persists without applying nativewind. Looks like it is a react native issue.

I think this is very much a NativeWind issue. The issue does not persist for me when using 'regular' styling.

**Comment by marklawlor** [comment]
Please note that `text-` set both font size & line height. From the Tailwind CSS docs:

```
text-lg: font-size: 18px; line-height: 28px
```

If you do not wish for the line-height to change, I would recommend creating a new set of `text-` classes in your theme that only set `font-size`
