### ISSUE TITLE
White flash when app comes to foreground

### ISSUE THREAD

**Issue by imransilvake** [marklawlor/nativewind#478]
**Describe the bug**
When app comes to foreground the dark theme takes a bit to apply on the elements and due to that the Light theme shows on the app.

**To Reproduce**
1. Move the app to background by opening another app
2. then switch back you your react native app
3. when app comes to foreground, the Light theme shows up for a bit of 1-2 seconds then it turns to Dark theme

**Expected behavior**
Light theme should not show when Dark theme is selected during foreground

**Screenshots**
**Wrong:**
![IMG_2813](https://github.com/marklawlor/nativewind/assets/13087225/37043846-4285-4cb9-940c-09273af18b6b)

**Correct:**
![IMG_2815](https://github.com/marklawlor/nativewind/assets/13087225/2d8048da-55ca-4468-b870-59a810c8eedd)

**Additional context**
If I remove `bg-54 dark:bg-50` class from the elements, then the background looks fine
```
<View className="bg-54 dark:bg-50">{content()}</View>
```

**Comment by rinorocks8** [comment]
I also had this error. I believe I fixed it by doing this:

```
  const { colorScheme, setColorScheme } = useColorScheme();
  const loadTheme = async () => {
    const storedTheme = await AsyncStorage.getItem("colorScheme");
    if (storedTheme !== null) {
      setColorScheme(storedTheme);
    } else {
      setColorScheme(colorScheme); // I had the flash when I didn't set the colorScheme when storedTheme is null
    }
  };

  useEffect(() => {
    loadTheme();
  }, []);
```
  
  So I believe it happens when setColorScheme is called conditionally or not applied?

**Comment by imransilvake** [comment]
> It's this issue: [facebook/react-native#28525](https://github.com/facebook/react-native/issues/28525)
> 
> Weirdly enough, it doesn't happen when using useColorScheme from React Native directly - seems like the nativewind hook is slightly slow to update

exactly that's what I noticed

**Comment by imransilvake** [comment]
I solved it finally 🎉.

```
import { useColorScheme as useNativeWindColorScheme } from 'nativewind';
import { AppState, useColorScheme } from 'react-native';

const Root = () => {
	const currentColorScheme = useColorScheme();
	const { colorScheme, setColorScheme } = useNativeWindColorScheme();
	const isDarkTheme = colorScheme === GlobalSchemeEnum.DARK;
	const LightTheme = { dark: !isDarkTheme, colors: ThemeNavigationLightColors };
	const DarkTheme = { dark: isDarkTheme, colors: ThemeNavigationDarkColors };
	const theme = isDarkTheme ? DarkTheme : LightTheme;

	useEffect(() => {
		const subscription = AppState.addEventListener('change', (state) => {
			const isActive = state === 'active';
			if (!isActive) return;
			currentColorScheme && setColorScheme(currentColorScheme);
		});
		return () => subscription.remove();
	}, [colorScheme, setColorScheme, currentColorScheme]);

	{/* Navigation */}
	<NavigationContainer theme={theme}>
		<App />		
	</NavigationContainer>
};

AppRegistry.registerComponent(appName, () => Root);
```

Let me know if it doesn't work!

**Comment by baesumin** [comment]
+1

**Comment by anieve01** [comment]
> I solved it finally 🎉.
> 
> ```
> import { useColorScheme as useNativeWindColorScheme } from 'nativewind';
> import { AppState, useColorScheme } from 'react-native';
> 
> const Root = () => {
> 	const currentColorScheme = useColorScheme();
> 	const { colorScheme, setColorScheme } = useNativeWindColorScheme();
> 	const isDarkTheme = colorScheme === GlobalSchemeEnum.DARK;
> 	const LightTheme = { dark: !isDarkTheme, colors: ThemeNavigationLightColors };
> 	const DarkTheme = { dark: isDarkTheme, colors: ThemeNavigationDarkColors };
> 	const theme = isDarkTheme ? DarkTheme : LightTheme;
> 
> 	useEffect(() => {
> 		const subscription = AppState.addEventListener('change', (state) => {
> 			const isActive = state === 'active';
> 			if (!isActive) return;
> 			currentColorScheme && setColorScheme(currentColorScheme);
> 		});
> 		return () => subscription.remove();
> 	}, [colorScheme, setColorScheme, currentColorScheme]);
> 
> 	{/* Navigation */}
> 	<NavigationContainer theme={theme}>
> 		<App />		
> 	</NavigationContainer>
> };
> 
> AppRegistry.registerComponent(appName, () => Root);
> ```
> 
> Let me know if it doesn't work!

it worked! thank you 💯

**Comment by anieve01** [comment]
@imransilvake's solution worked! thank you @imransilvake  💯

**Comment by believer** [comment]
It seems like the issue happens here: https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/runtime/native/globals.ts#L123

`addChangeListener` gets called with the wrong color scheme when the app is sent to the background. This might happen because iOS [takes a screenshot of the app state](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background#3222195) for the app switcher.

If we modify the change listener to only update the color scheme when the app is `active`, we don't get any styling flashes and everything seems to work:

```js
let appearanceListener = appearance.addChangeListener((state) => {
  if (AppState.currentState !== "active") return
  _colorScheme.set(state.colorScheme ?? "light")
});
```

Maybe @marklawlor knows if this can break some behavior that I'm missing?

**Comment by JClackett** [comment]
I cant figure it out, by I get a flash of the opposite color scheme every time I go from background to foreground. Doesn't matter what my phones color scheme is, it always flashes the opposite each time??

**Comment by marklawlor** [comment]
@believer I'll test it out, but that change should be fine. There appears to be an upstream issue with these listeners, so its probably best to only listen when the app is active.

**Comment by JClackett** [comment]
Adding this, seems to temporary fix it.

```ts
  const colorScheme = useColorScheme()
  const { setColorScheme } = useNWColorScheme()
  React.useEffect(() => {
    setColorScheme(colorScheme as "light" | "dark")
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [colorScheme])
```

**Comment by marklawlor** [comment]
Can people please try `4.0.28`

**Comment by believer** [comment]
Tested with `4.0.29` and I'm not seeing the issue anymore. Thanks for the fix!
