### ISSUE TITLE
Expo app is not bundling properly, throwing error,"cannot read property "Create" of undefined".

### ISSUE THREAD

**Issue by Rakshank-Meena** [marklawlor/nativewind#484]
===================PLEASE REFER TO THE SCREENSHOT TO GET A REFERENCE===================

This problem appears upon running expo app using npx expo start. the app was bundling correctly until day before yesterday. suddenly,upon running the app,it threw me this error. To debug the problem,i initialized a new expo app using npx create-expo-app and the problem seems to appear upon setting it up with nativewind.

The Above bug or problem appears when setting up nativewind for expo app. To debug and to find the root of the problem,i previewed the app on expo go using npx expo start after each step that is described in the nativewind docs. the error seems to appear only after entering the plugins array containing "nativewind/babel" in plugins.

![error](https://github.com/marklawlor/nativewind/assets/116524581/4ffb9b8e-adda-4bfa-8feb-17bdcaec5a58)

**Comment by redReno** [comment]
I have a similar issue. I could add the plugin to babel.config.js without issue but the second I try using the tailwind classes in my Expo blank template project I get the same error.

**Comment by Rakshank-Meena** [comment]
I found the solution,but the problem shouldn't be arriving at first.
Try running npm install expo@48.0.0 . 
I have come to find that nativewind and other libraries only work with this exact version of expo.

**Comment by redReno** [comment]
I got it working after cleaning out the project a couple of times using expo 48.0.18. I needed to run 'npx expo start -c" to clear the cache as well.

**Comment by Rakshank-Meena** [comment]
Yeah I tried that,but it didn't work. I don't know why are these kind of issues so frequent. Makes me wanna shift to flutter tbh.

**Comment by hbracy** [comment]
I'm also running into this- with just react native cli.

**Comment by marklawlor** [comment]
This is due to an incorrectly `content` array containing your `node_modules`. If you update to `v4` we made this error less likely to occur and we will advise you if you need to make any changes to your `content`
