### ISSUE TITLE
When I pass a string as a parameter in React Native, it doesn't apply the styling to the className.

### ISSUE THREAD

**Issue by Leanderson01** [marklawlor/nativewind#485]
**Describe the bug**

In order to remove the tailwind-rn lib from the project, we started replacing it to Native Wind with className. However, some screens exhibited strange behaviors. Background colors and text size are not being applied correctly to components.

**To Reproduce**

Steps to reproduce the behavior for DeviceFlag component:
1. Create a component in React Native;
2. Add a parameter that requests a styling (in my case, it was 'bg' which requires a color, for example: bg-green-200);
3. Concatenate your parameter with a preferred styling (in my case, I applied 'bg' inside the className within a View);
4. See error;

Steps to reproduce the behavior for getFirstLetter component:
1. Create a component in React Native;
2. It should return a <View> with a <Text> inside it.
3. The <Text> style is style={tailwind('text-2xl text-white font-roboto-bold').
4. When style is replaced with className='text-2xl text-white font-roboto-bold', the classes are not applied to the <Text>.
5. The style of the <View> has the same color problem as the DeviceFlag component.

**Expected behavior**

For DeviceFlag component:
It was expected that the passed and concatenated styling would be applied within the className, in my case, to style the background of the View. Here's how it should look when I retrieve the 'bg' information:
![photo_4922929224944299061_y](https://github.com/marklawlor/nativewind/assets/50268751/c6157a49-b6a6-4091-895f-27840fc1c61a)

For getFirstLetter component:
It should create a circle with a defined color and a white letter in the center of it with size 2xl.

![photo_4929610686523354019_y](https://github.com/marklawlor/nativewind/assets/50268751/7f1c9c11-e9e1-459f-a617-e84d54c1e20b)

**Screenshots**

![photo_4922941190723185507_y](https://github.com/marklawlor/nativewind/assets/50268751/80d92ad2-9caa-4651-a6c5-615c80ff41dd)

![photo_4922941190723185508_y](https://github.com/marklawlor/nativewind/assets/50268751/a04e279d-c2d2-4a53-a91c-c40a92446617)

![photo_4929610686523354020_y](https://github.com/marklawlor/nativewind/assets/50268751/06309f20-9089-4e06-aa09-41df7f5c8e07)

**Additional context**

Doing tests, some relevant points were noticed:

For the DeviceFlag component:
When the background-color is written directly to className, the style is applied correctly.
When the string is defined within the component file instead of coming from another file, even concatenating the background-color into className, it works correctly. But for our project, we can't define these styles within the component file.

**Comment by kokokj124** [comment]
@Leanderson01 
Hi bro
I have this problem too, would you happen to have any solution?

**Comment by marklawlor** [comment]
This sounds like the `context` glob was not correctly set in the `tailwind.config.js` file and did not include the extra files where these strings are kept.

I'm going to close this issue, as I can't assist you with only screenshots. The best way to get help is to share your repo (or a minimal reproducible version of it). That way I can clone it, debug the problem and tell you how to fix it.
