### ISSUE TITLE
Sample on website does not work

### ISSUE THREAD

**Issue by MichelBahl** [marklawlor/nativewind#489]
https://www.nativewind.dev/#in-action the expo sample does not work due to unmet peer dependency:

Error:
'nativewind' requires peer-dependency 'tailwindcss'.Dependencies

**Comment by ebulku** [comment]
Have you installed tailwindcss? If not run:

`npm i --save-dev tailwindcss@3.3.2`

**Comment by marklawlor** [comment]
`tailwindcss` is a required peer dependency, but it is not used in the demos. They will work without it installed
