### ISSUE TITLE
Error: Use process(css).then(cb) to work with async plugins (RN 0.72.X)

### ISSUE THREAD

**Issue by Cnordbo** [marklawlor/nativewind#498]
**Describe the bug**
Nativewind/babel - Complaining about async plugin after updating to version 0.72.X

Exact error: 
```
Use process(css).then(cb) to work with async plugins
```

**To Reproduce**
1. Setup a new react-native project using the CLI v0.72.X (npx react-native init nativewindTest)
2. Set up nativewind according to the docs

**Expected behavior**
Expected the app to load with styling

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/385693/19cbc00d-3335-4686-b504-acbe080b3f24)

**Additional context**
Occured after upgrading from 0.71.X to 0.72.X

Stack traces are inconsistent in how they show up, so i was unable to get a full stack trace during the test project. But the issue seems to be related to how `postcss` is used.

**Comment by dylanmeivis** [comment]
@Cnordbo I'm having the same issue at the moment. If you find a fix in the meantime could you please let us know here?

**Comment by amireds** [comment]
Experiencing same issue here as well...

**Comment by marklawlor** [comment]
Tailwindcss published a breaking change as a minor version. Please lock your `tailwindcss@3.3.2`

**Comment by dylanmeivis** [comment]
Can confirm this fixed it for me, thanks @marklawlor !

**Comment by amireds** [comment]
> Tailwindcss published a breaking change as a minor version. Please lock your `tailwindcss@3.3.2.`

It worked for me... Thanks @marklawlor

**Comment by Cnordbo** [comment]
Worked for me as well! Thanks a lot @marklawlor :)

**Comment by Daniel-MSoares** [comment]
It Worked for me as well! Thanks a lot @marklawlor :)

**Comment by JClackett** [comment]
Still having the same issue, expo 48, tailwind 3.3.2?

```
Use process(css).then(cb) to work with async plugins
```

Failing to build on expo

**Comment by akinadebowale** [comment]
Issue persists on RN CLI @marklawlor. Tried `yarn add --dev tailwindcss@3.3.2`.

**Comment by marklawlor** [comment]
If your still having this issue, then you should manually check inside your node_modules at the package.json version of tailwindcss and use commands like `npm list tailwindcss` to ensure you don't have multiple versions installed. 

If you still have the issue after manual verification then provide a link to your repo.

**Comment by akinadebowale** [comment]
Thanks @marklawlor. After doing some digging and testing, seems the issue on end was cache related. Did some deep cleaning, re-installed everything, and now it working correctly.

**Comment by JClackett** [comment]
Ahhh finally solved, had to remove the `^` from the tailwind package json version

**Comment by israelsaraiva** [comment]
I'm using Expo + expo-router + Nx. It was solved just removing `^`

**Comment by dexitional** [comment]
It worked Great for me. Thanks **@marklawlor**

**Comment by bndkt** [comment]
@marklawlor I just upgraded to nativewind@4.0.0-alpha.25 and tailwindcss@3.3.4 (new) and this problem seems to be fixed!

**Comment by marklawlor** [comment]
> any idea if this will be fixed for nativewind v2 and newer versions of tailwind, 3.3.5 for example? v2 + 3.3.5 still errors

v2 most likely will not be updated as I simply don't have the capacity. If someone backports the work from v4 back to v2 I'll merge it.

**Comment by JClackett** [comment]
ah, I thought it was a bug in tailwind. is the recommended version v4 now?

**Comment by devSahinur** [comment]
It worked for me... Thanks @marklawlor

**Comment by KleKlai** [comment]
> Tailwindcss published a breaking change as a minor version. Please lock your `tailwindcss@3.3.2`

It worked for me Thank you

as of today 3.3.2 is the stable higher version break expo

**Comment by XChikuX** [comment]
@bndkt Hey! I tried upgrading to nativewind v4 from v2.
After solving most errors. All I get is a white screen..

Any chance you've encountered this?

**Comment by iamursky** [comment]
> Tailwindcss published a breaking change as a minor version. Please lock your `tailwindcss@3.3.2`

So, any ideas on how to use the latest version of NativeWind 3.3.6 with Expo 49 with the next-router?

**Comment by JackNgulale** [comment]
solution.

change the pakage.json

old
"tailwindcss": "^3.3.6",

new
"tailwindcss": "3.3.2",

it's worked for me

**Comment by JackNgulale** [comment]
`npm install`

**Comment by jorgeacruz** [comment]
> any idea if this will be fixed for nativewind v2 and newer versions of tailwind, 3.3.5 for example? v2 + 3.3.5 still errors

I have same issue, and just add presets: ['babel-preset-expo'], and worked fine

**Comment by wali-developer** [comment]
> Tailwindcss published a breaking change as a minor version. Please lock your `tailwindcss@3.3.2`

Thanks, it works for me

**Comment by ashutosh887** [comment]
Hey Everyone!
Use these version:
Let me know if any further help is needed

```
npm i -D tailwindcss@3.3.2
```

```
yarn add --dev tailwindcss@3.3.2
```

**Comment by JClackett** [comment]
Whats the situation going forward, is it gna be possible to upgrade to latest tailwind at some point?

**Comment by ashutosh887** [comment]
We'll see @JClackett 
For the time being I'm using this version only

**Comment by tylerkahn** [comment]
This should probably be added to the docs. I just ran into this issue with a new project.

**Comment by Felix-Asante** [comment]
> This should probably be added to the docs. I just ran into this issue with a new project.

have you been able to fix it? I have also run into this issue

**Comment by tylerkahn** [comment]
> > This should probably be added to the docs. I just ran into this issue with a new project.
> 
> have you been able to fix it? I have also run into this issue

This is the solution, downgrading and locking the version: https://github.com/marklawlor/nativewind/issues/498#issuecomment-1851133054

**Comment by derek-primumco** [comment]
> Whats the situation going forward, is it gna be possible to upgrade to latest tailwind at some point?

I think the goal is for us to all move to Nativewind v4, which is not released as the default version but is available to install manually (`4.0.23` is latest).

Unfortunately for us, Nativewind eliminated the `styled` HOC, so any upgrade is going to be a large refactor.

The v4 docs https://www.nativewind.dev/v4/overview/ don't include any upgrade instructions either.

**Comment by cernockyd** [comment]
I encountered the same issue with expo router. Switching to Nativewind v4 and following the [installation docs](https://www.nativewind.dev/v4/getting-started/expo-router) has worked fine. Consider these points:
- If you don't comply with the SDK version, you might still get the error. Make sure to use the configs for the right SDK versions, they are all prepared in the [docs tutorial](https://www.nativewind.dev/v4/getting-started/expo-router), in my case, I had to use SDK 50+.
- In my case, it was a new project, so there was no refactoring needed for the switch to Nativewind v4.

**Comment by andres-dos-santos** [comment]
Hi everyone, I'm having a problem with the Android build.

It was running smoothly but after changing the folder name to `(auth)/[user-info]` it started giving this error.

![Captura de tela de 2024-03-14 13-54-09](https://github.com/marklawlor/nativewind/assets/151848729/f2171d76-62f6-4ce9-8f4a-17784587bbd5)

Does anyone know what it could be?

I'm going to remove the parentheses to see if it solves it, but in any case it's strange, it could even be something in the `content`, but I followed the way the documentation says.

```content: ['./app/**/*.tsx', './components/**/*.tsx'],```

**Comment by derek-primumco** [comment]
It's probably the same issue as everyone else:
 - The local minor version of Tailwind and Nativewind got automatically bumped (say by a `^` version number in `package.json`).
 - But the two latest versions are *not* compatible.
 - You either have to lock the Tailwind CSS to the compatible version or upgrade to the pre-release Nativewind 4 version.
   - https://www.nativewind.dev/v4/overview

**Comment by andres-dos-santos** [comment]
thanks @derek-primumco, but I removed nativewind completely, before that I had already generated several builds that worked perfectly and that started to give errors out of nowhere, I can't afford to use the library and have to change everything later, the idea is very good but...

**the packages were in the right version and the build still gave an error**

**Comment by derek-primumco** [comment]
@andres-dos-santos Welcome to React Native / Expo development... This kind of stuff happens for no reason every few weeks. :blush: I'll try to post back after we tackle the Nativewind 4 update to see if I have any tips to share. :wave:

**Comment by Pratham-05** [comment]
I tried everything still th error presist

**Comment by Pratham-05** [comment]
{
  "name": "agrinest",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "expo": "~50.0.14",
    "expo-status-bar": "~1.11.1",
    "nativewind": "^2.0.11",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0"
  },
  "devDependencies": {
    "@babel/core": "7.20.0",
    "tailwindcss": "3.3.2"
  },
  "private": true
}

**Comment by jovimoura** [comment]
hey guys, I solve it removing ^ and installing tailwind 3.3.2!

my package: {
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "dev": "npx expo start --clear",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.2.3",
    "@expo/vector-icons": "^14.0.0",
    "@gorhom/bottom-sheet": "^4.6.3",
    "@react-navigation/native": "^6.0.2",
    "clsx": "^2.1.1",
    "expo": "~51.0.8",
    "expo-font": "~12.0.5",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.14",
    "expo-splash-screen": "~0.27.4",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "expo-web-browser": "~13.0.3",
    "nativewind": "2.0.11",
    "phosphor-react-native": "^2.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-bouncy-checkbox": "^4.0.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-paper": "^5.12.3",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-web": "~0.19.10",
    "tailwind-merge": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.2",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "~5.3.3"
  },
  "private": true
}

**Comment by Hirannuwanpriya** [comment]
I solved this error by changing the tailwindcss version to 3.3.2
Here are the commands I followed

`yarn add nativewind
yarn add --dev tailwindcss@3.3.2`

**Comment by meghraj-suthar** [comment]
After upgrading to latest expo, the entire UI is breaking of the app that is built using nativewind and tailwindcss only. Some screens not having "flex-1" was working fine before but no longer after upgrading.

**Comment by dennyzain** [comment]
> Tailwindcss published a breaking change as a minor version. Please lock your `tailwindcss@3.3.2`

thanks a lot, it worked
