### ISSUE TITLE
Nativewind installation breaks Expo app

### ISSUE THREAD

**Issue by nohr** [marklawlor/nativewind#499]
**Describe the bug**
Adding Nativewind by following the Expo section in the docs producing an app breaking bug that prevents builds from completing:

```zsh
iOS Bundling failed 1142ms
error: app/(tabs)/index.tsx: .../app/(tabs)/index.tsx: Use process(css).then(cb) to work with async plugins
```

**To Reproduce**
1. Create a new expo app with npx create-expo-app@latest (this error occurs on both expo sdks 49 and 48)
2. add Nativewind following the [docs](https://www.nativewind.dev/quick-starts/expo) 

**Expected behavior**
I expected the app to build and show my preview app.

**Comment by marklawlor** [comment]
Please refer to the pinned issue https://github.com/marklawlor/nativewind/issues/498
