### ISSUE TITLE
Use process(css).then(cb) to work with async plugins 

### ISSUE THREAD

**Issue by Koykoy200078** [marklawlor/nativewind#500]
Using react-native 0.72.3, The error doesn't seem to have a stack trace. 

Problem: Use process(css).then(cb) to work with async plugins

**Comment by ihassanamjad** [comment]
Change your tailwindcss version to 3.3.2 and then rum npm/yarn install. This is a tailwind issue.

**Comment by johnslemmer** [comment]
I'm seeing this as well, and the fix that @ihassanamjad mentioned works. Has anyone created an issue with tailwind, if it is their issue?

**Comment by Koykoy200078** [comment]
> Change your tailwindcss version to 3.3.2 and then rum npm/yarn install. This is a tailwind issue.

Thank you for the info.

**Comment by itsyoboieltr** [comment]
It is not an issue, it is a feature to improve performance, based on [Make PostCSS plugin async to improve performance #11548](https://github.com/tailwindlabs/tailwindcss/pull/11548). I assume NativeWind needs to change its behaviour to support/handle the new asynchronous approach.

cc: @marklawlor

**Comment by grandwaterman** [comment]
Nativewind needs to update the package and support Tailwind version changes, this is not a tailwind problem for sure.

The same issue happening in the React Native CLI setup as well as Expo. People have to downgrade to a lower version of Tailwind to make it work.

**Comment by morty052** [comment]
this issue still not fixed, only way is to downgrade tailwind.

**Comment by burakakca** [comment]
Same

**Comment by marklawlor** [comment]
Duplicate of #498. This is fixed in v4
