### ISSUE TITLE
Unexpected token 'export' in `/nativewind/babel.js`

### ISSUE THREAD

**Issue by Rednegniw** [marklawlor/nativewind#506]
**Describe the bug**

Hey guys, I am running into an issue with using nativewind with expo.  Anything I do, I seem to run into this issue when Expo tries to compile the app:

`Unexpected token 'export'  (While processing: "/<path_to_root>/node_modules/nativewind/babel.js")`

This is my `babel.config.js`

![image](https://github.com/marklawlor/nativewind/assets/16265289/21fc144e-27aa-4fff-89e5-7d88c19fa9ce)

I am using `turborepo` and my native app is one of the apps in the `apps` package.

**To Reproduce**

Not sure honestly, just try to setup nativewind as normal in a turborepo monorepo.

**Expected behavior**

For it to compile.

**Screenshots**

![image](https://github.com/marklawlor/nativewind/assets/16265289/fa1821c3-b653-4b9f-9bc2-6f713aa7fc0f)

**Comment by Medkhat** [comment]
Hi there! I also had this issue. I'm working with React Native CLI. This error occured after adding and configuring `eslint-plugin-import`

**Comment by Rednegniw** [comment]
In the end I had a different issue, it was fairly specific to my monorepo configuration, where I imported a file into `tailwind.config.js` which had `export default`.. the error wasn't helpful at all to find it unfortunately 😄 closing the issue now.
