### ISSUE TITLE
I want use library other scale for mutil devices #508

### ISSUE THREAD

**Issue by kokokj124** [marklawlor/nativewind#509]
- Hi all
- How can I use a third-party library to scale to multiple devices?
- Desired:
`import { scale } from 'react-native-size-matters';
`
`<View className={'mx-[${scale(24)}]'}>`
where scale is a function from the 3rd library

**Comment by furkancakici** [comment]
I am wondering too

**Comment by marklawlor** [comment]
You can use PixelRatio and other inbuilt RN functions to scale your theme values https://www.nativewind.dev/customization/theme#pixelratio

Dynamic class names (`'mx-[${scale(24)}]'`) are not allowed in Tailwind CSS (as its a static compiler)
