### ISSUE TITLE
v4.0.0-alpha.0 not working - I want to test

### ISSUE THREAD

**Issue by pakerekchdz** [marklawlor/nativewind#515]
**Describe the bug**
When I run it (even with the --clear flag) it stops the build in progress and doesn't go any further. After removing the global.css import, it builds to the end, but it does not render any nativewind features at all, i.e. nothing changes after entering e.g. className="w-10 h-10 bg-red-600"

**To Reproduce**
1. Install react-native-css-interop@latest and nativewind@^4.0.0-alpha.0
2. Adds to presets: 'nativewind/babel'
3. Configure the tailwind.config.js file
4. Adds `const { withNativeWind } = require('nativewind/metro')
module.exports = withNativeWind(config, {
   input: 'global.css'
})` and create a global.css file
5. import in main layout file.

**Comment by pakerekchdz** [comment]
I want to run this, on a clean copy with expo router.

**Comment by pakerekchdz** [comment]
@marklawlor up

**Comment by XantreGodlike** [comment]
@marklawlor can i help with nativewind4 implementation?)

**Comment by pakerekchdz** [comment]
@XantreGodlike Help me enable this xD

**Comment by marklawlor** [comment]
`v4.0.0-alpha` is not ready for public testing yet, hence no details have been released. But its all open-source, so there's nothing stopping you just copying the example in the repo :man_shrugging:

This won't be part of initial release of v4, the two topics I will need contributor help with are `background-image` and optimising the animation/transition code. Or simply find a className that hasn't been implemented yet. You can used the unit tests as a reference. They are sorted by the same categories as tailwindcss.com and should help you find whats missing - but most of the obvious low hanging fruit has been completed.

**Comment by XantreGodlike** [comment]
Wow. Seems to be here is a lot of work, I've read some code, and will be appreciate to help). Anyone adding signals to react
