### ISSUE TITLE
gap-y-1 does not equal style={{rowGap: 4}}(same as x and columnGap)

### ISSUE THREAD

**Issue by chen-rn** [marklawlor/nativewind#520]
**Describe the bug**
![Screenshot 2023-08-05 at 6 51 26 PM](https://github.com/marklawlor/nativewind/assets/36214945/f6570d1a-7e76-4d56-930b-e89425c768c1)
The class gap-x-1 does not give the same behavior as style={{columnGap: 4}}
It seems like the Nativewind gap adds a marginLeft and marginTop, as opposed to only adding margin inbetween elements.

**Screenshot examples**
This is with style={{columnGap:4}} and style={{rowGap:4}}
![Screenshot 2023-08-05 at 6 52 23 PM](https://github.com/marklawlor/nativewind/assets/36214945/365e809f-a2ef-4ef1-ab32-e926e2aacecc)

This is className="gap-x-1" and "gap-y-1"
![Screenshot 2023-08-05 at 6 55 40 PM](https://github.com/marklawlor/nativewind/assets/36214945/05833b5b-f68e-490d-abd6-7183372fff00)

**Comment by marklawlor** [comment]
This is by design and documented https://www.nativewind.dev/tailwind/flexbox/gap

`columnGap` & `rowGap` is only available in 0.71+. A future version will increase the minimal RN version and remove the `gap` polyfill
