### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by itmejayesh** [marklawlor/nativewind#521]
![Screenshot 2023-08-06 155748](https://github.com/marklawlor/nativewind/assets/103041733/caab16d0-7dec-4bdc-bfa7-048ab71f0154)

I changes my tailwind version in the package.json but still again this error come how do fix this

**Comment by ebulku** [comment]
Did you run `npm install` after you changed the version?

**Comment by marklawlor** [comment]
Please re-read the error message and then use the search function. There is a pinned issue https://github.com/marklawlor/nativewind/issues/498
