### ISSUE TITLE
I can't seem to get Nativewind running in Expo 49 without Expo router

### ISSUE THREAD

**Issue by Stancobridge** [marklawlor/nativewind#523]
Subject: Issue with Upgrading to Expo Router Version 3.0.0-next.34 and NativeWind Integration

Description:
I'm encountering an issue while upgrading an existing project to Expo Router version 3.0.0-next.34 and integrating NativeWind. Previously, I had been using version 2.0.11, and my teammate's new project with version 3.0.0-next.34 is working well with the new features. I've followed the updated documentation on the Expo website but have been unable to successfully implement the feature in my older project.

Issue:
When attempting to run the project, I'm encountering the following error related to Android bundling:

```
Android Bundling failed 1955ms
error: node_modules/expo/AppEntry.js: [BABEL] /home/idevosm/idevosm/osmaxin/scorebanter/score-banter-app/node_modules/expo/AppEntry.js: NativeWind preset was not included (While processing: "/home/idevosm/idevosm/osmaxin/scorebanter/score-banter-app/node_modules/nativewind/babel.js")
```

Attempts Made:
1. I've included the necessary configurations in my `metro.config.js` file as follows:
   ```js
   const metroConfig = require('@expo/metro-config');
   const withNativewind = require('nativewind/metro');

   const config = withNativewind(metroConfig.getDefaultConfig(__dirname));

   module.exports = config;
   ```

2. In my `babel.config.js` file, I've made the following adjustments:
   ```js
   module.exports = function (api) {
     api.cache(true);
     return {
       presets: ['babel-preset-expo'],
       plugins: ['react-native-reanimated/plugin', 'nativewind/babel'],
     };
   };
   ```

3. I've also tried using the recommended `metro.config.js` from the Expo website:
   ```js
   // metro.config.js
   const { getDefaultConfig } = require("expo/metro-config");

   const config = getDefaultConfig(__dirname, {
     isCSSEnabled: true,
   });

   module.exports = config;
   ```

4. To resolve the issue, I even moved the `"nativewind/babel"` plugin from the plugins array to the presets array in the `babel.config.js` file as my teammate's project is working fine with this configuration.

Despite these attempts, I am still encountering the same error. I also tried removing the entire metro file, but the error persists.

Any guidance or suggestions to resolve this issue would be greatly appreciated. Thank you.

**Comment by brayden-wong** [comment]
I am having the same issues, could you perhaps post the package.json so I can get the same versions of expo and nativewind as you?

**Comment by hukpo** [comment]
You need to follow all the required steps to use V3
Update your tailwind.config.js and it'll work

<img width="350" alt="image" src="https://github.com/marklawlor/nativewind/assets/40897161/4b021917-ad6b-4e86-8eda-a51e045ab2db">

**Comment by MHase** [comment]
you can find newer instruction how to setup for expo here https://next.nativewind.dev/quick-starts/expo
works like a charm for
```
"expo": "~49.0.7",
```

**Comment by marklawlor** [comment]
v2 has some compatibility issues with Expo Router.

NativeWind v4 has full support https://www.nativewind.dev/v4/getting-started/expo-router

**Comment by Stancobridge** [comment]
> v2 has some compatibility issues with Expo Router.
> 
> NativeWind v4 has full support https://www.nativewind.dev/v4/getting-started/expo-router

Thanks for this update, I will like to know is the v4 stable for production, when should we be expecting it to be production ready. Again, I really appreciate the good work you have been doing on this project
