### ISSUE TITLE
nativewind@next requires outdated package @expo/config-plugins@5.0.4

### ISSUE THREAD

**Issue by benrbowers** [marklawlor/nativewind#524]
**Describe the bug**
For the most part, nativewind seems to be working quite well with expo 49. However, I'm having issues with my react-native-web NextJs port (using [solito](https://solito.dev)).  This issue is coming from being unable to use the latest version of @expo/config-plugins.

Currently, nativewind@next seems to require @expo/config-plugins@5.0.4, which requires me to use an outdated version of @expo/next-adapter, which in turn requires me to use an outdated version of NextJS.

Expo 49 is looking for @expo/config-plugins@~7.2.2, so I suppose I am asking for nativewind to either support this package or to provide some workaround.

Again, Expo app is working fine on Android and iOS with @expo/config-plugins@5.0.4 (at least in expo go on my macbook),
the issue is with using NextJS with react-native-web.

**To Reproduce**
1. Create Expo@49 project with nativewind@next
2. npx expo install --fix
3. yarn why @expo/config-plugins => 5.0.4 instead of 7.2.2
4. Create NextJs@13.2.0 project with react-native-web and nativewind@next
5. Add @expo/next-adapter@5.0.2
6. Next app runs into several issues, mainly being that plugins are not added properly from next.config.js

**Expected behavior**
nativewind@next should be compatible with the latest @expo/config-plugins

**Comment by benrbowers** [comment]
Realizing this also may just be an issue of not knowing how to setup my next.config.js in order to properly transpile the myriad expo packages in my project which _say_ they are web compatible, but are just not ready for next 13.2

Any insight from folks using @expo/next-adapter@5.02+ is appreciated 🙌

**Comment by marklawlor** [comment]
This is resolved in v4

It will be releasing soon. The documentation is [here](https://www.nativewind.dev/v4/overview) if you wish to update early

**Comment by benrbowers** [comment]
Great! Looks like this issue is in fact solved with v4, just tried it on a new branch. Excited for the release!
