### ISSUE TITLE
add pnpm to setup section

### ISSUE THREAD

**Issue by esau-morais** [marklawlor/nativewind#526]
as a pnpm user, it feels bad not to have pnpm option, even tho i don't even need to because of fig/zsh, but someone will

**Comment by tyrauber** [comment]
hey @esau-morais, it might be worth adding pnpm monorepo instructions as well.

```
// pnpm-workspace.yaml
packages:
  - 'apps/**'
  - 'packages/**'
```
```
// .npmrc
node-linker=hoisted
```
