### ISSUE TITLE
bg-opacity-10 is not working

### ISSUE THREAD

**Issue by nateshmbhat** [marklawlor/nativewind#527]
**Describe the bug**
Here's the code i wrote : 
```
 <View
            className="rounded-full h-20 w-20 flex items-center justify-center bg-white bg-opacity-10"> .... </View>
```

**Expected behavior**
Background color is `rgba(255,255,255,0.1)`

Actual behavior : 
It shows full white background as if we never reduced the opacity.

**Workaround I did**
```
<View
            className="rounded-full h-20 w-20 flex items-center justify-center"
            style={{
              backgroundColor: 'rgba(255,255,255,0.1)',
            }}>....</View>
```

**Comment by JWesorick** [comment]
`bg-white/10` or `opacity-10` but `bg-opacity-10` is not a class I believe.

**Comment by jmamadeu** [comment]
> `bg-white/10` or `opacity-10` but `bg-opacity-10` is not a class I believe.

On react native `bg-white/10~` does not work you must use `opacity-<number>`

**Comment by marklawlor** [comment]
`bg-opacity-[n]` are from Tailwind 2. NativeWind only supports Tailwind 3
