### ISSUE TITLE
Request to add support for `border-opacity-*` classes

### ISSUE THREAD

**Issue by darwinshameran** [marklawlor/nativewind#541]
I'm exploring NativeWind for a possible migration from twrnc, unfortunately it seems like NativeWind doesn't support [border-opacity-*](https://v2.tailwindcss.com/docs/border-opacity) classes. 😔

Example: `<View className="border-t border-white border-opacity-10 android:pb-2" />`

**Comment by detachedsoul** [comment]
You can just use /the specified opacity scale you want.

For example your example would be border-white/10.

https://tailwindcss.com/docs/border-color

**Comment by marklawlor** [comment]
NativeWind only supports Tailwind 3. `border-opacity-` is from Tailwind v2
