### ISSUE TITLE
Nativewind not working in expo

### ISSUE THREAD

**Issue by grandwaterman** [marklawlor/nativewind#556]
### Discussed in https://github.com/marklawlor/nativewind/discussions/555

<div type='discussions-op-text'>

<sup>Originally posted by **grandwaterman** September 14, 2023</sup>
Followed the doc https://www.nativewind.dev/quick-starts/expo. 

The three steps, and it is NOT working. and checking the example on Github, it is very different from the doc.

**Got error: Use process(css).then(cb) to work with async plugins**

package.json - dep
  "dependencies": {
    "autoprefixer": "^10.4.15",
    "expo": "~49.0.10",
    "expo-status-bar": "~1.6.0",
    "nativewind": "^2.0.11",
    "postcss": "^8.4.29",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "tailwindcss": "^3.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  
  Are postcss and autoprefixer needed?
  
  Document quality -1</div>

**Comment by 3ddelano** [comment]
Its solved here https://github.com/marklawlor/nativewind/issues/500

**Comment by kevingrondin** [comment]
use this : 

```json
"dependencies": {
"autoprefixer": "^10.4.15",
"expo": "~49.0.10",
"expo-status-bar": "~1.6.0",
"nativewind": "^2.0.11",
"postcss": "^8.4.29",
"react": "18.2.0",
"react-native": "0.72.4",
"tailwindcss": "^3.3.3"
},
"devDependencies": {
"@babel/core": "^7.20.0"
},
```
