### ISSUE TITLE
Vertical Spacing y elements on flex-col (normally use gap-4)

### ISSUE THREAD

**Issue by imprisonedmind** [marklawlor/nativewind#559]
**Describe the bug**
It appears the bug I am experience is when having a parent of flex and using gap then having a child component below, the flex relationship between the parent and child seems to break.

**Code that generates bug**
![Screenshot 2023-09-20 at 21 14 19](https://github.com/marklawlor/nativewind/assets/51891628/421e4cd0-679a-4615-946c-2a15d1ec0483)
![Screenshot 2023-09-20 at 21 15 21](https://github.com/marklawlor/nativewind/assets/51891628/a39f8be8-f1e1-4f72-adbc-291c02a298af)

**Behaviour**
![Frame 1](https://github.com/marklawlor/nativewind/assets/51891628/cc9ddd81-31ad-438d-857f-a48a53718354)

**Comment by imprisonedmind** [comment]
This appears to only happen when I change a child into a component, It seems to break the flex relation ship.

**Comment by imprisonedmind** [comment]
I found a way to fix this, but it is really gross...
If you wrap your FC in a <View> it retains the relationship.

```
<TouchableOpacity
      key={props.index}
      className={`bg-zinc-900 p-2 pr-3 rounded-3xl border border-zinc-700 mb-4`}
    >
      <View className={`flex flex-row items-center w-max justify-between`}>
        <View className={`flex flex-row items-center gap-2`}>
          <View>
            <UserImage Uri={props.user.photoUrl} />
          </View>
          <View>
            <UserDetails
              name={props.user.name}
              isPos={props.isPos}
              recentCategory={props.user.recentCategory}
            />
          </View>
        </View>
        <PriceChip
          isPos={props.isPos}
          recentTransaction={props.user.recentTransaction}
        />
      </View>
    </TouchableOpacity>
```

**Comment by daannet** [comment]
@imprisonedmind Nativewind does not support the new React Native gap yet. It is currently translated to margins added to your child elements. When separating components make sure to add a style prop and pass it down to the first element in it.

By using gap-4 there is a style prop added to the UserCard. Pass this prop down to TouchableOpacity in this case :)

**Comment by daannet** [comment]
@imprisonedmind 
You can find it here: https://www.nativewind.dev/guides/custom-components#passing-styles-to-components

However, it is not very clearly documented when it comes to gap, spacing, divide and the like. Every time I run into issues, I realize I forgot the style prop again, haha.
https://www.nativewind.dev/tailwind/spacing/space-between#how-it-works
