### ISSUE TITLE
Styles do not merge properly

### ISSUE THREAD

**Issue by alexzobi** [marklawlor/nativewind#560]
**Describe the bug**
I am trying to create base components with default props for my app, like font family, etc. Passing in `className` prop to a custom component with previously declared styling doesn't properly merge styles. I actually lose the default styles and only the passed in styling is resolved. 

**To Reproduce**
```typescript
// AppText.tsx
import React from 'react';
import { Text, TextProps } from 'react-native';

const AppText = ({ style, ...props }: TextProps) => (
  <Text
    className="leading-5 font-[AmericanTypewriter] text-base tracking-wide"
    style={style}
    {...props}
  />
);

export default AppText;

// Home.tsx
import React from 'react';
import { View } from 'react-native';
import { Text } from '../../components/ui-kit';

const Home = () => (
  <View>
    <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit</Text>
    <Text className="text-xl">Lorem ipsum dolor sit amet, consectetur adipiscing elit</Text>
  </View>
);

export default Home;
```
**Expected behavior**
The second text component should have larger text (text-xl as opposed to text-base) but should otherwise match the styling of the first text component. 

**Screenshots**
![simulator_screenshot_1153B721-FC8C-477E-B17D-8780F698D872](https://github.com/marklawlor/nativewind/assets/35748903/feeea248-c9e9-4629-9fd3-e9f4b4a374df)

Notice in the screenshot, the second text block has lost all styling except the `text-xl` styling. font family, line height and letter spacing are all lost.

**Comment by badalsaibo** [comment]
Text is a different component. AppText is a different component.

**Comment by marklawlor** [comment]
This is fixed in v4

`className` is now passed as a prop, so you would write 

```tsx
const AppText = ({ className, ...props }: TextProps) => (
  <Text
    className={`leading-5 font-[AmericanTypewriter] text-base tracking-wide ${className}`}
    {...props}
  />
);
```

There is not documentation on how these styles merge https://www.nativewind.dev/v4/core-concepts/style-specificity
