### ISSUE TITLE
className - No overload matches this call.

### ISSUE THREAD

**Issue by mashwishi** [marklawlor/nativewind#561]
I am encountering an issue while using NativeWind with TypeScript in my Expo project. I have followed the documentation and checked the provided resources, but I am still facing the following error:
```
No overload matches this call.
  Overload 1 of 2, '(props: TextProps | Readonly<TextProps>): Text', gave the following error.
    Type '{ children: string; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.
      Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.
  Overload 2 of 2, '(props: TextProps, context: any): Text', gave the following error.
    Type '{ children: string; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.
      Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.ts(2769)
```

**./app.d.ts (located at root):**
```ts
/// <reference types="nativewind/types" />
```

**package.json:**
```json
{
  "dependencies": {
    // ... other dependencies
    "expo": "49.0.3",
    "nativewind": "2.0.11",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.72.3",
    // ... other dependencies
  },
  "devDependencies": {
    // ... other devdependencies
    "tailwindcss": "3.3.2",
    "typescript": "5.0.2"
  },
}
```

**tailwind.config.js:**
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./App.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**tsconfig.json**
```json
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "jsx": "react",
    "module": "es6",
    "target": "es6",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "typeRoots": [
      "./src/types"
    ],
    "strict": true
  },
  "include": [
    "./*.d.ts",
  ],
}
```

**babel.config.js:**
```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      'nativewind/babel',
      ["module:react-native-dotenv", {
        "envName": "APP_ENV",
        "moduleName": "@env",
        "path": ".env",
        "blocklist": null,
        "allowlist": null,
        "blacklist": null, // DEPRECATED
        "whitelist": null, // DEPRECATED
        "safe": false,
        "allowUndefined": true,
        "verbose": false
      }],
    ],
  };
};
```

I have checked the official documentation and quick starts for NativeWind with TypeScript, but the issue persists.

This error started occurring after upgrading to specific versions of Expo, NativeWind, and TypeScript.

I appreciate any guidance on resolving this issue. Thank you!

**Comment by magnum6actual** [comment]
Did you restart your editor after adding app.d.ts?

**Comment by mashwishi** [comment]
> Did you restart your editor after adding app.d.ts?

Yes i already tried that too also did some clear cache in expo

**Comment by mashwishi** [comment]
![image](https://github.com/marklawlor/nativewind/assets/62344860/395f29c3-5b45-43f5-98b7-a328a87aca6d)

I dont know how but this one works...

**Comment by imprisonedmind** [comment]
Your type reference is in the wrong place, it needs to go inside:
```
app.d.ts
```

![Screenshot 2023-09-20 at 20 37 20](https://github.com/marklawlor/nativewind/assets/51891628/833f9442-c05d-4654-a6f0-7cb9f7420afb)

**Comment by jsandev** [comment]
I have the same problem: 

```
{
  "dependencies": {
    "@hookform/resolvers": "^2.9.10",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "@react-navigation/stack": "^6.3.0",
    "@reduxjs/toolkit": "^1.8.5",
    "axios": "^1.1.3",
    "classnames": "^2.3.2",
    "expo": "~47.0.14",
    "expo-build-properties": "~0.4.1",
    "expo-camera": "^13.1.0",
    "expo-clipboard": "~4.0.1",
    "expo-constants": "~14.0.2",
    "expo-dev-client": "~2.0.1",
    "expo-device": "~5.0.0",
    "expo-file-system": "^15.1.1",
    "expo-font": "^11.0.1",
    "expo-image-picker": "^14.0.2",
    "expo-linking": "~3.3.1",
    "expo-local-authentication": "~13.0.2",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "^0.15.6",
    "lottie-react-native": "5.1.4",
    "nativewind": "^2.0.11",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-hook-form": "^7.39.1",
    "react-native": "0.70.8",
    "react-native-bouncy-checkbox": "^3.0.4",
    "react-native-confirmation-code-field": "^7.3.1",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-modal": "^13.0.1",
    "react-native-reanimated": "~2.12.0",
    "react-native-render-html": "^6.3.4",
    "react-native-root-toast": "^3.3.1",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-svg": "13.4.0",
    "react-native-web": "~0.18.7",
    "react-redux": "^8.0.2",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@types/expo": "^33.0.1",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "@types/react-native-svg-charts": "^5.0.12",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "eslint": "^8.0.1",
    "eslint-config-standard": "^17.0.0",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-react": "^7.31.8",
    "prettier": "^2.7.1",
    "react-native-svg-transformer": "^1.0.0",
    "tailwindcss": "3.3.2",
    "typescript": "^4.6.3"
  },
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "version": "1.0.0",
  "private": true,
  "name": "flip"
}

```

My app.d.ts
![image](https://github.com/marklawlor/nativewind/assets/85639396/f82eaf6b-ae59-4607-aec7-345bfd4fc341)


Error:
![image](https://github.com/marklawlor/nativewind/assets/85639396/4364120c-d1c9-40f4-96fc-2d95e3ce3bf2)

**Comment by mashwishi** [comment]
> Your type reference is in the wrong place, it needs to go inside:
> ```
> app.d.ts
> ```
> 
> ![Screenshot 2023-09-20 at 20 37 20](https://github.com/marklawlor/nativewind/assets/51891628/833f9442-c05d-4654-a6f0-7cb9f7420afb)
> 

I think you need to read my first app.d.ts  again like yeah that's how i actually set it up but it's not working

**Comment by mashwishi** [comment]
> @mashwishi if I put `/// <reference types="nativewind/types" />` in `App.tsx` works good 🤔 
> 
> 
> ![image](https://github.com/marklawlor/nativewind/assets/85639396/303dc5ae-063b-4afe-a11c-b2cb72925c59)
> 
> Or: Move the `app.d.ts` into `src/` works good too.
> ![image](https://github.com/marklawlor/nativewind/assets/85639396/91426d86-4633-4b4a-85e0-da5b4ffcdfad)
> 
> 
> Result: ✅ 
> ![image](https://github.com/marklawlor/nativewind/assets/85639396/1fe5dbda-dcaf-44f4-9a74-02727042e932)
> 

Okay I'll try this

**Comment by imprisonedmind** [comment]
> > Your type reference is in the wrong place, it needs to go inside:
> > ```
> > app.d.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Screenshot 2023-09-20 at 20 37 20](https://user-images.githubusercontent.com/51891628/269385108-833f9442-c05d-4654-a6f0-7cb9f7420afb.png)
> 
> I think you need to read my first app.d.ts again like yeah that's how i actually set it up but it's not working

In the screenshot, you provided app.d.ts is empty...

**Comment by mashwishi** [comment]
> ```
> Assuming you are using [v2] configure as such:
> ```
> 
> ![Screenshot 2023-09-21 at 09 08 25](https://user-images.githubusercontent.com/51891628/269521839-b8f0902e-0a72-475d-be75-a24646afc79b.png)

Sorry I didn't get what you want to deliver with that screenshot (_not to be mean, im curious_). Yes, I am using yes V2 and also as [stated at the post it's in the app.d.ts](https://github.com/marklawlor/nativewind/issues/561#issue-1905193970) Also based on the [Expo - NativeWind Docs](https://www.nativewind.dev/quick-starts/expo) there is 3 steps then for typescript user like me in version 2 base on docs [create a new app.d.ts with the reference](https://www.nativewind.dev/getting-started/typescript)

**NOTE:** Expo project is for Android/iOS (not web) 

![image](https://github.com/marklawlor/nativewind/assets/62344860/72d7b7d2-9d4d-48fd-9794-eee7f06eb4e8)
![image](https://github.com/marklawlor/nativewind/assets/62344860/6cab99da-301f-45a4-8cae-0871411c2b27)

**Comment by marklawlor** [comment]
Please just share your repo, or create a new project that you can share, to demonstrate the issue. Screenshots and code snippets are too confusing to troubleshoot.

**Comment by hdsuperman** [comment]
try this:

```json
{
  "extends": "@tsconfig/react-native/tsconfig.json",
  "include": ["app.d.ts", "locales/react-i18next.d.ts", "screens"]
}
```

add "screens" folder

**Comment by badalsaibo** [comment]
FYI the `app.d.ts` at the root level works for RN CLI project. For expo however it doesn't.

**Comment by mashwishi** [comment]
> FYI the `app.d.ts` at the root level works for RN CLI project. For expo however it doesn't, but moving inside the `src` works.

Will try..

**Comment by marklawlor** [comment]
You cannot call the file the same as an existing `node_module` or folder in your project. E.g if you have a folder `app` you cannot call it `app.d.ts`. I recommend calling it `app-env.d.ts`

**Comment by mashwishi** [comment]
> You cannot call the file the same as an existing `node_module` or folder in your project. E.g if you have a folder `app` you cannot call it `app.d.ts`. I recommend calling it `app-env.d.ts`

this one works.

**Comment by mashwishi** [comment]
> You cannot call the file the same as an existing `node_module` or folder in your project. E.g if you have a folder `app` you cannot call it `app.d.ts`. I recommend calling it `app-env.d.ts`

![image](https://github.com/marklawlor/nativewind/assets/62344860/acb4bc92-9767-4ae8-b77b-d841d1e6fb6f)

**Comment by mashwishi** [comment]
> @mashwishi if I put `/// <reference types="nativewind/types" />` in `App.tsx` works good 🤔
> 
> ![image](https://private-user-images.githubusercontent.com/85639396/269460260-303dc5ae-063b-4afe-a11c-b2cb72925c59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTg5NzEsIm5iZiI6MTcwMjcxODY3MSwicGF0aCI6Ii84NTYzOTM5Ni8yNjk0NjAyNjAtMzAzZGM1YWUtMDYzYi00YWZlLWExMWMtYjJjYjcyOTI1YzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZDJjMjE3YTFkN2NhNjc0NTliMTQzZjYyMGYwYjFiMTdmMmYxYWI4YmM0OGQ2NmE3MGQxMzQzNmNmYWQwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xjHolKkS8uMWFx_epzSUpUgwhrJ6nkL6I-H92M8tdBI)
> 
> Or: Move the `app.d.ts` into `src/` works good too. ![image](https://private-user-images.githubusercontent.com/85639396/269460660-91426d86-4633-4b4a-85e0-da5b4ffcdfad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTg5NzEsIm5iZiI6MTcwMjcxODY3MSwicGF0aCI6Ii84NTYzOTM5Ni8yNjk0NjA2NjAtOTE0MjZkODYtNDYzMy00YjRhLTg1ZTAtZGE1YjRmZmNkZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YjBmMDllMjY1OTk0YzIyNmY5NTJlYzE3YWQ3YzcyZThjMTQ0YzNjMGNjZjRmZjA0M2UxZWQzY2NkYjgyMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HwSopCPYpPi4fkg9wNpkMfV_htKZxvzxFV03wfMDX8w)
> 
> Result: ✅ ![image](https://private-user-images.githubusercontent.com/85639396/269460730-1fe5dbda-dcaf-44f4-9a74-02727042e932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTg5NzEsIm5iZiI6MTcwMjcxODY3MSwicGF0aCI6Ii84NTYzOTM5Ni8yNjk0NjA3MzAtMWZlNWRiZGEtZGNhZi00NGY0LTlhNzQtMDI3MjcwNDJlOTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYTgwNzI0YWEwMTkzNTRkMjVhZTU3NTNiODk2MmJlMDQ5Njg2NzljMTU1NzE3MzFjMjY0ZTc5NGUwYzcxMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SIeN1FSHi_HS2bx0-4Rbqn1blZmPSLHxLQgI0sArTIU)

this one works, i am not sure what is the cons but yeah..

**Comment by mashwishi** [comment]
This solved my issue, i already tried reopening it many times and the redline (error) doesn't come back anymore

![image](https://github.com/marklawlor/nativewind/assets/62344860/7b3101c2-fd30-44be-91b4-31b825c803c7)
