### ISSUE TITLE
Does Nativewind support custom syntax ?

### ISSUE THREAD

**Issue by chrisarts** [marklawlor/nativewind#563]
Hi @marklawlor Im finishing an alternative to NW (not the same Im using runtime and not babel) in this lib I created a custom TW syntax parser that support utility grouping also for modifiers, variants etc... (also comes with a rudimentary ts plugin to do autocompletion) and I want to know if NW can use such syntax if I isolate the parser to an independant npm package.

for ex:
```tsx
<View className={`
    flex-1
  md:border-1
  hover:(web:(bg-blue-600) ios:(bg-green-600) android:(bg-black))
  ios:(p-14 bg-rose-200 border-white border-2)
  android:(p-14 border-green-200 border-2 bg-gray-50)
`} />
```

produces: 
```ts
[ '.flex-1',
  '.md:border-1',
  '.web:hover:bg-blue-600',
  '.ios:hover:bg-green-600',
  '.android:hover:bg-black',
  '.ios:p-14',
  '.ios:bg-rose-200',
  '.ios:border-white',
  '.ios:border-2',
  '.android:p-14',
  '.android:border-green-200',
  '.android:border-2',
  '.android:bg-gray-50' ]
  ```

Thanks for come back to NW!

**Comment by marklawlor** [comment]
NativeWind uses the output of Tailwind CLI, so it only supports what Tailwind CLI offers.
