### ISSUE TITLE
babel config plugins key is missing

### ISSUE THREAD

**Issue by alex-izrailov** [marklawlor/nativewind#566]
**Describe the bug**

OS: Ubuntu 22.04
trying to run create-expo-app with nativewind for the web, the app crashes with the following error

Error: [BABEL] ./my-expo-app/node_modules/expo/AppEntry.js: .plugins is not a valid Plugin property

**To Reproduce**
1 create expo app
2 npm install nativewind @expo/webpack-config
3 npm install -D tailwindcss postcss autoprefixer postcss-loader
4 npx tailwindcss init -p -f
5 update tailwind.config.js file with content: ["App.{js,ts.jsx,tsx}", "./**/*.{js,ts.jsx,tsx}"]

**Expected behavior**
the app should open whitin the browser and display what ever the default app is

**Additional context**
tried it with both nativewind version 2 and current versions 4.0.0-alpha.{7,8}
tried it with both javascript and typescript
tried it with different expo templates

the expo app works perfectly fine without nativewind, but cant work with it

**Comment by scott-harrison** [comment]
Also getting this issue, I am not using expo, but same issue occurs

**Comment by theblondealex** [comment]
I have encountered the same issue on these versions, It works on v2 nativewind on old projects I have done but thought best to use latest versions and hitting this error when running expo go 

I have used nativewind lower versions before,

Ran expo setup, installed tailwind and setup that and babel config however met this error on npm start --clear

error: node_modules\expo\AppEntry.js: [BABEL]  .plugins is not a valid Plugin property

"nativewind": "^4.0.13",
"@babel/core": "^7.20.0",
"tailwindcss": "^3.3.5"

I have published a Repo to clone and test 

https://github.com/theblondealex/Plugins-issue.git

**Comment by marklawlor** [comment]
To clarify, v2 uses a plugin while v4 switched to a **preset**.

@gulisashvili "me too" comments do not provide me with any information to help you. I cannot tell if your issue is the same or different. You may get the same error but from a different cause. Please provide a reproduction if you would like assistance.

**Comment by dgrcode** [comment]
Hi I'm facing the same problem. I've created a repo that should reproduce the problem: https://github.com/dgrcode/nativewind-issue

I'll try to update to v4 and see if I get this working

**Comment by gulisashvili** [comment]
@marklawlor  i was able to resolve it by myself.

issue was that installation guides don't target v2 and it automatically installs v4 for which there is completely different configurations ...

**Comment by marklawlor** [comment]
https://github.com/marklawlor/nativewind/issues/600#issuecomment-1804741121

**Comment by iRoySwift** [comment]
https://www.nativewind.dev/getting-started/expo-router#6-typescript-optional

Add the Babel preset
