### ISSUE TITLE
Builds fail for Expo as well as React Native CLI with tailwind 3.3.3

### ISSUE THREAD

**Issue by iamjoshua** [marklawlor/nativewind#567]
**Describe the bug**
With a fresh install of Expo, installing nativewind throws an error as outlined [here](https://github.com/marklawlor/nativewind/issues/566).

With a fresh install of a non-Expo React Native app, it will throw the following [error](https://stackoverflow.com/questions/76688256/getting-error-use-processcss-thencb-to-work-with-async-plugins). 

**To Reproduce**
Follow the nativewind install docs as outlined.

**Additional context**
Downgrading tailwind version to 3.3.2 allows builds for React Native CLI to complete successfully but I haven't followed up with Expo.

**Comment by mryechkin** [comment]
Just trying out Nativewind for the first time, and immediately ran into this issue as well. Downgrading Tailwind to `3.3.2` solved it for me as well.

**Comment by marklawlor** [comment]
Documented in pinned issue. Resolved in upcoming v4
