### ISSUE TITLE
Retrieving spacing values

### ISSUE THREAD

**Issue by hoangvu12** [marklawlor/nativewind#569]
Is there anyway I can get spacing value at runtime? Something like:

```tsx
import { spacing } from 'nativewind'
import { Dimensions } from 'react-native';

const { width } = Dimensions.get('screen');

const ASPECT_RATIO = 9 / 16;
const PADDING = spacing(4) // 16

<View
  style={{
     height: (width - (PADDING * 2)) * ASPECT_RATIO}
  }}
>
</View>
```

**Comment by marklawlor** [comment]
No. But you should be using a combination of  React Natives `aspectRatio` and `padding` styles https://reactnative.dev/docs/layout-props#aspectratio

Then you can use the `aspect-` and `p-` classNames.

**Comment by hoangvu12** [comment]
> No. But you should be using a combination of  React Natives `aspectRatio` and `padding` styles https://reactnative.dev/docs/layout-props#aspectratio
> 
> Then you can use the `aspect-` and `p-` classNames.

Hey, I think you misunderstood what I meant. I'm using `react-native-youtube-iframe` and it is required to pass a `height` props. 

In other case where I have to create a 2 column grid. I can't use className props as I need to calculate the style myself.

```tsx
const WIDTH = Dimensions.get("screen").width;

const PADDING = spacing(2);
const SPACE_BETWEEN = spacing(4);

<View className="flex flex-row flex-wrap justify-between">
          {episodes.map((episode, index) => (
            <View
              style={{
                width: WIDTH / 2 - PADDING - SPACE_BETWEEN,
                marginBottom:
                  index < episodes.length - 2 ? SPACE_BETWEEN * 2 : 0,
              }}
              key={episode.id}
            >
              <EpisodeCard episode={episode} />
            </View>
          ))}
        </View>
```

**Comment by marklawlor** [comment]
Does `react-native-youtube-iframe` need a height? It looks like it will accept `aspectRatio` though the [`viewContainerStyle` 
 prop](https://github.com/LonelyCpp/react-native-youtube-iframe/blob/2fd9bc4b46a410679869eaee60dd1f7c90152c4d/src/YoutubeIframe.js#L262C36-L262C54) and width/height are only used for shortcuts for styles. You could also ignore the `viewContainerStyle` and just map to `webViewStyle`

I don't understand your second point about 2 column grids. You can use flexbox styles to create 2 column grid with margin and you can use aspectRatio to have a responsive height.

**Comment by hoangvu12** [comment]
> Does `react-native-youtube-iframe` need a height? It looks like it will accept `aspectRatio` though the [`viewContainerStyle` prop](https://github.com/LonelyCpp/react-native-youtube-iframe/blob/2fd9bc4b46a410679869eaee60dd1f7c90152c4d/src/YoutubeIframe.js#L262C36-L262C54) and width/height are only used for shortcuts for styles. You could also ignore the `viewContainerStyle` and just map to `webViewStyle`
> 
> I don't understand your second point about 2 column grids. You can use flexbox styles to create 2 column grid with margin and you can use aspectRatio to have a responsive height.

It does require a height as it mention in the docs here:

![image](https://github.com/marklawlor/nativewind/assets/68330291/d6e2f84e-a572-48ec-877c-c31923fcc5a2)
