### ISSUE TITLE
[4.0.0-alpha.12] examples/expo-router issues

### ISSUE THREAD

**Issue by tyrauber** [marklawlor/nativewind#572]
**Describe the bug**

On the main branch (4.0.0-alpha.12) expo-router example, there are currently 3 issues:

1) running the ios simulator in development raises:
```
TypeError: ws_1.WebSocketServer is not a constructor
    at tailwindCli (/node_modules/nativewind/dist/metro/tailwind-cli.js:27:21)
    at Object.getTransformOptions node_modules/nativewind/dist/metro/index.js:56:54)
```
Reloading resolves the issue.

2)  expo-router isn't finding the updates to the app directory. Renders the default "Welcome to Expo" screen.

3) build for web crashes:
```
node_modules/react-native-css-interop/dist/css-to-rn/index.js:28
    (0, lightningcss_1.transform)({
                                 ^
SyntaxError: Unexpected end of input
    at cssToReactNativeRuntime (node_modules/react-native-css-interop/dist/css-to-rn/index.js:28:34)
    at Socket.<anonymous> (node_modules/nativewind/dist/metro/tailwind-cli.js:44:84)
```

1 & 3 were introduced in previous releases.  2 was introduced in 10.

**To Reproduce**

1. clone github.com/marklawlor/nativewind
2. install the dependencies
3. run start -c in examples/expo-router

**Comment by tyrauber** [comment]
@marklawlor, Nice work!  

4.0.0-alpha.14 addresses all these issues.  Issue 2 is resolved with npm, yarn and pnpm could use some monorepo configuration and testing.

A new issue has popped up for expo web though

- Web bundling hangs and the page fails to resolve:

`npx expo start --web`

> Web Bundling complete 8799ms
> Web ./index.js ░░░░░░░░░░░░░░░░  0.0% (0/1)"transform" style array value is deprecated. Use space-separated string functions, e.g., "scaleX(2) rotateX(15deg)".

Also, a couple minor modifications are needed to the documentation:

-  In a monorepo, you must pass projectRoot to withNativeWind ([like the example](https://github.com/marklawlor/nativewind/blob/main/examples/expo-router/metro.config.js#L21-L25)):
```
module.exports = withNativeWind(config, {
  // 3. Set `input` to your CSS file with the Tailwind at-rules
  input: "global.css",
  projectRoot,
});
```
-  You must import the plugin default on tailwind.config.js (like the [example](https://github.com/marklawlor/nativewind/blob/main/examples/expo-router/tailwind.config.js#L1-L9)):

```
module.exports = {
  content: ["src/app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset").default],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

It's been fun watching this evolve. Excited for a 4.0.0 release.

**Comment by marklawlor** [comment]
Should be fixed in `alpha.15`

**Comment by tyrauber** [comment]
Awesome! Thanks @marklawlor.

Corrections to my previous comment. With 4.0.0-alpha.16, calling default is not needed and will fail. The instructions and [examples](https://github.com/marklawlor/nativewind/blob/main/examples/expo-router/tailwind.config.js#L1-L9) are correct. The example has been updated to follow the documentation.

Web and mobile rendering styles in 4.0.0-alpha.16! 🎉
