### ISSUE TITLE
[4.0.0-alpha.12] Tailwind cli can not handle large CSS / 8192 bytes limit

### ISSUE THREAD

**Issue by daannet** [marklawlor/nativewind#574]
**Describe the bug**
The tailwind-cli stdout data listener only listens to the [first output](https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/src/metro/tailwind-cli.ts#L62) When you have a larger CSS the following parts are ignored because it is already processing it via lightningcss, that fails because of "Invalid token in pseudo element: WhiteSpace("  ")"

**To Reproduce**
- Make sure the tailwind output is more than 8192 bytes
- Start bundler
- Node fails because of broken css data passed to lightningcss.

**Expected behavior**
The data listener for the Tailwind cli should handle larger css files too.

**Comment by marklawlor** [comment]
Where does the limitation of 8192 bytes come from, is this windows specific issue? I'm testing on linux/macosx on Node 16/18 and I'm receiving a single chunk >100k bytes

**Comment by marklawlor** [comment]
Fixed in `alpha.15`
