### ISSUE TITLE
Output `global.css.native.css` is cut `Error: Unexpected end of input at global.css.native.css:618:2`

### ISSUE THREAD

**Issue by surgeharb** [marklawlor/nativewind#575]
Hi I would like to appreciate the effort and the quality of work that you are putting here for open-source! I would like to contribute if there are areas where I can add value, I went through the code for the past week to check how it works. Amazing work 🙌 

**Describe the bug**
Version `alpha.15` works when there are few components, but when adding more and more different classes to the codebase, `global.css.native.css` will be generated with max around ~500-600 lines, the rest is abnormally cut (screenshot below).
I debugged using `bunx tailwindcss --input global.css > ./test.css` as described in the docs and it outputs correctly ~1200 lines.

NOTE: with every run it seems cutting at a different point, so I am trying to check https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/src/metro/tailwind-cli.ts#L65 in case I can find anything.

**To Reproduce**
Steps to reproduce the behavior (MacBook Pro M1 Pro, MacOS Sonoma 14.0):
1. Add a lot of components with classes and tailwind variables in order to make the CSS bundle take more than 700 lines. I forked the repo and created an example code: [commit](https://github.com/marklawlor/nativewind/compare/main...surgeharb:nativewind:main)
2. Run the project `expo start`.
3. Launch any native emulator to trigger talwindcss build.
4. Check last line `./node_modules/.cache/nativewind/global.css.native.css`
5. Also we will have this error crashing the server: `Error: Unexpected end of input at global.css.native.css:618:2`

**Expected behavior**
Having full CSS compilation in  `global.css.native.css` and `global.css.web.css`

**Screenshots**
My: `global.css.native.css`

<img width="801" alt="Screenshot 2023-10-09 at 10 59 05" src="https://github.com/marklawlor/nativewind/assets/22060043/64f40000-b3a8-4adc-ab87-38164c638b04">

My `global.css.web.css`:

<img width="754" alt="Screenshot 2023-10-09 at 11 00 25" src="https://github.com/marklawlor/nativewind/assets/22060043/21a59b8b-d94a-4087-a23f-4f776a5093f1">

**Comment by surgeharb** [comment]
Can be tested in this repo: https://github.com/surgeharb/nativewind, I added many components in my single [commit](https://github.com/marklawlor/nativewind/compare/main...surgeharb:nativewind:main) to showcase the error.

This represents a multi-screen big repository using nativewinf and classNames.
`Error: Unexpected end of input at global.css.native.css:684:7`

Broken output css:

<img width="526" alt="Screenshot 2023-10-09 at 11 18 44" src="https://github.com/marklawlor/nativewind/assets/22060043/a85e7579-84cf-4037-bc95-7e2c059b886e">

**Comment by tyrauber** [comment]
@surgeharb, this is resolved in 4.0.0-alpha.16.
