### ISSUE TITLE
[v4] Appearance is broken and theme cannot be switched on the fly

### ISSUE THREAD

**Issue by thespacemanatee** [marklawlor/nativewind#581]
**Describe the bug**

**To Reproduce**

[Repro](https://github.com/thespacemanatee/nativewind-expo-appearance-repro)

**Expected behavior**

Using the shortcut `Cmd+Shift+A` changes the system theme of the iOS simulator, but the app only responds to it once, and never again until restarted. Logging `useColorScheme` reveals that the value does not change.

**Screenshots**

This is me spamming `Cmd+Shift+A`, you can see the blurry effect of that. The app stays in one theme, and going to the home screen, it is clear that the shortcut is working.

https://github.com/marklawlor/nativewind/assets/6837599/d0d76a77-d0c7-442a-87b0-b2d6f17b57b5

**Additional context**

The only thing I did in the repro was install `nativewind@alpha` after running `npx create-expo-app@latest --template tabs@49`

**Comment by marklawlor** [comment]
Your reproduction does not look complete. Your add NativeWind to your project and then never use it?

**Comment by thespacemanatee** [comment]
> Your reproduction does not look complete. You add NativeWind to your project and then never use it?

It doesn't matter if it's used right? Appearance immediately stops working after setting it up. It should not break react native StyleSheet. Look at the video, it works the first time I change the theme. It should work all the time.

**Comment by marklawlor** [comment]
I'm having trouble reproducing this issue, so I'm to need some more depth troubleshooting from the community

- Can you confirm that it only occurs when you add nativewind to the project?
- Is it isolated to iOS?
- Does it only occur if you use nativewind with Expo (e.g can you replicate with vanilla RN?)
- Are you using Expo Go or a custom build?

**Comment by thespacemanatee** [comment]
> I'm having trouble reproducing this issue, so I'm to need some in-depth troubleshooting from the community
> 
> - Can you confirm that it only occurs when you add nativewind to the project?
> - Is it isolated to iOS?
> - Does it only occur if you use nativewind with Expo (e.g can you replicate with vanilla RN?)
> - Are you using Expo Go or a custom build?
> 
> For extra context, NativeWind doesn't touch any React Native internals. You can see the implementation of dark mode [here](https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/runtime/native/color-scheme.ts), in which we use normal public facing APIs.
> 

Have you tried running my reproduction and changing the system theme using the shortcut? Without setting ColorScheme imperatively.

If you look into the repro you'll be able to see that it's running in Expo Go, however this happens on custom build as well. It occurs immediately after adding nativewind to the project and happens on both Android and iOS.

**Comment by marklawlor** [comment]
@thespacemanatee Yes. I cannot reproduce with your repo - hence I'm asking for more information.

**Comment by marklawlor** [comment]
A troubleshooting step I forgot to ask - installing NativeWind is a multiple step process, Babel config, Metro Config, adding the CSS import. After which step does the project fail?

**Comment by marklawlor** [comment]
@thespacemanatee Can you please test using a development build of your app.

After updating my Expo Go, I experienced the same issue. From my testing this seems to be an issue with Expo Go and is not caused by NativeWind (it occurs in new projects). Switching to a development build seems like the best workaround for now.

**Comment by thespacemanatee** [comment]
> @thespacemanatee Can you please test using a development build of your app.
> 
> After updating my Expo Go, I experienced the same issue. From my testing this seems to be an issue with Expo Go and is not caused by NativeWind (it occurs in new projects). Switching to a development build seems like the best workaround for now.

When I create a new project from scratch with `npx create-expo-app@latest --template tabs@49`, the Appearance works fine in the latest Expo Go. It only stops working after I set up NativeWind.

It continues to not work even after I run `expo prebuild` and convert the project to use the development client. I don't think I'm doing anything wrong and I have a team of engineers that have also validated my findings. Hope this helps.

> A troubleshooting step I forgot to ask - installing NativeWind is a multiple step process, Babel config, Metro Config, adding the CSS import. After which step does the project fail?

The bug occurs right after I set up the Babel config.

**Comment by marklawlor** [comment]
I don't believe you've anything wrong. Often issues like this occur because of some obscure detail.

The babel preset is interesting, as it only enables two plugins - one of which I assumed maybe the culprit. Can you please comment out this line in your `node_modules/react-native-css-interop/babel.js` file https://github.com/marklawlor/nativewind/blob/864251b84fc780e676e18894e07329ae173e1700/packages/react-native-css-interop/babel.js#L4

**Comment by thespacemanatee** [comment]
@marklawlor I tried that and the bug still occurs.

One more interesting piece of information I have is that the changes to both `babel.config.js` and `metro.config.js` have to be reverted before the bug goes away. If either one of them is edited according the the docs, it will trigger this bug, so it could be an issue in `metro.config.js` as well, or both of them. Tough to debug this one 😞

**Comment by marklawlor** [comment]
What if you keep the metro & babel config unchanged and simple add `import "react-native-css-interop" to your app? If it occurs, you can go though the `node_modules/react-native-css-interop/dist/index.native.js` file and simply comment out lines. Following this process you can isolate the trouble file

**Comment by thespacemanatee** [comment]
@marklawlor Yes I can reproduce with the steps you described without even having to restart the metro server! Will look for the erroneous lines.

**Comment by thespacemanatee** [comment]
@marklawlor I've managed to trace the bug somewhere down to `node_modules/react-native-css-interop/dist/runtime/native/color-scheme.js`. Changing Appearance using the keyboard shortcut doesn't trigger the event in

```ts
appearanceListener = appearance.addChangeListener(({ colorScheme }) => {
    console.log(colorScheme) // <-- nothing happens
    if (isSystem) {
        signal.set(colorScheme ?? "light");
    }
});
```

If I comment out the entire file and restart the app, Appearance works as per normal again.

**Comment by thespacemanatee** [comment]
@marklawlor I propose the following fix but feel free to let me know if it can be improved:

```patch
diff --git a/node_modules/react-native-css-interop/dist/runtime/native/color-scheme.js b/node_modules/react-native-css-interop/dist/runtime/native/color-scheme.js
index 345003d..084eca5 100644
--- a/node_modules/react-native-css-interop/dist/runtime/native/color-scheme.js
+++ b/node_modules/react-native-css-interop/dist/runtime/native/color-scheme.js
@@ -16,7 +16,7 @@ exports.useColorScheme = useColorScheme;
 function createColorScheme(appearance) {
     let isSystem = true;
     const signal = (0, signals_1.createSignal)(appearance.getColorScheme() ?? "light");
-    const set = (colorScheme) => {
+    const set = (colorScheme, fromSystem) => {
         let newColorScheme;
         if (colorScheme === "system") {
             newColorScheme = appearance.getColorScheme() ?? "light";
@@ -25,7 +25,9 @@ function createColorScheme(appearance) {
             newColorScheme = colorScheme;
         }
         signal.set(newColorScheme);
-        appearance.setColorScheme(newColorScheme);
+        if (!fromSystem) {
+            appearance.setColorScheme(newColorScheme);
+        }
     };
     const toggle = () => {
         if (signal.get() === "light") {
@@ -37,25 +39,25 @@ function createColorScheme(appearance) {
     };
     let appStateListener = react_native_1.AppState.addEventListener("change", (state) => {
         if (state === "active" && isSystem) {
-            set(appearance.getColorScheme() ?? "light");
+            set(appearance.getColorScheme() ?? "light", true);
         }
     });
     let appearanceListener = appearance.addChangeListener(({ colorScheme }) => {
         if (isSystem) {
-            set(colorScheme ?? "light");
+            set(colorScheme ?? "light", true);
         }
     });
     const reset = (appearance) => {
         appStateListener.remove();
         appStateListener = react_native_1.AppState.addEventListener("change", (state) => {
             if (state === "active" && isSystem) {
-                set(appearance.getColorScheme() ?? "light");
+                set(appearance.getColorScheme() ?? "light", true);
             }
         });
         appearanceListener.remove();
         appearanceListener = appearance.addChangeListener(({ colorScheme }) => {
             if (isSystem) {
-                signal.set(colorScheme ?? "light");
+                signal.set(colorScheme ?? "light", true);
             }
         });
         isSystem = true;

```

**Comment by marklawlor** [comment]
@thespacemanatee Can you try `4.0.0-alpha.27` it uses a reworked version of the color scheme logic.

**Comment by thespacemanatee** [comment]
@marklawlor works great now, thank you!
