### ISSUE TITLE
Dynamic parameters (param) `w-[${param}]`

### ISSUE THREAD

**Issue by ValyaBabenkov** [marklawlor/nativewind#585]
Good afternoon.
I am trying to add a calculated parameter, but nativewind (^2.0.11) does not apply it.
My code
```
const width = 100
<View className={`w-[${width}]`}/>
или 
<View className={`w-[${String(width)}]`}/>
```

**Comment by marklawlor** [comment]
This is not allowed by Tailwind CSS https://tailwindcss.com/docs/content-configuration#dynamic-class-names
