### ISSUE TITLE
v4: remapProps not working

### ISSUE THREAD

**Issue by johnf** [marklawlor/nativewind#586]
**Describe the bug**
For components like `ImageBackground` prop remapping isn't being applied

**To Reproduce**
Add the following to an app

```jsx
<ImageBackground className="flex-1" />
```

Inspect the element in the React Native inspector and the styles are missing.

**Expected behavior**
The flex styles should be applied.

**Expo Snack**
TBA

**Additional context**

I'm pretty confident that the problem lies at https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/runtime/css-interop.native.ts#L104-L108

```js
// Changing 
rawStyles.push(opaqueStyle);
// to
rawStyles.push(style);
```

fixes the problem.

I was going to do a PR but I'm not sure what this code is actually trying to do

**Comment by marklawlor** [comment]
Fixed in latest alpha
