### ISSUE TITLE
v4: Unable to manually set color scheme without using darkMode: class

### ISSUE THREAD

**Issue by guess** [marklawlor/nativewind#587]
**Describe the bug**
I am using v4 (4.0.0-alpha.24) and I am getting this error when trying to set the color scheme.

```
 ERROR  Error: Unable to manually set color scheme without using darkMode: class. See: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

This error is located at:
    in SessionProvider (created by Application)
    in Application
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in Citizen(RootComponent), js engine: hermes
```

**To Reproduce**
1. My `tailwind.config.js` is has `darkMode` set:
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        neutral: {
          950: 'rgb(var(--color-neutral-950) / <alpha-value>)',
          ...
        },
      },
    },
  },
};
```
2. I am calling it like so:
```tsx
import { useColorScheme } from 'nativewind';

export const SessionProvider = (props: any) => {
  const { setColorScheme } = useColorScheme();
  setColorScheme('dark');

  return (
    <SessionContext.Provider value={session}>
      {props.children}
    </SessionContext.Provider>
  );
};
```

**Additional context**
I have just upgraded to v4 to try it for the dynamic themes, so in case my setup/upgrade is incorrect here are other files changed for the upgrade:

Here is `babel.config.js`:
```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset', 'nativewind/babel'],
  plugins: [
    'babel-plugin-transform-typescript-metadata',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    'react-native-reanimated/plugin',
  ],
};

```

Here is `metro.config.js`:
```js
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const { withNativeWind } = require('nativewind/metro');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter(ext => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg'],
  },
};

module.exports = withNativeWind(mergeConfig(defaultConfig, config), {
  input: './src/assets/css/global.css',
});
```

Here is `global.css`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --color-neutral-950: #101010;
}

@media (prefers-color-scheme: dark) {
  :root {
    --color-neutral-950: #FFFFFF;
  }
}
```
and it is included in `index.js`.

**Comment by guess** [comment]
Just tried the latest `4.0.0-alpha.25` and still having the same problem

**Comment by guess** [comment]
Ok so I actually just got it to work by doing the following:
1. Removed `darkMode: 'class'` from `tailwind.config.js`
2. Do not call `setColorScheme` from `nativewind` and instead just use `Appearance`:
```ts
import { Appearance, useColorScheme } from 'react-native';

export const SessionProvider = (props: any) => {
  console.log(useColorScheme());
  Appearance.setColorScheme('dark');
  console.log(useColorScheme());
  ...
}
```
3. Now the color changes based on color scheme:
```tsx
<Text className="text-neutral-950">Home</Text>
```

It still feels like this is a bug so I'm going to leave the issue open.

**Comment by marklawlor** [comment]
There's a couple of issues here.

1. There is a bug I'll fix
2. Your CSS variables are invalid. `rgb(var(--color-neutral-950) / <alpha-value>)` is going to evaluate to `rgb(#101010 / 1)` which is invalid both in NativeWind and CSS in general.
3. You most likely don't want to use media query combined with `darkMode: 'class'`. Dark mode class is saying "I want to control the color scheme" while media queries state "I want the device to control the color scheme". So the two are going to be out of sync. On native, NativeWind doesn't distinguish between the two, which I consider a bug, and will fix soon

**Comment by marklawlor** [comment]
Fixed in `4.0.1`. I decided against point 3, so native doesn't distinguish between the two systems - but web still will.

**Comment by ammarfaris** [comment]
> Ok so I actually just got it to work by doing the following:
> 
> 1. Removed `darkMode: 'class'` from `tailwind.config.js`
> 2. Do not call `setColorScheme` from `nativewind` and instead just use `Appearance`:
> 
> ```ts
> import { Appearance, useColorScheme } from 'react-native';
> 
> export const SessionProvider = (props: any) => {
>   console.log(useColorScheme());
>   Appearance.setColorScheme('dark');
>   console.log(useColorScheme());
>   ...
> }
> ```
> 
> 3. Now the color changes based on color scheme:
> 
> ```tsx
> <Text className="text-neutral-950">Home</Text>
> ```
> 
> It still feels like this is a bug so I'm going to leave the issue open.

I am encountering the same issue now with 4.0.22, via solito 4.2.0 and expo ^49.0.21

**Comment by ammarfaris** [comment]
> > Ok so I actually just got it to work by doing the following:
> > 
> > 1. Removed `darkMode: 'class'` from `tailwind.config.js`
> > 2. Do not call `setColorScheme` from `nativewind` and instead just use `Appearance`:
> > 
> > ```ts
> > import { Appearance, useColorScheme } from 'react-native';
> > 
> > export const SessionProvider = (props: any) => {
> >   console.log(useColorScheme());
> >   Appearance.setColorScheme('dark');
> >   console.log(useColorScheme());
> >   ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Now the color changes based on color scheme:
> > 
> > ```tsx
> > <Text className="text-neutral-950">Home</Text>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It still feels like this is a bug so I'm going to leave the issue open.
> 
> I am encountering the same issue now with `nativewind 4.0.22`, with `solito 4.2.0` and `expo 49.0.21` ; this suggested method seems to work - but for manual triggers only, for trigger on every change in useColorScheme(), cannot find a way to auto-triggering it =>
> 
> This does not seem to work:
> 
> ```js
> 	const colorScheme = useColorScheme()
> 
> 	useEffect(() => {
> 		console.log('Current colorScheme:', colorScheme)
> 		Appearance.setColorScheme(colorScheme)
> 	}, [colorScheme])
> ```
> 
> only this work:
> 
> ```js
> 	useEffect(() => {
> 		console.log('Current colorScheme:', colorScheme)
> 		Appearance.setColorScheme('light') // 'dark' , this is manual or via button
> 	}, [colorScheme])
> ```

[UPDATE] 
apparently there is a difference between having 


and it seems that the auto-trigger via system dark-light toggle

**Comment by luihugo** [comment]
> Ok so I actually just got it to work by doing the following:
> 
> 1. Removed `darkMode: 'class'` from `tailwind.config.js`
> 2. Do not call `setColorScheme` from `nativewind` and instead just use `Appearance`:
> 
> ```ts
> import { Appearance, useColorScheme } from 'react-native';
> 
> export const SessionProvider = (props: any) => {
>   console.log(useColorScheme());
>   Appearance.setColorScheme('dark');
>   console.log(useColorScheme());
>   ...
> }
> ```
> 
> 3. Now the color changes based on color scheme:
> 
> ```tsx
> <Text className="text-neutral-950">Home</Text>
> ```
> 
> It still feels like this is a bug so I'm going to leave the issue open.

This work around worked for me using native "4.0.1", expo 50.0.7 and "tailwindcss": "^3.4.1"

**Comment by trevorpfiz** [comment]
I am running into this error in this project https://github.com/trevorpfiz/create-t3-turbo-supabase/tree/05-15-nativewind_hairlinewidth_bug_and_darkmode_bug

I updated https://github.com/mrzachnugent/react-native-reusables/tree/main/apps/starter-base to the latest dependencies and it seemed to be working, so not sure what is wrong...

**Comment by KMJ-007** [comment]
any update on this?

still facing the same issue in v4

**Comment by hydra1983** [comment]
@KMJ-007 see [NativeWind + React Navigationでダークモード絡みのエラーが発生したときの解決策](https://www.exceedsystem.net/2024/11/04/how-to-fix-cannot-manually-set-color-scheme-error-in-nativewind-and-react-navigation/)

**Comment by saspal02** [comment]
I'm also getting the same issue.

**Comment by rogerkerse** [comment]
I have same issue, even if I switch to darkMode: 'class' or 'media', no matter, still crashing. no meaningful logs

**Comment by huix9527** [comment]
> [@KMJ-007](https://github.com/KMJ-007) see [NativeWind + React Navigationでダークモード絡みのエラーが発生したときの解決策](https://www.exceedsystem.net/2024/11/04/how-to-fix-cannot-manually-set-color-scheme-error-in-nativewind-and-react-navigation/). Hope this can help

Not working

**Comment by alyiev** [comment]
Why is it closed if the problem still exist?

**Comment by Gerald-ux-ux** [comment]
> Why is it closed if the problem still exist?

Yes @alyiev i'm still experiencing the same issue and its been more than 3 days now and there's no fix

**Comment by cwooldridge1** [comment]
Still not working

**Comment by Gerald-ux-ux** [comment]
I think i found a fix. Try this 
`import React from 'react'
import { config } from './config'
import { ColorSchemeName, useColorScheme, View, ViewProps } from 'react-native'
import { OverlayProvider } from '@gluestack-ui/overlay'
import { ToastProvider } from '@gluestack-ui/toast'
import { colorScheme as colorSchemeNW } from 'nativewind'

type ModeType = 'light' | 'dark' | 'system'

const getColorSchemeName = (
  colorScheme: ColorSchemeName,
  mode: ModeType,
): 'light' | 'dark' => {
  if (mode === 'system') {
    return colorScheme ?? 'light'
  }
  return mode
}

export function GluestackUIProvider({
  mode = 'light',
  ...props
}: {
  mode?: 'light' | 'dark' | 'system'
  children?: React.ReactNode
  style?: ViewProps['style']
}) {
  const colorScheme = useColorScheme()

  const colorSchemeName = getColorSchemeName(colorScheme, mode)

  colorSchemeNW.set(mode)

  return (
    <View
      style={[
        config[colorSchemeName],
        { flex: 1, height: '100%', width: '100%' },
        props.style,
      ]}
    >
      <OverlayProvider>
        <ToastProvider>{props.children}</ToastProvider>
      </OverlayProvider>
    </View>
  )
}`

**Comment by Gerald-ux-ux** [comment]
Try this, it worked for me 

`import React from 'react'
import { config } from './config'
import { ColorSchemeName, useColorScheme, View, ViewProps } from 'react-native'
import { OverlayProvider } from '@gluestack-ui/overlay'
import { ToastProvider } from '@gluestack-ui/toast'
import { colorScheme as colorSchemeNW } from 'nativewind'

type ModeType = 'light' | 'dark' | 'system'

const getColorSchemeName = (
  colorScheme: ColorSchemeName,
  mode: ModeType,
): 'light' | 'dark' => {
  if (mode === 'system') {
    return colorScheme ?? 'light'
  }
  return mode
}

export function GluestackUIProvider({
  mode = 'light',
  ...props
}: {
  mode?: 'light' | 'dark' | 'system'
  children?: React.ReactNode
  style?: ViewProps['style']
}) {
  const colorScheme = useColorScheme()

  const colorSchemeName = getColorSchemeName(colorScheme, mode)

  colorSchemeNW.set(mode)

  return (
    <View
      style={[
        config[colorSchemeName],
        { flex: 1, height: '100%', width: '100%' },
        props.style,
      ]}
    >
      <OverlayProvider>
        <ToastProvider>{props.children}</ToastProvider>
      </OverlayProvider>
    </View>
  )
}`

**Comment by regrunge** [comment]
Check your `metro.config.js`, it might have been altered. You will need both the import...
`const { withNativeWind } = require('nativewind/metro');` and the wrapper around the export
`module.exports = withNativeWind(config, { input: './global.css' });`

**Comment by devaku** [comment]
@regrunge 

This is my current `metro.config.js` and it still gives the error.

`
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './assets/css/global.css' });
`

**Comment by devaku** [comment]
Alright! That fixed it. Having these in my `tailwind.config.css` removed the error.

`
/** @type {import('tailwindcss').Config} */
module.exports = {
	// NOTE: Update this to include the paths to all of your component files.
	content: ['./app/**/*', './components/**/*.{js,jsx,ts,tsx}'],
	presets: [require('nativewind/preset')],
	theme: {
		extend: {},
	},
	plugins: [],
	darkMode: 'class', // Specifically this line
};

`

**Comment by syafiqmuda** [comment]
I see there is too many solution, Which is working?

**Comment by TiagoAndreAlmeida** [comment]
Still facing this problem, my `tailwind.config.css ` have `darkMode: "media"`

**Comment by DudeFactory** [comment]
Why closed, same error: "nativewind": "^4.1.23",

**Comment by Sascha195** [comment]
This is still an issue in "nativewind": "4.1.23" and setting darkMode: 'class' does not work.

**Comment by huix9527** [comment]
> I see there is too many solution, Which is working?

update metro.config.js works for me:
withNativeWind(config, {input: './global.css'})

**Comment by TerryMinn** [comment]
solve?

**Comment by tanjunior** [comment]
"nativewind": "^4.1.23"
"tailwindcss": "^3.4.17"

Not working at all. I think there is issue with the setState

```ts
  const { colorScheme, setColorScheme } = useColorScheme();

  useEffect(() => {
    console.log("colorScheme useeffect", colorScheme);
  }, [colorScheme]);

  const toggleColorScheme = () => {
    setColorScheme(colorScheme === "dark" ? "light" : "dark");
  };
```

the useEffect is not getting triggered at all.

**Comment by raphox** [comment]
```javascript
// tailwind.config.js

module.exports = {
  darkMode: process.env.DARK_MODE ? process.env.DARK_MODE : 'media',
  // rest of the config
}
```

After this, we need to update our scripts in the package.json file as shown below:

```javascript
{
  "scripts": {
    "android": "DARK_MODE=media expo start --android",
    "ios": "DARK_MODE=media expo start --ios",
    "web": "DARK_MODE=class expo start --web"
  }
}
```

Reference: https://gluestack.io/ui/docs/home/theme-configuration/dark-mode

**Comment by PaulKroner** [comment]
All the solutions did not work for me.
What I did:

- npx create-expo-app@latest
- npx gluestack-ui init

So I did not edit any other files than the tailwind.config.js or anny of the apps folder files. Does anyone has the same problem?
On YouTube they just started the same process and it worked.

I am using Expo Go on my Android phone. Somehow the app works in the browser just fine.

Edit: even on android simulator I get this error:

```
Warning: Error: Unable to manually set color scheme without using darkMode: class. 
See: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

This error is located at:

Call Stack
  RootLayoutNav (<anonymous>)
  ErrorBoundary(./_layout.tsx) (<anonymous>)
  RNCSafeAreaProvider (<anonymous>)
  App (<anonymous>)
  ErrorOverlay (<anonymous>)
```

**Comment by ardecht** [comment]
Add import
`
import "@/global.css";
`

**Comment by PaulKroner** [comment]
@ardecht that fixed it

**Comment by Layhout** [comment]
> Add import `import "@/global.css";`

inside `app/_layout.tsx`. the RootLayout.
