### ISSUE TITLE
v4: inlineRem not working

### ISSUE THREAD

**Issue by solaldunckel** [marklawlor/nativewind#592]
**Describe the bug**
Setting `inlineRem` in `withNativeWind` has no effect

```ts
module.exports = withNativeWind(config, {
  projectRoot,
  input: "./global.css",
  inlineRem: 16,
});
```

**Additional context**
The options doesn't seems to be propagated from the metro config up to `react-native-css-interop` since the `parseLength` function works correctly.

Applying this temporary fix works for changing the `inlineRem`.

```diff
 function parseLength(length, options) {
-    const { inlineRem = 14 } = options;
+    const { inlineRem = 16 } = options;
```

**Comment by marklawlor** [comment]
Fix the latest alpha
