### ISSUE TITLE
v4: Build issues in CI

### ISSUE THREAD

**Issue by johnf** [marklawlor/nativewind#593]
**Describe the bug**
I was experiencing the following error when building in CI

```
error Unable to resolve module [SNIP]/node_modules/.cache/nativewind/global.css.native.css from [SNIP]/src/global.css: 

None of these files exist:
  * node_modules/.cache/nativewind/global.css.native.css(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.css|.native.css|.css)
  * node_modules/.cache/nativewind/global.css.native.css/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.css|.native.css|.css)
> 1 | @tailwind base;
  2 | @tailwind components;
  3 | @tailwind utilities;
  4 |.
```

**To Reproduce**
```bash
rm -rf node_modules/.cache/nativewind
node node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --minify false --bundle-output /tmp/main.jsbundle --assets-dest /tmp/dev.app --sourcemap-output main.jsbundle.map
```

**Expected behavior**
The app builds without any issues

**Expo Snack**
N/A

**Screenshots**
N/A
**Additional context**
This was a marathon debugging session, as I could only replicate it in CI.

This is what happens during the bundling process
* node_modules/.cache/nativewind/global.css.native.css doesn't exist
* Metro builds a cache of the file tree https://github.com/facebook/metro/blob/main/packages/metro-file-map/src/index.js#L336-L406
* tailwind-cli runs and creates global.css.native.css
* metro tries to use the file. The file map doesn't have it cached even though it exists on disk so it fails to find it

I think the difference to ```react-native start``` is that the same thing happens but `watchman` is run by the file-map and picks up the new file.

A workaround in CI is to do the following
```sh
mkdir -p node_modules/.cache/nativewind 
touch node_modules/.cache/nativewind/global.css.native.css
```

In terms of a proper fix, perhaps touch the file at https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/src/metro/index.ts#L52

**Comment by marklawlor** [comment]
Which version are you using? 

Be aware that carat `^` versioning does not work for pre-releases. If you are using a carat in your `package.json`, please remove it and specify the latest version.

**Comment by johnf** [comment]
> Which version are you using?

```json
"nativewind": "4.0.0-alpha.25"
```

**Comment by johnf** [comment]
I just tested with `.26` same issue

**Comment by surgeharb** [comment]
With Expo we do the follwing, maybe a similar hook to be used with bare RN project (to generate CSS file after installing dependencies)

https://github.com/marklawlor/nativewind/issues/591#issuecomment-1777414561

**Comment by marklawlor** [comment]
Should be fixed in the latest alpha. If your still having issues can you please follow this comment https://github.com/marklawlor/nativewind/issues/591#issuecomment-1783662675

Closing in favour of #591

**Comment by johnf** [comment]
the options.hot fix from a few days ago fixed this for me

**Comment by jongbelegen** [comment]
This issue persists for me when running `expo export -p web` with `"nativewind": "^4.0.22"` when i haven't build the project before (like in CI).

Running `tailwindcss -i ./assets/main.css -o ./node_modules/.cache/nativewind/global.css.native.css` before building works though.

my metro config looks like this:

```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require("nativewind/metro");

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, {
  isCSSEnabled: true,
});

config.resolver.assetExts.push(
  "woff",
  "woff2",
);

module.exports = withNativeWind(config, {
  input: "./assets/main.css"
});
```

**Comment by PedroAugustoRamalhoDuarte** [comment]
@jongbelegen thanks for the solution!! With the default metro.config.js from 4.0.1 nativewind, this work for me when I am exporting my app

`yarn tailwindcss -i ./src/global.css -o ./node_modules/.cache/nativewind/global.css.web.css && npx expo export -p web`
