### ISSUE TITLE
Unable to resolve "./styles.css" from "App.tsx"

### ISSUE THREAD

**Issue by jdmoliner** [marklawlor/nativewind#598]
Hello,

I have followed the guide (https://www.nativewind.dev/quick-starts/expo) to get Tailwind working with Expo but I always get this error:

```
Android Bundling failed 28ms
Unable to resolve "./styles.css" from "App.tsx"
```
Also cloned this official example (and after update several packages) I get same error: https://github.com/marklawlor/nativewind/tree/next/examples/expo

I have used tailwind version 3.3.2 as suggested in this thread: https://github.com/marklawlor/nativewind/issues/501

package.json:
```
{
  "name": "expo-example",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "^49.0.16",
    "expo-status-bar": "^1.7.1",
    "nativewind": "^2.0.11",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "^0.72.6",
    "react-native-web": "^0.19.9"
  },
  "devDependencies": {
    "@babel/core": "7.12.9",
    "@expo/webpack-config": "0.17.2",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "autoprefixer": "^10.4.8",
    "babel-preset-expo": "^9.2.0",
    "postcss": "^8.4.16",
    "postcss-loader": "^4.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "^4.6.3"
  },
  "private": true
}
```

the rest of the code is the same as: https://github.com/marklawlor/nativewind/tree/next/examples/expo

My node version: v18.18.2
In a Macbook air M2 with Ventura 13.4

**Comment by marklawlor** [comment]
Hi that example is for the upcoming v4, so it won't work with your current `package.json`. I'd suggest either updating to v4 (you will will to update your `package.json`, `babel.config.js`, `metro.config.js`), or updating this issue with a reproducible demo of you using v2.

**Comment by marklawlor** [comment]
Pinned comment has link to v4 documentation. If you are just starting a new project, I would recommend starting there.
