### ISSUE TITLE
v4: Fast refresh not working and Pressable styles not applied

### ISSUE THREAD

**Issue by robcaldecott** [marklawlor/nativewind#604]
Using v4.0.5, Tailwind 3.3.5 with Expo 49.

- Refresh not working when any of the source files change n iOS or Android simulators. It sometimes struggles to connect at all and  often requires Expo Go in each simulator to be killed off for even a full refresh to work.
- `Pressable` styles are not applied.
- Adding `active:` styles to a `View` breaks the styling as I think internally it upgrades the `View` to a `Pressable`?

Sample repo:  https://github.com/robcaldecott/nativewind-4-issues

It's an Expo app and works with Expo Go. Clone the app, run `npm start` and load it up in a simulator. Make some changes to `App.js` and note that changes are not reflected. The app contains some `Pressable` examples that are missing styling.

I have kept the repo with the minimum of dependencies but have included SVG support. It's applying Tailwind styles to `View` so I think it's close.

Note that I needed to add `plugins: ["react-native-reanimated/plugin"]` else the iOS sim would crash with a C++ runtime error.

**Comment by marklawlor** [comment]
Fixed in `4.0.6`

**Comment by marklawlor** [comment]
Styling is fixed, but fast-refresh isn't working correctly.

**Comment by robcaldecott** [comment]
@marklawlor FYI I just updated to `4.0.6` and now I get this on startup in the iOS sim (no other deps have changed.)

![image](https://github.com/marklawlor/nativewind/assets/796702/b9f3b7a3-2bdc-41d3-ab08-5d5a9f8a3e69)

**Comment by robcaldecott** [comment]
Android gives me this.

![image](https://github.com/marklawlor/nativewind/assets/796702/998b2240-0f9a-4d56-b91d-9c8c37f55d32)

**Comment by robcaldecott** [comment]
Added `react-native-reanimated@3.3.0` solves this. Might be something for the NativeWind docs? But being able to use the latest will be important (we need it for our app as it fixes some other issues.)

**Comment by Jrousell** [comment]
I've updated to `"nativewind": "^4.0.6"` and still `fast-refresh` is not working. Doing a `r` to reload the app works fine though.

**Comment by marklawlor** [comment]
> Adding `react-native-reanimated@3.3.0` solves this. Might be something for the NativeWind docs? But being able to use the latest will be important (we need it for our app as it fixes some other issues.)

This is an Expo Go issue which comes pre-built with reanimated. If you want to upgrade you need to swap to a development build

**Comment by marklawlor** [comment]
Fast refresh fixed in `4.0.8`

**Comment by Jrousell** [comment]
> Fast refresh fixed in `4.0.8`

yup, now working for me - great stuff

**Comment by robcaldecott** [comment]
@marklawlor you are an absolute star. Fast refresh now working.
Now to try it in our app and give it a good run.

**Comment by pencilcheck** [comment]
I'm on 4.0.22, fast refresh is not working, either it doesn't work or it uses the wrong style completely. I have user defined custom styles loaded, I only see those correct style applied after I kill the metro completely.

**Comment by marklawlor** [comment]
@pencilcheck How can I resolve your issue if you don't provide any context? I don't have access to your computer. Please create a new issue explain your issue in detail and provide as much relevant information as possible

**Comment by pencilcheck** [comment]
> @pencilcheck How can I resolve your issue if you don't provide any context? I don't have access to your computer. Please create a new issue explain your issue in detail and provide as much relevant information as possible

That is the problem I have with many libraries with great following, is that a bug shows up, but I have no clue how to reduce to the minimum since to effort to produce a minimal example in my existing app is a lot of work.

I am not the developer of the app, I don't know the details, I can't know what is going on.

Let me try to be more specific in the issue, when I add a custom color in tailwind.config.js such as this:
```
    extend: {
      colors,
      fontFamily: {
        'app-black': ['WhitneyBlack'],
        'app-black-italic': ['WhitneyBlackItalic'],
        'app-bold': ['WhitneyBold'],
        'app-bold-italic': ['WhitneyBoldItalic'],
        'app-book': ['WhitneyBook'],
        'app-book-italic': ['WhitneyBookItalic'],
        'app-light': ['WhitneyLight'],
        'app-light-italic': ['WhitneyLightItalic'],
        'app-medium': ['WhitneyMedium'],
        'app-medium-italic': ['WhitneyMediumItalic'],
        'app-semibold': ['WhitneySemibold'],
        'app-semibold-italic': ['WhitneySemiboldItalic'],
      }
    }

```

When I add a className "app-semibold" while i'm on dev build on expo, the style is not applied, but it will if I kill expo, and restart the app completely.

I notice that because the only time I see this line in the console:
```
tailwindcss(native) rebuilding... warn - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`....
.....
```

only when I restart expo completely and recompile the app.

If I change the style while having expo up, I don't see this, and the style will not be included.

**Comment by marklawlor** [comment]
@pencilcheck I don't need a huge technical explanation, the best explainations are:

- a link to a project
- what commands you use to run the project
- what operating system your using

Right now I still can't assist you as for all I know you could be accidentally running the app in a mode with fast-refresh disabled!

You also don't need to share your entire app, the smaller the better!
