### ISSUE TITLE
Extending color theme with variable breaks when using hsl(var(--variable))

### ISSUE THREAD

**Issue by ravilmc** [marklawlor/nativewind#606]
**Describe the bug**
I was trying to use variables from the shadcnui in nativewind. 
Shadcn uses variables like this in css file
`
root : {
    primary : 0 84.2% 60.2%;
}
`
and 

`
theme : {
   extend : {
      colors : {
          primary : "hsl(var(--primary)
      }
   }
}
`
But this does not work with nativewind

However the following works : 
`
root : {
    primary : hsl( 0 84.2% 60.2%);
}
`
and 
`
theme : {
   extend : {
      colors : {
          primary : "var(--primary)"
      }
   }
}
`

Am I doing something wrong. Or is this expected

**Comment by marklawlor** [comment]
Fixed in `4.0.9`, just make sure you are correctly writing your theme as ` theme: { extend: { colors: { primary: "hsl(var(--primary))" } } },`
