### ISSUE TITLE
v4: TouchableOpacity styles not working

### ISSUE THREAD

**Issue by robcaldecott** [marklawlor/nativewind#608]
Nativewind v4.0.8, Expo 49

In 4.0.8 you cannot style `TouchableOpacity` even though it seems to be configured here: https://github.com/marklawlor/nativewind/blob/35b47ec552c730758f446708f824f5ed6e0516e6/packages/react-native-css-interop/src/core-components.ts#L109

Here's an example repo: https://github.com/robcaldecott/nativewind-4-issues

You can workaround this using `cssInterop`:

```tsx
cssInterop(TouchableOpacity, { className: { target: "style" } });
```

Here's the full code:

```tsx
import * as React from "react";
import { Text, TouchableOpacity, View } from "react-native";
import { cssInterop } from "nativewind";
import "./globals.css";

// Uncomment to fix the TouchableOpacity issue
// cssInterop(TouchableOpacity, { className: { target: "style" } });

export default function App() {
  return (
    <View className="flex-1 bg-white items-center justify-center gap-8">
      <TouchableOpacity className="p-4 bg-yellow-300">
        <Text>TouchableOpacity</Text>
      </TouchableOpacity>
    </View>
  );
}
```

Without `cssInterop`:
![image](https://github.com/marklawlor/nativewind/assets/796702/5904b61e-6a4d-4203-b279-399c16235ad9)

With `cssInterop`:
![image](https://github.com/marklawlor/nativewind/assets/796702/b0da681a-0979-4a4b-b404-5087cf12b86a)

Note that uncommenting out `cssInterop` makes it work and if you comment it out again it stays working until you perform a full app refresh, which is a little confusing.

Also, what are the chances of having out-of-the-box `className` support for some Expo components (`expo-image` for example), the popular `SafeAreaView` from `react-native-safe-area-context`, etc.? I am using `cssInterop` for these as well.

And as some general guidance where do you recommend we use `cssInterop` in our code? Slap them all in a file and import in our main `App.tsx`? Thanks!

**Comment by marklawlor** [comment]
`4.0.9` contains fixes for `TouchableOpacity` and other native components (e.g. `SafeAreaView`)

Note that `TouchableOpacity` is deprecated by `react-native`. You can get the similar behaviour with `<View className="active:opacity-20 transition" />`.

I've had a late minute realisation on how to improve `cssInterop` which I'll be working on this week and I'll be updating the docs about its usage. Ideally the average user should never have to use `cssInterop`
