### ISSUE TITLE
v4.0.8 - Next.js ReferenceError: __DEV__ is not defined error

### ISSUE THREAD

**Issue by enesozturk** [marklawlor/nativewind#611]
**Describe the bug**

In my Solitp app, I upgraded NativeWind to v4. It's working as expected on mobile side according to the setup [instructions in v4 documents](https://www.nativewind.dev/v4/getting-started/react-native).

On the Next.js side, I followed [Next.js setup instructions](https://www.nativewind.dev/v4/getting-started/nextjs), made updates to `tsconfig.json`as described:

```js
{
  "compilerOptions": {
    "jsxImportSource": "nativewind"
  }
}
```

After this, Next.js started throwing error like the following: 

```js
Server Error
ReferenceError: __DEV__ is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

<details>
<summary>See screenshot</summary>

<img width="1036" alt="Screenshot 2023-11-04 at 20 29 16" src="https://github.com/marklawlor/nativewind/assets/19428358/2e8ecc78-50f4-456d-9550-36c1fc739962">

</details>

Also, when I open any file inside the Next.js app, the whole JSX functions show a TS error like the following:

```js
Could not find a declaration file for module 'nativewind/jsx-runtime'. '/{MY_PROJECT_PATH}/node_modules/nativewind/jsx-runtime/index.js' implicitly has an 'any' type.

Try `npm i --save-dev @types/nativewind` if it exists or add a new declaration (.d.ts) file containing `declare module 'nativewind/jsx-runtime';`ts(7016)

```

@marklawlor Sorry I cannot directly share a reproducible project, would it work if I add you to my private repo so you can fetch and test?

**Comment by marklawlor** [comment]
Fixed in `4.0.9`

FYI: In the future, just create a new repo using `npx create-next-app` to demonstrate issues, no need to share your full project.
