### ISSUE TITLE
/App.js: Use process(css).then(cb) to work with async plugins

### ISSUE THREAD

**Issue by tarifalhasan** [marklawlor/nativewind#621]
error: App.js: /home/tarif/Documents/projects/app/my-scholl/App.js: Use process(css).then(cb) to work with async plugins

![Screenshot from 2023-11-08 10-39-38](https://github.com/marklawlor/nativewind/assets/92237522/4b34027b-b110-4259-9b36-1a98ce33812d)
![Screenshot from 2023-11-08 10-39-18](https://github.com/marklawlor/nativewind/assets/92237522/ca14d577-5f8c-4e06-84c2-578326455886)

**Comment by GustavoBonfimS** [comment]
Any solution ?

**Comment by GustavoBonfimS** [comment]
solution https://github.com/marklawlor/nativewind/issues/498#issuecomment-1635038692
