### ISSUE TITLE
Strange padding when using flex and View

### ISSUE THREAD

**Issue by anthony-bernardo** [marklawlor/nativewind#622]
**Describe the bug**
When i'm using flex and stacked `View`, there is a strange padding on left (on screenshot, see the padding left of the "+") 

**To Reproduce**
```
<View className="flex-col items-center justify-center flex-grow gap-2 bg-blue-400">
    <View className="flex-row justify-between w-1/2 gap-2 bg-red-400 ">
        <Text>+</Text>
        <Text>4</Text>
        <Text>-</Text>
    </View>
</View>
```

**Screenshots**
![k5FEm](https://github.com/marklawlor/nativewind/assets/739621/5b983fbc-057e-4a96-b379-3d7bb5b95ab2)

**Additional context**
Related to my post stackoverflow https://stackoverflow.com/questions/77438716/nativewind-view-with-padding-left

**Comment by robcaldecott** [comment]
Is this version 2? If so, the `gap` property does not have native support and instead messes with the margins. Could be that?

Try this:

```tsx
<View className="flex-col items-center justify-center flex-grow bg-blue-400" style={{ gap: 8 }}>
    <View className="flex-row justify-between w-1/2 bg-red-400 " style={{ gap: 8 }}>
        <Text>+</Text>
        <Text>4</Text>
        <Text>-</Text>
    </View>
</View>
```

**Comment by marklawlor** [comment]
This is a bug in v2 due to the `gap-` polyfill (flexbox gap was not available at the time) and the clashing margins. You read about the polyfill and its limitations here https://www.nativewind.dev/tailwind/flexbox/gap

I would recommend using an inline style adding `gap` or upgrade to v4 which removes the poly-fill
