### ISSUE TITLE
Dynamic styling using className

### ISSUE THREAD

**Issue by ShaneKeney** [marklawlor/nativewind#624]
**Describe the bug**
I have the following:

```
export default function Register() {
  const { isDarkMode } = useTheme();
  const insets = useSafeAreaInsets();

  return (
    <View className={`flex-1 bg-background pl-[${insets.left.toString()}]`}>
      ...
    </View>
  );
}
```

The `insets.left` which in my case on an iPhone 15 is 59.  If I replace with `pl-[59]` I see the change reflected with left padding of 59.

**To Reproduce**
Any attempt to inject variable that is calculated at runtime is not possible in the `className` prop.

**Expected behavior**
Should `className` be compatible for dynamically changing values.  I can't seem to find any docs on this exact type of use case.  If not, I can always use the `style` prop.  But wanted to make sure I wasn't misunderstanding something.

**Comment by marklawlor** [comment]
Tailwind CSS does not allow dynamic classNames https://tailwindcss.com/docs/content-configuration#dynamic-class-names

You can either use inline styles or CSS variables (if using the v4 preview) for dynamic styles.
