### ISSUE TITLE
v4: The placeholderClassName prop does not work

### ISSUE THREAD

**Issue by robcaldecott** [marklawlor/nativewind#629]
```
nativewind@4.0.13
expo@49.0.13
```

The 4.0.13 release of NativeWind no longer supports `placeHolderClassName`:

```tsx
import * as React from "react";
import { Text, TextInput, View } from "react-native";
import "./globals.css";

export default function App() {
  return (
    <View className="flex-1 bg-white items-center justify-center gap-8 p-6">
      <View className="gap-2 w-full">
        <Text>The placeholder below should be yellow-300</Text>
        <TextInput
          className="bg-slate-900 h-10 text-white px-2"
          placeholder="Placeholder text"
          placeholderClassName="text-yellow-300"
        />
      </View>
    </View>
  );
}
```

Unless I am missing something, `placeholderClassName` above should work.

Sample repo here: https://github.com/robcaldecott/natibewind-4-placeholder

**Comment by panzacoder** [comment]
WOAH this was hard to find. It would be really great if the docs could point to a list of all the clever additions you've made, even if it's just a typedef somewhere. Unless this is a TW thing I'm not familiar with, this was really non-discoverable for me.
