### ISSUE TITLE
Babel errors when using nativewind/babel plugin on brand new bare React Native Project

### ISSUE THREAD

**Issue by lakardion** [marklawlor/nativewind#631]
**Describe the bug**
Creating a new project with react-native-cli crashes on babel

**To Reproduce**
1. [Follow the react-native-cli getting started
](https://www.nativewind.dev/quick-starts/react-native-cli)
3. Run the project
4. The app should crash on babel

**Expected behavior**
App runs properly and allows adding tailwind classes to react native components

**Expo Snack**
<wip>

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/52294448/c34964c3-2dd6-4d09-9361-a3c7fcd90c31)

**Additional context**
```js
//babel.config.js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['nativewind/babel'],
};

```

**Comment by Linzo99** [comment]
@lakardion I got that error when trying the V4 which i think moved away from using Babel Plugin.
Check other versions

**Comment by marklawlor** [comment]
https://github.com/marklawlor/nativewind/issues/600#issuecomment-1804741121
