### ISSUE TITLE
v4: disabled and focus-within modifiers do not work on React Native

### ISSUE THREAD

**Issue by robcaldecott** [marklawlor/nativewind#634]
```
nativewind@4.0.13
```

The Tailwind `disabled` and `focus-within` modifiers do not work in React Native. Is this expected?

Sample repo here: https://github.com/robcaldecott/nativewind-4-modifiers

**Disabled**
Should use `opacity-50`:

```tsx
<Pressable
  disabled
  className="rounded-full w-full p-4 bg-indigo-500 active:bg-indigo-900 items-center justify-center disabled:opacity-50"
>
  <Text className="text-white text-lg font-bold">{children}</Text>
</Pressable>
```

**Focus within**
Should use an indigo border when the `TextInput` within has focus.

```tsx
<View className="border-2 border-slate-300 py-2 px-4 bg-white rounded-xl focus-within:border-indigo-500 h-12 justify-center">
  <TextInput {...props} />
  </View>
```

For now I am handling this manually, e.g.:

```tsx
function Button({
  children,
  disabled,
  ...props
}: React.PropsWithChildren<PressableProps>) {
  return (
    <Pressable
      className={cn(
        "rounded-full w-full p-4 bg-indigo-500 active:bg-indigo-900 items-center justify-center",
        {
          "opacity-50": disabled,
        }
      )}
      disabled={disabled}
      {...props}
    >
      <Text className="text-white text-lg font-bold">{children}</Text>
    </Pressable>
  );
}
```

```tsx
function TextField({ onFocus, onBlur, ...props }: TextInputProps) {
  const [hasFocus, setHasFocus] = React.useState(false);

  return (
    <View
      className={cn(
        "border-2 border-slate-300 py-2 px-4 bg-white rounded-xl h-12 justify-center",
        {
          "border-indigo-500": hasFocus,
        }
      )}
    >
      <TextInput
        {...props}
        onFocus={(event) => {
          setHasFocus(true);
          if (onFocus) {
            onFocus(event);
          }
        }}
        onBlur={(event) => {
          setHasFocus(false);
          if (onBlur) {
            onBlur(event);
          }
        }}
      />
    </View>
  );
}
```

**Comment by ghmendonca** [comment]
For me, the `active` modifier doesn't work. If I do something like `<Pressable className="bg-green-500 active:bg-green-700" />`, when I press the button, it never changes the background color. This used to work on v2

**Comment by marklawlor** [comment]
`disabled` will come after the v4 release

Unless someone proposes a nice generic way to implement `focus-with` it will probably never be supported. I don't think I can put an event listener on every child component of a view. My gut feeling is that I would need to introduce a new concept, e.g extend the group syntax with `group-focus-within` and then child components could have `focusable`.

**Comment by marklawlor** [comment]
@ghmendonca Your comment does not seem related to this issue. Please open a new issue with a reproducible example

**Comment by ghmendonca** [comment]
@marklawlor sorry, just created a new project and I can confirm that the `active` modifier works. I think I had an issue with `clsx` which was not setting the class properly. But I can also confirm the `disabled` modifier is not working, but it's expected since you said this will only be added after the v4 release

**Comment by robcaldecott** [comment]
Thanks for the update @marklawlor
