### ISSUE TITLE
v4: Next.js not applying class names

### ISSUE THREAD

**Issue by tamagokun** [marklawlor/nativewind#635]
**Describe the bug**
Started a new project with next.js and react-native-web. I believe I have nativewind v4 set up correctly, however there are no class names being output.

Is this style of setting up react-native-web obsolete?

**To Reproduce**

1. Clone https://github.com/tamagokun/example-nativewind-4-nextjs
2. `yarn` and `yarn dev`
3. Open up http://localhost:3000

Update:

I've added `verifyInstallation`, which says:

```
Error: jsxImportSource was not set to 'nativewind'. Please refer to http://nativewind.dev/troubleshooting#jsxImportSource
```

However, it's definitely in the tsconfig.

**Expected behavior**
Should a blue box with white text "Welcome to next.js". Everything appears to be unstyled

**Comment by rpweb** [comment]
Same for me, I tried it with app router though.

**Comment by nivans-pro** [comment]
try to add "jsxImportSource": "nativewind" to your tsconfig.json in the Next.JS app folder

**Comment by tamagokun** [comment]
> try to add "jsxImportSource": "nativewind" to your tsconfig.json in the Next.JS app folder

take a look at the example repo, it's there

**Comment by luixo** [comment]
Yep, going through the [Getting Started](https://www.nativewind.dev/v4/getting-started/nextjs) with Next.js doesn't work.
Also, Next.js [overrides](https://github.com/vercel/next.js/discussions/19155) `jsx` in `compilerOptions` to `preserve`, though disabling it via patching Next.js doesn't help.

**Comment by marklawlor** [comment]
`4.0.14` should fix this issue.

If your still having problems, please check if your project has a Babel config file. If it does, make sure you followed the Babel instructions, and not the `SWC` ones.

**Comment by tamagokun** [comment]
✌️ all working over here!

**Comment by wibb36** [comment]
> `4.0.14` should fix this issue.
> 
> If your still having problems, please check if your project has a Babel config file. If it does, make sure you followed the Babel setup instructions, and not the `SWC` ones.

@marklawlor I'm a bit confused here. Did you mean to use Babel instructions only if you already have Babel config within the project or `SWC` simply won't work? or i'm missing something.

For reference, I'm using Nativewind 4.0.23 with Next.js + app directory, and SWC. I've been scratching my head for a solid two hours on this one and it simply won't output any classes 🤔 no errors though.
