### ISSUE TITLE
When will nativewind v4 have caching?

### ISSUE THREAD

**Issue by pakerekchdz** [marklawlor/nativewind#639]
Because as another project's statistics for checking UI libraries shows, it is quite slow.

**Comment by cureau** [comment]
I realize this is off topic, but @pakerekchdz your history is full of discouraging and unhelpful comments. There's one guy working on this lib. If your skill and generosity is equal to his, I'd suggest submitting PRs. At the very least, make sure the issues you open are clearly written, reproducible, and considerate.

**Comment by marklawlor** [comment]
Duplicate https://github.com/marklawlor/nativewind/discussions/642
