### ISSUE TITLE
Import TS module in `tailwind.config.js`

### ISSUE THREAD

**Issue by vitaliyirtlach** [marklawlor/nativewind#640]
**Describe the bug**
error: index.js: [BABEL] /Users/vitaliyirtlach/projects/indigo/apps/app/index.js: Cannot use import statement outside a module (While processing: "/Users/vitaliyirtlach/projects/indigo/apps/app/node_modules/nativewind/babel.js")

**To Reproduce**
1. Go to 'tailwind.config.js'
2. Import TS module
3. See error

**Expected behavior**
Error is goen

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**
<img width="962" alt="Снимок экрана 2023-11-12 в 16 30 32" src="https://github.com/marklawlor/nativewind/assets/63682036/b62e4a97-fbcc-4f56-a08e-20d81f1a72b7">

**Additional context**

**Comment by marklawlor** [comment]
This will be fixed in `v4`.

However your use case will still fail, as your importing a `.ts` file from a `.js` file, so you'll get invalid syntax errors. You should use a `tailwind.config.ts` if you wish to import `.ts` files.

**Comment by vitaliyirtlach** [comment]
> This will be fixed in `v4`.
> 
> However your use case will still fail, as your importing a `.ts` file from a `.js` file, so you'll get invalid syntax errors. You should use a `tailwind.config.ts` if you wish to import `.ts` files.

Yep, I have tried with `ts` config, but the error persisted
