### ISSUE TITLE
v4: web not hot reloading (metro/sdk49/expo-router)

### ISSUE THREAD

**Issue by gorbypark** [marklawlor/nativewind#643]
**Describe the bug**
I setup a new SDK49 project with expo router and followed the steps in the expor-router section of the v4 docs to install nativewind.  Everything is working great except that on web, hot reloading classNames is not working.  Hot loading in general is working on the web (example: changing `<Text>one</Text>` to` <Text>two</Text>`) works as expected.  The issue is that if you add or change something in a className, the web version does not hot reload (works fine on iOS).  It actually requires reloading metro with the --clear flag (refreshing the browser does not work).  I am assuming for some reason the CSS is not being regenerated on a change.

**To Reproduce**
1. Change anything in a className

**Expected behavior**
I'd expect hot reloading would be active/working

**Additional context**
I believe I have everything setup as per the docs.  Invoking verifyInstallation() in `app/_layout.tsx` gives a `WARN  NativeWind verifyInstallation() found no errors`.

metro.config.js
```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require("nativewind/metro");

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, {
  // [Web-only]: Enables CSS support in Metro.
  isCSSEnabled: true,
});

config.resolver.sourceExts.push("mjs");

module.exports = withNativeWind(config, { input: "./global.css" });
```

babel.config.js
```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
    plugins: [
      // Required for expo-router
      "expo-router/babel",
      "@babel/plugin-proposal-export-namespace-from",
      "react-native-reanimated/plugin",
    ],
  };
};
```

tailwind.config.js
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

global.css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

app/_layout.tsx (top of file)
```tsx
import "../global.css";
```

**Comment by marklawlor** [comment]
NativeWind uses Expo's CSS support for fast-refresh on web, which unfortunately has an issue with Metro aggressively caching CSS. This PR will resolve the issue https://github.com/expo/expo/pull/25339

I'll keep this open as I might be able to work around it (NativeWind doesn't need to use the feature that is causing the issue, PostCSS)

**Comment by cedarbaum** [comment]
FYI the patch mentioned above appears to be in Expo version 49.0.19. I upgraded and am now seeing hot reloads work correctly!

**Comment by bidah** [comment]
I happens @marklawlor that sometimes the hotrealoding works and others you are out of luck and just don't work. I would be great to have a fix before metro since getting the fix for metro will take time as you know.

**Comment by daniellmartins** [comment]
A quick solution is in a new terminal running on tailwind watch input and output

`npx tailwindcss --watch -i ./src/styles/global.css -o ./src/styles/output.css`

`
import "styles/output.css";
`

https://github.com/marklawlor/nativewind/assets/4332656/5501ec54-9be8-4bc0-8408-d6189eb00075

**Comment by marklawlor** [comment]
`4.0.14` should resolve this issue.
