### ISSUE TITLE
v4: platformColor usage in tailwind.config.js not working as expected

### ISSUE THREAD

**Issue by gorbypark** [marklawlor/nativewind#645]
**Describe the bug**
When using a custom theme color value that uses platformColor, there is an error.  I'm not quite sure of how this is all working, but I am assuming that platformColor on native platforms is eventually actually passed into the component itself (hence the `ios/platformColor(systemRed)` type stuff in the node_modules .cache), but somewhere along the chain it is not being parsed properly? As a quick test, I changed the usage of platformColor to a hardcoded color value (`ios: "green"`), and it works as expected, so that can rule out platformSelect as a contributing factor.

```
 ERROR  Warning: Failed prop type: Invalid prop `color` supplied to `Text`: [object Object]
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "color": "[object Object]"
}
```

Here how it is being used
```tsx
<Text className="text-customcolortest">Some Text</Text>
```

and the tailwind.config.js
```js
const { platformSelect, platformColor } = require("nativewind/theme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        customcolortest: platformSelect({
          // Now you can provide platform specific values
          ios: platformColor("systemRed"),
          android: platformColor("?android:colorError"),
          default: "red",
        }),
      },
    },
  },
  plugins: [],
};
  ```

Looking in `.node_modules/.cache/nativewind/global.css.native.css` I can see the class is 
```css
.text-customcolortest {
  color: platformSelect(ios/platformColor(systemRed),android/platformColor(\?android\:colorError),default/red)
}
```

**To Reproduce**
1. Add custom theme color using platformColor
2. Attempt to use the class

**Expected behavior**
Working colors

**Comment by uyasarkocal** [comment]
Have you found a solution (even temporary) for this? PlatformColor usage is critical for accessibility...

**Comment by marklawlor** [comment]
I believe this is fixed ([unit test](https://github.com/marklawlor/nativewind/blob/fa595f88a2e5423835e27bce0e8d89eb9244b020/packages/react-native-css-interop/src/__tests__/functions-test.ios.tsx#L50-L66)). Can you let me know if you are still having this issue or if you have any other feedback. I'm still collecting feedback on these APIs to improve them

**Comment by uyasarkocal** [comment]
It worked correctly when there is only one element that uses a platformColor, when there are **multiple elements** that use the **same color**, app crashes. I guess that's how it passed the unit test 😅 @marklawlor

Version:  4.0.17

# Example
## This works as expected:
```jsx
<View >
          <Text className="text-4xl text-secondaryLabel">TEST</Text>
          <Text className="text-4xl text-label">TEST</Text>
</View> 
```
        
## This don't work! 
```jsx
 <View >
          <Text className="text-4xl text-secondaryLabel">TEST</Text>
          <Text className="text-4xl text-secondaryLabel">TEST</Text>
 </View> 
```

The error it gave:
```
ERROR  Error: You attempted to set the key `0` with the value `"secondaryLabel"` on an object that is meant to be immutable and has been frozen.

This error is located at:
    in CSSInterop.Text (created by Page)
    in RCTView (created by View)
    in View (created by CSSInterop.View)```

**Comment by uyasarkocal** [comment]
Tried with nativewind@4.0.35 and can confirm it works. Thank you @marklawlor

**Comment by vktrl** [comment]
I'm getting this with `4.0.36`
