### ISSUE TITLE
Hover styles are not cleared on web

### ISSUE THREAD

**Issue by mhaagens** [marklawlor/nativewind#646]
**Describe the bug**
Hover events linger and are not cleared on web.

**To Reproduce**
Create a pressable with a hover style
```
<Pressable
    className="flex-row items-center h-10 px-3 hover:bg-red-500"
    onPress={() => {}}
>
    <Text> {item.title}</Text>
</Pressable>
```

**Expected behavior**
The hover style is cleared on mouseout.

**Screenshots**
![nativewind_hover](https://github.com/marklawlor/nativewind/assets/3270517/256c9d90-669e-456d-8641-5b8b2386cb6a)

**Additional context**
Nativewind 2.0.11, TailwindCSS 3.3.2, Expo SDK 49

**Comment by fechan** [comment]
I'm using the same Nativewind and TailwindCSS verions and I'm also encountering this problem with both `hover` and `active` pseudo-selectors.

**Comment by JinYuSha0** [comment]
@marklawlor Dear marklawlor, I found this bug in version 2.0.11, but I found that this project is not completely open source. This is a really good project. Will you try to involve people in the community to maintain it? Give me my best wishes
```
// node_modules/nativewind/dist/styled/use-interaction.js
        if (isParentOrGroup || (0, selector_1.matchesMask)(mask, selector_1.HOVER)) {
            handlers.onHoverIn = function (event) {
                if (ref.current.onHoverIn) {
                    ref.current.onHoverIn(event);
                }
                dispatch({ type: "hover", value: true });
            };
            handlers.onHoverOut = function (event) {
                if (ref.current.onHoverIn) {
                    ref.current.onHoverIn(event);
                }
                dispatch({ type: "hover", value: true }); // value should be false
            };
        }
```

**Comment by marklawlor** [comment]
This is fixed in v4
