### ISSUE TITLE
V4: TailwindCSS classes occasionally break.

### ISSUE THREAD

**Issue by fendyk** [marklawlor/nativewind#648]
**Describe the bug**
The issue extends beyond just the 400 strength colors like `bg-red-400` or `bg-orange-400`; a broader range of Tailwind CSS classes are not functioning properly. The inconsistency in functionality makes it difficult to predict which classes will work.

To Reproduce
- Clone https://github.com/fendyk/expo-router-typescript-nativewind-example
- Run on android of ios
- Visit the `app/(tabs)/index.tsx`
- Observe that certain classes do not apply any styling.

**Expected behavior**
All Tailwind CSS classes should be correctly parsed and applied, resulting in the intended styles being reflected on the elements.

**Comment by marklawlor** [comment]
Please provide a full reproduction.

**Comment by gorbypark** [comment]
I am finding something similar, however I don't think it's just background colours and I don't think it's specific to any one class.  I'm finding that sometimes classes will work, and then they just stop.  I can see in the node_modules/.cache that they are there, but they just don't apply.  I haven't quite figured out exactly when it's happening and how to fix it.  Sometimes just changing a class to something else and then back again makes it work...sometimes it does not.  Sometimes restarting metro and clearing the cache work, and sometimes it doesn't.  I will try to make a reproduction at some point, but here's a quick little demo of it not working.  The `text-1xl` and `text-2xl` classes are not working, but they are in the cache.

I'm taking a guess that this issue is related to mine.

https://github.com/marklawlor/nativewind/assets/19569469/ab4622da-fb55-4973-999e-65df02ebc58e

**Comment by fendyk** [comment]
Here's a quick snippet of the issue, will make a reproduction asap

https://github.com/marklawlor/nativewind/assets/56702979/70749b02-2055-457d-83c2-b6e1ab779313

**Comment by fendyk** [comment]
> Please provide a full reproduction.

Here's the reproduction

https://github.com/fendyk/expo-router-typescript-nativewind-example

**Comment by enesozturk** [comment]
@fendyk I think we could improve the description a bit. This is not just related to `-400`. Many of the Tailwind classes doesn't work. E.g just use `italic`, `underline` for a text. Use `w-10`, `h-20`, etc. Flex properties like `align-center`, `justify-center`, etc works. So it's hard to understand which will work which is not.

It's actually putting the class names to the elements in DOM. But there are no these classes defined in CSS in DOM.

**Comment by fendyk** [comment]
@enesozturk, could you please test my repo to identify any additional non-functional classes? If you find any, commit your findings, and I'll merge them into the main branch

**Comment by GustavoBonfimS** [comment]
In my project none of the Tailwind colors work, only the custom colors that were added to the theme.

**Comment by fendyk** [comment]
I've added various new styles to test out, and found more issues. You can check them out @marklawlor

**Comment by marklawlor** [comment]
Can people please upgrade to `4.0.14` and test again.

If your issue is still occurring, please respond with as much detail as possible - even if you don't think its relevant. E.g Your operating system, are your using an emulator or on device, etc

During development, NativeWind uses a custom web-socket server to load styles. So if your having issue, even something unusual like a firewall could be causing issues.

**Comment by fendyk** [comment]
can confirm `4.0.14` is broken on `MacOS` as-well. Doing the exact same on a (Android emulator) And running `npx expo start --android` I get this error:

```bash
tailwindcss(native) rebuilding... done
Android Bundling complete 5666ms
 ERROR  TypeError: Cannot convert undefined value to object

This error is located at:
    in CSSInterop.StatusBar (created by Tutorial)
    in RCTView (created by View)
    in View (created by View)
    in View
    in bound createPsuedoClassView (created by Tutorial)
    in Tutorial (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by wrapper)
    in wrapper (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App) (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot convert undefined value to object

This error is located at:
    in CSSInterop.StatusBar (created by Tutorial)
    in RCTView (created by View)
    in View (created by View)
    in View
    in bound createPsuedoClassView (created by Tutorial)
    in Tutorial (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by wrapper)
    in wrapper (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App) (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

```

**Comment by marklawlor** [comment]
@fendyk can you try `4.0.15`

**Comment by marklawlor** [comment]
> can confirm `4.0.14` is broken on `MacOS` as-well. Doing the exact same on a (Android emulator) And running `npx expo start --android` I get this error:
> 
> ```shell
> tailwindcss(native) rebuilding... done
> Android Bundling complete 5666ms
>  ERROR  TypeError: Cannot convert undefined value to object
> 
> This error is located at:
>     in CSSInterop.StatusBar (created by Tutorial)
> ```

This is a different issue. Can you please create a new issue with a reproduction

**Comment by fendyk** [comment]
> @fendyk can you try `4.0.15`

On Windows 4.0.15 solved the .js file issue but displays a new error:

```Bash
ERROR  Error: jsxImportSource was not set to 'nativewind'. Please refer to http://nativewind.dev/troubleshooting#jsxImportSource


This error is located at:
    in RootLayout
    in Try
    in Unknown
    in Unknown (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App) (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

 I am using https://github.com/fendyk/expo-router-typescript-nativewind-example for testing

**Comment by trevorpfiz** [comment]
> Can people please upgrade to `4.0.14` and test again.
> 
> If your issue is still occurring, please respond with as much detail as possible - even if you don't think its relevant. E.g Your operating system, are your using an emulator or on device, etc
> 
> During development, NativeWind uses a custom web-socket server to load styles. So if your having issue, even something unusual like a firewall could be causing issues.

I was having the same issues where a lot of different styles would not work unpredictably. On WSL2 Windows 11. Was using `expo start --tunnel` though? Super confused.

changed this:
```
[wsl2]
memory=8GB

[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
networkingMode=mirrored
dnsTunneling=true
autoProxy=true

```

to this:
```
[wsl2]
memory=8GB
networkingMode=NAT
dnsTunneling=false
autoProxy=false

[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
```
and things started working again.

I also ran `expo start -c`. Is `expo start -c --tunnel` supposed to work, because I was running that before and no luck.

Sorry if this just causes more confusion. Will keep playing with it and update if things break again.

**Comment by trevorpfiz** [comment]
after some more testing I can confidently say that `expo start --tunnel` is not working for me, but `expo start` is.

**Comment by the-simian** [comment]
This is still breaking in 4.0.23 I've tested this on web, ios and android hardware and also on OSX and WSL. The behavior is similar to what @trevorpfiz  is describing. The only difference is that `expo start` does not work, nor does the tunnel. the behavior is the same either way.

- on both OSX and Windows 11 (wsl) the web works just fine. 
    -You can add a 'new' class like `bg-yellow-500` and you'll see it.
    
- on both OSX and Windows 11 (wsl) all hardware devices **do not update.** 
    - If the class was present in the initial load you will see it
    - if the class is added later you will not. This means if you add, say `bg-yellow-500` you will see it on the web but *not* on your device.
    - this is the case for literally any class, regardless of it is layout, font, etc.
    - in both cases inside of node_modules/.cache/nativewind I can see the classes *do* get added to the stylesheet. In other words if you add `bg-yellow-500` in both `global.cssnative.css.css` as well as `global.css.web.css` the new class will appear, 
    ```
    .bg-yellow-500 {
     background-color: #eab308;
   }
 ```
 
 - other changes, such as text copy do update with normal fast-refresh behavior.
 
 
I have reproduced with with a completely newly scaffolded `create-expo-app`, and all latest dependencies:

```
  "expo": "50.0.4",
  "nativewind": "4.0.23",
  "tailwindcss": "^3.4.1"
```

**Comment by marklawlor** [comment]
There are a number of issues being reported within the same issue, so I'm not sure if I'm addressing them all correctly (please create separate issues for different things!).

`4.0.28` should address `--tunnel` not works and styles not being applied on windows builts.

If this wasn't your issue, please create a new ticket.
