### ISSUE TITLE
Gap cause error / crash. `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined`

### ISSUE THREAD

**Issue by kyle-belle** [marklawlor/nativewind#652]
**Describe the bug**
Whenever i use the classname gap-{n} i get the error
```cmd
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef(useStyled)`.
```
**To Reproduce**
1. setup project with nativewind `@next / v3 im using`
2. try to render this element: `Note: it only crashes when the parent / element with gap has children in it. `
```tsx
<View className="gap-3">
  <View></View>
</View>
```
**Expected behavior**
Expected the application to not crash

**Screenshots**
![Screenshot_2023-11-19-17-02-02-37_ad20c43ec96ba1d90298ada815a11cdc](https://github.com/marklawlor/nativewind/assets/43228761/2aafb32f-ced0-4956-a793-ab3f6c8a106e)

**Comment by marklawlor** [comment]
Fixed in the v4 release
