### ISSUE TITLE
Nativewind V4 not refreshing new class changes till i clean build everytime

### ISSUE THREAD

**Issue by ursnj** [marklawlor/nativewind#653]
**Describe the bug**

Nativewind not refreshing new class changes till i clean build everytime. i tried looking at .cache changes are not building till i clean build it.

**To Reproduce**

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by GustavoBonfimS** [comment]
See https://github.com/marklawlor/nativewind/issues/643

**Comment by marklawlor** [comment]
This doesn't seem related to #643, as the files in `.cache/nativewind` are not being updated. The logic behind generating/updating these files is not related to fast refresh, its controlled by the `dev` and `hot` settings in Metro.

We use Tailwind CLI to generate the files and we only pass it the `--watch` flag if both `dev` and `hot` settings are enabled. https://github.com/marklawlor/nativewind/blob/3755a62875d5eb802ae56706b5847e4e63b852cd/packages/nativewind/src/metro/tailwind-cli.ts#L70-L72

I'm going to close this isssue, as there isn't enough information for me to troubleshoot and hopefully the infomation provide assists you. If not, can you please provide a reproduction with instructions on how you start your project (or add it as an `npm start` script)
