### ISSUE TITLE
Dark selector does not work for fill or stroke

### ISSUE THREAD

**Issue by enchorb** [marklawlor/nativewind#657]
Using the dark selector on fill/stroke property does not work (iOS, Android)

ie. `'fill-white dark:fill-black stroke-stone-200 stroke-[0.5] dark:stroke-neutral-600'`

**Comment by marklawlor** [comment]
Fixed in v4.

Please make sure you have enabled the interop for components needing these classes https://www.nativewind.dev/v4/tailwind/svg/fill
