### ISSUE TITLE
4.0.14 is broken on Windows

### ISSUE THREAD

**Issue by ghmendonca** [marklawlor/nativewind#666]
**Describe the bug**
Looks like the CLI change to use the `tailwindcss/lib/cli.js` script instead of calling `npx tailwindcss` made so it doesn't work on Windows. I did not test on Linux or Mac, but on Windows when you execute that script, the terminal hangs forever and the process never really starts to build de css file.

**To Reproduce**
1. Install the latest version, 4.0.14
2. Run the app on Windows
3. Try to open the app using Expo Go

**Expected behavior**
It should build the css file and run the app.

**Comment by marklawlor** [comment]
Just published `4.0.15` which updates to command to `node <path_to_tailwindcss>/lib/cli.js`. I believe this should work on Windows.

You can also customise this command by passing a custom `cliCommand` option to `withNativeWind()`.

https://github.com/marklawlor/nativewind/blob/6bb5648f0cd0cd045e2f6a29f96ed73469fd9d25/packages/nativewind/src/metro/index.ts#L34-L38

If your still having issues, I would appreciate any feedback and I'm not a Windows user.

**Comment by ghmendonca** [comment]
@marklawlor thank you so much, it's fixed
