### ISSUE TITLE
[V4] NativeWindStyleSheet has no property to set output for web / default

### ISSUE THREAD

**Issue by ritmillio** [marklawlor/nativewind#676]
During upgrade from v2 to v4 I discovered that our app used back in v2 NativeWindStyleSheet.setOutput for selecting the correct output for web and mobile. NativeWindStyleSheet has no longer this prop so I'm a bit confused here why It got removed.

**To Reproduce**
[v2] -> [v4] upgrade:
`NativeWindStyleSheet.setOutput({
  web: 'css',
  default: 'native'
})`

**Expected behavior**
Property 'setOutput' does not exist on type 'typeof import("/Users/ritmillio/Developer/expo-router-starter-kit/node_modules/nativewind/dist/index")'.ts(2339)

**Comment by marklawlor** [comment]
NativeWind v4 no longer supports changing the output per platform. Web is always CSS and native and always StyleSheet.create. This only only existed as React Native Web's CSS support was very young and not many projects had upgraded
