### ISSUE TITLE
[v4][Android] `contentContainerClassName` on `FlatList` results in TypeError: right operand of 'in' is not an object

### ISSUE THREAD

**Issue by thespacemanatee** [marklawlor/nativewind#677]
**Describe the bug**

Using the `contentContainerClassName` results in `TypeError: right operand of 'in' is not an object`. This only happens on Android.

**To Reproduce**
1. Use the `contentContainerClassName` property on `FlatList`
2. See error

**Expected behavior**

- No error should be seen

**Screenshots**

![Screenshot 2023-11-27 at 12 29 04 AM](https://github.com/marklawlor/nativewind/assets/6837599/352c7a69-9192-453c-9cdd-0271a25d5e30)

![Screenshot 2023-11-27 at 12 30 02 AM](https://github.com/marklawlor/nativewind/assets/6837599/afeee45a-888a-4a73-9023-fcc240cbf6d0)

**Additional context**

- Running `nativewind@4.0.16`
- This issue does not appear on `nativewind@4.0.1`, I haven't tested many version in between but it's safe to assume that the issue appeared between these 2 versions

**Comment by benfavre** [comment]
This brakes React Native Paper inputs :disappointed: 

Any progress

**Comment by Revanthshalon** [comment]
I am facing the same issue. Any updates on how to resolve this issue?

**Comment by marklawlor** [comment]
This issue appears to be fixed
