### ISSUE TITLE
nativewind with tailwind typescript not working

### ISSUE THREAD

**Issue by vinibgoulart** [marklawlor/nativewind#679]
Im trying to configure my tailwind config file using typescript but without success

file `tailwind.config.ts`
```ts
import type { Config } from 'tailwindcss'

export default {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config
```

![image](https://github.com/marklawlor/nativewind/assets/88122830/9f13d7c9-5c94-486b-a59c-708ed058e1ae)

**Comment by marklawlor** [comment]
This appears outside the scope of NativeWind, I would be looking at the Tailwind repo for answers on setting up Tailwind CSS.

Its also very hard to troubleshoot a typescript issue without seeing your projects code or even a tsconfig.
