### ISSUE TITLE
Nativewind not working with create-react-native-library

### ISSUE THREAD

**Issue by sidghimire** [marklawlor/nativewind#686]
Reference Repository: https://github.com/sidghimire/sphereui

This is a project made using create-react-native-library, i have made all configurations correctly in the library component itself as well as the test application. The test application as a standalone support Nativewind configurations but when same thing is imported using the package library it doesnt work

**Comment by Yangsoomin** [comment]
me too

**Comment by marklawlor** [comment]
The reference repository is no longer available.

Descriptions like "it doesn't work" are not very informative, so I'm not sure what the reported issue is. I'm going to close the issue as I'm unsure how to proceed. If your still having this issue please create a new issue.
