### ISSUE TITLE
TypeError with StyleSheet.registerCompiled and Invariant Violation in NativeWind v4.0.13

### ISSUE THREAD

**Issue by erickgtzh** [marklawlor/nativewind#687]
**Hey everyone!**

I've encountered a critical issue with NativeWind version 4.0.13 in my React Native project. This problem emerged recently and was not present until this Monday.

#### Issue Description:
When I include my `global.css` file in `App.tsx`, the application throws a TypeError related to `StyleSheet.registerCompiled`, indicating that it is not a function. Furthermore, an Invariant Violation error regarding the registration of "name" occurs. These errors do not appear when I comment out the import statement for `global.css`.

#### Error Messages:
1. `TypeError: _$$_REQUIRE(_dependencyMap[1], "(...)op").StyleSheet.registerCompiled is not a function (it is undefined), js engine: hermes`
2. `Invariant Violation: "name" has not been registered.`

#### Relevant Code:
**App.tsx:**
```tsx
import React from 'react';
import { AuthProvider } from '../context/AuthContex';
import Navigation from '../navigation/Navigation';
import '../global.css';

const App = () => {
  return (
    <AuthProvider>
      <Navigation />
    </AuthProvider>
  );
};

export default App;
```

**global.css:**
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**tailwind.config.js:**
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './App.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './app/**/**/*.{js,jsx,ts,tsx}',
    './app/**/**/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {},
  },
  presets: [require('nativewind/preset')],
  plugins: [],
};
```

**metro.config.js:**
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const {withNativeWind} = require('nativewind/metro-config');

const config = {};

module.exports = withNativeWind(
  mergeConfig(getDefaultConfig(__dirname), config),
  {input: './global.css'},
);
```

#### Additional Context:
- This issue appears specifically when I try to integrate the global stylesheet (`global.css`).
- The project runs without any errors when `global.css` import is commented out.
- I have followed the installation and setup instructions as per the NativeWind documentation.
- I suspect the issue might be related to my configuration, but despite having deleted `node_modules`, reinstalled all dependencies, cleared cache, reinstalled libraries, and attempted to run the project more than 20 times, I am still encountering the same problem.
- I couldn't find any information on the internet about this issue, so I am hoping to find assistance here in case someone else has experienced this configuration error.

**Thank you for your assistance.**

**Comment by marklawlor** [comment]
Currently your issue is missing files that I would need to troubleshoot the issue, so I cannot even start troubleshooting.

I would highly advise simply just linking me your repo. If you cannot link the repo, create a new empty project and demonstrate the issue there.

**Comment by josephfh** [comment]
Having this problem too. I've provided a reproduction repo in the new issue: https://github.com/marklawlor/nativewind/issues/777

**Comment by harrisontaee** [comment]
FYI, I fixed it by removing `react-native-css-interop` from my dependencies.
