### ISSUE TITLE
v4: line-clamp-1 removes all styling

### ISSUE THREAD

**Issue by johnf** [marklawlor/nativewind#691]
**Describe the bug**
Something strange is going on with the hoisting. As soon as I add `line-clamp-1` to a `Text` component all the styling disappears

When I take a look in dev-tools the entire style is being see to the number of lines

I suspect this might be related to #671 and #690 I'll test once next release comes out to see if it goes away

**To Reproduce**
```jsx
// This works
<Text className="text-3xl" numberOfLines={1}>OK</Text>

// This doesn't have a big font
<Text className="text-3xl line-clamp-1">OK</Text>
```

**Expected behavior**
Correct styling is applied

**Expo Snack**
Is there a snack for v4 yet?

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/42590/45dfdc6c-bff4-4f0a-80fa-8c8bd6063ece)

![image](https://github.com/marklawlor/nativewind/assets/42590/403e8028-94ef-496b-8fe9-ab081c8609b6)

**Comment by marklawlor** [comment]
This appears to be fixed in the latest v4 release
