### ISSUE TITLE
Non-std c++ exception

### ISSUE THREAD

**Issue by tonnyhc** [marklawlor/nativewind#696]
**Describe the bug**

Using react native expo with typescript, tailwindcss and nativewind.
When the nativewind/babel plugin is added inside babel.config.js 

**To Reproduce**
Open babel.config.js, and paste the "plugins: ["nativewind/babel"],"
stop the server
run the server again using npx expo start --clear (to clear the cache)
and this error occurs "non-std C++ exception"

**Screenshots**
![400509796_898418984692987_5286089385705706336_n](https://github.com/marklawlor/nativewind/assets/92336437/fce34f0d-6736-4370-b9d6-9cd742e4b8d9)

**Additional context**
This dont happen everytime, it happens from time to time, and the only solution is to create a completely new app, paste all the code inside and after some time clearing the cache it will happen.

**Comment by takuyahirata23** [comment]
Same here

**Comment by ngoc2003** [comment]
<img width="335" alt="Ảnh màn hình 2023-12-12 lúc 02 00 41" src="https://github.com/marklawlor/nativewind/assets/90141097/d5725754-cd8c-4167-b559-54650aa8c93a">
I found that this is causes by this plugins. I tried to comment this line and it work, but my tailwind code not working anymore, needed to be suppport now:(

**Comment by siquick** [comment]
Just started getting this too. Complete clean Expo project 

```sh
{
  "name": "myapp",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "ts:check": "tsc"
  },
  "dependencies": {
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "typescript": "^5.1.3",
    "@types/react": "~18.2.14"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "tailwindcss": "3.3.2"
  },
  "private": true
}
```

**Comment by Logan9312** [comment]
Having this issue too, has anyone found a fix?

**Comment by marionlouis1** [comment]
same

**Comment by oscar-v0** [comment]
Had the same issue and managed to resolve this by moving all my js/ts files into a src directory and changing `tailwind.config.js` to only target jsx, tsx & html files in my src dir:

```diff
module.exports = {
- content: ['./**/*.{js,jsx,ts,tsx}'],
+ content: ['./src/**/*.{html,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};

```

**Comment by marklawlor** [comment]
I cannot troubleshoot an issue with reproduction repo. I'm going to close this issue as not enough information has been provided.

If your experiencing this issue, make sure your `content` isn't also including your `node_modules`. If your still having the issue, please create a new issue with a full reproduction.

**Comment by finallyblueskies** [comment]
I just had this. Completely out of the blue and only resolvable with @oscar-v0's solution

**Comment by conradkoh** [comment]
Had the same problem. Frustrating because it was working fine the day before. It was also strange because it should have broke many commits ago but decided to fail all of a sudden.

@oscar-v0 wdyt if we just added a line to the docs to warn people not to put in something that may accidentally include node_modules?

Debugging this was really hard too, as there is no indication in the error that nativewind was causing the issue, even from the macos console. I had to deconstruct the entire app down to a simple App.js and add the dependencies one by one to ultimately find that this caused the issue.

**Comment by marklawlor** [comment]
@conradkoh That warning is in the Tailwind installation docs. NativeWind v4 has code to attempt to detect this and warn the user.

**Comment by myleftshoe** [comment]
> make sure your `content` isn't also including your `node_modules`.

There's  high chance this is what is happening. If you name the top level files explicitly like in the [nativewind docs](https://www.nativewind.dev/quick-starts/expo#2-setup-tailwind-css) it shouldn't happen.

``` js
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by surajahmed** [comment]
In my situation, the presence of spaces in the `displayName` of a component led to this issue. This problem was resolved by removing the space from the `displayName`. The adjustment was made from:
`CustomSelectComponent.displayName = 'Custom Select Component'`
to
`CustomSelectComponent.displayName = 'CustomSelectComponent'`

**Comment by CyxouD** [comment]
In my case, it was due to babel presets in `babel.config.js`

**Comment by AhmedAbuelenin** [comment]
I faced this error because of wrong metro config, i missed to add the config to the newConfig object as follow, after doing so make sure to clean metro cache and start over again

```
import {getDefaultConfig} from 'expo/metro-config';

const config = getDefaultConfig(__dirname);
const {transformer, resolver} = config;

const newConfig = {
  ...config, // forgot to add this one
  transformer: {
    ...transformer,
    babelTransformerPath: require.resolve('react-native-svg-transformer/expo')
  },
  resolver: {
    ...resolver,
    assetExts: resolver?.assetExts?.filter(ext => ext !== 'svg'),
    sourceExts: [...(resolver?.sourceExts || []), 'svg']
  }
};

module.exports = newConfig;

```
Hope this help someone

**Comment by CristianFigueredo** [comment]
In my case Cursor change some zh translation causing this problem.

**Comment by dbenahmed** [comment]
kind of the same sollution @oscar-v0 did worked for me
The problem for me was inside of my **NativeWind configuration file**
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: [
                    "./app/**/*.{js,jsx,ts,tsx}", 
                     "./components/**/*.{js,jsx,ts,tsx}",
                      // "./**/*.{js,jsx,ts,tsx}"],  <<< THIS IS THE PROBLEM
                      // I added this path pointing to the root of my project ( where node_modules was )
// after removing it and adding paths pointing to all my jsx file only like this one >
                     "./components/**/*.{js,jsx,ts,tsx}" // solved the problem for me 
                    
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      
    },
  },
  plugins: [],
}
```
