### ISSUE TITLE
v4: Can't use odd-numbered values for border-{n}

### ISSUE THREAD

**Issue by hassankhan** [marklawlor/nativewind#697]
**Describe the bug**

When I try and use an odd-numbered width for a border, it doesn't seem to work. Oddly, while testing it seems like `border-6` doesn't work either.

**To Reproduce**
1. Create a `<View />` component with `className="border-1 border-gray-500"`
2. See the lack of border

**Expected behavior**
I expected a border of width `1` to be set on the component.

**Screenshots**

https://github.com/marklawlor/nativewind/assets/1781985/d0fa8237-a24b-43f9-b4bd-4751191ae1c7

**Additional context**
This seems to happen with any odd-numbered width I set, as well as `6` for some reason.

**Comment by marklawlor** [comment]
https://tailwindcss.com/docs/border-width

The detail theme does not have odd border numbers

**Comment by hassankhan** [comment]
Apologies, sorry for the noise
