### ISSUE TITLE
Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by ngoc2003** [marklawlor/nativewind#698]
Hi, every thing work fine until today, i have this issue when start on my android device. I have tried to install tailwindcss@3.3.2 but it still not work. 
![image](https://github.com/marklawlor/nativewind/assets/90141097/60295b8c-783b-439f-a9ab-062157f3f816)

I relize that when i comment this plugins, my app run correctly without tailwindcss's style. So that mean this plugin is problem???
<img width="343" alt="Ảnh màn hình 2023-12-12 lúc 02 08 33" src="https://github.com/marklawlor/nativewind/assets/90141097/50480e22-f62b-45c4-8e69-e903d9d44273">

**Comment by mhmtyasr** [comment]
I have this problem. Do you have  any answer ?

**Comment by ngoc2003** [comment]
@mhmtyasr  no answer:( I uninstall this package and use this instead https://www.npmjs.com/package/twrnc

**Comment by byronwade** [comment]
same problem

**Comment by marklawlor** [comment]
If you have this issue, please upgrade the to 4.0 beta

**Comment by 592da** [comment]
@marklawlor first, thank you for your awesome work on this great project!

unfortunately v4 is still not ready for production apps, had few issues with it
(all touch events stop working after few press events, and other weird side effects)

We tried to implement v2 then (2.0.11), and development env is very difficult to work with,
we getting this error: 

```Cannot read property 'create' of undefined```
anytime we add/remove new component that used the classNames, and we need to reload the whole metro bundler and clean cache...

any way we can solve it until v4 will be production ready?
will be happy to try to help with it, can you please at least give us some directions for the solution?

thanks!

**Comment by hbracy** [comment]
I also have this issue. Working off a totally vanilla project today with expo.

**Comment by WillSmithTE** [comment]
@marklawlor since it's the way past this issue, do you have a migration guide from v2 to v4?

**Comment by serranoarevalo** [comment]
I fixed this by running `npm run start -- --clear` which ran `expo start --clear`.

**Comment by anirbanpaulcom** [comment]
![WhatsApp Image 2024-08-27 at 8 48 30 AM](https://github.com/user-attachments/assets/159df8b5-3b5c-4348-98a3-b2f5534ba74e)
 can anyone fixed this?

**Comment by anirbanpaulcom** [comment]
> ![WhatsApp Image 2024-08-27 at 8 48 30 AM](https://private-user-images.githubusercontent.com/130109852/361640362-159df8b5-3b5c-4348-98a3-b2f5534ba74e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTMxMzAsIm5iZiI6MTcyNTI1MjgzMCwicGF0aCI6Ii8xMzAxMDk4NTIvMzYxNjQwMzYyLTE1OWRmOGI1LTNiNWMtNDM0OC05OGEzLWIyZjU1MzRiYTc0ZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDQ1MzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM3MDYxYjYwMzYxNWFmZjc5MTQzMWQ4MWE1MDBkNGQzNTg2ZDY0OWJmMzI0NDUxZTdhMzc1MmMxMjNhMzI5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eMApBt5QfxZ9KZzR7LoxDrboyFbqYo4-I2oMSoMbxlA) can anyone fixed this?

**Comment by MelvinSnijders** [comment]
Make sure you configured `content` properly in the TailwindCSS config. After I changed that to only include files from `/app` and `/components`, it started working again:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: { }
  },
  plugins: [],
};

```

Also clear the cache with:

```
npm run start -- --clear
```

**Comment by MuhammadAflah** [comment]
![expo error](https://github.com/user-attachments/assets/a694aae7-d249-4847-9c8a-45d14eb50041)

i am facing an error like this in my expo app. if anyone know how to resolve this, your responses will be greatfull.
