### ISSUE TITLE
NativeWind v4 doesn't work as expected with pnpm

### ISSUE THREAD

**Issue by VaniaPopovic** [marklawlor/nativewind#701]
**Describe the bug**
In a project using Expo 50, PNPM and expo router, trying to install native wind causes an issue 
<img width="427" alt="image" src="https://github.com/marklawlor/nativewind/assets/17993952/90604306-556a-4acb-93e3-45575519ab2c">
I suspect that the react-native-css-interop isnt compatible with pnpm or it's not bundled correctly?

**To Reproduce**
1. Clone https://github.com/VaniaPopovic/expo-monorepo-example 
2.  Run pnpm i and then pnpm expo run:android
3. The project runs fine
4. Checkout the nativewind branch which just adds nativewind
5. Run pnpm i and then pnpm expo run:android
6. See the problem

**Expected behavior**
I know pnpm just started working properly without the need of link-hoisted, but it would be nice for nativewind to run on a pnpm workspace. I have dabbled with the nativewind repository to try and find the problem, but could not find it

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by byCedric** [comment]
Yep, I second this! This is a similar issue to the `@babel/runtime` import issues if you don't have `@babel/runtime` as direct project dependency.

In short, I guess this is happening:
- We add an import to `react-native-css-interop/jsx-runtime` through the transformation step
- This can't be resolved through isolated modules, as no "link" or dependency chain exists between this file (the project) and this library.

**Comment by NomadicOx** [comment]
So I ran into this as well. The only workaround I came to was to pin Nativewind at 4.0.13. It seems something happened after then as no matter what version I use from .14 onwards, I get this issue. Tested with Expo 49 and Expo 50 (preview 7).

**Comment by tyrauber** [comment]
Hey @byCedric, could https://github.com/marklawlor/nativewind/issues/734 be related to this?  I've been trying unsuccessfully to use Nativewind to style paackages in a pnpm monorepo. Have you tried styling packages in a pnpm monorepo outside of the projectRoot? Trying to determine if it is an issue with nativewind, pnpm setup or human error.

**Comment by siquick** [comment]
> So I ran into this as well. The only workaround I came to was to pin Nativewind at 4.0.13. It seems something happened after then as no matter what version I use from .14 onwards, I get this issue. Tested with Expo 49 and Expo 50 (preview 7).

I'm not using pnpm (using npm) and was having another issue but this is what ended up working for me.

**Comment by charkour** [comment]
It's working for us on expo v50 and router v3 with pnpm. @VaniaPopovic, looks like your babel config is missing the Nativewind preset: https://github.com/VaniaPopovic/expo-monorepo-example/blob/main/apps/mobile/babel.config.js

Our babel.config.js looks like this:
```js
/** @type {import('@babel/core').ConfigFunction} */
module.exports = function (api) {
    api.cache(true);
    return {
        presets: [
            [
                'babel-preset-expo',
                {
                    jsxImportSource: 'nativewind',
                },
            ],
            'nativewind/babel',
        ],
        plugins: ['expo-router/babel', 'react-native-reanimated/plugin'],
    };
};
```

**Comment by VaniaPopovic** [comment]
Are you sure you are not using ``node-linker=hoisted`` in a .npmrc file in the root directory? With that pnpm works, but because of the changes made in Expo 50, I'm trying to run it with symlinked dependancies withtout that .npmrc file.

**Comment by charkour** [comment]
Correct, I'm not using `node-linker=hoisted`, but I am using `public-hoist-pattern[]=*`

**Comment by the-simian** [comment]
I was able to get this working with pnpm, but I did need to use `node-linker=hoisted` in the .npmrc and pin the `nativewind` version at 4.0.13.

**Comment by jukkamarttinen** [comment]
Using 
`
public-hoist-pattern[]=*metro*
public-hoist-pattern[]=@babel*
public-hoist-pattern[]=*prettier*
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*typescript*
public-hoist-pattern[]=*react*
`
cleared this issue for me, for pnpm monorepo. Did not need to hoist all of the packages.

**Comment by marklawlor** [comment]
I'm going to close this issue as pnpm isn't fully supported by React Native and I'm not sure what I need to action here.

If someone wants to contribute a `configuring pnpm` guide to the website I'll add it.

**Comment by SalihColak** [comment]
I am also using npm (not pnpm) and have this issue

**Comment by marklawlor** [comment]
@SalihColak This issue is for `pnpm` please open a new issue for different package manager. Also, how I can a help you with your issue, if you don't provide me with any information? At least provide me with an example repo so I can see what your issue is

**Comment by RMorgan179** [comment]
I am also getting this issue using NPM. With Nativewind v4.0.23. It was working fine for me and now im getting, "Unable to resolve "react-native-css-interop/jsx-runtime" from "node_modules/expo-router/src/renderRootComponent.tsx". When trying to run the ios simulator. Any ideas or will l just move to Nativewind v4.0.13 as suggested previously?

**Comment by parkwherever** [comment]
I'm having this issue with jest tests (yarn workspace setup) but not when building my app. Any suggestions? v4.0.13 does not solve it

**Comment by danstepanov** [comment]
Can confirm that the fix here is the `.npmrc` file containing `node-linker=hoisted`. I'm using NativeWind v4.0.36 and pnpm v8.15.5.

If you have been trying other solutions, you may need to run the following commands after adding the `.npmrc` file:

1. rm -rf node_modules
2. watchman watch-del-all
3. pnpm i
4. pnpm start --reset-cache
5. Click "i" on your keyboard to launch the iOS simulator

## Working Examples
- `npx create-expo-stack@latest my-app --nativewind --pnpm`
- `npx create-expo-stack@latest my-app --nativewind --expo-router --pnpm`

## Note
Previously, for https://rn.new, I only added this `.npmrc` file when using both NativeWind *and* Expo Router with pnpm. I have since changed it to add a `.npmrc` whenever pnpm is used. I'm still unclear (haven't tested) whether the file is needed if you are not using Expo Router + NativeWind.

**Comment by aman08singh** [comment]
Just for testing purposes:

Uninstall the react-native-reanimated library.
Build the project.

or

Without installing react-native-reanimated, follow steps from: https://www.nativewind.dev/getting-started/react-native

**Comment by nickplee** [comment]
I'm not in love with it, but my solution was to add an entry to my `babel.config.js` `overrides` that resets the jsx transform set by the NativeWind Babel preset back to the RN default. This was the only thing that got me past the (unresolvable) NativeWind JSX runtime import being added to jsx/tsx files in unrelated modules.

```javascript
/** @type {import('@babel/core').TransformOptions} */
module.exports = {
  presets: [
    'module:@react-native/babel-preset', 
    'nativewind/babel'
  ],
  plugins: [
    'react-native-reanimated/plugin' // must be last
  ],
  overrides: [
    {
      test: (filename) => !filename.startsWith(__dirname),
      plugins: [
        [
          "@babel/plugin-transform-react-jsx",
          {
            runtime: "automatic",
          },
        ]
      ],
    }
  ]
};
```

**Comment by ballestrino** [comment]
I've this problem and i use npx expo install --check, this solve my interop issue.
