### ISSUE TITLE
V4: transition animation breaks when you add a child to it

### ISSUE THREAD

**Issue by bidah** [marklawlor/nativewind#712]
**Describe the bug**
When using `transition` on a View if I add a child element animation happens but app breaks when I toggle again the animation throwing a render error. Toggle is to animate transition. Tried with `scale` and `rounded` on both happens.

**To Reproduce**
Repo with only the code that has issue.
<https://github.com/bidah/nativewind-child-issue-when-using-transition-animation>

**Expected behavior**
add child and app does not break.

**Screenshots**
![render error](https://i.imgur.com/5luzNWF.png)

**Comment by marklawlor** [comment]
This is resolved in the latest v4
