### ISSUE TITLE
Tailwind styles not compiling to css in Expo

### ISSUE THREAD

**Issue by Raidoxe** [marklawlor/nativewind#714]
**BUG**

Nativewind styles are not reflected in css or visually (Expo), specifically flex-wrap and text color.

This is the compiled html:
```
<div class="css-view-175oi2r flex flex-row h-screen space-x-2">
    <div dir="auto" class="css-text-146c3p1 text-white flex-none">01</div>
    <div dir="auto" class="css-text-146c3p1 r-flexBasis-1mlwlqe r-flexGrow-18kxxzh r-flexShrink-1wbh5a2">02</div>
    <div dir="auto" class="css-text-146c3p1 r-flexBasis-1mlwlqe r-flexGrow-18kxxzh r-flexShrink-1wbh5a2">03</div><
/div>
```

This is the compiled css:
```
.css-view-175oi2r {
    align-items: stretch;
    background-color: rgba(0, 0, 0, 0);
    border: 0px solid black;
    box-sizing: border-box;
    display: flex;
    flex-basis: auto;
    flex-direction: column;
    flex-shrink: 0;
    list-style: none;
    margin: 0px;
    min-height: 0px;
    min-width: 0px;
    padding: 0px;
    position: relative;
    text-decoration: none;
    z-index: 0;
```
and 
```
css-text-146c3p1 {
    background-color: rgba(0, 0, 0, 0);
    border: 0px solid black;
    box-sizing: border-box;
    color: rgb(0, 0, 0);
    display: inline;
.....
```

**To Reproduce**
1. App.tsx file 
```
import React from "react";
import { Text, View } from "react-native";

export default function App() {
  return (
    <View className="flex flex-row h-screen space-x-2">
      <Text className="text-white flex-none">01</Text>
      <Text className="flex-initial">02</Text>
      <Text className="flex-initial">03</Text>
    </View>
  );
}
```
3. tailwind.config.js
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./<custom directory>/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```
4. tsconfig.json
```
{
  "compilerOptions": {
    "strict": true,
    "types": ["nativewind/types"]
  },
  "extends": "expo/tsconfig.base",
  "include": ["**/*.ts", "**/*.tsx", "App.js"]
}
```

**Expected behavior**
The compiled css should have the flex-wrap: wrap attribute and the text-color: white attribute. However only display: flex is reflected correctly.

**Screenshots**
<img width="415" alt="Screenshot 2023-12-27 at 1 02 41 pm" src="https://github.com/marklawlor/nativewind/assets/52924806/b8a7ef58-e8e3-4eb0-a194-7537f884bae2">

**Additional context**
Not sure if this is a problem with my machine, expo, or actually Nativewind itself. But this has been really bugging me for a while and I can't seem to get to the bottom of it. Thanks for your time.

**Comment by marklawlor** [comment]
I'm going to close this issue as I cannot assist you with a full reproduction repo. It appears that you a missing a CSS stylesheet in your HTML (the one with the Tailwind styles, your only seeing the React Native Web styles right now), but without seeing the project I cannot advise you on why that is happening. If you provide a reproduction, I can reopen the issue.
