### ISSUE TITLE
Inverted FlatList doesn't work after first render

### ISSUE THREAD

**Issue by hukpo** [marklawlor/nativewind#717]
nativewind 4.0.22

**To Reproduce**
1. Add FlatList with inverted prop
2. Update state
3. See error

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/40897161/b754134c-de0a-4c19-9187-913fe3efb6d9)

**Comment by marklawlor** [comment]
Appears to be fixed in `4.0.29`
