### ISSUE TITLE
Nativewind V4: Changing metro config and babel config to metro.config.cjs and babel.config.cjs breaks the styling (app loads but no styling shows up)

### ISSUE THREAD

**Issue by pencilcheck** [marklawlor/nativewind#720]
**Describe the bug**

Went from Expo SDK 48 to Expo SDK 49

Nativewind V4: Changing metro config and babel config to metro.config.cjs and babel.config.cjs breaks the styling (app loads but no styling shows up)

**To Reproduce**
1. Change metro.config.js to metro.config.cjs and babel.config.js to babel.configj.cjs
2. Do the usual, expo start the app
3. No style shows up

**Expected behavior**

The styling still shows up

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by marklawlor** [comment]
Yes, if you change your config file so that it invalid and never loads, that will cause NativeWind not to work.

I do not understand how this is a NativeWind issue. If you'd like Metro to support `.cjs` files, then you should raise the issue with Metro
