### ISSUE TITLE
scale font dynamics in v4 is posibble?

### ISSUE THREAD

**Issue by pixelkoduje** [marklawlor/nativewind#726]
**To Reproduce**
Is it possible to dynamically change the font size in v4? This is how I did it in v3.
`NativeWindStyleSheet.setVariables({ "--rem": 16 });`
5. **Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/102321542/f5563315-1032-456f-996f-3f21f7cc5c59)

**Comment by marklawlor** [comment]
You need to either:
-disable `inline-rem` (will affect padding and other styles that use rem)
-change your theme so your fonts use a custom CSS variable (will only affect fonts)

https://www.nativewind.dev/v4/tailwind/typography/font-size#rem-scaling

This is missing from the docs, but if you disable `rem` you can change the value at runtime like so.

```tsx
import { rem } from "nativewind"

rem.set(<value>)
```
