### ISSUE TITLE
Expo Nativewind Monorepo Issues - Unable to style packages

### ISSUE THREAD

**Issue by tyrauber** [marklawlor/nativewind#734]
**Describe the bug**

In an Expo PNPM Monorepo with an Expo Application in the `./apps/example` and a UI package in `./packages/ui`, the expectation is that Nativewind will be able style components defined anywhere within the monorepo, including outside of the project root.

With the following tailwind.config.js content declaration:

```
content: ["./src/**/*.{js,jsx,ts,tsx}", "../../packages/ui/src/**/*.{js,jsx,ts,tsx}"],
```

The expectation is that Nativewind will style JSX components defined in both  `./apps/example`  and `./packages/ui`. 

Unfortunately, components imported from the UI package fails to style, unlike the same components imported from the app.

**To Reproduce**
1. Create a monorepo similar to [expo-monorepo-example](https://github.com/byCedric/expo-monorepo-example)
2. Install and configure Nativewind V4
3. Create a component in `apps/*/src/components` and in `packages/*/src/components`
4. Import the component into the primary app page from both locations

**Expected behavior**
Expectation is that both components would render the same. 

**Demonstration**
The following example demonstrates the issue [expo-nativewind-monorepo-issue](https://github.com/tyrauber/expo-nativewind-monorepo-issue).

This is an Expo PNPM Monorepo with an Expo Application in the `./apps/example` and a UI package in `./packages/ui`.

There are two tabs. Both tabs load the exact same code. The first tab, Home, imports components from `./apps/example/components`. The second tab, Package, imports the same code from `./packages/ui/src`.

The tailwind.config.js content declaration should tell Nativewind to style components in the UI package.

```
content: ["./src/**/*.{js,jsx,ts,tsx}", "../../packages/ui/src/**/*.{js,jsx,ts,tsx}"],
```

However, as this test shows, that isn't the case and Nativewind fails to style the UI package.

Clicking between the two tabs demonstrate this issue.

**Screenshots**

![FromApp](https://github.com/marklawlor/nativewind/assets/109972/c128d1b4-dc74-4208-8fac-d85f9486b80d)
![FromPackage](https://github.com/marklawlor/nativewind/assets/109972/3295db7b-37c6-4fc5-a05c-354c46d82c42)

**Additional context**

This repo uses Expo SDK 50 Preview 7 with the following libraries:
```
    "@expo/vector-icons": "^13.0.0",
    "expo": "^50.0.0-preview.7",
    "expo-constants": "~15.4.2",
    "expo-linking": "~6.2.1",
    "expo-router": "~3.4.1",
    "expo-splash-screen": "~0.26.1",
    "expo-status-bar": "~1.11.1",
    "nativewind": "^4.0.22",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.1",
    "react-native-reanimated": "~3.6.0",
    "react-native-safe-area-context": "4.7.4",
    "react-native-screens": "~3.27.0",
    "react-native-web": "~0.19.6",
    "tailwind-variants": "^0.1.19",
    "tailwindcss": "^3.4.0"

```

**Comment by tyrauber** [comment]
Ok, Different approach.

Move global.css and tailwind.config.js to workspaceRoot, not app directory (projectRoot). Update the metro.config.js options, per the documentation, specifying the configPath and input relative to workspaceRoot.

```
const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

module.exports = withTurborepoManagedCache(
  withMonorepoPaths(
    withNativeWind(getDefaultConfig(__dirname), { 
      projectRoot: projectRoot,
      configPath: "../../tailwind.config.js",
      input: "../../global.css" 
    })
  )
);
```

(I tried setting the projectRoot to workspaceRoot, but  [nativewindConfig doesn't taking into account the projectRoot config option when resolving the input path or tailwindConfig path](https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/src/metro/index.ts#L53-L57). If you patch that resolving to workspaceRoot, then you need to resolve the outputDir to the projectRoot node modules. This seemed easier.)

Update global.css to point to tailwind.config.js, as per the [tailwind documentation](https://tailwindcss.com/docs/configuration#using-a-different-file-name).

```
@config "./tailwindcss-config.js";

@tailwind base;
@tailwind components;
@tailwind utilities;
```

Update references to global.css to reflect the workspaceRoot path.

Because tailwindcss is being run from projectRoot, the tailwind.config content must still relative to project root. 

```
content: ["../../apps/example/src/**/*.{js,jsx,ts,tsx}", "../../packages/ui/src/**/*.{js,jsx,ts,tsx}"],
```

This was counterintuitive to me - the goal of moving everything to workspace root was to make it relative to workspace root. BUT whatever, this does work. Kinda. At least for components in projectRoot.  The UI packages are still not rendering. 🤯 

Something else must be happening here.  @marklawlor, any ideas?

**Comment by marklawlor** [comment]
Currently `projectRoot` is only used for specifying the output file location. I guess it should also set the `cwd` of the spawned instance of `tailwind`.

https://github.com/marklawlor/nativewind/blob/32b937111a1820ac5f7e4e422bb12a31122e9564/packages/nativewind/src/metro/tailwind-cli.ts#L97-L102

**Comment by tyrauber** [comment]
Thanks @marklawlor, I appreciate you weighing in.

With the above configuration changes, you don't actually have to patch anything. At least, to generate the `global.css.native.css`.   No errors or warning are raised, and it builds the nativewind cache directory.  What I don't understand is that when rendering, only the app components render.   The components from the package do not. With normal configuration, or this second approach.  I would think both content paths would be parsed?

```
content: ["../../apps/example/src/**/*.{js,jsx,ts,tsx}", "../../packages/ui/src/**/*.{js,jsx,ts,tsx}"],
```

I now believe the issue isn't with the css generation but in the rendering.

The css types highlight in VScode from both the app and package components! The tsconfig, I believe is working:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "@expo-starter/ui/*": ["../../packages/ui/src/*"],
    }
  },
  "extends": "expo/tsconfig.base",
  "include": [
    "../../global.d.ts", 
    "**/*.ts", 
    "**/*.tsx",
    "../../packages/ui/src/**/*.ts", 
    "../../packages/ui/src/**/*.tsx"
  ]
}

```

It's just if I import the component from the package, it is not parsing the className out of the component UI if it is outside of the packageRoot. Does that make sense?

**Comment by tyrauber** [comment]
Note: There is no reason for the workspaceRoot configuration outlined in the second comment above - unless you prefer having the global.css and tailwind.config.js in root. It is NOT required in a monorepo.

Tailwindcss cli will parse content outside of app root, i.e. `content: ["../../packages/ui/src/**/*.{js,jsx,ts,tsx}"]`. To prove this, I removed the app directory from the content declaration and only supplied `"../../packages/ui/src/**/*.{js,jsx,ts,tsx}"`.  Tailwind css generation was successful- `tailwindcss(native) rebuilding... done`. If it wasn't, I would think tailwind cli would have warned:
> warn - No utility classes were detected in your source files.

The most interesting part of this experiment is that the app defined components render (even though the app src wasn't included in the  tailwind content declaration), while the package components (which were) failed to render!  If I include an empy content declaration tailwindcss warns on build and neither app or package ui components render.

**Oddly, [className on expo/html-elements somehow work in package components!](https://github.com/tyrauber/expo-nativewind-monorepo-issue/blob/main/packages/ui/src/page.tsx#L21)** it is just react-native components (View, Text) that fail.  Adding cssInterop on Text and View in the package does not help.

@marklawlor, does this help?  I believe I've isolated it to a rendering issue of className on react-native components (View, Text) defined in a package outside of projectRoot.  I believe  [2138497](https://github.com/tyrauber/expo-nativewind-monorepo-issue/commit/213849783d8803c00497917683d0372797566bcb) demonstrates the above.  Any suggestions of where to dig and patch? I'd love to get to the bottom of this.

**Comment by tyrauber** [comment]
Oh, Bloody hell.  This is not a Nativewind issue.  It's a PNPM configuration issue.

Looking back through @byCedric's [expo-monorepo-example](https://github.com/byCedric/expo-monorepo-example), I noticed this line in the [metro.config.js](https://github.com/byCedric/expo-monorepo-example/blob/8229117fd826dd51562f17725a8084b9bf450b99/apps/mobile/metro.config.js#L13C1-L14C50) which I hadn't included in the example config:

```
// #3 - Force resolving nested modules to the folders below
config.resolver.disableHierarchicalLookup = true;
```

This line is REQUIRED to make Nativewind work within monorepo packages.

**Comment by turkerdev** [comment]
For nativewind v4 with turborepo setup, I had to follow the v4 docs and also the code piece below.

```js
config.cacheStores = [
  new FileStore({
    root: path.join(projectRoot, "node_modules", ".cache", "metro"),
  }),
];
```

**Comment by akashdevcc** [comment]
> Oh, Bloody hell. This is not a Nativewind issue. It's a PNPM configuration issue.
> 
> Looking back through @byCedric's [expo-monorepo-example](https://github.com/byCedric/expo-monorepo-example), I noticed this line in the [metro.config.js](https://github.com/byCedric/expo-monorepo-example/blob/8229117fd826dd51562f17725a8084b9bf450b99/apps/mobile/metro.config.js#L13C1-L14C50) which I hadn't included in the example config:
> 
> ```
> // #3 - Force resolving nested modules to the folders below
> config.resolver.disableHierarchicalLookup = true;
> ```
> 
> This line is REQUIRED to make Nativewind work within monorepo packages.

@tyrauber 
Thanks for going deep into this and finding the solution, I am now able to render my components from other packages with proper nativewind/tailwind styles.

But I can confirm, it does not work without having `node-linker=hoisted` in `.npmrc` file.
I tried this in a [t3-oss/create-t3-turbo](https://github.com/t3-oss/create-t3-turbo) which I cloned a month ago.

I am getting below error:
```
Error: Unable to resolve module @expo/metro-runtime from D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\expo-router@3.4.7_expo-constants@15.4.5_expo-linking@6.2.2_expo-modules-autolinking@1.10.3_ex_k7sh6uksy2gboe6kqtnw3jouyi\node_modules\expo-router\entry.js: @expo/metro-runtime could not be found within the project or in these directories:
  node_modules
  ..\..\node_modules
  1 | // `@expo/metro-runtime` MUST be the first import to ensure Fast Refresh works
  2 | // on web.
> 3 | import '@expo/metro-runtime';
    |         ^
  4 |
  5 | import { App } from 'expo-router/build/qualified-entry';
  6 | import { renderRootComponent } from 'expo-router/build/renderRootComponent';
    at ModuleResolver.resolveDependency (D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:153:15)
    at DependencyGraph.resolveDependency (D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\node-haste\DependencyGraph.js:271:43)
    at D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\lib\transformHelpers.js:176:21
    at resolveDependencies (D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\DeltaBundler\buildSubgraph.js:56:25)
    at visit (D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\DeltaBundler\buildSubgraph.js:107:30)
    at async Promise.all (index 0)
    at visit (D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\DeltaBundler\buildSubgraph.js:116:5)
    at async Promise.all (index 0)
    at buildSubgraph (D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\DeltaBundler\buildSubgraph.js:127:3)
    at Graph._buildDelta (D:\development\akashdevcc\github-issues\nativewind\nativewind-font-size-style-issue-in-monorepo\node_modules\.pnpm\metro@0.80.5\node_modules\metro\src\DeltaBundler\Graph.js:249:22)
```

But `create-t3-turbo` devs have also reverted this change [here](https://github.com/t3-oss/create-t3-turbo/pull/870) due to this [issue here](https://github.com/t3-oss/create-t3-turbo/issues/867). So, I think it's still a while that pnpm can fully support expo and nativewind, so that it works without `node-linker=hoisted` and `config.resolver.disableHierarchicalLookup = true;` configurations.

**Comment by akashdevcc** [comment]
@tyrauber 
I re-cloned my repo to a new location on my computer and removed `node-linker=hoisted` in `.npmrc` and `config.resolver.disableHierarchicalLookup = true;` in `metro.config.js`.

And the issue is gone. The nativewind styles are working properly for components coming from different package than the app's package. 

My dependencies versions are:
```
    "expo": "~50.0.7",
    "expo-router": "~3.4.7",
    "nativewind": "~4.0.13",
    "tailwindcss": "^3.4.0"
```

**Comment by Knaackee** [comment]
For me, adding `config.resolver.disableHierarchicalLookup = true;` solved the issue.

**Comment by albertdbio** [comment]
Does anyone have a working repo up?

**Comment by philhradecs** [comment]
Solution for me was to include the path to the ui package in the app's tailwind config

`content: ["./src/**/*.{ts,tsx}", "../../packages/ui/src/**/*.{ts,tsx}"]`

**Comment by tolotrasamuel** [comment]
`config.resolver.disableHierarchicalLookup = true;` does not work for me. If I add it, I get

> 
> Unable to resolve "@expo/metro-runtime" from "node_modules/.bun/expo-router@6.0.23+db119c6dd99dd9b8/node_modules/expo-router/entry-classic.js"
>   1 | // `@expo/metro-runtime` MUST be the first import to ensure Fast Refresh works
>   2 | // on web.
> > 3 | import '@expo/metro-runtime';
>     |         ^
>   4 |
>   5 | import { App } from 'expo-router/build/qualified-entry';
>   6 | import { renderRootComponent } from 'expo-router/build/renderRootComponent';
> 
> Import stack:
> 
>  node_modules/.bun/expo-router@6.0.23+db119c6dd99dd9b8/node_modules/expo-router/entry-classic.js
>  | import "@expo/metro-runtime"
> 
>  node_modules/.bun/expo-router@6.0.23+db119c6dd99dd9b8/node_modules/expo-router/entry.js
>  | import "expo-router/entry-classic"

I am using Bun
