### ISSUE TITLE
fontSize configuration customizations not respected.

### ISSUE THREAD

**Issue by z1haze** [marklawlor/nativewind#739]
**Describe the bug**
When overriding the fontSize when extending the theme, the changes are not respected, despite intellisense reading the correct updated values:

**To Reproduce**
1. modify your tailwindcss config to change the fontSize for a particular text class.. see my example:
```js
module.exports = {
  content: ['./src/App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontSize: {
        '3xl': ['30px', {lineHeight: '40px'}]
      },
    }
  },
  plugins: []
};
```
2. Restart your project, observe your intellisense to appear updated with the correct expected values:
![image](https://github.com/marklawlor/nativewind/assets/6024725/b73a363e-4009-473d-8bfd-d42eb26f9dd0)
4. Observe that the font size or line height changes from the config are not respected.
![image](https://github.com/marklawlor/nativewind/assets/6024725/30c9fca9-7be1-49b4-be40-c9c39197a09d)

**Expected behavior**
Overrides made to the tailwindcss config (as per the documentation claiming they are the same) should be respected

**Expo Snack**
Unable to get tailwindcss 3.3.2 to install in snack therefore cannot show. however this is the snack I attempted to produce
https://snack.expo.dev/@shendricks-tillys/hello-world

**Comment by z1haze** [comment]
related to #404 however not the same

**Comment by klcantrellsep** [comment]
@z1haze I was able to see fontSize config customizations work with nativewind@4.0.22 + tailwindcss@3.4.1. I'm using Expo Router so I followed [these docs](https://www.nativewind.dev/v4/getting-started/expo-router) to get things setup. Then I added your customizations just as you described above and it worked.

**Comment by klcantrell** [comment]
@z1haze I was able to see fontSize config customizations work with nativewind@4.0.22 + tailwindcss@3.4.1. I'm using Expo Router so I followed [these docs](https://www.nativewind.dev/v4/getting-started/expo-router) to get things setup. Then I added your customizations just as you described above and it worked.

**Comment by marklawlor** [comment]
This appears fixed in the v4 release
