### ISSUE TITLE
Pressable onPress stale closure when using group

### ISSUE THREAD

**Issue by gavinhow** [marklawlor/nativewind#740]
**Describe the bug**
Tried to create a basic form with an TextInput and Pressable button which logs the output of the state, using an effect I was able to see the state being updated. However when logging the state from the onPress of a Pressable it wasn't working. I've narrowed this down to the `group` class being added to className. You 

**To Reproduce**
1. Add a basic one input one pressable form with the `group` class on the Pressable.
2. Log the output of the state in the Pressable `onPress`.
3. See the stale state being outputed.

**Expected behavior**
Should operate the same way as without the `group` class

**Comment by NoZiL** [comment]
Hi, I am also encountering an issue with `onPress` of a `Pressaable` compo but when using a `className` with the `active:` pseudo classes. I suspect something in the interop that would trigger this behavior.
Wrapping a view and applying the classNames dynamically with the states works.

**Comment by williamrobertson13** [comment]
+1 seeing the same issue with the `active` modifier

**Comment by mwarger** [comment]
This seems to be an issue regardless of using group. Any modifier seems to cause this (active, hover, etc).

**Comment by marklawlor** [comment]
Fixed in `4.0.29`
