### ISSUE TITLE
v4 not working with Nx monorepo and pnpm

### ISSUE THREAD

**Issue by saaymeen** [marklawlor/nativewind#742]
**Describe the bug**
Trying to set up v4 with a react native cli project inside a Nx workspace with pnpm fails on multiple steps.

Setup as per docs results in two errors of modules `@babel/plugin-transform-react-jsx` and `react-native-css-interop` missing, if I add them manually to the repo metro crashes with the invariant violation message that the app is not registered.

Reproduction can be found [here](https://github.com/saaymeen/nativewind-test).

Clone, and then `pnpm install`, `nx pod-install nativewind-test-app`, `nx run-ios nativewind-test-app`.

**Additional context**
pnpm@8.13.1
nx@17.2.8
react-native@0.72.6

**Comment by marklawlor** [comment]
React Native is very sensitive to the location of modules in your `node_modules`. It is highly recommend to use the `nohoist` option https://docs.expo.dev/guides/monorepos/

This is React Native issue and not a NativeWind issue
