### ISSUE TITLE
v4 - iOS Expo Project failing to archive

### ISSUE THREAD

**Issue by iceColdChris** [marklawlor/nativewind#751]
**Describe the bug**
When trying to archive the application within XCode to push to the app store, The build fails and I am met with the following error

> tailwindcss(native) rebuilding... 
Error running TailwindCSS CLI, please run the CLI manually to see the error.

When running the CLI manually I am not met with any error and the command runs successfully, Normal builds also seem to be working just fine, It's just failing on the archive step. I was able to reproduce this on a fresh expo project as well.

**To Reproduce**
1. Create a new Expo Tabs Project using `npx create-expo-app@latest --template tabs@50`
2. Follow the Nativewind v4 instructions for expo-router
3. Open up the iOS project in XCode using the xcworkspace file
4. Select any ios device for the target
5. Click Product -> Archive
6. After a while the build will fail and the error message will point to the above error

**Expected behavior**
The App should archive as intended

**Screenshots**
<img width="792" alt="Screenshot 2024-01-19 at 8 27 26 AM" src="https://github.com/marklawlor/nativewind/assets/10732885/3f722c5b-c077-46ce-bc11-357341efd7e0">

**Additional context**

Node version: 20.10.0 via nvm
XCode 15.2

packages: 
_"expo": "~50.0.2",
"nativewind": "^4.0.1",
"react-native-reanimated": "~3.6.0",
"tailwindcss": "^3.4.1"_

**Comment by promer94** [comment]
After add some log at https://github.com/marklawlor/nativewind/blob/4232087bd2405e8d9b42979fcda429b5ddaa2a49/packages/nativewind/src/metro/tailwind-cli.ts#L107

![20240124-221415](https://github.com/marklawlor/nativewind/assets/15878786/bcdb9dbe-e67a-4e77-95fd-4fafa0750f99)
![20240124-221422](https://github.com/marklawlor/nativewind/assets/15878786/4977d54e-4d70-4bac-b83e-56cf6ef581b3)

I find the real error is that the current node executable is installed in a directory that's not in Xcode's default search path.

https://andrewchaa.me.uk/how-to-fix-the-node-command-not-found-error-when-building-a-react-native-app-in-xcode/

**Comment by iceColdChris** [comment]
That ended up working for me, Thank you @promer94!

**Comment by yishin** [comment]
It seems like you're encountering errors regardless of the node link.

**Comment by dacitto** [comment]
Thank you @promer94.
