### ISSUE TITLE
Responsive Breakpoint are not working on native devices

### ISSUE THREAD

**Issue by oliviercperrier** [marklawlor/nativewind#752]
**Describe the bug**
I tried using the targeting breakpoint (https://tailwindcss.com/docs/responsive-design#targeting-a-breakpoint-range), but it seems it doesnt work on native devices.

for example: if i use `max-sm:text-xl`, on web i will have the text with size `xl` when screen width is 0px to 640px, but on a mobile native i will have the default text size. 

if i use sm:text-xl, everything seems to be ok on both web and native.

The only difference i see between sm:text-xl and max-sm:text-xl is the use of `not all` is the generated media query, which i guess is what is not working on native.

**Expected behavior**
using `max-sm:text-xl` on web and native should have the same behaviour.

**Screenshots**
Using the following code:
```
<Text role="heading" className="max-sm:text-3xl text-center font-bold tracking-tighter">
    Welcome to Project ACME
</Text>
```
<img width="1070" alt="Screenshot 2024-01-19 at 11 39 34 PM" src="https://github.com/marklawlor/nativewind/assets/28421005/12242aed-5af2-409b-b474-fd1cd54b7902">
<img width="529" alt="Screenshot 2024-01-19 at 11 39 43 PM" src="https://github.com/marklawlor/nativewind/assets/28421005/3535aeaa-0e93-4adf-a0d0-b7bacf5b7649">

**Comment by marklawlor** [comment]
This should work in `4.0.35`. Yep `not all` was the problem :+1:
