### ISSUE TITLE
Style not apply on physical device

### ISSUE THREAD

**Issue by JinYuSha0** [marklawlor/nativewind#753]
**Describe the bug**
Modified style was not applied on physical device, whether it is reload bundle or restart metro, only add `--reset-cache` flag will apply.

**To Reproduce**
1. npm start
2. react-native memu 'reload'
3. nothing changes

**Expected behavior**
Modify className and apply the style immediately

**Comment by JinYuSha0** [comment]
@marklawlor I found the problem by looking at the source code, tailwind-cli start ws server listen on 8089(default) port, but physical device can't access, I think it's better to disclose this issue in README or console that sometimes we have to execute `adb reverse tcp:8089 tcp:8089` to take effect, I spent an hour researching this problem in the hope that newbies won't run into it

**Comment by odysseaspapadimas** [comment]
> @marklawlor I found the problem by looking at the source code, tailwind-cli start ws server listen on 8089(default) port, but physical device can't access, I think it's better to disclose this issue in README or console that sometimes we have to execute `adb reverse tcp:8089 tcp:8089` to take effect, I spent an hour researching this problem in the hope that newbies won't run into it

Spent an hour trying to solve this as well, thank you so much it worked🙏

**Comment by marklawlor** [comment]
By default you should not need to do this. Can people please provide information about their setups so I can add this to the documentation.

**Comment by JinYuSha0** [comment]
@marklawlor Just install the application normally on the android device, `--tunnel` flag not used, 
Android devices use USB to connect to the computer, and you need to execute this command to access the computer's port. the official website also has relevant tips [method-1-using-adb-reverse-recommended-1](https://reactnative.dev/docs/running-on-device#method-1-using-adb-reverse-recommended-1), I recommend you to execute this command in `tailwind-cli.ts`:
```javascript
import {exec} from 'node:child_process';

// ....
const port = options.hotServerOptions.port;
exec(`adb wait-for-device reverse tcp:${port} tcp:${port}`)
// or 
console.log(`You can use this method if your device is running Android 5.0 (Lollipop) or newer, it has USB debugging enabled, and it is connected via USB to your development machine.`)
console.log(`adb reverse tcp:${port} tcp:${port}`)
```

**Comment by marklawlor** [comment]
`4.0.28` has a number of fixes for this issue. You should no longer have to use `adb` to reverse ports
