### ISSUE TITLE
v4 TypeError: right operand of 'in' is not an object - react-native-paper/TextInput 

### ISSUE THREAD

**Issue by josetr** [marklawlor/nativewind#756]
**To Reproduce**

Install `react-native-paper` and use

```.ts
import { TextInput } from "react-native-paper";

export default function MyScreen() {
  return <TextInput />
}
```

**Error location & stack trace**

The issue seems to be `Platform.OS === 'web' && { outline: 'none' }`, located at https://github.com/callstack/react-native-paper/blob/9c9a6149ba75d773a4c2595c2af4ff03ed2f704f/src/components/TextInput/TextInputFlat.tsx#L421

```
ERROR  TypeError: right operand of 'in' is not an object

This error is located at:
    in CssInteropComponent (created by TextInputFlat)
    in RCTView (created by View)
    in View (created by TextInputFlat)
    in RCTView (created by View)
    in View (created by TextInputFlat)
    in TextInputFlat
    in Unknown (created by MyScreen)
```

**Solution**

`Platform.OS === 'web' ? { outline: 'none' } : undefined` fixes the problem.

**Comment by marklawlor** [comment]
Fixed in `4.0.28`

**Comment by oldo** [comment]
Oh wow, this solved the issue for me, but took me a long time to realise that I was looking at this issue on nativewind's repo. I thought I was still on react-native-paper...

**Comment by oldo** [comment]
...but with upgrade I just realised that none of the TW styles are working anymore. Something must of changed in requirements between 4.0.23 and 4.0.36?

**Comment by gyanbhartip** [comment]
Could someone please explain why does this fix work? Even if short-circuiting is used, it would return a false instead of undefined (after the solution). But Does react-native not accept false as a value in style array? Why would it fail?
