### ISSUE TITLE
Class names are not output in Jest snapshot tests

### ISSUE THREAD

**Issue by mogusbi** [marklawlor/nativewind#758]
**Describe the bug**
When creating snapshot test with Jest, class names are not output

**To Reproduce**
Create a snapshot of an element with nativewind classes applied and look at the output

**Expected behavior**
I would expect the class names to be output in the snapshot

**Comment by mogusbi** [comment]
Here's an example

```tsx
# HeaderTitle.tsx
import { ReactNode } from 'react';
import { Text, View } from 'react-native';

/** HeaderTitle component props */
interface IHeaderTitleProps {
  /** Contents of component */
  children: ReactNode;
}

/**
 * Custom header bar title
 *
 * @param props - HeaderTitle component props
 *
 * @returns HeaderTitle component
 */
function HeaderTitle({ children }: IHeaderTitleProps) {
  return (
    <View className="flex-1 flex-row h-9 items-center ml-5">
      <Text className="font-display text-2xl text-night">
        {children}
      </Text>
    </View>
  )
}

export default HeaderTitle;

# __tests__/HeaderTitle.test.tsx
import { setup } from "../../utilities/jest";
import HeaderTitle from "../HeaderTitle";

describe('HeaderTitle', () => {
  it('should render header title component', () => {
    const { toJSON } = setup(<HeaderTitle>Hello world</HeaderTitle>); // This is just a wrapper for React Native Testing Library render function

    expect(toJSON()).toMatchSnapshot();
  });
});
```

And this is the snapshot created

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`HeaderTitle should render header title component 1`] = `
<View>
  <Text>
    Hello world
  </Text>
</View>
`;
```

**Comment by marklawlor** [comment]
NativeWind needs to compile and inject your styles into the application. There isn't a well documented way on how to do this for tests.

NativeWind uses a very rough method for its own [internal testing](https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/src/test-utils.tsx) but this needs cleaning up before making it a public API.

You can use this as a rough DIY guide, or I'm happy to assist with a PR that exposes this API

**Comment by mogusbi** [comment]
@marklawlor this appears to be working now after upgrading recently from 4.0.23. Thank you!

**Comment by Hosam-hsm** [comment]
@marklawlor  Is it still recommended to use the internal testing methods to get the classNames as mentioned in your previous comment? Or is it already available as a public API now? 

I am trying to test a component: 
   ```
const { getByTestId } = await render(
      <FAB onPress={() => {}} iconName="menu" />,
    );
    const fabButton = getByTestId("fab-button");
    expect(fabButton.props.className).toContain("bg-surface");
```
And fabButton.props.className is undefined. 

Any help?
