### ISSUE TITLE
v4: Image doesn't show if I set the width, height with className

### ISSUE THREAD

**Issue by teddybee** [marklawlor/nativewind#759]
**Describe the bug**
Image doesn't show when I use className to declare width and height.
I have to use inline style to draw an image.

**To Reproduce**
Put an image into a screen
```
<Image
        className="w-80 h-80"  
        //style={{width: 80, height:80}}      
        source="https://media.istockphoto.com/id/1005187314/hu/fot%C3%B3/golden-mix-kutya-j%C3%A1t%C3%A9k-fetch.jpg?s=1024x1024&w=is&k=20&c=e8QhUrdlyDllTWnx68t12OyvAF2uTJ3dmSSL6dKzKBQ="
        transition={1000}
      />
```

**Expected behavior**
Shows the image

**Expo Snack**
[https://snack.expo.dev/0vOFJPOvN6Icy4EgBN78Z](https://snack.expo.dev/0vOFJPOvN6Icy4EgBN78Z)
(not working, I couldn't install tailwindcss package)

**Screenshots**

**Additional context**
Nativewind: 4.0.23
expo-image: "~1.3.5",

**Comment by JinYuSha0** [comment]
[cssInterop](https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/runtime/components.ts#L23)

```
import {cssInterop} from 'nativewind'
import { Image } from 'expo-image';

cssInterop(Image, { className: "style" });
```

You can try this and make sure it runs in front

**Comment by teddybee** [comment]
@JinYuSha0 Thank you, it is working.

**Comment by JuanFCVal** [comment]
> [cssInterop](https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/runtime/components.ts#L23)
> 
> ```
> import {cssInterop} from 'nativewind'
> import { Image } from 'expo-image';
> 
> cssInterop(Image, { className: "style" });
> ```
> 
> You can try this and make sure it runs in front
Hey, where do I make that import? 
I found this when I try to import it: 
Module '"nativewind"' has no exported member 'cssInterop'.t

I'm using RN CLI not expo.
