### ISSUE TITLE
cssInterop & remapProps Type error

### ISSUE THREAD

**Issue by huynqjmango360** [marklawlor/nativewind#760]
**Describe the bug**
cssInterop & remapProps cause Type error with typescript

**To Reproduce**

```typescript


const AnimatedTouchable = Animated.createAnimatedComponent(TouchableOpacity);

interface Props extends AnimatedProps<TouchableOpacityProps> {
  labelStyle?: StyleProp<TextStyle>;
  className?: string;
  labelClass?: string;
  ...
}

const Button: FunctionComponent<Props> = () => {
  ...
}

...

export default remapProps(Button, {
  labelStyle: true,
});
``` 

**Screenshots**
<img width="947" alt="Screenshot 2024-01-23 at 15 46 05" src="https://github.com/marklawlor/nativewind/assets/104605872/b6ea9628-43f6-4c8a-991f-f85f203bf34b">
<img width="923" alt="Screenshot 2024-01-23 at 15 48 50" src="https://github.com/marklawlor/nativewind/assets/104605872/145f3f56-f53d-4d38-b158-4fa6d8e61d8d">

**Additional context**
RN 0.73.2
nativewind: 4.0.23
Typescript: 5.3.3

**Comment by HGCollier** [comment]
Any luck with this?

**Comment by huynqjmango360** [comment]
this worked
`
...
cssInterop(Button, {
  className: 'style',
  labelClass: 'labelStyle',
});

export default Button;
`
