### ISSUE TITLE
Can't use "calc(a - b)" as theme extend variable in tailwind config.

### ISSUE THREAD

**Issue by rajatsandeepsen** [marklawlor/nativewind#764]
**Describe the bug**
Can't use "calc(a - b)" inside tailwind config. Not just `a-b`, it can't do any calculations similar to css.
```ts 
export default {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
				lg: "var(--radius)", // working ✅ 
				md: "calc(var(--radius) - 2px)", // ❎ not working 
				sm: "calc(var(--radius) - 4px)", // ❎ not working
			}
    }
  },
  presets: [nativewind],
} satisfies Config;

```

**To Reproduce**
1. using `"nativewind": "^4.0.13"`
2. Go to `tailwind.config.ts`
3. Add a variable with `calc( )` 
4. Run the `npx expo start --go`
5. See error at log

```bash
> tailwindcss(native) rebuilding... done
> Android Bundling complete 3355ms
> LOG  [{"property": "border-radius", "type": "IncompatibleNativeFunctionValue", "value": "calc"}]
```

**Screenshots**

`tailwind.config.ts`
> ![image](https://github.com/marklawlor/nativewind/assets/93584596/99854b3d-d718-4a76-aa8b-0495b4294746) 

`console`
> ![image](https://github.com/marklawlor/nativewind/assets/93584596/053e9c2f-4757-4337-8d5f-bafc2d1e5cf2)

**Additional context**
I think the expo aka react native doesn't support `calc( )`

**Comment by marklawlor** [comment]
NativeWind doesn't support `calc()`. 

If you'd like to contribute this change, as we would need to
- compile `calc()` into a JSON form (LightningCSS should do most of this for you)
- create a new entry inside `resolveValue` that understands this structure and can return the new value.
