### ISSUE TITLE
Custom `boxShadow` theme in tailwind config doesn't properly override default tailwind theme on mobile (iOS and Android). 

### ISSUE THREAD

**Issue by sbsto** [marklawlor/nativewind#765]
**Describe the bug**
Custom `boxShadow` theme in tailwind config doesn't properly override default tailwind theme on mobile (iOS and Android). 

**To Reproduce**
1. Define a tailwind theme with custom `boxShadow` styles

```js
export default {
  theme: {
    boxShadow: {
       // shadow-red works as expected, as it doesn't conflict with the default tailwind naming for shadows
       red: '0px 40px 100px rgba(255, 0, 0, 0.1)',
       // shadow-lg shows the default tailwind shadow-lg, rather than the green one defined below.
       lg: '0px 40px 100px rgba(0, 255, 0, 0.1)',
       // shadow-sm, shadow-xl, etc. are still available on mobile, despite this being a theme override rather than a theme extension
    }
  }
}
```

2. Apply the classes and observe the visible difference on web vs mobile.

```
<View className="shadow-lg bg-elevation-base h-[150px] w-[150px] border border-black"><Text>shadow-lg</Text></View>
<View className="shadow-red bg-elevation-base h-[150px] w-[150px] border border-black"><Text>shadow-red</Text></View>
```

**Expected behavior**
Expect mobile to behave the same as web: all default tailwind shadow sizes become unavailable, and the shadows should show as defined in the theme.

**Screenshots**
I've attached the expected and actual visual results (expected is on web, actual is on iOS).

Expected:
<img width="581" alt="Screenshot 2024-01-25 at 13 27 17" src="https://github.com/marklawlor/nativewind/assets/37947148/66cb6917-0ce0-4e28-8ddf-41be5d031b7f">

Actual:
<img width="340" alt="Screenshot 2024-01-25 at 13 28 18" src="https://github.com/marklawlor/nativewind/assets/37947148/c1eb3f18-30fd-4576-9318-aa3d66e7e353">

The `shadow-lg` class on mobile should be applying the massive green shadow, like we see on web, but instead, it seems to apply the tailwind default for `shadow-lg`.

**Comment by marklawlor** [comment]
Fixed in `4.0.29`.
