### ISSUE TITLE
v4 FlastList erroring on Web w/ Expo Router: columnWrapperStyle not supported for single column lists 

### ISSUE THREAD

**Issue by kimchouard** [marklawlor/nativewind#767]
**Describe the bug**
Can't use the `<FlatList />` RN component on the web. Throwing this error:
```
Uncaught Invariant Violation: columnWrapperStyle not supported for single column lists
```

<img width="748" alt="CleanShot 2024-01-25 at 16 49 44@2x" src="https://github.com/marklawlor/nativewind/assets/2856923/88a1ebf1-ed1c-40dd-8220-2496c895220d">

**To Reproduce**
1. Create a new Expo Router v3 app based on the NativeWind boilerplate: `npx create-expo-app -e with-router-tailwind`
2. On any page, say `src/app/index.tsx`, add a `<FlatList />`
3. Load the page on the web (`npx expo start --web`) and you'll see the error.

```jsx
import { FlatList, ... } from "react-native";

// (...)

<FlatList
  data={[
    {
      title: "allo",
    },
    {
      title: "allo",
    },
  ]}
  renderItem={(item) => <Text>{item.item.title}</Text>}
/>
```

**Expected behavior**
Render the FlatList normally, like it does on Native.

**Expo Snack**
Seems to be working on a plain Snack: https://snack.expo.dev/@kimik/flatlist-test

**Additional context**
- The issues doesn't happen on a plain Expo Router app. Only when hooked-up with NativeWind.
- Adding a `numColumns={2}` param to the FlatList won't throw this issue.

**Comment by dannyhw** [comment]
maybe related to how this remapping happens?
https://github.com/marklawlor/nativewind/blob/4232087bd2405e8d9b42979fcda429b5ddaa2a49/packages/react-native-css-interop/src/runtime/components.ts#L47

**Comment by kimchouard** [comment]
> maybe related to how this remapping happens?
> 
> https://github.com/marklawlor/nativewind/blob/4232087bd2405e8d9b42979fcda429b5ddaa2a49/packages/react-native-css-interop/src/runtime/components.ts#L47

AH! Yes. When commenting line 51 from this file on my local project, it fixes the issue. 

```js
remapProps(FlatList, {
  className: "style",
  ListFooterComponentClassName: "ListFooterComponentStyle",
  ListHeaderComponentClassName: "ListHeaderComponentStyle",
  // columnWrapperClassName: "columnWrapperStyle",
  contentContainerClassName: "contentContainerStyle",
  indicatorClassName: "indicatorStyle",
});
```

This might require a deeper fix:
- Either to make those remapping conditional (in this case, when `numColumns > 1` for `FlatList`),
- or in a more "clean" way, to simply **not** apply those remapped parameters if no values are passed. 
I.e. :
  -  if I call a `<FlatList />` with no `columnWrapperClassName`, then no `columnWrapperStyle` is mapped/passed
  - if I add a `columnWrapperStyle`, then the mapping happens.

Trying to understand how `cssInterop` works, but would be interesting to get @marklawlor 's take on this 🧐

**Comment by kimchouard** [comment]
Alright, found a cleaner fix, in `api.ts#L37`:

https://github.com/marklawlor/nativewind/blob/4232087bd2405e8d9b42979fcda429b5ddaa2a49/packages/react-native-css-interop/src/runtime/api.ts#L37

As I suspected, the param is still passed on even if no styles are set (`newStyles` array is empty). 

Proposed fix:

```js
let styles: StyleProp = props[config.target];
if (Array.isArray(styles)) {
  styles = [...newStyles, ...styles];
} else if (styles) {
  styles = [...newStyles, styles];
// 👉 added a IF on the last ELSE, checking the newStyles.length to only create a param if there is a style to pass...
} else if (newStyles.length) { 
  styles = newStyles;
}
```

This resolved the bug for me locally. Opened PR #768 for it.

**Comment by JN-forkwork** [comment]
Hey Kim, where did you make this edit? node_modules?

**Comment by kimchouard** [comment]
Yes:
![CleanShot 2024-02-05 at 11 11 13@2x](https://github.com/marklawlor/nativewind/assets/2856923/e9cbdcbc-e46f-481c-b3fd-c9bf0ba8d0fb)

**Tip:** Keep this file open, you'll need to do this change on each new package install until this is merged ;)

**Comment by JN-forkwork** [comment]
Thank you, works! Now I am setting my styles for Flatlist using className but they are ignored. Only if I use style prop does it work. Do you think the fix might be affecting that? Isn't it through className that I set styles?

**Comment by marklawlor** [comment]
Fixed in `4.0.29`

**Comment by aademola1979** [comment]
Adding numColumns={2} solved the issue for me.

**Comment by DanG-Mergin** [comment]
> Adding numColumns={2} solved the issue for me.

It "solves it" by adding another column.  Updating nativewind is the easier option, per this thread
