### ISSUE TITLE
Wrapped in Proxy components are unstyled

### ISSUE THREAD

**Issue by XantreGodlike** [marklawlor/nativewind#773]
**Describe the bug**
If component wrapped with Proxy - it will not be styled correctly.

Nativewind 4.0 [relies on object strict reference](https://github.com/marklawlor/nativewind/blob/4232087bd2405e8d9b42979fcda429b5ddaa2a49/packages/react-native-css-interop/src/runtime/components.ts#L43) to style it - wrapping it in Proxy changes reference and breaks styling

**To Reproduce**
```tsx
const ProxyView = new Proxy(View, {});

const App = () => (
  <View className="flex-1 items-center justify-center">
    <View className="w-4 h-4" style={{ backgroundColor: "red" }} />
    <ProxyView
      className="w-4 h-4"
      style={{ backgroundColor: "red" }}
    />
  </View>
);
```

**Expected behavior**
Styling is not breaks when using proxies

**Expo Snack**
Is not working in snack

**Screenshots**
<img width="349" alt="image" src="https://github.com/marklawlor/nativewind/assets/57757211/ddde75bc-feeb-4857-8588-22fd8c601302">

**Comment by marklawlor** [comment]
`cssInterop` is available as a public API. You will need to create your own mapping for these components.

`cssInterop(ProxyView, { className: "style" })`
