### ISSUE TITLE
StyleSheet.registerCompiled is not a function on fresh install of React Native and Nativewind 4.0.1

### ISSUE THREAD

**Issue by josephfh** [marklawlor/nativewind#777]
**Describe the bug**
I'm seeing this error with a fresh install of React Native

`TypeError: _$$_REQUIRE(_dependencyMap[1], "(...)op").StyleSheet.registerCompiled is not a function (it is undefined), js engine: hermes`

Same as reported last November: https://github.com/marklawlor/nativewind/issues/687

**To Reproduce**

1. Install react native from cli:

`npx react-native@latest init reactNativeFreshInstall` 

2. Follow getting started instructions

https://www.nativewind.dev/v4/getting-started/react-native

3. Add missing dependency: react-native-css-interop

**Reproduction repo**

https://github.com/josephfh/react-native-nativewind-issue

**Comment by jfh001** [comment]
Update! Using the newer version of this package (which was not being installed/found/something) in my react native app has fixed the above problem:

"react-native-css-interop": "0.0.22"

`pnpm i react-native-css-interop` only installs 0.0.13

**Comment by harrisontaee** [comment]
FYI, I fixed it by removing `react-native-css-interop` from my dependencies.
