### ISSUE TITLE
React Native Reanimated does not work in versions higher than 4.0.13 

### ISSUE THREAD

**Issue by the-simian** [marklawlor/nativewind#785]
**Describe the bug**
Any version of nativewind higher than v4.0.13 throws an error when using the useSharedValue hook from `react-native-reanimated`

Exact Errors:
```sh
4.0.13 │ Working ✅
4.0.14 │ ERROR  TypeError: Cannot convert undefined value to object
4.0.23 │ Error: [Reanimated] Invalid value passed to `arguments`, maybe you forgot to use `.value`
```

**Mimimal Example Code  to Repro**
```tsx
import * as React from 'react';
import { Pressable } from 'react-native';
import Animated, { useSharedValue, withTiming } from 'react-native-reanimated';
function FadingTextExample(){
  const [isChecked, setIsChecked] = React.useState(false);
  const opacity = useSharedValue(0);
  opacity.value = withTiming(isChecked === true ? 1.0 : 0.0, {duration: 200});
  return (
  <Pressable  onPress={() => {setIsChecked(!isChecked)}}>
    <Text className="text-foreground">Click Me<Text>
    <Animated.View style={{ opacity }}>
        <Text className="text-foreground">Fading Stuff</Text>
      </Animated.View>
  </Pressable>
  )
} 
```

**To Reproduce**
Working: 4.0.13
1. Install nativewind with lock ` "nativewind": "4.0.13",`
2. run demo code
3. success

Not Working: 4.0.13 >
You actually get different errors per version:

1. Install nativewind with lock ` "nativewind": "4.0.14",` then  `"nativewind": "4.0.23"`
2. run demo code
3. failure

**Expected behavior**
I expect versions higher than 4.0.13 to work in the mobile build.

**Screenshots (tested with this [Checkbox](https://github.com/mrzachnugent/react-native-reusables/blob/main/components/ui/checkbox.tsx) Example)**

| 4.0.13 | 4.0.14 | 4.0.23|
|--------|--------|--------|
| ![image](https://github.com/marklawlor/nativewind/assets/954596/96b089c9-6629-4331-a366-fb21e7d796bd) | ![image](https://github.com/marklawlor/nativewind/assets/954596/f3b5f5cd-61df-4756-b535-eef498dc30d4) | ![image](https://github.com/marklawlor/nativewind/assets/954596/92c9a8ed-9eca-4b77-a7ec-9ac1ff470bf4) |
| Works ✅ | Cannot convert undefined value to object | Error: [Reanimated] Invalid value passed to `arguments`, maybe you forgot to use `.value` |

**Trace information**

<details><summary>4.0.14 Trace </summary>
<pre>
Android Bundled 13417ms (node_modules/expo-router/entry.js)
 ERROR  TypeError: Cannot convert undefined value to object

This error is located at:
    in CSSInterop.StatusBar (created by ExpoStatusBar)
    in ExpoStatusBar (created by wrapper)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot convert undefined value to object

This error is located at:
    in CSSInterop.StatusBar (created by ExpoStatusBar)
    in ExpoStatusBar (created by wrapper)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
</pre>
</details>

<details><summary>4.0.23 Trace </summary>
<pre>
Android Bundled 14062ms (node_modules/expo-router/entry.js)
 ERROR  Error: [Reanimated] Invalid value passed to `arguments`, maybe you forgot to use `.value`?

This error is located at:
    in CSSInteropAnimationWrapper (created by CSSInterop.Pressable)
    in CssInteropComponent (created by Label)
    in _c (created by CheckboxExample)
    in RCTView (created by View)
    in View (created by CSSInterop.View)
    in CssInteropComponent (created by CheckboxExample)
    in RCTView (created by View)
    in View (created by CSSInterop.View)
    in CssInteropComponent (created by CheckboxExample)
    in CheckboxExample
    in Unknown (created by Route(checkbox))
    in Suspense (created by Route(checkbox))
    in Route (created by Route(checkbox))
    in Route(checkbox) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by UiExamplesStack)
    in UiExamplesStack
    in Unknown (created by Route(ui-examples))
    in Suspense (created by Route(ui-examples))
    in Route (created by Route(ui-examples))
    in Route(ui-examples) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by AuthenticatedLayoutNav)
    in AuthenticatedLayoutNav (created by AuthenticatedLayout)
    in AuthenticatedLayout
    in Unknown (created by Route((authenticated)))
    in Suspense (created by Route((authenticated)))
    in Route (created by Route((authenticated)))
    in Route((authenticated)) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by QualifiedSlot)
    in QualifiedSlot (created by Slot)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by QualifiedNavigator)
    in QualifiedNavigator (created by Navigator)
    in Navigator (created by Slot)
    in Slot (created by Root)
    in SessionProvider (created by Root)
    in ThemeProvider (created by Root)
    in Root
    in Try
    in Unknown
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
</pre>
</details>

**Additional context**
1. Here are the other versions of critical dependencies. These are the exact versions (not ranged)
```json
{
 "expo": "50.0.6",
 "expo-router": "3.4.7",
 "nativewind": "4.0.13", | "4.0.14", | "4.0.23",
 "react": "18.2.0",
 "react-dom": "18.2.0",
 "react-native-reanimated": "3.6.2",
 "tailwindcss": "3.4.1",
 
 "@babel/core": "7.23.9",
 "typescript": "5.3.3"
 }
```
 2. The web export seems to still work correctly in higher versions
 3. The screenshots were tested on *Android* with WSL on Windows 11 running the expo server

Several components break such as the 
Checkbox, Toggle and Drawers. You can see these implementation in the repo. The example above is very similar to the [Checkbox](https://github.com/mrzachnugent/react-native-reusables/blob/main/components/ui/checkbox.tsx)

**Comment by marklawlor** [comment]
Fixed in `4.0.27`. You can also take advantage of NativeWind v4 and rewrite your component as

```tsx
import { View } from 'react-native';

function FadingTextExample(){
  return (
    <View className="group">
      <Text className="text-foreground">Click Me</Text>
      <View className="group-active:opacity-0 transition">
        <Text className="text-foreground">Fading Stuff</Text>
      </View>
    </View>
  )
} 
```
