### ISSUE TITLE
v4: ref is not passing to component

### ISSUE THREAD

**Issue by kdwkr** [marklawlor/nativewind#787]
**Describe the bug**
if i am using container query and passed ref to props, ref is not passing to component.

https://github.com/marklawlor/nativewind/blob/1b99062fd130f72225f60db34fa31e312a637b90/packages/react-native-css-interop/src/runtime/native/render-component.ts#L153-L170

maybe this codes are problem. when i log ref, it is not undefined. but props.ref is undefined. so ref was missed.

i used "group/item"

**Comment by marklawlor** [comment]
I think this is fixed in `4.0.31`. I still need better test coverage for refs :disappointed:
