### ISSUE TITLE
v4: disabled attribute are not working properly

### ISSUE THREAD

**Issue by kdwkr** [marklawlor/nativewind#788]
**Describe the bug**

nativewind: 4.0.30
react-native-css-interop: 0.0.30

If I pass any value to the disabled prop, always disabled style are applied

https://github.com/marklawlor/nativewind/blob/1b99062fd130f72225f60db34fa31e312a637b90/packages/react-native-css-interop/src/css-to-rn/normalize-selectors.ts#L294

https://github.com/marklawlor/nativewind/blob/1b99062fd130f72225f60db34fa31e312a637b90/packages/react-native-css-interop/src/runtime/native/conditions.ts#L345

it seems need to check value is true

**To Reproduce**
pass anything to disabled prop even false.

**Comment by marklawlor** [comment]
Fixed in `4.0.31` Commit: https://github.com/marklawlor/nativewind/commit/0480fa163e07bd8b4cc1675f5cbf9169407e0642
