### ISSUE TITLE
v4: ref cannot passed to class component.

### ISSUE THREAD

**Issue by kdwkr** [marklawlor/nativewind#789]
**Describe the bug**

when i tried to pass ref prop to class component, error occured.

and using react-native-svg.

https://github.com/marklawlor/nativewind/blob/1b99062fd130f72225f60db34fa31e312a637b90/packages/react-native-css-interop/src/runtime/native/api.ts#L29-L56

<img width="215" alt="image" src="https://github.com/marklawlor/nativewind/assets/5188404/a905e733-60b8-4821-8c81-e13d145df5d8">

<img width="845" alt="image" src="https://github.com/marklawlor/nativewind/assets/5188404/03952985-cab2-4f22-978d-0df8ff1c4e20">

**Comment by marklawlor** [comment]
Fixed in `4.0.32`
