### ISSUE TITLE
Application crashes due to attempted change of frozen props

### ISSUE THREAD

**Issue by firatoezcan** [marklawlor/nativewind#790]
**Describe the bug**
Hey, first off, thanks for this project. I know this is quite a lot of work maintaining it so I want to keep this quick.

I've started implementing a few designs a few days ago with this library and on the web-side it works flawlessly. Today when I wanted to test how it looks in the native app I got a crash with the error: `Error: You attempted to set the key `type` with the value `"runtime"` on an object that is meant to be immutable and has been frozen., js engine: hermes`.

This linked to this line: https://github.com/marklawlor/nativewind/blob/516c0c620384fdd058d060c034a09f8816e3f6dc/packages/react-native-css-interop/src/runtime/native/style.ts#L1217

As far as I understood correctly, `react-native-reanimated` freezes props. This function however changes the props by mutating the source object.

I've tested out if it would still crash when I rewrote the function to be immutable and it worked. Not sure if I would solve it by doing that as the immutable function definitely creates a lot more unnecessary objects. Maybe a fast copy and then mutating it would be the best solution, or maybe the issue lies somewhere else that makes the props be frozen in the first place.

**To Reproduce**
The project is sadly a bit too convoluted for me to give a reproduction. From what I gathered however it should happen when rendering a component like `<Pressable className="active:bg-red-500 bg-white"/>` and then clicking it.

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**
"nativewind": "4.0.23",
"react-native": "0.73.4",
"react-native-reanimated": "3.6.2",

**Comment by marklawlor** [comment]
Can you please try version `4.0.31`

**Comment by firatoezcan** [comment]
Works with 4.0.33 now, thanks a lot!

**Comment by eli-front** [comment]
seeing this on `4.1.12`

**Comment by marklawlor** [comment]
@eli-front The original reported issue was fixed, and we added tests to ensure the reported scenario doesn't occur. If you are still experiencing this issue please create a new issue with a reproduction
