### ISSUE TITLE
[v4.0.31] Updating Color Scheme on the web does not work and shows error

### ISSUE THREAD

**Issue by mrzachnugent** [marklawlor/nativewind#792]
**Describe the bug**
**On Web Only:** Updating Color Scheme on the web does not work and shows error

**To Reproduce**
1. Open the expo app on the web
2. Press a button that calls `setColorScheme` from nativewind's `useColorScheme` hook with the argument opposite to the current colorScheme.

**Expected behavior**
It should change the theme to the colorScheme passed to `setColorScheme` without throwing am error.

**Screenshots**
<img width="540" alt="Screenshot 2024-02-14 at 11 34 36 AM" src="https://github.com/marklawlor/nativewind/assets/63797719/e3353877-847f-45e0-8517-8b5183bfc5fd">

**Additional context**
I got it to work by adding the following code in a file that exports nativewind's `useColorScheme` hook:

```jsx
import { useColorScheme as useNativewindColorScheme } from 'nativewind';
import { Appearance, Platform } from 'react-native';

if (Platform.OS === 'web') {
  // Appearance.setColorScheme is not supported on web
  Appearance.setColorScheme = (scheme) => {
    if (scheme === 'dark') {
      globalThis.window?.document.documentElement.classList.add('dark');
    } else {
      globalThis.window?.document.documentElement.classList.remove('dark');
    }
  };
}

export const useColorScheme = useNativewindColorScheme;
```

**Comment by marklawlor** [comment]
Fixed in `4.0.33`
