### ISSUE TITLE
v4: onPress of Pressable not work when nested text has active styles

### ISSUE THREAD

**Issue by kdwkr** [marklawlor/nativewind#794]
**Describe the bug**

if i apply active style to nested Text in Pressable,
onPress of Pressable prop are not work.

https://github.com/marklawlor/nativewind/blob/bc5af30f4ce5c4519a54ab612d76c05fc474e576/packages/react-native-css-interop/src/runtime/native/render-component.ts#L75-L87

maybe it makes me confusing. according to other articles, rn gesture handler can solve this problem. but i want to use pure Pressable component. are there any solution to fix it?

**To Reproduce**
nativewind: 4.0.32

```tsx
<Pressable onPress={() => console.log(1)}>
  ..
  <Text className="bg-black active:bg-red">
    blabla
  </Text>
  ..
</Pressable>
```

if i press this, no log.

**Comment by marklawlor** [comment]
This is how React Native works

```tsx
<Pressable onPress={() => console.log("I don't log")}>
  <Text onPress={() => console.log("I will log")}>Press me</Text>
</Pressable>
```

You can work around this issue by restructuring your styles

```tsx
<Pressable className="group" onPress={() => console.log("I will now log!")}>
  <Text className="group-active:text-red-500">Press me</Text>
</Pressable>
```

https://www.nativewind.dev/v4/core-concepts/states#styling-based-on-parent-state
