### ISSUE TITLE
Sizing height render incorrect value

### ISSUE THREAD

**Issue by huynqjmango360** [marklawlor/nativewind#795]
**Describe the bug**
Some default height render incorrect value. eg: h-10 render output height 35

**Screenshots**
<img width="673" alt="Screenshot 2024-02-15 at 15 41 30" src="https://github.com/marklawlor/nativewind/assets/104605872/10c2b36a-82d6-48fe-93a5-c148787e62ee">
<img width="425" alt="Screenshot 2024-02-15 at 15 41 48" src="https://github.com/marklawlor/nativewind/assets/104605872/fb29e267-fbae-4880-8a57-ef5d2fe9157f">

**Additional context**
NativeWind 4.0.33
React native 0.73.4
tailwind 3.4.1

**Comment by marklawlor** [comment]
Your editor is showing you an estimated value based upon the assumption `1rem === 16px`. But that's just an assumption, as in reality the `rem` can be changed by the website/browser extension/etc.

NativeWind uses a `rem` value of 14, as this is the default fontSize for React Native `<Text />`. `14 x 2.5 = 35`
