### ISSUE TITLE
[Question] Enforce 1 rem = 16px on every platform in Nativewind@4

### ISSUE THREAD

**Issue by HenryWu01** [marklawlor/nativewind#798]
Hi, thanks for this nice project that ship React Native project with Tailwindcss support.

If I recall correctly, the Nativewind documentation mentions that 1 rem equals 14px on Android and iOS, but 16px on the Web. I'm wondering if it's possible to enforce 1 rem = 16px across all platforms, including Android, iOS, and Web, in Nativewind version 4?

**Comment by marklawlor** [comment]
If you are using inlined `rem` (recommend) https://www.nativewind.dev/v4/tailwind/typography/font-size#changing-the-default-inlined-rem-value

Otherwise

```tsx
import { rem } from 'nativewind'

rem.set(16)
```

**Comment by HenryWu01** [comment]
> If you are using inlined `rem` (recommend) https://www.nativewind.dev/v4/tailwind/typography/font-size#changing-the-default-inlined-rem-value
> 
> Otherwise
> 
> ```tsx
> import { rem } from 'nativewind'
> 
> rem.set(16)
> ```

Thank you so much for quick answering!
