### ISSUE TITLE
v4: tailwindcss shadows are too aggressive on iOS

### ISSUE THREAD

**Issue by mprync** [marklawlor/nativewind#802]
**Describe the bug**
`shadow-sm` on iOS is very aggressive compared to Android. This is the smallest value for shadow..

**To Reproduce**
Use `shadow-sm` on Android and iOS to replicate

**Expected behavior**
They match or are very close. Increasing the shadows on iOS to `shadow-md` (one higher) is way too much shadow.

**Screenshots**

iOS
<img width="170" alt="image" src="https://github.com/marklawlor/nativewind/assets/4587382/feae809d-db16-4d07-bc02-212eee9511e7">

Android
<img width="170" alt="image" src="https://github.com/marklawlor/nativewind/assets/4587382/02892809-4af1-4af6-9d97-afa9006a8253">

**Comment by marklawlor** [comment]
The base theme was generated via https://github.com/ethercreative/react-native-shadow-generator and used to as closely match TailwindCSS's default values.

This obviously isn't great from a design perspective, but I'm not a designer :man_shrugging:  I would like a designer to help contribute a good default theme, with reasoning behind their decisions.

Until then I would recommend using `tailwind.config.js` to override the theme with your preferred values.
