### ISSUE TITLE
IncompatibleNativeProperty v4

### ISSUE THREAD

**Issue by kations** [marklawlor/nativewind#807]
If you mix native and web tailwind classes I get a lot of terminal logs, would be great if there is a way to disable them.

 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  background-image
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter
 LOG  IncompatibleNativeProperty  backdrop-filter

**Comment by marklawlor** [comment]
This are current disabled on the latest version. You can also disabled them by marking those styles are web only with `web:`
