### ISSUE TITLE
TypeError: Cannot read property 'makeMutable' of undefined

### ISSUE THREAD

**Issue by keygun-development** [marklawlor/nativewind#812]
**Describe the bug**
When using any of the `transition` or `duration` classes I'm getting the `TypeError: Cannot read property 'makeMutable' of undefined`.

**To Reproduce**
1. Create any React Native component with e.g. `duration-300 transition-transform` classNames.
2. Build the app for Ios simulator (that's where I'm testing my app)
3. Run the Expo app

**Expected behavior**
I would've expected nativewind to be able to resolve the tailwind classes and create styles for it.

**Expo Snack**
Is this still possible in `v4`? Can't find anything in the v4 docs.

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/84903974/7bb1dc34-5891-4787-ac9b-ba7865b53374)
![image](https://github.com/marklawlor/nativewind/assets/84903974/0390c698-4204-4270-89fd-7214bc114e4a)
![image](https://github.com/marklawlor/nativewind/assets/84903974/ac75e256-1e7c-41a6-af0d-456b31e2f5fb)

**Additional context**
My package.json for versions:
```
"dependencies": {
    "@expo/metro-runtime": "~3.1.3",
    "classnames": "^2.5.1",
    "expo": "~50.0.6",
    "expo-status-bar": "~1.11.1",
    "expo-updates": "~0.24.10",
    "nativewind": "^4.0.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.4",
    "react-native-reanimated": "^3.7.0",
    "react-native-render-html": "^6.3.4",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@quickdevelopment/wp-js": "^4.0.2",
    "@types/react": "~18.2.45",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.1.3"
  }
```

**Reproduction**
[Here's](https://github.com/keygun-development/react-app-demo) a link to my react-native app demo.

**Steps to reproduce:**
- git clone https://github.com/keygun-development/react-app-demo
- npm i
- npm run ios

**Comment by marklawlor** [comment]
Please include a minimal reproduction repo. `makeMutable` is an export from `react-native-reanimated`, so your project is failing to import that dependancy. There are many reasons why module resolution can fail, none of which I can debug from the information provided.

**Comment by keygun-development** [comment]
In the meantime I'm using a different approach for this transition.
I'm using the `Animated` namespace along with the `Pressable` component exported by `react-native`.
When pressing the pressable component I call a function that changes the scale using `Animated.spring` and when letting go I call a function that sets it back to the old value.

I have a preview for anyone wondering how to achieve this:
```
const ScaleableContent: React.FC<IScaleableContent> = (props) => {
  const [scale] = useState(new Animated.Value(1));
  
  const handlePressIn = () => {
      Animated.spring(scale, {
          toValue: 1.05, // Change this value for the scale
          useNativeDriver: true,
      }).start();
  };
  
  const handlePressOut = () => {
      Animated.spring(scale, {
          toValue: 1,
          useNativeDriver: true,
      }).start();
  };
  return (
    <Pressable onPressIn={handlePressIn} onPressOut={handlePressOut} className="aspect-[14/9]">
        <View>
            <Animated.View style={{transform: [{scale: scale}]}}>
                {/*Here goes your content*/}
            </Animated.View>
        </View>
    </Pressable>
  );
}
export default ScaleableContent;
```

**Comment by luixo** [comment]
This is a problem in `react-native-reanimated: 3.7.0` or newer: https://github.com/software-mansion/react-native-reanimated/issues/1132
Downgrading to `3.6.3` works great.

**Comment by keygun-development** [comment]
@luixo Thanks! After downgrading to `3.6.3` it does in fact work.
