### ISSUE TITLE
[V4]: Touchable Opacity Not Getting Styled

### ISSUE THREAD

**Issue by theblondealex** [marklawlor/nativewind#822]
**Describe the bug**
TW Styles are not being applyed to touchable opacity elements, Worked in v2 in my other apps but using expo router and starting a new project in v4

**To Reproduce**
1. Using nativewind version 4.0.1 and expo 50.0.7 with expo router 3.4.7
2. Tailwind classes are working other elements so nativewind is clearly working and installed correctly.
3. Setup element as below and reproduce

```ts
import { Stack } from "expo-router";
import React from "react";
import LinkButton from "src/components/LinkButton";
import { View, Text, Button, TouchableOpacity } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

export default function HomeScreen() {
  return (
    <SafeAreaView>
      <View className="h-full w-full items-center justify-center">
        <Stack.Screen options={{ title: "Home Screen" }} />
        <Text className="m-4 border border-gray-500 p-8">🏠</Text>
        <LinkButton href="/second" text="Go To Second Screen" />
        <TouchableOpacity
          // style={{
          //   backgroundColor: "blue",
          //   padding: 20,
          //   borderRadius: 10,
          //   marginTop: 20,
          // }}
          className="mt-12 border border-gray-500 p-4"
        >
          <Text className="">Change Theme</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
```

**Expected behavior**
Styles should be applied - see code sippit

**Expo Snack**
could not be reproduced as expo app router would not work correctly with snacK

**Screenshots**

![sada](https://github.com/marklawlor/nativewind/assets/65453441/2b3a1746-819e-4ca4-bc73-bbcaed72c164)

**Additional context**

Have used nativewind in a few projects so far huge fan!

**Comment by M1ck0** [comment]
@theblondealex at least provide a guide on what did you do to make it work

**Comment by theblondealex** [comment]
@M1ck0 

No. You can use TouchableOpacity in 4.0.36 I am currently using it,

You can see after the ^4.0.1 release there were multiple commits that added support/fixes for them [here](https://github.com/marklawlor/nativewind/commit/01fed3efc75bf3c0269cceb3c0cc37347b8d19dd) and [here](https://github.com/marklawlor/nativewind/commit/2b15c2e831813ef836e66278a50bb270d7e529bc)

My issue was solved by properly upgrading to this version

**Comment by M1ck0** [comment]
Well, my test worked. People indeed do like to correct others, even tho initially they won't help with the actual answer :)

Thanks for proving it :)
