### ISSUE TITLE
Can we have a `vars` provider?

### ISSUE THREAD

**Issue by cxa** [marklawlor/nativewind#827]
It feels bad to create a root view that servers `vars` only, e.g.

```jsx
<NavigationContainer theme={navTheme}>
      <View style={vars(theme)} className="h-full">
     // ...
     </View>
</NavigationContainer>
```
It'll be nice if we can avoid this dummy view. Thanks.

**Comment by marklawlor** [comment]
For `vars()` to work on the web, it needs to set the styles on an actual element. I believe inserting a random `div` and possibly breaking people's layouts is more frustrating that requiring the use of a `<View />`. At least this way its transparent about what is happening on all platforms.

In the future this could be solved with scoped CSS, but that's still developing tech
