### ISSUE TITLE
Variable in className not work

### ISSUE THREAD

**Issue by cxa** [marklawlor/nativewind#829]
Example like

```jsx
className={`size-[${size}px]`}
```
Will not work in v4.

The interesting thing is, assume the `size` value is 25, if you manually change `className` to `size-[25px]`, and restore the `size-[${size}px]`, this will work. So maybe this is a cache issue?

**Comment by feledori** [comment]
As far as I know, this is a limitation of the tailwind compiler as values like these can't be statically analyzed so it won't generate the necessary styles for this. If you need to set styles programmatically it should be done with inline styles.
Example:
```tsx
function Example() {
    return <View className="p-4 etc..." style={{width: size, height: size}} />
}
```
