### ISSUE TITLE
Keeping classNames's

### ISSUE THREAD

**Issue by Knaackee** [marklawlor/nativewind#834]
At first, thanks for the great work!

I have a shared component library for my expo and my website project.
When using a component on the web, the classNames are compiled to a new class name. 

```
<View>
  <Text className="bg-teal-500 font-extrabold">Hello World</Text>
</View>
```
    
becomes

```
<div class="css-view-175oi2r">
    <div dir="auto" class="css-text-146c3p1">Hello World</div>
</div>

```
How to keep the original classNames for the web version?

On the other side, the styles are not applied in the expo app when using the component from the shared component library.

I use V4.

Thanks again!

**Comment by marklawlor** [comment]
These classNames created by React Native Web. The NativeWind ones are missing, most likely because the `jsx` transform has not been setup for this project

**Comment by Knaackee** [comment]
Thanks! I'm still trying to figure out how to get this working. Can you elaborate on setting up the JSX transform? I am using vite.

**Comment by Knaackee** [comment]
The web version is working fine now, thanks! 

But the native app isn't. The styles work when directly applied in the expo app. But the styles from the shared lib are missing. 

Thanks!

**Comment by Topiya** [comment]
Can you please let me know how to do jsx transform in bare react native project?
I am new to this.

**Comment by marklawlor** [comment]
@Topiya if your having issues create a new issue with a minimum reproduction. I cannot assist you when I can't see your code.

If things work on native but not on web, then your probably not using Expo. The community CLI does not support web very well, and is neither recommend by NativeWind and Meta for new users.

**Comment by Topiya** [comment]
I have tried to apply tailwind classes to **VIEW** and **DIV** tag in same file.

When I put same class win both, but `css-view-175oi2r` is automatically gets added in VIEW only. In div it is not adding, so working properly with div. I want use this codebase both for web also and for App also. So I need to solve this issue.

**Code sample:**

   ```
         <View className="py-8 mx-auto">
                <View className="flex">
                    <Text>VIEW - Code sample</Text>
                    <View className="bg-orange-600 w-15 h-7">
                        <Text>VIEW</Text>
                    </View>
                </View>
            </View>

            <div className="py-8 mx-auto">
                <div className="flex">
                    DIV - Code sample 
                    <div className="bg-orange-600 w-15 h-7">
                        DIV
                    </div>
                </div>
            </div>
```



**Browser Output:**

![image](https://github.com/user-attachments/assets/26ba1c95-37aa-4a90-8bd1-e448083f856c)


Can you let me know how to prevent automatic addition of `css-view-175oi2r`?

**Comment by Topiya** [comment]
@marklawlor I have tried to apply tailwind classes to VIEW and DIV tag in same file.

When I put same class win both, but css-view-175oi2r is automatically gets added in VIEW only. In div it is not adding, so working properly with div. I want use this codebase both for web also and for App also. So I need to solve this issue.

**Code sample:**

```
        <View className="py-8 mx-auto">
                <View className="flex">
                    <Text>VIEW - Code sample</Text>
                    <View className="bg-orange-600 w-15 h-7">
                        <Text>VIEW</Text>
                    </View>
                </View>
            </View>

            <div className="py-8 mx-auto">
                <div className="flex">
                    DIV - Code sample 
                    <div className="bg-orange-600 w-15 h-7">
                        DIV
                    </div>
                </div>
            </div>
```


**Browser Output:**

![image](https://github.com/user-attachments/assets/527462d4-0c75-41b8-98f5-3f9ed1fa8b99)


Can you let me know how to prevent automatic addition of css-view-175oi2r?

**Comment by marklawlor** [comment]
That class is coming from React Native Web, I don't believe you can remove it.

If this class is overriding your TailwindCSS classes, then ideally you should rearrange your stylesheets so TailwindCSS is last, or increase the specificity of the TailwindCSS classes

https://www.nativewind.dev/getting-started/nextjs#styles-are-not-being-applied

**Comment by Topiya** [comment]
@marklawlor 
Specificity of classes means I should add some another class also along with existing class right?

For ex. I need to add flex-direction class along with flex. Am I getting your point correctly?

**Comment by marklawlor** [comment]
The link I provided describes what you need to do, did you try setting `important`?

You can read the TailwindCSS documentation if you need more context on what the setting does.
