### ISSUE TITLE
[V4] Error ".plugins is not a valid Plugin property" after upgrading from V2

### ISSUE THREAD

**Issue by baesslerpa** [marklawlor/nativewind#841]
I'm getting the Error mentioned here https://github.com/marklawlor/nativewind/issues/600#issuecomment-1804741121. Sadly, there is no way mentioned to resolve the issue (I want to use V4)

I'm using React Native CLI. All steps from the setup are done, and I tried a clean install, but nothing worked. 

Since it's a known issue, maybe someone can provide a solution

**Comment by fredfgb** [comment]
I've followed the exact same instructions as described [here](https://www.nativewind.dev/v4/getting-started/expo-router) and worked for me, problably you're missing some `babel config` or `metro.config.js` changes, but I agree should be better explained on the docs!

**Comment by baesslerpa** [comment]
i found my Problem. in case anyone has the same Problem. 
in `babel.config.js` 
`nativewind/babel` belongs in the presets: []
 not in plugins: []
