### ISSUE TITLE
Please release v4 with solito 

### ISSUE THREAD

**Issue by manjunath-nuveb** [marklawlor/nativewind#844]
Has been waiting for V4 for a long time. please provide beta release atleast

**Comment by theblondealex** [comment]
There is a beta release of v4... see the documentation 

There are v4 installation instructions [here](https://www.nativewind.dev/v4/getting-started/react-native)[](https://www.nativewind.dev/v4/getting-started/react-native)

**Comment by manjunath-nuveb** [comment]
https://github.com/mikevocalz/solito-nativewind-v4
this is what i was looking for
