### ISSUE TITLE
Next.js: styles not working on Native Elements.

### ISSUE THREAD

**Issue by Knaackee** [marklawlor/nativewind#851]
At first, thanks for your great work!

I have an Expo/Next.js app. 

**Next.js**
Styles are not applied on the `react-native-web` elements, but on `<div/>`s it's working.

**Expo**
The styles are getting applied (off course `<div/>`s don't work on native, but e.g., the Text gets styled)

Example Component:

```
import { Text, View } from "react-native";

export default function App() {
  return (
    <View>
      <Text className="text-red-700 ">Welcome to Expo + Next.js 👋</Text>
      <div className="this-is-my-class text-3xl text-red-700">This is a div</div>
    </View>
  );
}
```

Clearly something config related. I played around the whole day.

Any idea?

**Comment by mfentross** [comment]
Hi @Knaackee, we are facing the same issue. How did you solve this?

**Comment by joaodematejr** [comment]
@Knaackee  I have the same problem, could you share the solution?
