### ISSUE TITLE
Luicide-react-native icon styling using className not working on native devices

### ISSUE THREAD

**Issue by rajat946** [marklawlor/nativewind#869]
**Describe the bug**
I tried to use nativewind on my expo project, and I am using **luicide-react-native** icons I want to style it using **className** but it is not working on native devices. Please fix this on priority as I am using it in my project. I have also seen the issues regarding icon but none of them solved my problem 
https://github.com/expo/vector-icons/issues/277
https://github.com/marklawlor/nativewind/issues/614

sharig below the github repo for reference - https://github.com/rajat693/nw-expo

**To Reproduce**

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by mz-evia** [comment]
@rajat946 First of all, this is an open source library by volunteers, so please do not demand a priority for your problem unless you are sponsoring the author. To do so please visit https://github.com/sponsors/marklawlor

Probably this is related to a problem that Lucide components are not using the className prop automatically. Could you try to add a compatibility layer like this (in a `Icons.tsx` file for example)

```tsx
import { AlertCircle, CheckCircle, LucideIcon, XCircle } from 'lucide-react-native';
import { cssInterop } from 'nativewind';

function interopIcon(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: 'style',
      nativeStyleToProp: {
        color: true,
        opacity: true,
      },
    },
  });
}

interopIcon(AlertCircle);
interopIcon(CheckCircle);
interopIcon(XCircle);

export { AlertCircle, CheckCircle, XCircle };
```

Maybe you can add a comment if this fixes your problem. Thanks!

**Comment by rajat946** [comment]
I apologize for the tone I used earlier; it wasn't my intention. I attempted the approach suggested above, but unfortunately, it didn't solve my problem. Nonetheless, I'll continue to explore other solutions. Thank you for your assistance.

**Comment by hayata-suenaga** [comment]
@rajat946, make sure that `interopIcon` is called in your app entry point (root `_layout` file, for example, if you're using Expo Router.

Here is the documentation on `cssInterop` -> https://www.nativewind.dev/api/css-interop

**Comment by a16n-dev** [comment]
For anyone coming across this issue, I ran into this same problem and ended up writing a package to apply `cssInterop` over all the lucide icons: https://github.com/a16n-dev/lucide-nativewind. Hopefully this helps!

**Comment by ShadiBlitz** [comment]
This should fix it.
Example: 
```tsx
<Icon
    name="ChevronDown"
    className="text-blue-500"
    size={12}
/>
```

```typescript
import { icons, LucideProps } from 'lucide-react-native'
import { cssInterop } from 'nativewind'
import { memo, useMemo } from 'react'

type IconName = keyof typeof icons
type IconProps = LucideProps & { name: IconName; className?: string }

const Icon: React.FC<IconProps> = memo(
    ({ name, className, ...props }: IconProps) => {
        const CustomIcon = useMemo(() => {
            // eslint-disable-next-line import/namespace
            const Icon = icons[name]
            Icon.displayName = name

            return cssInterop(Icon, {
                className: {
                    target: 'style',
                    nativeStyleToProp: {
                        color: true,
                        width: true,
                        height: true,
                    },
                },
            })
        }, [name])

        return <CustomIcon className={className} {...props} />
    },
)

Icon.displayName = 'Icon'

export default Icon
```
