### ISSUE TITLE
Issue with expo-linear-gradient

### ISSUE THREAD

**Issue by benomzn** [marklawlor/nativewind#877]
When I use the "className" prop of Nativewind on "LinearGradient" component, it doesn't work in iOS simulator, only in Android emulator. But If I use "style" prop instead of "className", it works on both simulators

Code:

```
import { Slot } from "expo-router";
import "../../global.css";
import { View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";

const Root = (): JSX.Element => {
  return (
    <>
      <View className="flex-1">
      <LinearGradient
          start={{ x: 0, y: 1 }}
          end={{ x: 1, y: 0 }}
          colors={["#00d976", "#00a55a"]}
          className="absolute h-full top-0 right-0 left-0 bottom-0"
          // style={{
          //   position: "absolute",
          //   height: "100%",
          //   top: 0,
          //   right: 0,
          //   left: 0
          // }}
        />
        <Slot />
      </View>
    </>
  );
}

export default Root;
```

<img width="999" alt="image" src="https://github.com/marklawlor/nativewind/assets/87614390/da39187b-1cb2-44db-a625-c63c604aa3e5">

**Comment by benomzn** [comment]
I think the reason is because the properties of LinearGradient are as follows:

export type LinearGradientProps = ViewProps & {
  colors: string[];
  locations?: number[] | null;
  start?: LinearGradientPoint | null;
  end?: LinearGradientPoint | null;
};

And ViewProps only accepts "style" prop, but then why on Android does it work with "className"?

**Comment by bailletced** [comment]
Have you tried with cssInterop?
https://www.nativewind.dev/v4/api/css-interop
```js
cssInterop(LinearGradient, { className: 'style' })
```

**Comment by benomzn** [comment]
> Have you tried with cssInterop? https://www.nativewind.dev/v4/api/css-interop
> 
> ```js
> cssInterop(LinearGradient, { className: 'style' })
> ```

It works! Thanks @bailletced

**Comment by benomzn** [comment]
> Have you tried with cssInterop? https://www.nativewind.dev/v4/api/css-interop
> 
> ```js
> cssInterop(LinearGradient, { className: 'style' })
> ```

It works! Thanks, @bailletced
