### ISSUE TITLE
[V4] Unable to detect the 'nativewind/preset'

### ISSUE THREAD

**Issue by dhatGuy** [marklawlor/nativewind#905]
**Describe the bug**
I noticed variable colors were not working. I decided to troubleshoot the issue with [verifyInstallation](https://www.nativewind.dev/v4/guides/troubleshooting#verifying-nativewind-installation) which throws error
```
Error: Nativewind: was unable to detect the 'nativewind/preset'. Please refer to http://nativewind.dev/troubleshooting#tailwind-preset
```

**To Reproduce**
https://github.com/dhatGuy/drug-inventory

**Expected behavior**
Variable colors should work fine.

**Comment by GustavoBonfimS** [comment]
Try installing`nativewind@canary` and see if it works as expected. I tested it now with your repository and it worked.

**Comment by dhatGuy** [comment]
Thanks, the canary version works fine
